codecov:
  require_ci_to_pass: yes

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

coverage:
  status:
    project:
      default:
        target: 99.51%
    patch: off

ignore:
  # This package is not shipped.
  - "Tests"
