// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import XCTest

@testable import SafeDIPlugin

final class SafeDIPluginTests: XCTestCase {

    // MARK: Code Generation Tests

    func test_run_successfullyGeneratesOutputFileWhenNoCodeInput() async throws {
        let output = try await SafeDIPlugin.run(
            swiftFileContent: [],
            dependentModuleNames: [],
            dependentInstantiables: [[]],
            buildDependencyTreeOutput: true
        )

        XCTAssertEqual(
            try XCTUnwrap(output.dependencyTree),
            """
            // This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
            // Any modifications made to this file will be overwritten on subsequent builds.
            // Please refrain from editing this file directly.

            #if canImport(SwiftUI)
            import SwiftUI
            #endif
            #if canImport(UIKit)
            import UIKit
            #endif

            // No root @Instantiable-decorated types found.
            """
        )
    }

    func test_run_doesNotWriteExtensionIfRootAlreadyHasEmptyInitializer() async throws {
        let output = try await SafeDIPlugin.run(
            swiftFileContent: [
                """
                import Foundation

                public protocol NetworkService {}

                @Instantiable(fulfillingAdditionalType: [NetworkService.self])
                public final class DefaultNetworkService: NetworkService {
                    public init() {}
                    let urlSession: URLSession = .shared
                }
                """,
            ],
            dependentModuleNames: [],
            dependentInstantiables: [[]],
            buildDependencyTreeOutput: true
        )

        XCTAssertEqual(
            try XCTUnwrap(output.dependencyTree),
            """
            // This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
            // Any modifications made to this file will be overwritten on subsequent builds.
            // Please refrain from editing this file directly.

            #if canImport(SwiftUI)
            import SwiftUI
            #endif
            #if canImport(UIKit)
            import UIKit
            #endif

            // No root @Instantiable-decorated types found.
            """
        )
    }

    func test_run_writesConvenienceExtensionOnRootOfTree_whenRootIsClass() async throws {
        let output = try await SafeDIPlugin.run(
            swiftFileContent: [
                """
                import Foundation

                public protocol NetworkService {}

                @Instantiable(fulfillingAdditionalType: [NetworkService.self])
                public final class DefaultNetworkService: NetworkService {
                    public init() {}
                    let urlSession: URLSession = .shared
                }
                """,
                """
                import UIKit

                @Instantiable
                public final class RootViewController: UIViewController {
                    public init(networkService: NetworkService) {
                        self.networkService = networkService
                    }

                    @Instantiated
                    let networkService: NetworkService
                }
                """,
            ],
            dependentModuleNames: [],
            dependentInstantiables: [[]],
            buildDependencyTreeOutput: true
        )

        XCTAssertEqual(
            try XCTUnwrap(output.dependencyTree),
            """
            // This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
            // Any modifications made to this file will be overwritten on subsequent builds.
            // Please refrain from editing this file directly.

            #if canImport(SwiftUI)
            import SwiftUI
            #endif
            #if canImport(UIKit)
            import UIKit
            #endif

            extension RootViewController {
                convenience init() {
                    let networkService: NetworkService = DefaultNetworkService()
                    self.init(networkService: networkService)
                }
            }
            """
        )
    }

    func test_run_writesConvenienceExtensionOnRootOfTree_whenRootIsActor() async throws {
        let output = try await SafeDIPlugin.run(
            swiftFileContent: [
                """
                import Foundation

                public protocol NetworkService {}

                @Instantiable(fulfillingAdditionalType: [NetworkService.self])
                public final class DefaultNetworkService: NetworkService {
                    public init() {}
                    let urlSession: URLSession = .shared
                }
                """,
                """
                import UIKit

                @Instantiable
                public actor Root {
                    public init(networkService: NetworkService) {
                        self.networkService = networkService
                    }

                    @Instantiated
                    let networkService: NetworkService
                }
                """,
            ],
            dependentModuleNames: [],
            dependentInstantiables: [[]],
            buildDependencyTreeOutput: true
        )

        XCTAssertEqual(
            try XCTUnwrap(output.dependencyTree),
            """
            // This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
            // Any modifications made to this file will be overwritten on subsequent builds.
            // Please refrain from editing this file directly.

            #if canImport(SwiftUI)
            import SwiftUI
            #endif
            #if canImport(UIKit)
            import UIKit
            #endif

            extension Root {
                init() {
                    let networkService: NetworkService = DefaultNetworkService()
                    self.init(networkService: networkService)
                }
            }
            """
        )
    }

    func test_run_writesConvenienceExtensionOnRootOfTree_whenRootIsStruct() async throws {
        let output = try await SafeDIPlugin.run(
            swiftFileContent: [
                """
                import Foundation

                public protocol NetworkService {}

                @Instantiable(fulfillingAdditionalType: [NetworkService.self])
                public final class DefaultNetworkService: NetworkService {
                    public init() {}
                    let urlSession: URLSession = .shared
                }
                """,
                """
                import UIKit

                @Instantiable
                public struct Root {
                    public init(networkService: NetworkService) {
                        self.networkService = networkService
                    }

                    @Instantiated
                    let networkService: NetworkService
                }
                """,
            ],
            dependentModuleNames: [],
            dependentInstantiables: [[]],
            buildDependencyTreeOutput: true
        )

        XCTAssertEqual(
            try XCTUnwrap(output.dependencyTree),
            """
            // This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
            // Any modifications made to this file will be overwritten on subsequent builds.
            // Please refrain from editing this file directly.

            #if canImport(SwiftUI)
            import SwiftUI
            #endif
            #if canImport(UIKit)
            import UIKit
            #endif

            extension Root {
                init() {
                    let networkService: NetworkService = DefaultNetworkService()
                    self.init(networkService: networkService)
                }
            }
            """
        )
    }

    func test_run_writesConvenienceExtensionOnRootOfTree_whenRootHasMultipleLayers() async throws {
        let output = try await SafeDIPlugin.run(
            swiftFileContent: [
                """
                public struct User {}
                """,
                """
                public protocol AuthService {
                    func login(username: String, password: String) async -> User
                }

                @Instantiable(fulfillingAdditionalTypes: [AuthService.self])
                public final class DefaultAuthService: AuthService {
                    public init(networkService: NetworkService) {
                        self.networkService = networkService
                    }

                    public func login(username: String, password: String) async -> User {
                        User()
                    }

                    @Received
                    let networkService: NetworkService
                }
                """,
                """
                public protocol NetworkService {}

                @Instantiable(fulfillingAdditionalTypes: [NetworkService.self])
                public final class DefaultNetworkService: NetworkService {
                    public init() {}
                }
                """,
                """
                import UIKit

                @Instantiable
                public final class RootViewController: UIViewController {
                    public init(authService: AuthService, networkService: NetworkService, loggedInViewControllerBuilder: ForwardingInstantiator<User, LoggedInViewController>) {
                        self.authService = authService
                        self.networkService = networkService
                        self.loggedInViewControllerBuilder = loggedInViewControllerBuilder
                        derivedValue = false
                        super.init(nibName: nil, bundle: nil)
                    }

                    @Instantiated
                    let networkService: NetworkService

                    @Instantiated
                    let authService: AuthService

                    @Instantiated
                    let loggedInViewControllerBuilder: ForwardingInstantiator<User, LoggedInViewController>

                    private let derivedValue: Bool

                    func login(username: String, password: String) {
                        Task { @MainActor in
                            let user = await authService.login(username: username, password: password)
                            let loggedInViewController = loggedInViewControllerBuilder.instantiate(user)
                            pushViewController(loggedInViewController)
                        }
                    }
                }
                """,
                """
                import UIKit

                @Instantiable
                public final class LoggedInViewController: UIViewController {

                    public init(user: User, networkService: NetworkService) {
                        self.user = user
                        self.networkService = networkService
                    }

                    @Forwarded
                    private let user: User

                    @Received
                    let networkService: NetworkService
                }
                """,
            ],
            dependentModuleNames: [],
            dependentInstantiables: [[]],
            buildDependencyTreeOutput: true
        )

        XCTAssertEqual(
            try XCTUnwrap(output.dependencyTree),
            """
            // This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
            // Any modifications made to this file will be overwritten on subsequent builds.
            // Please refrain from editing this file directly.

            #if canImport(SwiftUI)
            import SwiftUI
            #endif
            #if canImport(UIKit)
            import UIKit
            #endif

            extension RootViewController {
                convenience init() {
                    let networkService: NetworkService = DefaultNetworkService()
                    let authService: AuthService = DefaultAuthService(networkService: networkService)
                    let loggedInViewControllerBuilder = ForwardingInstantiator<User, LoggedInViewController> { user in
                        LoggedInViewController(user: user, networkService: networkService)
                    }
                    self.init(authService: authService, networkService: networkService, loggedInViewControllerBuilder: loggedInViewControllerBuilder)
                }
            }
            """
        )
    }

    func test_run_writesConvenienceExtensionOnRootOfTree_whenRootInstantiatesPropertiesThatUtilizedForwardedPropertyInSubBuilders() async throws {
        let output = try await SafeDIPlugin.run(
            swiftFileContent: [
                """
                public struct User {}
                """,
                """
                public protocol AuthService {
                    func login(username: String, password: String) async -> User
                }

                @Instantiable(fulfillingAdditionalTypes: [AuthService.self])
                public final class DefaultAuthService: AuthService {
                    public init(networkService: NetworkService) {
                        self.networkService = networkService
                    }

                    public func login(username: String, password: String) async -> User {
                        User()
                    }

                    @Received
                    let networkService: NetworkService
                }
                """,
                """
                public protocol NetworkService {}

                @Instantiable(fulfillingAdditionalTypes: [NetworkService.self])
                public final class DefaultNetworkService: NetworkService {
                    public init() {}
                }
                """,
                """
                import UIKit

                @Instantiable
                public final class RootViewController: UIViewController {
                    public init(authService: AuthService, networkService: NetworkService, loggedInViewControllerBuilder: ForwardingInstantiator<User, LoggedInViewController>) {
                        self.authService = authService
                        self.networkService = networkService
                        self.loggedInViewControllerBuilder = loggedInViewControllerBuilder
                        derivedValue = false
                        super.init(nibName: nil, bundle: nil)
                    }

                    @Instantiated
                    let networkService: NetworkService

                    @Instantiated
                    let authService: AuthService

                    @Instantiated
                    let loggedInViewControllerBuilder: ForwardingInstantiator<User, LoggedInViewController>

                    private let derivedValue: Bool

                    func login(username: String, password: String) {
                        Task { @MainActor in
                            let user = await authService.login(username: username, password: password)
                            let loggedInViewController = loggedInViewControllerBuilder.instantiate(user)
                            pushViewController(loggedInViewController)
                        }
                    }
                }
                """,
                """
                @Instantiable
                public final class UserService {
                    public init(user: User) {
                        self.user = user
                    }

                    @Received
                    let user: User
                }
                """,
                """
                import UIKit

                @Instantiable
                public final class LoggedInViewController: UIViewController {

                    public init(user: User, networkService: NetworkService, userService: UserService) {
                        self.user = user
                        self.networkService = networkService
                        self.userService = userService
                    }

                    @Forwarded
                    private let user: User

                    @Received
                    let networkService: NetworkService

                    @Instantiated
                    let userService: UserService
                }
                """,
            ],
            dependentModuleNames: [],
            dependentInstantiables: [[]],
            buildDependencyTreeOutput: true
        )

        XCTAssertEqual(
            try XCTUnwrap(output.dependencyTree),
            """
            // This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
            // Any modifications made to this file will be overwritten on subsequent builds.
            // Please refrain from editing this file directly.

            #if canImport(SwiftUI)
            import SwiftUI
            #endif
            #if canImport(UIKit)
            import UIKit
            #endif

            extension RootViewController {
                convenience init() {
                    let networkService: NetworkService = DefaultNetworkService()
                    let authService: AuthService = DefaultAuthService(networkService: networkService)
                    let loggedInViewControllerBuilder = ForwardingInstantiator<User, LoggedInViewController> { user in
                        let userService = UserService(user: user)
                        return LoggedInViewController(user: user, networkService: networkService, userService: userService)
                    }
                    self.init(authService: authService, networkService: networkService, loggedInViewControllerBuilder: loggedInViewControllerBuilder)
                }
            }
            """
        )
    }

    func test_run_writesConvenienceExtensionOnRootOfTree_whenRootInstantiatesPropertiesThatUtilizePropertiesNotDirectlyProvidedByParent() async throws {
        let output = try await SafeDIPlugin.run(
            swiftFileContent: [
                """
                public struct User {}
                """,
                """
                public protocol AuthService {
                    func login(username: String, password: String) async -> User
                }

                @Instantiable(fulfillingAdditionalTypes: [AuthService.self])
                public final class DefaultAuthService: AuthService {
                    public init(networkService: NetworkService) {
                        self.networkService = networkService
                    }

                    public func login(username: String, password: String) async -> User {
                        User()
                    }

                    @Received
                    let networkService: NetworkService
                }
                """,
                """
                public protocol NetworkService {}

                @Instantiable(fulfillingAdditionalTypes: [NetworkService.self])
                public final class DefaultNetworkService: NetworkService {
                    public init() {}
                }
                """,
                """
                import UIKit

                @Instantiable
                public final class RootViewController: UIViewController {
                    public init(authService: AuthService, networkService: NetworkService, loggedInViewControllerBuilder: ForwardingInstantiator<User, LoggedInViewController>) {
                        self.authService = authService
                        self.networkService = networkService
                        self.loggedInViewControllerBuilder = loggedInViewControllerBuilder
                        derivedValue = false
                        super.init(nibName: nil, bundle: nil)
                    }

                    @Instantiated
                    let authService: AuthService

                    @Instantiated
                    let networkService: NetworkService

                    @Instantiated
                    let loggedInViewControllerBuilder: ForwardingInstantiator<User, LoggedInViewController>

                    private let derivedValue: Bool

                    func login(username: String, password: String) {
                        Task { @MainActor in
                            let user = await authService.login(username: username, password: password)
                            let loggedInViewController = loggedInViewControllerBuilder.instantiate(user)
                            pushViewController(loggedInViewController)
                        }
                    }
                }
                """,
                """
                @Instantiable
                public final class UserService {
                    public init(networkService: NetworkService, user: User) {
                        self.networkService = networkService
                        self.user = user
                    }

                    @Received
                    let user: User

                    @Received
                    private let networkService: NetworkService
                }
                """,
                """
                import UIKit

                @Instantiable
                public final class LoggedInViewController: UIViewController {

                    public init(user: User, userService: UserService) {
                        self.user = user
                        self.userService = userService
                    }

                    @Forwarded
                    private let user: User

                    @Instantiated
                    let userService: UserService
                }
                """,
            ],
            dependentModuleNames: [],
            dependentInstantiables: [[]],
            buildDependencyTreeOutput: true
        )

        XCTAssertEqual(
            try XCTUnwrap(output.dependencyTree),
            """
            // This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
            // Any modifications made to this file will be overwritten on subsequent builds.
            // Please refrain from editing this file directly.

            #if canImport(SwiftUI)
            import SwiftUI
            #endif
            #if canImport(UIKit)
            import UIKit
            #endif

            extension RootViewController {
                convenience init() {
                    let networkService: NetworkService = DefaultNetworkService()
                    let authService: AuthService = DefaultAuthService(networkService: networkService)
                    let loggedInViewControllerBuilder = ForwardingInstantiator<User, LoggedInViewController> { user in
                        let userService = UserService(networkService: networkService, user: user)
                        return LoggedInViewController(user: user, userService: userService)
                    }
                    self.init(authService: authService, networkService: networkService, loggedInViewControllerBuilder: loggedInViewControllerBuilder)
                }
            }
            """
        )
    }

    func test_run_writesConvenienceExtensionOnRootOfTree_whenRootInstantiatesPropertiesWithMultipleLayersOfInstantiators() async throws {
        let output = try await SafeDIPlugin.run(
            swiftFileContent: [
                """
                public struct User {}
                """,
                """
                public protocol AuthService {
                    func login(username: String, password: String) async -> User
                }

                @Instantiable(fulfillingAdditionalTypes: [AuthService.self])
                public final class DefaultAuthService: AuthService {
                    public init(networkService: NetworkService) {
                        self.networkService = networkService
                    }

                    public func login(username: String, password: String) async -> User {
                        User()
                    }

                    @Received
                    let networkService: NetworkService
                }
                """,
                """
                public protocol NetworkService {}

                @Instantiable(fulfillingAdditionalTypes: [NetworkService.self])
                public final class DefaultNetworkService: NetworkService {
                    public init() {}
                }
                """,
                """
                import UIKit

                @Instantiable
                public final class RootViewController: UIViewController {
                    public init(authService: AuthService, networkService: NetworkService, loggedInViewControllerBuilder: ForwardingInstantiator<User, LoggedInViewController>) {
                        self.authService = authService
                        self.networkService = networkService
                        self.loggedInViewControllerBuilder = loggedInViewControllerBuilder
                        derivedValue = false
                        super.init(nibName: nil, bundle: nil)
                    }

                    @Instantiated
                    let authService: AuthService

                    @Instantiated
                    let networkService: NetworkService

                    @Instantiated
                    let loggedInViewControllerBuilder: ForwardingInstantiator<User, LoggedInViewController>

                    private let derivedValue: Bool

                    func login(username: String, password: String) {
                        Task { @MainActor in
                            let user = await authService.login(username: username, password: password)
                            let loggedInViewController = loggedInViewControllerBuilder.instantiate(user)
                            pushViewController(loggedInViewController)
                        }
                    }
                }
                """,
                """
                @Instantiable
                public final class UserService {
                    public init(networkService: NetworkService, user: User) {
                        self.networkService = networkService
                        self.user = user
                    }

                    @Received
                    let user: User

                    @Received
                    private let networkService: NetworkService
                }
                """,
                """
                import UIKit

                @Instantiable
                public final class LoggedInViewController: UIViewController {

                    public init(user: User, userServiceInstantiator: Instantiator<UserService>) {
                        self.user = user
                        _userService = LazyInstantiated(userServiceInstantiator)
                    }

                    @Forwarded
                    private let user: User

                    @LazyInstantiated
                    var userService: UserService
                }
                """,
            ],
            dependentModuleNames: [],
            dependentInstantiables: [[]],
            buildDependencyTreeOutput: true
        )

        XCTAssertEqual(
            try XCTUnwrap(output.dependencyTree),
            """
            // This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
            // Any modifications made to this file will be overwritten on subsequent builds.
            // Please refrain from editing this file directly.

            #if canImport(SwiftUI)
            import SwiftUI
            #endif
            #if canImport(UIKit)
            import UIKit
            #endif

            extension RootViewController {
                convenience init() {
                    let networkService: NetworkService = DefaultNetworkService()
                    let authService: AuthService = DefaultAuthService(networkService: networkService)
                    let loggedInViewControllerBuilder = ForwardingInstantiator<User, LoggedInViewController> { user in
                        let userServiceInstantiator = Instantiator<UserService> {
                            UserService(networkService: networkService, user: user)
                        }
                        return LoggedInViewController(user: user, userServiceInstantiator: userServiceInstantiator)
                    }
                    self.init(authService: authService, networkService: networkService, loggedInViewControllerBuilder: loggedInViewControllerBuilder)
                }
            }
            """
        )
    }

    func test_run_writesConvenienceExtensionOnRootOfTree_whenRootInstantiatesPropertiesWithMultipleTreesThatReceiveTheSameProperty() async throws {
        let output = try await SafeDIPlugin.run(
            swiftFileContent: [
                """
                @Instantiable()
                public final class Root {
                    public init(childA: ChildA, childB: ChildB, greatGrandchild: GreatGrandchild) {
                        self.childA = childA
                        self.childB = childB
                        self.greatGrandchild = greatGrandchild
                    }

                    @Instantiated
                    let childA: ChildA
                    @Instantiated
                    let childB: ChildB
                    @Instantiated
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class ChildA {
                    public init(grandchildAA: GrandchildAA, grandchildAB: GrandchildAB) {
                        self.grandchildAA = grandchildAA
                        self.grandchildAB = grandchildAB
                    }

                    @Instantiated
                    let grandchildAA: GrandchildAA
                    @Instantiated
                    let grandchildAB: GrandchildAB
                }
                """,
                """
                @Instantiable()
                public final class GrandchildAA {
                    public init(greatGrandchild: GreatGrandchild) {
                        self.greatGrandchild = greatGrandchild
                    }

                    @Received
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GrandchildAB {
                    public init(greatGrandchild: GreatGrandchild) {
                        self.greatGrandchild = greatGrandchild
                    }

                    @Received
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class ChildB {
                    public init(grandchildBA: GrandchildBA, grandchildBB: GrandchildBB) {
                        self.grandchildAA = grandchildAA
                        self.grandchildAB = grandchildAB
                    }

                    @Instantiated
                    let grandchildBA: GrandchildBA
                    @Instantiated
                    let grandchildBB: GrandchildBB
                }
                """,
                """
                @Instantiable()
                public final class GrandchildBA {
                    public init(greatGrandchild: GreatGrandchild) {
                        self.greatGrandchild = greatGrandchild
                    }

                    @Received
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GrandchildBB {
                    public init(greatGrandchild: GreatGrandchild) {
                        self.greatGrandchild = greatGrandchild
                    }

                    @Received
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GreatGrandchild {
                    public init() {}
                }
                """,

            ],
            dependentModuleNames: [],
            dependentInstantiables: [[]],
            buildDependencyTreeOutput: true
        )

        XCTAssertEqual(
            try XCTUnwrap(output.dependencyTree),
            """
            // This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
            // Any modifications made to this file will be overwritten on subsequent builds.
            // Please refrain from editing this file directly.

            #if canImport(SwiftUI)
            import SwiftUI
            #endif
            #if canImport(UIKit)
            import UIKit
            #endif

            extension Root {
                convenience init() {
                    let greatGrandchild = GreatGrandchild()
                    let childA = {
                        let grandchildAA = GrandchildAA(greatGrandchild: greatGrandchild)
                        let grandchildAB = GrandchildAB(greatGrandchild: greatGrandchild)
                        return ChildA(grandchildAA: grandchildAA, grandchildAB: grandchildAB)
                    }()
                    let childB = {
                        let grandchildBA = GrandchildBA(greatGrandchild: greatGrandchild)
                        let grandchildBB = GrandchildBB(greatGrandchild: greatGrandchild)
                        return ChildB(grandchildBA: grandchildBA, grandchildBB: grandchildBB)
                    }()
                    self.init(childA: childA, childB: childB, greatGrandchild: greatGrandchild)
                }
            }
            """
        )
    }

    func test_run_writesConvenienceExtensionOnRootOfTree_whenRootInstantiatesPropertiesWithMultipleTreesThatInstantiateTheSamePropertyInMiddleLevel() async throws {
        let output = try await SafeDIPlugin.run(
            swiftFileContent: [
                """
                @Instantiable()
                public final class Root {
                    public init(childA: ChildA, childB: ChildB) {
                        self.childA = childA
                        self.childB = childB
                    }

                    @Instantiated
                    let childA: ChildA
                    @Instantiated
                    let childB: ChildB
                }
                """,
                """
                @Instantiable()
                public final class ChildA {
                    public init(grandchildAA: GrandchildAA, grandchildAB: GrandchildAB, greatGrandchild: GreatGrandchild) {
                        self.grandchildAA = grandchildAA
                        self.grandchildAB = grandchildAB
                        self.greatGrandchild = greatGrandchild
                    }

                    @Instantiated
                    let grandchildAA: GrandchildAA
                    @Instantiated
                    let grandchildAB: GrandchildAB
                    @Instantiated
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GrandchildAA {
                    public init(greatGrandchild: GreatGrandchild) {
                        self.greatGrandchild = greatGrandchild
                    }

                    @Received
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GrandchildAB {
                    public init(greatGrandchild: GreatGrandchild) {
                        self.greatGrandchild = greatGrandchild
                    }

                    @Received
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class ChildB {
                    public init(grandchildBA: GrandchildBA, grandchildBB: GrandchildBB, greatGrandchild: GreatGrandchild) {
                        self.grandchildAA = grandchildAA
                        self.grandchildAB = grandchildAB
                        self.greatGrandchild = greatGrandchild
                    }

                    @Instantiated
                    let grandchildBA: GrandchildBA
                    @Instantiated
                    let grandchildBB: GrandchildBB
                    @Instantiated
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GrandchildBA {
                    public init(greatGrandchild: GreatGrandchild) {
                        self.greatGrandchild = greatGrandchild
                    }

                    @Received
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GrandchildBB {
                    public init(greatGrandchild: GreatGrandchild) {
                        self.greatGrandchild = greatGrandchild
                    }

                    @Received
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GreatGrandchild {
                    public init() {}
                }
                """,

            ],
            dependentModuleNames: [],
            dependentInstantiables: [[]],
            buildDependencyTreeOutput: true
        )

        XCTAssertEqual(
            try XCTUnwrap(output.dependencyTree),
            """
            // This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
            // Any modifications made to this file will be overwritten on subsequent builds.
            // Please refrain from editing this file directly.

            #if canImport(SwiftUI)
            import SwiftUI
            #endif
            #if canImport(UIKit)
            import UIKit
            #endif

            extension Root {
                convenience init() {
                    let childA = {
                        let greatGrandchild = GreatGrandchild()
                        let grandchildAA = GrandchildAA(greatGrandchild: greatGrandchild)
                        let grandchildAB = GrandchildAB(greatGrandchild: greatGrandchild)
                        return ChildA(grandchildAA: grandchildAA, grandchildAB: grandchildAB, greatGrandchild: greatGrandchild)
                    }()
                    let childB = {
                        let greatGrandchild = GreatGrandchild()
                        let grandchildBA = GrandchildBA(greatGrandchild: greatGrandchild)
                        let grandchildBB = GrandchildBB(greatGrandchild: greatGrandchild)
                        return ChildB(grandchildBA: grandchildBA, grandchildBB: grandchildBB, greatGrandchild: greatGrandchild)
                    }()
                    self.init(childA: childA, childB: childB)
                }
            }
            """
        )
    }

    func test_run_writesConvenienceExtensionOnRootOfTree_whenRootInstantiatesPropertiesWithMultipleTreesThatInstantiateTheSamePropertyMultipleLayersDeep() async throws {
        let output = try await SafeDIPlugin.run(
            swiftFileContent: [
                """
                @Instantiable()
                public final class Root {
                    public init(childA: ChildA, childB: ChildB) {
                        self.childA = childA
                        self.childB = childB
                    }

                    @Instantiated
                    let childA: ChildA
                    @Instantiated
                    let childB: ChildB
                }
                """,
                """
                @Instantiable()
                public final class ChildA {
                    public init(grandchildAA: GrandchildAA, grandchildAB: GrandchildAB) {
                        self.grandchildAA = grandchildAA
                        self.grandchildAB = grandchildAB
                    }

                    @Instantiated
                    let grandchildAA: GrandchildAA
                    @Instantiated
                    let grandchildAB: GrandchildAB
                }
                """,
                """
                @Instantiable()
                public final class GrandchildAA {
                    public init(greatGrandchild: GreatGrandchild) {
                        self.greatGrandchild = greatGrandchild
                    }

                    @Instantiated
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GrandchildAB {
                    public init(greatGrandchild: GreatGrandchild) {
                        self.greatGrandchild = greatGrandchild
                    }

                    @Instantiated
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class ChildB {
                    public init(grandchildBA: GrandchildBA, grandchildBB: GrandchildBB) {
                        self.grandchildAA = grandchildAA
                        self.grandchildAB = grandchildAB
                    }

                    @Instantiated
                    let grandchildBA: GrandchildBA
                    @Instantiated
                    let grandchildBB: GrandchildBB
                }
                """,
                """
                @Instantiable()
                public final class GrandchildBA {
                    public init(greatGrandchild: GreatGrandchild) {
                        self.greatGrandchild = greatGrandchild
                    }

                    @Instantiated
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GrandchildBB {
                    public init(greatGrandchild: GreatGrandchild) {
                        self.greatGrandchild = greatGrandchild
                    }

                    @Instantiated
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GreatGrandchild {
                    public init() {}
                }
                """,

            ],
            dependentModuleNames: [],
            dependentInstantiables: [[]],
            buildDependencyTreeOutput: true
        )

        XCTAssertEqual(
            try XCTUnwrap(output.dependencyTree),
            """
            // This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
            // Any modifications made to this file will be overwritten on subsequent builds.
            // Please refrain from editing this file directly.

            #if canImport(SwiftUI)
            import SwiftUI
            #endif
            #if canImport(UIKit)
            import UIKit
            #endif

            extension Root {
                convenience init() {
                    let childA = {
                        let grandchildAA = {
                            let greatGrandchild = GreatGrandchild()
                            return GrandchildAA(greatGrandchild: greatGrandchild)
                        }()
                        let grandchildAB = {
                            let greatGrandchild = GreatGrandchild()
                            return GrandchildAB(greatGrandchild: greatGrandchild)
                        }()
                        return ChildA(grandchildAA: grandchildAA, grandchildAB: grandchildAB)
                    }()
                    let childB = {
                        let grandchildBA = {
                            let greatGrandchild = GreatGrandchild()
                            return GrandchildBA(greatGrandchild: greatGrandchild)
                        }()
                        let grandchildBB = {
                            let greatGrandchild = GreatGrandchild()
                            return GrandchildBB(greatGrandchild: greatGrandchild)
                        }()
                        return ChildB(grandchildBA: grandchildBA, grandchildBB: grandchildBB)
                    }()
                    self.init(childA: childA, childB: childB)
                }
            }
            """
        )
    }

    func test_run_writesConvenienceExtensionOnRootOfTree_whenRootInstantiatesPropertiesWithMultipleTreesThatInstantiateAndLazyInstantiateTheSameProperty() async throws {
        let output = try await SafeDIPlugin.run(
            swiftFileContent: [
                """
                @Instantiable()
                public final class Root {
                    public init(childA: ChildA, childB: ChildB) {
                        self.childA = childA
                        self.childB = childB
                    }

                    @Instantiated
                    let childA: ChildA
                    @Instantiated
                    let childB: ChildB
                }
                """,
                """
                @Instantiable()
                public final class ChildA {
                    public init(grandchildAA: GrandchildAA, grandchildAB: GrandchildAB) {
                        self.grandchildAA = grandchildAA
                        self.grandchildAB = grandchildAB
                    }

                    @Instantiated
                    let grandchildAA: GrandchildAA
                    @Instantiated
                    let grandchildAB: GrandchildAB
                }
                """,
                """
                @Instantiable()
                public final class GrandchildAA {
                    public init(greatGrandchild: GreatGrandchild) {
                        self.greatGrandchild = greatGrandchild
                    }

                    @Instantiated
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GrandchildAB {
                    public init(greatGrandchild: GreatGrandchild) {
                        self.greatGrandchild = greatGrandchild
                    }

                    @Instantiated
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class ChildB {
                    public init(grandchildBA: GrandchildBA, grandchildBB: GrandchildBB) {
                        self.grandchildAA = grandchildAA
                        self.grandchildAB = grandchildAB
                    }

                    @Instantiated
                    let grandchildBA: GrandchildBA
                    @Instantiated
                    let grandchildBB: GrandchildBB
                }
                """,
                """
                @Instantiable()
                public final class GrandchildBA {
                    public init(greatGrandchildInstantiator: Instantiator<GreatGrandchild>) {
                        _greatGrandchild = LazyInstantiated(greatGrandchildInstantiator)
                    }

                    @LazyInstantiated
                    var greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GrandchildBB {
                    public init(greatGrandchildInstantiator: Instantiator<GreatGrandchild>) {
                        _greatGrandchild = LazyInstantiated(greatGrandchildInstantiator)
                    }

                    @LazyInstantiated
                    var greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GreatGrandchild {
                    public init() {}
                }
                """,
            ],
            dependentModuleNames: [],
            dependentInstantiables: [[]],
            buildDependencyTreeOutput: true
        )

        XCTAssertEqual(
            try XCTUnwrap(output.dependencyTree),
            """
            // This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
            // Any modifications made to this file will be overwritten on subsequent builds.
            // Please refrain from editing this file directly.

            #if canImport(SwiftUI)
            import SwiftUI
            #endif
            #if canImport(UIKit)
            import UIKit
            #endif

            extension Root {
                convenience init() {
                    let childA = {
                        let grandchildAA = {
                            let greatGrandchild = GreatGrandchild()
                            return GrandchildAA(greatGrandchild: greatGrandchild)
                        }()
                        let grandchildAB = {
                            let greatGrandchild = GreatGrandchild()
                            return GrandchildAB(greatGrandchild: greatGrandchild)
                        }()
                        return ChildA(grandchildAA: grandchildAA, grandchildAB: grandchildAB)
                    }()
                    let childB = {
                        let grandchildBA = {
                            let greatGrandchildInstantiator = Instantiator<GreatGrandchild> {
                                GreatGrandchild()
                            }
                            return GrandchildBA(greatGrandchildInstantiator: greatGrandchildInstantiator)
                        }()
                        let grandchildBB = {
                            let greatGrandchildInstantiator = Instantiator<GreatGrandchild> {
                                GreatGrandchild()
                            }
                            return GrandchildBB(greatGrandchildInstantiator: greatGrandchildInstantiator)
                        }()
                        return ChildB(grandchildBA: grandchildBA, grandchildBB: grandchildBB)
                    }()
                    self.init(childA: childA, childB: childB)
                }
            }
            """
        )
    }

    func test_run_writesConvenienceExtensionOnRootOfTree_whenRootInstantiatesPropertiesWithMultipleTreesThatInstantiateAndLazyInstantiateTheSamePropertyAcrossMultipleModules() async throws {
        let greatGrandchildModuleOutput = try await SafeDIPlugin.run(
            swiftFileContent: [
                """
                @Instantiable()
                public final class GreatGrandchild {
                    public init() {}
                }
                """,
            ],
            dependentModuleNames: [],
            dependentInstantiables: [[]],
            buildDependencyTreeOutput: false
        )

        let grandchildModuleOutput = try await SafeDIPlugin.run(
            swiftFileContent: [
                """
                @Instantiable()
                public final class GrandchildAA {
                    public init(greatGrandchild: GreatGrandchild) {
                        self.greatGrandchild = greatGrandchild
                    }

                    @Instantiated
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GrandchildAB {
                    public init(greatGrandchild: GreatGrandchild) {
                        self.greatGrandchild = greatGrandchild
                    }

                    @Instantiated
                    let greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GrandchildBA {
                    public init(greatGrandchildInstantiator: Instantiator<GreatGrandchild>) {
                        _greatGrandchild = LazyInstantiated(greatGrandchildInstantiator)
                    }

                    @LazyInstantiated
                    var greatGrandchild: GreatGrandchild
                }
                """,
                """
                @Instantiable()
                public final class GrandchildBB {
                    public init(greatGrandchildInstantiator: Instantiator<GreatGrandchild>) {
                        _greatGrandchild = LazyInstantiated(greatGrandchildInstantiator)
                    }

                    @LazyInstantiated
                    var greatGrandchild: GreatGrandchild
                }
                """,
            ],
            dependentModuleNames: ["GreatGrandchildModule"],
            dependentInstantiables: [greatGrandchildModuleOutput.instantiables],
            buildDependencyTreeOutput: false
        )

        let childModuleOutput = try await SafeDIPlugin.run(
            swiftFileContent: [
                """
                @Instantiable()
                public final class ChildA {
                    public init(grandchildAA: GrandchildAA, grandchildAB: GrandchildAB) {
                        self.grandchildAA = grandchildAA
                        self.grandchildAB = grandchildAB
                    }

                    @Instantiated
                    let grandchildAA: GrandchildAA
                    @Instantiated
                    let grandchildAB: GrandchildAB
                }
                """,
                """
                @Instantiable()
                public final class ChildB {
                    public init(grandchildBA: GrandchildBA, grandchildBB: GrandchildBB) {
                        self.grandchildAA = grandchildAA
                        self.grandchildAB = grandchildAB
                    }

                    @Instantiated
                    let grandchildBA: GrandchildBA
                    @Instantiated
                    let grandchildBB: GrandchildBB
                }
                """,
            ],
            dependentModuleNames: ["GrandchildModule", "GreatGrandchildModule"],
            dependentInstantiables: [
                greatGrandchildModuleOutput.instantiables,
                grandchildModuleOutput.instantiables,
            ],
            buildDependencyTreeOutput: false
        )

        let topLevelModuleOutput = try await SafeDIPlugin.run(
            swiftFileContent: [
                """
                @Instantiable()
                public final class Root {
                    public init(childA: ChildA, childB: ChildB) {
                        self.childA = childA
                        self.childB = childB
                    }

                    @Instantiated
                    let childA: ChildA
                    @Instantiated
                    let childB: ChildB
                }
                """
            ],
            dependentModuleNames: ["ChildModule", "GrandchildModule", "GreatGrandchildModule"],
            dependentInstantiables: [
                greatGrandchildModuleOutput.instantiables,
                grandchildModuleOutput.instantiables,
                childModuleOutput.instantiables
            ],
            buildDependencyTreeOutput: true
        )

        XCTAssertEqual(
            try XCTUnwrap(topLevelModuleOutput.dependencyTree),
            """
            // This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
            // Any modifications made to this file will be overwritten on subsequent builds.
            // Please refrain from editing this file directly.

            #if canImport(ChildModule)
            import ChildModule
            #endif
            #if canImport(GrandchildModule)
            import GrandchildModule
            #endif
            #if canImport(GreatGrandchildModule)
            import GreatGrandchildModule
            #endif
            #if canImport(SwiftUI)
            import SwiftUI
            #endif
            #if canImport(UIKit)
            import UIKit
            #endif

            extension Root {
                convenience init() {
                    let childA = {
                        let grandchildAA = {
                            let greatGrandchild = GreatGrandchild()
                            return GrandchildAA(greatGrandchild: greatGrandchild)
                        }()
                        let grandchildAB = {
                            let greatGrandchild = GreatGrandchild()
                            return GrandchildAB(greatGrandchild: greatGrandchild)
                        }()
                        return ChildA(grandchildAA: grandchildAA, grandchildAB: grandchildAB)
                    }()
                    let childB = {
                        let grandchildBA = {
                            let greatGrandchildInstantiator = Instantiator<GreatGrandchild> {
                                GreatGrandchild()
                            }
                            return GrandchildBA(greatGrandchildInstantiator: greatGrandchildInstantiator)
                        }()
                        let grandchildBB = {
                            let greatGrandchildInstantiator = Instantiator<GreatGrandchild> {
                                GreatGrandchild()
                            }
                            return GrandchildBB(greatGrandchildInstantiator: greatGrandchildInstantiator)
                        }()
                        return ChildB(grandchildBA: grandchildBA, grandchildBB: grandchildBB)
                    }()
                    self.init(childA: childA, childB: childB)
                }
            }
            """
        )
    }

    // MARK: Error Tests

    func test_run_onCodeWithUnfulfillableInstantiatedProperty_throwsError() async {
        await assertThrowsError(
            """
            No `@Instantiable`-decorated type found to fulfill `@Instantiated` or  `@LazyInstantiated`-decorated property with type `URLSession`
            """
        ) {
            try await SafeDIPlugin.run(
                swiftFileContent: [
                    """
                    import Foundation

                    public protocol NetworkService {}

                    @Instantiable(fulfillingAdditionalType: [NetworkService.self])
                    public final class DefaultNetworkService: NetworkService {
                        public init(urlSession: URLSession) {
                            self.urlSession = urlSession
                        }

                        @Instantiated
                        let urlSession: URLSession // URLSession is not `@Instantiable`! This will fail!
                    }
                    """,
                    """
                    import UIKit

                    @Instantiable
                    public final class RootViewController: UIViewController {
                        public init(networkService: NetworkService) {
                            self.networkService = networkService
                        }

                        @Instantiated
                        let networkService: NetworkService
                    }
                    """,
                ],
                dependentModuleNames: [],
                dependentInstantiables: [[]],
                buildDependencyTreeOutput: true
            )
        }
    }

    func test_run_onCodeWithUnfulfillableReceivedProperty_throwsError() async {
        await assertThrowsError(
            """
            The following received properties were never instantiated:
            `urlSession: URLSession` is not instantiated in chain: RootViewController -> DefaultNetworkService
            """
        ) {
            try await SafeDIPlugin.run(
                swiftFileContent: [
                    """
                    import Foundation

                    public protocol NetworkService {}

                    @Instantiable(fulfillingAdditionalType: [NetworkService.self])
                    public final class DefaultNetworkService: NetworkService {
                        public init(urlSession: URLSession) {
                            self.urlSession = urlSession
                        }

                        @Received
                        let urlSession: URLSession // URLSession is not `@Instantiable`! This will fail!
                    }
                    """,
                    """
                    import UIKit

                    @Instantiable
                    public final class RootViewController: UIViewController {
                        public init(networkService: NetworkService) {
                            self.networkService = networkService
                        }

                        @Instantiated
                        let networkService: NetworkService
                    }
                    """,
                ],
                dependentModuleNames: [],
                dependentInstantiables: [[]],
                buildDependencyTreeOutput: true
            )
        }
    }

    func test_run_onCodeWithNestedInstantiable_throwsError() async {
        await assertThrowsError(
            """
            @Instantiable types must be top-level declarations. Found the following nested @Instantiable types: SplashViewController
            """
        ) {
            try await SafeDIPlugin.run(
                swiftFileContent: [
                    """
                    import UIKit

                    @Instantiable
                    public final class RootViewController: UIViewController {
                        public init() {}

                        @Instantiable
                        public final class SplashViewController: UIViewController {
                            public init() {}
                        }
                    }
                    """,
                ],
                dependentModuleNames: [],
                dependentInstantiables: [[]],
                buildDependencyTreeOutput: true
            )
        }
    }

    func test_run_onCodeWithMultipleNestedInstantiable_throwsError() async {
        await assertThrowsError(
            """
            @Instantiable types must be top-level declarations. Found the following nested @Instantiable types: AuthenticatedViewController, SplashViewController
            """
        ) {
            try await SafeDIPlugin.run(
                swiftFileContent: [
                    """
                    import UIKit

                    @Instantiable
                    public final class RootViewController: UIViewController {
                        public init() {}

                        @Instantiable
                        public final class SplashViewController: UIViewController {
                            public init() {}
                        }

                        @Instantiable
                        public final class AuthenticatedViewController: UIViewController {
                            public init() {}
                        }
                    }
                    """,
                ],
                dependentModuleNames: [],
                dependentInstantiables: [[]],
                buildDependencyTreeOutput: true
            )
        }
    }

    func test_run_onCodeWithDuplicateInstantiable_throwsError() async {
        await assertThrowsError(
            """
            @Instantiable-decorated types must have globally unique type names and fulfill globally unqiue types. Found multiple @Instantiable-decorated types fulfilling `RootViewController`
            """
        ) {
            try await SafeDIPlugin.run(
                swiftFileContent: [
                    """
                    import UIKit

                    @Instantiable
                    public final class RootViewController: UIViewController {
                        public init() {}
                    }
                    """,
                    """
                    import UIKit

                    @Instantiable
                    public final class RootViewController: UIViewController {
                        public init() {}
                    }
                    """,
                ],
                dependentModuleNames: [],
                dependentInstantiables: [[]],
                buildDependencyTreeOutput: true
            )
        }
    }

    func test_run_onCodeWithDuplicateInstantiableFulfillment_throwsError() async {
        await assertThrowsError(
            """
            @Instantiable-decorated types must have globally unique type names and fulfill globally unqiue types. Found multiple @Instantiable-decorated types fulfilling `UIViewController`
            """
        ) {
            try await SafeDIPlugin.run(
                swiftFileContent: [
                    """
                    import UIKit

                    @Instantiable(fulfillingAdditionalType: [UIViewController.self])
                    public final class RootViewController: UIViewController {
                        public init() {}
                    }
                    """,
                    """
                    import UIKit

                    @Instantiable(fulfillingAdditionalType: [UIViewController.self])
                    public final class SplashViewController: UIViewController {
                        public init() {}
                    }
                    """,
                ],
                dependentModuleNames: [],
                dependentInstantiables: [[]],
                buildDependencyTreeOutput: true
            )
        }
    }


    func test_run_onCodeWithCircularPropertyDependenciesInSameCombinedScope_throwsError() async {
        await assertThrowsError(
            """
            Dependency cycle detected!
            DefaultNetworkService -> DefaultLoggingService -> DefaultNetworkService
            """
        ) {
            try await SafeDIPlugin.run(
                swiftFileContent: [
                    """
                    import Foundation

                    public protocol NetworkService {}

                    @Instantiable(fulfillingAdditionalType: [NetworkService.self])
                    public final class DefaultNetworkService: NetworkService {
                        public init(loggingService: LoggingService) {
                            self.loggingService = loggingService
                        }

                        @Instantiated
                        let loggingService: LoggingService
                    }
                    """,
                    """
                    import Foundation

                    public protocol LoggingService {}

                    @Instantiable(fulfillingAdditionalType: [LoggingService.self])
                    public final class DefaultLoggingService: LoggingService {
                        public init(networkService: NetworkService) {
                            self.networkService = networkService
                        }

                        @Instantiated
                        let networkService: NetworkService
                    }
                    """,
                    """
                    import UIKit

                    @Instantiable
                    public final class RootViewController: UIViewController {
                        public init(networkService: NetworkService) {
                            self.networkService = networkService
                        }

                        @Instantiated
                        let networkService: NetworkService
                    }
                    """,
                ],
                dependentModuleNames: [],
                dependentInstantiables: [[]],
                buildDependencyTreeOutput: true
            )
        }
    }

    func test_run_onCodeWithCircularPropertyDependenciesInDifferentCombinedScopes_throwsError() async {
        await assertThrowsError(
            """
            Dependency cycle detected!
            UserManager -> AuthenticatedViewController -> UserManager
            """
        ) {
            try await SafeDIPlugin.run(
                swiftFileContent: [
                    """
                    @Instantiable
                    public final class UserManager {
                        public init(authenticatedViewControllerBuilder: ForwardingInstantiator<User, AuthenticatedViewController>) {
                            self.authenticatedViewControllerBuilder = authenticatedViewControllerBuilder
                        }

                        @Instantiated
                        let authenticatedViewControllerBuilder: ForwardingInstantiator<User, AuthenticatedViewController>

                        var user: User
                    }
                    """,
                    """
                    import UIKit

                    @Instantiable
                    public final class AuthenticatedViewController: UIViewController {
                        public init(userManager: UserManager) {
                            self.userManager = userManager
                        }

                        @Instantiated
                        let userManager: UserManager
                    }
                    """,
                    """
                    import UIKit

                    @Instantiable
                    public final class RootViewController: UIViewController {
                        public init(userManager: UserManager) {
                            self.userManager = userManager
                        }

                        @Instantiated
                        let userManager: UserManager
                    }
                    """,
                ],
                dependentModuleNames: [],
                dependentInstantiables: [[]],
                buildDependencyTreeOutput: true
            )
        }
    }
    
    private func assertThrowsError<ReturnType>(
        _ errorDescription: String,
        line: UInt = #line,
        block: () async throws -> ReturnType
    ) async {
        var didThrow = false
        do {
            _ = try await block()
        } catch {
            didThrow = true
            XCTAssertEqual((error as CustomStringConvertible).description, errorDescription, line: line)
        }
        XCTAssertTrue(didThrow, "Did not throw error!", line: line)
    }
}
