// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Collections

public actor DependencyTreeGenerator {
	// MARK: Initialization

	public init(
		importStatements: [ImportStatement],
		typeDescriptionToFulfillingInstantiableMap: [TypeDescription: Instantiable],
	) {
		self.importStatements = importStatements
		self.typeDescriptionToFulfillingInstantiableMap = typeDescriptionToFulfillingInstantiableMap
	}

	// MARK: Public

	public struct GeneratedRoot: Sendable {
		public let typeDescription: TypeDescription
		public let sourceFilePath: String?
		/// The generated extension code for this root, without the file header.
		public let code: String
	}

	/// The file header to prepend to each generated output file.
	public var fileHeader: String {
		let importsWhitespace = imports.isEmpty ? "" : "\n"
		return "// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.\n// Any modifications made to this file will be overwritten on subsequent builds.\n// Please refrain from editing this file directly.\n\(importsWhitespace)\(imports)\(importsWhitespace)\n"
	}

	public func generatePerRootCodeTrees() async throws -> [GeneratedRoot] {
		let rootScopeGenerators = try rootScopeGenerators

		return try await withThrowingTaskGroup(
			of: GeneratedRoot?.self,
			returning: [GeneratedRoot].self,
		) { taskGroup in
			for rootInfo in rootScopeGenerators {
				taskGroup.addTask {
					let code = try await rootInfo.scopeGenerator.generateCode()
					return GeneratedRoot(
						typeDescription: rootInfo.typeDescription,
						sourceFilePath: rootInfo.sourceFilePath,
						code: code,
					)
				}
			}
			var generatedRoots = [GeneratedRoot]()
			for try await generatedRoot in taskGroup {
				if let generatedRoot {
					generatedRoots.append(generatedRoot)
				}
			}
			return generatedRoots
		}
	}

	/// Generates mock code for all `@Instantiable` types.
	public func generateMockCode(
		mockConditionalCompilation: String?,
		currentModuleSourceFilePaths: Set<String>? = nil,
		moduleGenerateMocks: Bool = true,
	) async throws -> [GeneratedRoot] {
		// Build a map of erased wrapper types → concrete fulfilling types.
		// This lets mocks construct types like AnyUserService(DefaultUserService())
		// even when the erased type isn't directly @Instantiable.
		var erasedToConcreteTypeMap = [TypeDescription: TypeDescription]()
		for instantiable in typeDescriptionToFulfillingInstantiableMap.values {
			for dependency in instantiable.dependencies {
				if case let .instantiated(fulfillingTypeDescription, erasedToConcreteExistential) = dependency.source,
				   erasedToConcreteExistential,
				   let concreteType = fulfillingTypeDescription?.asInstantiatedType
				{
					erasedToConcreteTypeMap[dependency.property.typeDescription] = concreteType
				}
			}
		}

		// Build mock scope mapping — like production but includes all types and
		// promotes received dependencies as instantiated children.
		let typeDescriptionToScopeMap = createMockTypeDescriptionToScopeMapping()

		// Create mock-root ScopeGenerators using the production Scope tree.
		var seen = Set<TypeDescription>()
		return try await withThrowingTaskGroup(
			of: GeneratedRoot?.self,
			returning: [GeneratedRoot].self,
		) { taskGroup in
			for instantiable in typeDescriptionToFulfillingInstantiableMap.values
				.sorted(by: { $0.concreteInstantiable < $1.concreteInstantiable })
			{
				// Skip types with user-defined mock methods, duplicates, types not in the scope map,
				// types from dependent modules (their module generates their own mocks),
				// and types where mock generation is disabled.
				let effectiveGenerateMock = instantiable.generateMock ?? moduleGenerateMocks
				guard effectiveGenerateMock,
				      instantiable.mockInitializer == nil,
				      seen.insert(instantiable.concreteInstantiable).inserted,
				      let scope = typeDescriptionToScopeMap[instantiable.concreteInstantiable]
				else { continue }
				if let currentModuleSourceFilePaths {
					guard let sourceFilePath = instantiable.sourceFilePath,
					      currentModuleSourceFilePaths.contains(sourceFilePath)
					else { continue }
				}

				let mockRoot = try createMockRootScopeGenerator(
					for: instantiable,
					scope: scope,
					typeDescriptionToScopeMap: typeDescriptionToScopeMap,
					erasedToConcreteTypeMap: erasedToConcreteTypeMap,
				)
				taskGroup.addTask {
					let code = try await mockRoot.generateCode(
						codeGeneration: .mock(ScopeGenerator.MockContext(
							mockConditionalCompilation: mockConditionalCompilation,
						)),
					)
					guard !code.isEmpty else { return nil }
					return GeneratedRoot(
						typeDescription: instantiable.concreteInstantiable,
						sourceFilePath: instantiable.sourceFilePath,
						code: code,
					)
				}
			}
			var generatedRoots = [GeneratedRoot]()
			for try await generatedRoot in taskGroup {
				if let generatedRoot {
					generatedRoots.append(generatedRoot)
				}
			}
			return generatedRoots
		}
	}

	public func generateDOTTree() async throws -> String {
		let rootScopeGenerators = try rootScopeGenerators

		let dependencyTree = try await withThrowingTaskGroup(
			of: String.self,
			returning: String.self,
		) { taskGroup in
			for rootInfo in rootScopeGenerators {
				taskGroup.addTask { try await rootInfo.scopeGenerator.generateDOT() }
			}
			var generatedRoots = [String]()
			for try await generatedRoot in taskGroup {
				generatedRoots.append(generatedRoot)
			}
			return generatedRoots.removingEmpty().sorted().joined(separator: "\n\n")
		}

		return """
		\(dependencyTree)
		"""
	}

	// MARK: - DependencyTreeGeneratorError

	private enum DependencyTreeGeneratorError: Error, CustomStringConvertible {
		case noInstantiableFound(TypeDescription)
		case unfulfillableProperties([UnfulfillableProperty])
		case instantiableHasForwardedProperty(property: Property, instantiableWithForwardedProperty: Instantiable, parent: Instantiable)
		case constantDependencyCycleDetected([TypeDescription])
		case receivedInstantiatorDependencyCycleDetected(property: Property, directParent: TypeDescription, cycle: [TypeDescription])
		case receivedConstantCycleDetected(instantiated: Property, receivedPropertyChain: [Property])

		var description: String {
			switch self {
			case let .noInstantiableFound(typeDescription):
				"No `@\(InstantiableVisitor.macroName)`-decorated type or extension found to fulfill `@\(Dependency.Source.instantiatedRawValue)`-decorated property with type `\(typeDescription.asSource)`"
			case let .unfulfillableProperties(unfulfillableProperties):
				"""
				\(unfulfillableProperties.map {
					if $0.property.typeDescription.isOptional,
					   let nonOptionalAlternative = $0.suggestedAlternatives.first(where: { [unfulfilledProperty = $0.property] alternative in
					   	alternative.label == unfulfilledProperty.label
					   		&& alternative.typeDescription == unfulfilledProperty.typeDescription.unwrapped
					   })
					{
						"""
						@\(Dependency.Source.receivedRawValue) property `\($0.property.asSource)` is not @\(Dependency.Source.instantiatedRawValue) or @\(Dependency.Source.forwardedRawValue) in chain:\n\t\(([$0.instantiable.concreteInstantiable] + $0.parentStack)
							.reversed()
							.map(\.asSource)
							.joined(separator: " -> "))\($0.suggestedAlternatives.isEmpty ? "" : "\n\nThe non-optional `\(nonOptionalAlternative.asSource)` is available in chain. Did you mean to decorate this property with `@\(Dependency.Source.receivedRawValue)(onlyIfAvailable: true)`?")
						"""
					} else {
						"""
						@\(Dependency.Source.receivedRawValue) property `\($0.property.asSource)` is not @\(Dependency.Source.instantiatedRawValue) or @\(Dependency.Source.forwardedRawValue) in chain:\n\t\(([$0.instantiable.concreteInstantiable] + $0.parentStack)
							.reversed()
							.map(\.asSource)
							.joined(separator: " -> "))\($0.suggestedAlternatives.isEmpty ? "" : "\n\nDid you mean one of the following available properties?\n\($0.suggestedAlternatives.map { "\t`\($0.asSource)`" }.joined(separator: "\n"))")
						"""
					}
				}
				.sorted()
				.joined(separator: "\n\n"))
				"""
			case let .instantiableHasForwardedProperty(property, instantiable, parent):
				"Property `\(property.asSource)` on \(parent.concreteInstantiable.asSource) has at least one @\(Dependency.Source.forwardedRawValue) property. Property should instead be of type `\(Dependency.instantiatorType)<\(instantiable.concreteInstantiable.asSource)>`."
			case let .constantDependencyCycleDetected(instantiables):
				"""
				Dependency cycle detected:
				\t\(instantiables
					.map(\.asSource)
					.reversed()
					.joined(separator: " -> "))
				"""
			case let .receivedInstantiatorDependencyCycleDetected(property, directParent, instantiables):
				"""
				Dependency cycle detected! @\(Dependency.Source.instantiatedRawValue) `\(property.asSource)` is @\(Dependency.Source.receivedRawValue) in tree created by @\(Dependency.Source.instantiatedRawValue) `\(property.asSource)`. Declare @\(Dependency.Source.receivedRawValue) `\(property.asSource)` on `\(directParent.asSource)` as @\(Dependency.Source.instantiatedRawValue) to fix. Full cycle:
				\t\(instantiables
					.map(\.asSource)
					.reversed()
					.joined(separator: " -> "))
				"""
			case let .receivedConstantCycleDetected(instantiated, receivedPropertyChain):
				"""
				Dependency received in same chain it is instantiated:
				\t\("@\(Dependency.Source.instantiatedRawValue) \(instantiated.asSource) -> "
					+ receivedPropertyChain
					.map { "@\(Dependency.Source.receivedRawValue) \($0.asSource)" }
					.joined(separator: " -> "))
				"""
			}
		}

		struct UnfulfillableProperty: Hashable {
			let property: Property
			let instantiable: Instantiable
			let parentStack: [TypeDescription]
			let suggestedAlternatives: [Property]
		}
	}

	// MARK: Private

	private let importStatements: [ImportStatement]
	private let typeDescriptionToFulfillingInstantiableMap: [TypeDescription: Instantiable]
	private struct RootScopeInfo {
		let typeDescription: TypeDescription
		let sourceFilePath: String?
		let scopeGenerator: ScopeGenerator
	}

	private var rootScopeGenerators: [RootScopeInfo] {
		get throws {
			let rootScopeGenerators: [RootScopeInfo] = try {
				try validateReachableTypeDescriptions()

				let typeDescriptionToScopeMap = try createTypeDescriptionToScopeMapping()
				try validatePropertiesAreFulfillable(typeDescriptionToScopeMap: typeDescriptionToScopeMap)
				return try rootInstantiables
					.sorted()
					.compactMap { typeDescription in
						try typeDescriptionToScopeMap[typeDescription].map { scope in
							try RootScopeInfo(
								typeDescription: typeDescription,
								sourceFilePath: typeDescriptionToFulfillingInstantiableMap[typeDescription]?.sourceFilePath,
								scopeGenerator: scope.createScopeGenerator(
									for: nil,
									propertyStack: [],
									receivableProperties: [],
									erasedToConcreteExistential: false,
								),
							)
						}
					}
			}()
			return rootScopeGenerators
		}
	}

	private var imports: String {
		importStatements
			.reduce(into: [String: Set<ImportStatement>]()) { partialResult, importStatement in
				var importsForModuleName = partialResult[importStatement.moduleName, default: []]
				importsForModuleName.insert(importStatement)
				partialResult[importStatement.moduleName] = importsForModuleName
			}
			.flatMap {
				if let wholeModuleImport = $0.value.first(where: {
					$0.kind.isEmpty
						&& $0.type.isEmpty
				}) {
					[wholeModuleImport]
				} else {
					Array($0.value)
				}
			}
			.map {
				"""
				#if canImport(\($0.moduleName))
				\($0.asSource)
				#endif
				"""
			}
			.sorted()
			.joined(separator: "\n")
	}

	/// Creates a mock-root ScopeGenerator using the production Scope tree.
	/// Unsatisfied received dependencies are promoted as root-level children
	/// on a NEW Scope (the shared Scope is never mutated).
	private func createMockRootScopeGenerator(
		for instantiable: Instantiable,
		scope: Scope,
		typeDescriptionToScopeMap: [TypeDescription: Scope],
		erasedToConcreteTypeMap: [TypeDescription: TypeDescription],
	) throws -> ScopeGenerator {
		// Recursively collect all transitive received properties from the scope tree
		// and any promoted scopes' subtrees. Results are cached per Scope identity
		// (via ObjectIdentifier) so each scope is visited at most once — O(total_scopes).
		var cache = [ObjectIdentifier: (received: Set<Property>, onlyIfAvailable: Set<Property>)]()
		let (initialReceived, initialOnlyIfAvailable) = Self.collectReceivedProperties(
			from: scope,
			cache: &cache,
		)

		// Worklist: promoted scopes may introduce additional transitive received properties.
		var allReceived = initialReceived
		var allOnlyIfAvailable = initialOnlyIfAvailable
		var visitedTypes = Set<TypeDescription>()
		var worklist = Array(allReceived)

		while let property = worklist.popLast() {
			// Don't walk into scopes for onlyIfAvailable dependencies.
			// They become optional mock parameters with no default construction,
			// so their transitive dependencies don't need promoting.
			guard !allOnlyIfAvailable.contains(property) else { continue }

			var dependencyType = property.typeDescription.asInstantiatedType
			if typeDescriptionToScopeMap[dependencyType] == nil,
			   let concreteType = erasedToConcreteTypeMap[property.typeDescription]
			{
				dependencyType = concreteType
			}
			guard let promotedScope = typeDescriptionToScopeMap[dependencyType],
			      visitedTypes.insert(dependencyType).inserted
			else { continue }

			let (scopeReceived, scopeOnlyIfAvailable) = Self.collectReceivedProperties(
				from: promotedScope,
				cache: &cache,
			)
			for newProperty in scopeReceived where allReceived.insert(newProperty).inserted {
				worklist.append(newProperty)
			}
			allOnlyIfAvailable.formUnion(scopeOnlyIfAvailable)
		}

		// Promote all received properties that have scopes.
		// onlyIfAvailable dependencies are NOT promoted — they become optional
		// mock parameters with no default.
		// Filter out forwarded properties — they're bare mock parameters, not promoted children.
		// ScopeData.root doesn't carry forwardedProperties, so receivedProperties doesn't
		// subtract them. We filter them here instead.
		let forwardedProperties = Set(
			instantiable.dependencies
				.filter { $0.source == .forwarded }
				.map(\.property),
		)
		let mockRootScope = Scope(instantiable: instantiable)
		mockRootScope.propertiesToGenerate = scope.propertiesToGenerate

		for receivedProperty in allReceived.sorted() {
			guard !allOnlyIfAvailable.contains(receivedProperty),
			      !forwardedProperties.contains(receivedProperty)
			else { continue }

			var dependencyType = receivedProperty.typeDescription.asInstantiatedType
			var erasedToConcreteExistential = false
			if typeDescriptionToScopeMap[dependencyType] == nil,
			   let concreteType = erasedToConcreteTypeMap[receivedProperty.typeDescription]
			{
				dependencyType = concreteType
				erasedToConcreteExistential = true
			}
			guard let receivedScope = typeDescriptionToScopeMap[dependencyType] else {
				continue
			}
			mockRootScope.propertiesToGenerate.append(.instantiated(
				receivedProperty,
				receivedScope,
				erasedToConcreteExistential: erasedToConcreteExistential,
			))
		}

		// Build the final ScopeGenerator once.
		return try mockRootScope.createScopeGenerator(
			for: nil,
			propertyStack: [],
			receivableProperties: [],
			erasedToConcreteExistential: false,
			forMockGeneration: true,
		)
	}

	/// Recursively collects all unsatisfied received properties from a Scope tree.
	/// Mirrors ScopeGenerator's `receivedProperties` and `onlyIfAvailableUnwrappedReceivedProperties`
	/// computation but operates on Scope objects directly, with memoization for O(1) revisits.
	private static func collectReceivedProperties(
		from scope: Scope,
		cache: inout [ObjectIdentifier: (received: Set<Property>, onlyIfAvailable: Set<Property>)],
	) -> (received: Set<Property>, onlyIfAvailable: Set<Property>) {
		let id = ObjectIdentifier(scope)
		if let cached = cache[id] { return cached }
		// Cycle sentinel — re-entrant calls return empty (cycles contribute no new received).
		cache[id] = ([], [])

		// Properties declared at this scope (instantiated/aliased children).
		let propertiesToDeclare = Set(scope.propertiesToGenerate.compactMap { propertyToGenerate -> Property? in
			switch propertyToGenerate {
			case let .instantiated(property, _, _): return property
			case let .aliased(property, _, _, _): return property
			}
		})

		// Forwarded properties at this scope.
		let forwardedProperties = Set(
			scope.instantiable.dependencies
				.filter { $0.source == .forwarded }
				.map(\.property),
		)

		var received = Set<Property>()
		var onlyIfAvailable = Set<Property>()

		// Collect from instantiated children — mirrors ScopeGenerator's receivedProperties aggregation.
		// Aliases are handled below in the own-dependency loop: alias children's receivedProperties
		// = [fulfillingProperty], but the own-dependency union unconditionally adds the same
		// fulfillingProperty, making the child-path subtraction/filter redundant.
		for case let .instantiated(_, childScope, _) in scope.propertiesToGenerate {
			let (childReceived, childOnlyIfAvailable) = collectReceivedProperties(
				from: childScope,
				cache: &cache,
			)
			received.formUnion(
				childReceived
					.subtracting(propertiesToDeclare)
					.filter { property in
						!property.typeDescription.isOptional
							|| !propertiesToDeclare.contains(property.asUnwrappedProperty)
					}
					.subtracting(forwardedProperties),
			)
			// Subtract by unwrapped form — a declared `x: X` satisfies onlyIfAvailable `x: X?`.
			onlyIfAvailable.formUnion(
				childOnlyIfAvailable.filter { property in
					!propertiesToDeclare.contains(property.asUnwrappedProperty)
						&& !forwardedProperties.contains(property.asUnwrappedProperty)
				},
			)
		}

		// This scope's own received/aliased dependencies.
		// Store exact properties (not unwrapped) in onlyIfAvailable. This avoids
		// collisions between a required `x: X` and an onlyIfAvailable `x: X?` —
		// they are distinct Properties. The subtraction above uses unwrapped comparison
		// to correctly subtract when a declared property satisfies an optional one.
		for dependency in scope.instantiable.dependencies {
			switch dependency.source {
			case let .received(isOnlyIfAvailable):
				received.insert(dependency.property)
				if isOnlyIfAvailable {
					onlyIfAvailable.insert(dependency.property)
				}
			case let .aliased(fulfillingProperty, _, isOnlyIfAvailable):
				received.insert(fulfillingProperty)
				if isOnlyIfAvailable {
					onlyIfAvailable.insert(fulfillingProperty)
				}
			case .instantiated, .forwarded:
				break
			}
		}

		let result = (received, onlyIfAvailable)
		cache[id] = result
		return result
	}

	/// Builds a scope mapping for mock generation. Similar to `createTypeDescriptionToScopeMapping`
	/// but includes ALL types (not just reachable from roots). Received dependencies are NOT
	/// promoted here — they're promoted at the root level in `createMockRootScopeGenerator`.
	private func createMockTypeDescriptionToScopeMapping() -> [TypeDescription: Scope] {
		// Create scopes for all types.
		let typeDescriptionToScopeMap: [TypeDescription: Scope] = typeDescriptionToFulfillingInstantiableMap.values
			.reduce(into: [TypeDescription: Scope]()) { partialResult, instantiable in
				guard partialResult[instantiable.concreteInstantiable] == nil else { return }
				let scope = Scope(instantiable: instantiable)
				for instantiableType in instantiable.instantiableTypes {
					partialResult[instantiableType] = scope
				}
			}

		// Populate propertiesToGenerate on each scope.
		for scope in Set(typeDescriptionToScopeMap.values) {
			for dependency in scope.instantiable.dependencies {
				switch dependency.source {
				case let .instantiated(_, erasedToConcreteExistential):
					let instantiatedType = dependency.asInstantiatedType
					if let instantiatedScope = typeDescriptionToScopeMap[instantiatedType] {
						scope.propertiesToGenerate.append(.instantiated(
							dependency.property,
							instantiatedScope,
							erasedToConcreteExistential: erasedToConcreteExistential,
						))
					}
				case .received:
					// Received dependencies are NOT promoted on individual scopes.
					// They bubble up through receivedProperties to the mock root,
					// where they're promoted as root-level children.
					continue
				case let .aliased(fulfillingProperty, erasedToConcreteExistential, onlyIfAvailable):
					scope.propertiesToGenerate.append(.aliased(
						dependency.property,
						fulfilledBy: fulfillingProperty,
						erasedToConcreteExistential: erasedToConcreteExistential,
						onlyIfAvailable: onlyIfAvailable,
					))
				case .forwarded:
					continue
				}
			}
		}
		return typeDescriptionToScopeMap
	}

	/// A collection of `@Instantiable`-decorated types that are at the roots of their respective dependency trees.
	private lazy var rootInstantiables: Set<TypeDescription> = Set(
		typeDescriptionToFulfillingInstantiableMap
			.values
			.filter(\.isRoot)
			.map(\.concreteInstantiable),
	)

	/// A collection of `@Instantiable`-decorated types that are instantiated by at least one other
	/// `@Instantiable`-decorated type or do not explicitly receive dependencies.
	private lazy var reachableTypeDescriptions: Set<TypeDescription> = {
		var reachableTypeDescriptions = Set<TypeDescription>()

		func recordReachableTypeDescription(_ reachableTypeDescription: TypeDescription) {
			guard !reachableTypeDescriptions.contains(reachableTypeDescription) else {
				// We've visited this tree already. Ignore.
				return
			}
			reachableTypeDescriptions.insert(reachableTypeDescription)
			guard let instantiable = typeDescriptionToFulfillingInstantiableMap[reachableTypeDescription] else {
				// We can't find an instantiable for this type.
				// This is bad, but we'll handle this error in `validateReachableTypeDescriptions()`.
				return
			}
			let reachableChildTypeDescriptions = instantiable
				.dependencies
				.filter(\.isInstantiated)
				.map(\.asInstantiatedType)
			for reachableChildTypeDescription in reachableChildTypeDescriptions {
				recordReachableTypeDescription(reachableChildTypeDescription)
			}
		}

		for reachableTypeDescription in rootInstantiables {
			recordReachableTypeDescription(reachableTypeDescription)
		}

		return reachableTypeDescriptions
	}()

	private func createTypeDescriptionToScopeMapping() throws -> [TypeDescription: Scope] {
		// Create the mapping.
		let typeDescriptionToScopeMap: [TypeDescription: Scope] = reachableTypeDescriptions
			.reduce(into: [TypeDescription: Scope]()) { partialResult, typeDescription in
				if let instantiable = typeDescriptionToFulfillingInstantiableMap[typeDescription],
				   partialResult[instantiable.concreteInstantiable] == nil
				{
					let scope = Scope(instantiable: instantiable)
					for instantiableType in instantiable.instantiableTypes {
						partialResult[instantiableType] = scope
					}
				}
			}

		// Populate the propertiesToGenerate on each scope.
		for scope in Set(typeDescriptionToScopeMap.values) {
			for dependency in scope.instantiable.dependencies {
				switch dependency.source {
				case let .instantiated(_, erasedToConcreteExistential):
					let instantiatedType = dependency.asInstantiatedType
					if let instantiable = typeDescriptionToFulfillingInstantiableMap[instantiatedType],
					   let instantiatedScope = typeDescriptionToScopeMap[instantiatedType]
					{
						let type = dependency.property.propertyType
						if type.isConstant {
							guard instantiable.dependencies.filter(\.isForwarded).isEmpty else {
								throw DependencyTreeGeneratorError
									.instantiableHasForwardedProperty(
										property: dependency.property,
										instantiableWithForwardedProperty: instantiable,
										parent: scope.instantiable,
									)
							}
						}
						scope.propertiesToGenerate.append(.instantiated(
							dependency.property,
							instantiatedScope,
							erasedToConcreteExistential: erasedToConcreteExistential,
						))
					}
				case let .aliased(fulfillingProperty, erasedToConcreteExistential, onlyIfAvailable):
					scope.propertiesToGenerate.append(.aliased(
						dependency.property,
						fulfilledBy: fulfillingProperty,
						erasedToConcreteExistential: erasedToConcreteExistential,
						onlyIfAvailable: onlyIfAvailable,
					))
				case .forwarded, .received:
					continue
				}
			}
		}
		return typeDescriptionToScopeMap
	}

	private func validatePropertiesAreFulfillable(typeDescriptionToScopeMap: [TypeDescription: Scope]) throws {
		var unfulfillableProperties = Set<DependencyTreeGeneratorError.UnfulfillableProperty>()
		func validatePropertiesAreFulfillable(
			on scope: Scope,
			receivableProperties: Set<Property>,
			property: Property?,
			propertyStack: OrderedSet<Property>,
			root: TypeDescription,
		) throws {
			if let property {
				func validateNoCycleInReceivedProperties(
					scope: Scope,
					receivedPropertyStack: OrderedSet<Property>,
					instantiationStack: OrderedSet<Property>,
				) throws {
					for childProperty in scope.requiredReceivedProperties {
						guard childProperty != property else {
							throw DependencyTreeGeneratorError.receivedConstantCycleDetected(
								instantiated: property,
								receivedPropertyChain: receivedPropertyStack + [childProperty],
							)
						}
						guard !receivedPropertyStack.contains(childProperty) else {
							// We've found a cycle, but it's not our cycle. Bail and let a future loop find this.
							return
						}
						if let cycleIndex = instantiationStack.firstIndex(of: childProperty) {
							let instantiationProperties = Array(instantiationStack.elements[0...cycleIndex])
							let typesInCycle = (
								[childProperty]
									+ receivedPropertyStack.reversed()
									+ instantiationProperties,
							).map(\.typeDescription)
							switch childProperty.propertyType {
							case .instantiator,
							     .erasedInstantiator,
							     .sendableInstantiator,
							     .sendableErasedInstantiator:
								throw DependencyTreeGeneratorError.receivedInstantiatorDependencyCycleDetected(
									property: childProperty,
									directParent: scope.instantiable.concreteInstantiable,
									cycle: typesInCycle,
								)
							case .constant:
								throw DependencyTreeGeneratorError.constantDependencyCycleDetected(typesInCycle)
							}
						} else if let receivedPropertyScope = typeDescriptionToScopeMap[childProperty.typeDescription] {
							var childPropertyStack = receivedPropertyStack
							childPropertyStack.append(childProperty)
							try validateNoCycleInReceivedProperties(
								scope: receivedPropertyScope,
								receivedPropertyStack: childPropertyStack,
								instantiationStack: instantiationStack,
							)
						}
					}
				}
				var instantiationStack = propertyStack
				instantiationStack.insert(property, at: 0)
				try validateNoCycleInReceivedProperties(
					scope: scope,
					receivedPropertyStack: [],
					instantiationStack: instantiationStack,
				)
			}

			for receivedProperty in scope.requiredReceivedProperties {
				let parentContainsProperty = receivableProperties.contains(receivedProperty)
				let propertyIsCreatedAtThisScope = scope.createdProperties.contains(receivedProperty)
				if !parentContainsProperty, !propertyIsCreatedAtThisScope {
					if property != nil {
						// This property is in a dependency tree and is unfulfillable. Record the problem.
						unfulfillableProperties.insert(.init(
							property: receivedProperty,
							instantiable: scope.instantiable,
							parentStack: propertyStack.map(\.typeDescription) + [root],
							suggestedAlternatives: receivableProperties.filter {
								receivedProperty.typeDescription.leastQualifiedTypeDescription == $0.typeDescription.leastQualifiedTypeDescription
									|| receivedProperty.label == $0.label
							}.sorted(),
						))
					}
				}
			}

			// Check children for cycles.
			var childPropertyStack = propertyStack
			if let property {
				childPropertyStack.insert(property, at: 0)
			}
			for dependency in scope.instantiable.dependencies {
				let propertyForDependency = dependency.source.fulfillingProperty ?? dependency.property
				guard let cycleIndex = childPropertyStack.firstIndex(of: propertyForDependency) else {
					continue
				}
				let typesInCycle = (
					[propertyForDependency]
						+ childPropertyStack.elements[0...cycleIndex],
				).map(\.typeDescription)
				if propertyForDependency.propertyType.isConstant {
					// We can break a constant dependency cycle if there's lazy instantiation in the tree.
					if !typesInCycle.contains(where: { !$0.propertyType.isConstant }) {
						throw DependencyTreeGeneratorError.constantDependencyCycleDetected(typesInCycle)
					}
				} else if dependency.source.isReceived {
					throw DependencyTreeGeneratorError.receivedInstantiatorDependencyCycleDetected(
						property: propertyForDependency,
						directParent: scope.instantiable.concreteInstantiable,
						cycle: typesInCycle,
					)
				}
			}

			for childPropertyToGenerate in scope.propertiesToGenerate {
				switch childPropertyToGenerate {
				case let .instantiated(childProperty, childScope, _):
					guard !childPropertyStack.contains(childProperty) else {
						// There is a cycle in our scope tree. Do not re-enter it.
						continue
					}
					try validatePropertiesAreFulfillable(
						on: childScope,
						receivableProperties: receivableProperties
							.union(scope.properties)
							.removing(childProperty),
						property: childProperty,
						propertyStack: childPropertyStack,
						root: root,
					)
				case .aliased:
					break
				}
			}
		}

		for rootScope in rootInstantiables.compactMap({ typeDescriptionToScopeMap[$0] }) {
			try validatePropertiesAreFulfillable(
				on: rootScope,
				receivableProperties: Set(rootScope.properties),
				property: nil,
				propertyStack: [],
				root: rootScope.instantiable.concreteInstantiable,
			)
		}

		if !unfulfillableProperties.isEmpty {
			throw DependencyTreeGeneratorError.unfulfillableProperties(Array(unfulfillableProperties))
		}
	}

	private func validateReachableTypeDescriptions() throws {
		for reachableTypeDescription in reachableTypeDescriptions {
			if typeDescriptionToFulfillingInstantiableMap[reachableTypeDescription] == nil {
				throw DependencyTreeGeneratorError.noInstantiableFound(reachableTypeDescription)
			}
		}
	}
}

// MARK: - Dependency

extension Dependency {
	fileprivate var isInstantiated: Bool {
		switch source {
		case .instantiated:
			true
		case .aliased, .forwarded, .received:
			false
		}
	}

	fileprivate var isForwarded: Bool {
		switch source {
		case .forwarded:
			true
		case .aliased, .instantiated, .received:
			false
		}
	}
}

// MARK: - Set

extension Set {
	fileprivate func removing(_ element: Element) -> Self {
		var setWithoutElement = self
		setWithoutElement.remove(element)
		return setWithoutElement
	}
}

// MARK: - TypeDescription

extension TypeDescription {
	fileprivate var leastQualifiedTypeDescription: TypeDescription {
		switch self {
		case let .nested(name, _, generics):
			.simple(name: name, generics: generics)
		case let .any(typeDescription),
		     let .implicitlyUnwrappedOptional(typeDescription),
		     let .optional(typeDescription),
		     let .some(typeDescription):
			typeDescription.leastQualifiedTypeDescription
		case .array,
		     .attributed,
		     .closure,
		     .composition,
		     .dictionary,
		     .metatype,
		     .simple,
		     .tuple,
		     .unknown,
		     .void:
			self
		}
	}
}
