// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

public actor DependencyTreeGenerator {
	// MARK: Initialization

	public init(
		importStatements: [ImportStatement],
		typeDescriptionToFulfillingInstantiableMap: [TypeDescription: Instantiable],
	) {
		self.importStatements = importStatements
		self.typeDescriptionToFulfillingInstantiableMap = typeDescriptionToFulfillingInstantiableMap
	}

	// MARK: Public

	public struct GeneratedRoot: Sendable {
		public let typeDescription: TypeDescription
		public let sourceFilePath: String?
		/// The generated extension code for this root, without the file header.
		public let code: String
	}

	public struct MockGenerationResult: Sendable {
		public let generatedRoots: [GeneratedRoot]
		public let mockConfigurationCode: String?
	}

	/// The file header to prepend to each generated output file.
	public var fileHeader: String {
		let importsWhitespace = imports.isEmpty ? "" : "\n"
		return "// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.\n// Any modifications made to this file will be overwritten on subsequent builds.\n// Please refrain from editing this file directly.\n\(importsWhitespace)\(imports)\(importsWhitespace)\n"
	}

	public func generatePerRootCodeTrees() async throws -> [GeneratedRoot] {
		let rootScopeGenerators = try rootScopeGenerators

		return try await withThrowingTaskGroup(
			of: GeneratedRoot?.self,
			returning: [GeneratedRoot].self,
		) { taskGroup in
			for rootInfo in rootScopeGenerators {
				taskGroup.addTask {
					let code = try await rootInfo.scopeGenerator.generateCode()
					return GeneratedRoot(
						typeDescription: rootInfo.typeDescription,
						sourceFilePath: rootInfo.sourceFilePath,
						code: code,
					)
				}
			}
			var generatedRoots = [GeneratedRoot]()
			for try await generatedRoot in taskGroup {
				if let generatedRoot {
					generatedRoots.append(generatedRoot)
				}
			}
			return generatedRoots
		}
	}

	/// Generates mock code for all `@Instantiable` types.
	public func generateMockCode(
		mockConditionalCompilation: String?,
		currentModuleSourceFilePaths: Set<String>? = nil,
		additionalMocksToGenerate: Set<String> = [],
	) async throws -> MockGenerationResult {
		// Build a map of erased wrapper types → concrete fulfilling types.
		// This lets mocks construct types like AnyUserService(DefaultUserService())
		// even when the erased type isn't directly @Instantiable.
		var erasedToConcreteTypeMap = [TypeDescription: TypeDescription]()
		for instantiable in typeDescriptionToFulfillingInstantiableMap.values {
			for dependency in instantiable.dependencies {
				if case let .instantiated(fulfillingTypeDescription, erasedToConcreteExistential) = dependency.source,
				   erasedToConcreteExistential,
				   let concreteType = fulfillingTypeDescription?.asInstantiatedType
				{
					erasedToConcreteTypeMap[dependency.property.typeDescription] = concreteType
				}
			}
		}

		// Build mock scope mapping — like production but includes all types and
		// promotes received dependencies as instantiated children.
		let typeDescriptionToScopeMap = createMockTypeDescriptionToScopeMapping()

		// Validate mock scopes for cycles. Mock-only types (generateMock: true without
		// isRoot) bypass root validation but can still have partially-lazy cycles.
		// Uses cyclesOnly to skip unfulfillable property checks — mock-only types
		// have unfulfillable received properties by design (they become mock parameters).
		try validatePropertiesAreFulfillable(
			typeDescriptionToScopeMap: typeDescriptionToScopeMap,
			cyclesOnly: true,
		)

		// Compute types with hand-written mocks that can be called with zero arguments,
		// suitable for use as default values in forwarded mock parameters. This includes
		// standalone mockOnly types AND merged entries where a mockOnly declaration's mock
		// was copied onto a non-mockOnly production entry. Types whose mock method has
		// required parameters are excluded, since the generated default `Type.mock()` would
		// not compile.
		let forwardedParameterMockDefaults: [TypeDescription: String] = typeDescriptionToFulfillingInstantiableMap.values
			.reduce(into: [TypeDescription: String]()) { result, instantiable in
				guard !instantiable.generateMock,
				      let mockInitializer = instantiable.mockInitializer,
				      mockInitializer.arguments.allSatisfy(\.hasDefaultValue)
				else { return }
				result[instantiable.concreteInstantiable] = instantiable.customMockName ?? InstantiableVisitor.mockMethodName
			}

		// Create mock-root ScopeGenerators using the production Scope tree.
		var seen = Set<TypeDescription>()
		var mockRoots = [(instantiable: Instantiable, scopeGenerator: ScopeGenerator)]()
		for instantiable in typeDescriptionToFulfillingInstantiableMap.values
			.sorted(by: { $0.concreteInstantiable < $1.concreteInstantiable })
		{
			let isAdditionalMock = additionalMocksToGenerate.contains(instantiable.concreteInstantiable.asSource)
			// Skip types where generateMock is not enabled (unless explicitly listed
			// in additionalMocksToGenerate), duplicates, and types not in the scope map.
			// Types from dependent modules are skipped unless they appear in
			// additionalMocksToGenerate. When generateMock is true and a hand-written
			// mock exists, the generated mock calls through to the hand-written one
			// (which has a different name specified by customMockName).
			guard instantiable.generateMock || isAdditionalMock,
			      seen.insert(instantiable.concreteInstantiable).inserted,
			      let scope = typeDescriptionToScopeMap[instantiable.concreteInstantiable]
			else { continue }
			if let currentModuleSourceFilePaths, !isAdditionalMock {
				guard let sourceFilePath = instantiable.sourceFilePath,
				      currentModuleSourceFilePaths.contains(sourceFilePath)
				else { continue }
			}

			// Validate that this type's constant @Instantiated children have no @Forwarded properties.
			// Use the mock scope map (not typeDescriptionToFulfillingInstantiableMap) because
			// mockOnly types can win additional-type slots and may have different @Forwarded properties.
			for dependency in scope.instantiable.dependencies {
				guard case let .instantiated(fulfillingTypeDescription, _) = dependency.source else { continue }
				let instantiatedType = dependency.asInstantiatedType
				let childScope = typeDescriptionToScopeMap[instantiatedType]
					?? (fulfillingTypeDescription != nil
						? typeDescriptionToScopeMap[dependency.property.typeDescription.asInstantiatedType]
						: nil)
				if let childScope {
					try validateNoForwardedProperties(
						for: dependency,
						instantiable: childScope.instantiable,
						parent: scope.instantiable,
					)
				}
			}

			let mockRoot = try createMockRootScopeGenerator(
				for: instantiable,
				scope: scope,
				typeDescriptionToScopeMap: typeDescriptionToScopeMap,
				erasedToConcreteTypeMap: erasedToConcreteTypeMap,
			)
			mockRoots.append((instantiable: instantiable, scopeGenerator: mockRoot))
		}

		// Generate mock code and collect configuration types in parallel.
		let generatedRoots = try await withThrowingTaskGroup(
			of: (root: GeneratedRoot, configurationTypes: [(typeName: String, structCode: String)]).self,
			returning: [(root: GeneratedRoot, configurationTypes: [(typeName: String, structCode: String)])].self,
		) { taskGroup in
			for (instantiable, mockRoot) in mockRoots {
				taskGroup.addTask {
					async let code = mockRoot.generateCode(
						codeGeneration: .mock(ScopeGenerator.MockContext(
							mockConditionalCompilation: mockConditionalCompilation,
							forwardedParameterMockDefaults: forwardedParameterMockDefaults,
						)),
					)
					async let configurationTypes = mockRoot.collectConfigurationTypes()
					return try await (
						root: GeneratedRoot(
							typeDescription: instantiable.concreteInstantiable,
							sourceFilePath: instantiable.sourceFilePath,
							code: code,
						),
						configurationTypes: configurationTypes,
					)
				}
			}
			var results = [(root: GeneratedRoot, configurationTypes: [(typeName: String, structCode: String)])]()
			for try await result in taskGroup {
				results.append(result)
			}
			return results
		}

		let rootedTypeNames = Set(generatedRoots.map(\.root.typeDescription.asSource))
		// Deduplicate configuration types by type name across all roots.
		var seenTypeNames = Set<String>()
		var rootedConfigurationExtensions = [String: String]()
		var sharedConfigurationExtensions = [(typeName: String, structCode: String)]()
		for result in generatedRoots.sorted(by: { $0.root.typeDescription < $1.root.typeDescription }) {
			for configType in result.configurationTypes {
				if seenTypeNames.insert(configType.typeName).inserted {
					if rootedTypeNames.contains(configType.typeName) {
						rootedConfigurationExtensions[configType.typeName] = configType.structCode
					} else {
						sharedConfigurationExtensions.append(configType)
					}
				}
			}
		}

		let mergedGeneratedRoots = generatedRoots.map { result in
			let configurationCode = rootedConfigurationExtensions[result.root.typeDescription.asSource].map { structCode in
				generateMockConfigurationCode(
					configurationExtensions: [(typeName: result.root.typeDescription.asSource, structCode: structCode)],
					mockConditionalCompilation: mockConditionalCompilation,
				)
			}
			let code = if let configurationCode, !configurationCode.isEmpty {
				result.root.code + "\n\n" + configurationCode.trimmingCharacters(in: .whitespacesAndNewlines)
			} else {
				result.root.code
			}
			return GeneratedRoot(
				typeDescription: result.root.typeDescription,
				sourceFilePath: result.root.sourceFilePath,
				code: code,
			)
		}

		let mockConfigurationCode: String? = if sharedConfigurationExtensions.isEmpty {
			nil
		} else {
			generateMockConfigurationCode(
				configurationExtensions: sharedConfigurationExtensions,
				mockConditionalCompilation: mockConditionalCompilation,
			)
		}

		return MockGenerationResult(
			generatedRoots: mergedGeneratedRoots,
			mockConfigurationCode: mockConfigurationCode,
		)
	}

	private func generateMockConfigurationCode(
		configurationExtensions: [(typeName: String, structCode: String)],
		mockConditionalCompilation: String?,
	) -> String {
		let extensions = configurationExtensions.map { configurationExtension in
			"extension \(configurationExtension.typeName) {\n\(configurationExtension.structCode)\n}"
		}
		let body = extensions.joined(separator: "\n\n")
		if let mockConditionalCompilation {
			return "#if \(mockConditionalCompilation)\n\(body)\n#endif\n"
		} else {
			return "\(body)\n"
		}
	}

	public func generateDOTTree() async throws -> String {
		let rootScopeGenerators = try rootScopeGenerators

		let dependencyTree = try await withThrowingTaskGroup(
			of: String.self,
			returning: String.self,
		) { taskGroup in
			for rootInfo in rootScopeGenerators {
				taskGroup.addTask { try await rootInfo.scopeGenerator.generateDOT() }
			}
			var generatedRoots = [String]()
			for try await generatedRoot in taskGroup {
				generatedRoots.append(generatedRoot)
			}
			return generatedRoots.removingEmpty().sorted().joined(separator: "\n\n")
		}

		return """
		\(dependencyTree)
		"""
	}

	// MARK: - DependencyTreeGeneratorError

	private enum DependencyTreeGeneratorError: Error, CustomStringConvertible {
		case noInstantiableFound(TypeDescription)
		case unfulfillableProperties([UnfulfillableProperty])
		case instantiableHasForwardedProperty(property: Property, instantiableWithForwardedProperty: Instantiable, parent: Instantiable)
		case constantDependencyCycleDetected([TypeDescription])
		case partiallyLazyDependencyCycleDetected([TypeDescription])
		case receivedInstantiatorDependencyCycleDetected(property: Property, directParent: TypeDescription, cycle: [TypeDescription])
		case receivedConstantCycleDetected(instantiated: Property, receivedPropertyChain: [Property])

		var description: String {
			switch self {
			case let .noInstantiableFound(typeDescription):
				"No `@\(InstantiableVisitor.macroName)`-decorated type or extension found to fulfill `@\(Dependency.Source.instantiatedRawValue)`-decorated property with type `\(typeDescription.asSource)`"
			case let .unfulfillableProperties(unfulfillableProperties):
				"""
				\(unfulfillableProperties.map {
					if $0.property.typeDescription.isOptional,
					   let nonOptionalAlternative = $0.suggestedAlternatives.first(where: { [unfulfilledProperty = $0.property] alternative in
					   	alternative.label == unfulfilledProperty.label
					   		&& alternative.typeDescription == unfulfilledProperty.typeDescription.unwrapped
					   })
					{
						"""
						@\(Dependency.Source.receivedRawValue) property `\($0.property.asSource)` is not @\(Dependency.Source.instantiatedRawValue) or @\(Dependency.Source.forwardedRawValue) in chain:\n\t\(([$0.instantiable.concreteInstantiable] + $0.parentStack)
							.reversed()
							.map(\.asSource)
							.joined(separator: " -> "))\($0.suggestedAlternatives.isEmpty ? "" : "\n\nThe non-optional `\(nonOptionalAlternative.asSource)` is available in chain. Did you mean to decorate this property with `@\(Dependency.Source.receivedRawValue)(onlyIfAvailable: true)`?")
						"""
					} else {
						"""
						@\(Dependency.Source.receivedRawValue) property `\($0.property.asSource)` is not @\(Dependency.Source.instantiatedRawValue) or @\(Dependency.Source.forwardedRawValue) in chain:\n\t\(([$0.instantiable.concreteInstantiable] + $0.parentStack)
							.reversed()
							.map(\.asSource)
							.joined(separator: " -> "))\($0.suggestedAlternatives.isEmpty ? "" : "\n\nDid you mean one of the following available properties?\n\($0.suggestedAlternatives.map { "\t`\($0.asSource)`" }.joined(separator: "\n"))")
						"""
					}
				}
				.sorted()
				.joined(separator: "\n\n"))
				"""
			case let .instantiableHasForwardedProperty(property, instantiable, parent):
				"Property `\(property.asSource)` on \(parent.concreteInstantiable.asSource) has at least one @\(Dependency.Source.forwardedRawValue) property. Property should instead be of type `\(Dependency.instantiatorType)<\(instantiable.concreteInstantiable.asSource)>`."
			case let .constantDependencyCycleDetected(instantiables):
				"""
				Dependency cycle detected:
				\t\(instantiables
					.map(\.asSource)
					.reversed()
					.joined(separator: " -> "))
				"""
			case let .partiallyLazyDependencyCycleDetected(instantiables):
				"""
				Dependency cycle detected. Cycles with a mix of constant and lazy (Instantiator) dependencies cannot be resolved. Make all dependencies in the cycle lazy by using Instantiator:
				\t\(instantiables
					.map(\.asSource)
					.reversed()
					.joined(separator: " -> "))
				"""
			case let .receivedInstantiatorDependencyCycleDetected(property, directParent, instantiables):
				"""
				Dependency cycle detected! @\(Dependency.Source.instantiatedRawValue) `\(property.asSource)` is @\(Dependency.Source.receivedRawValue) in tree created by @\(Dependency.Source.instantiatedRawValue) `\(property.asSource)`. Declare @\(Dependency.Source.receivedRawValue) `\(property.asSource)` on `\(directParent.asSource)` as @\(Dependency.Source.instantiatedRawValue) to fix. Full cycle:
				\t\(instantiables
					.map(\.asSource)
					.reversed()
					.joined(separator: " -> "))
				"""
			case let .receivedConstantCycleDetected(instantiated, receivedPropertyChain):
				"""
				Dependency received in same chain it is instantiated:
				\t\("@\(Dependency.Source.instantiatedRawValue) \(instantiated.asSource) -> "
					+ receivedPropertyChain
					.map { "@\(Dependency.Source.receivedRawValue) \($0.asSource)" }
					.joined(separator: " -> "))
				"""
			}
		}

		struct UnfulfillableProperty: Hashable {
			let property: Property
			let instantiable: Instantiable
			let parentStack: [TypeDescription]
			let suggestedAlternatives: [Property]
		}
	}

	// MARK: Private

	private let importStatements: [ImportStatement]
	private let typeDescriptionToFulfillingInstantiableMap: [TypeDescription: Instantiable]
	private struct RootScopeInfo {
		let typeDescription: TypeDescription
		let sourceFilePath: String?
		let scopeGenerator: ScopeGenerator
	}

	private var rootScopeGenerators: [RootScopeInfo] {
		get throws {
			let rootScopeGenerators: [RootScopeInfo] = try {
				try validateReachableTypeDescriptions()

				let typeDescriptionToScopeMap = try createTypeDescriptionToScopeMapping()
				try validatePropertiesAreFulfillable(typeDescriptionToScopeMap: typeDescriptionToScopeMap, cyclesOnly: false)
				return try rootInstantiables
					.sorted()
					.compactMap { typeDescription in
						try typeDescriptionToScopeMap[typeDescription].map { scope in
							try RootScopeInfo(
								typeDescription: typeDescription,
								sourceFilePath: typeDescriptionToFulfillingInstantiableMap[typeDescription]?.sourceFilePath,
								scopeGenerator: scope.createScopeGenerator(
									for: nil,
									propertyStack: [],
									receivableProperties: [],
									erasedToConcreteExistential: false,
								),
							)
						}
					}
			}()
			return rootScopeGenerators
		}
	}

	private var imports: String {
		importStatements
			.reduce(into: [String: Set<ImportStatement>]()) { partialResult, importStatement in
				var importsForModuleName = partialResult[importStatement.moduleName, default: []]
				importsForModuleName.insert(importStatement)
				partialResult[importStatement.moduleName] = importsForModuleName
			}
			.flatMap {
				if let wholeModuleImport = $0.value.first(where: {
					$0.kind.isEmpty
						&& $0.type.isEmpty
				}) {
					[wholeModuleImport]
				} else {
					Array($0.value)
				}
			}
			.map {
				"""
				#if canImport(\($0.moduleName))
				\($0.asSource)
				#endif
				"""
			}
			.sorted()
			.joined(separator: "\n")
	}

	/// Creates a mock-root ScopeGenerator using the production Scope tree.
	/// Unsatisfied received dependencies are promoted as root-level children
	/// on a NEW Scope (the shared Scope is never mutated).
	private func createMockRootScopeGenerator(
		for instantiable: Instantiable,
		scope: Scope,
		typeDescriptionToScopeMap: [TypeDescription: Scope],
		erasedToConcreteTypeMap: [TypeDescription: TypeDescription],
	) throws -> ScopeGenerator {
		// Recursively collect all transitive received properties from the scope tree
		// and any promoted scopes' subtrees. Results are cached per Scope identity
		// (via ObjectIdentifier) so each scope is visited at most once — O(total_scopes).
		var cache = [ObjectIdentifier: (received: Set<Property>, onlyIfAvailable: Set<Property>)]()
		let (initialReceived, initialOnlyIfAvailable) = Self.collectReceivedProperties(
			from: scope,
			cache: &cache,
		)

		// Worklist: promoted scopes may introduce additional transitive received properties.
		var allReceived = initialReceived
		var allOnlyIfAvailable = initialOnlyIfAvailable
		var visitedTypes = Set<TypeDescription>()
		var worklist = Array(allReceived)

		while let property = worklist.popLast() {
			// Don't walk into scopes for onlyIfAvailable dependencies.
			// They become optional mock parameters with no default construction,
			// so their transitive dependencies don't need promoting.
			guard !allOnlyIfAvailable.contains(property) else { continue }

			var dependencyType = property.typeDescription.asInstantiatedType
			if typeDescriptionToScopeMap[dependencyType] == nil,
			   let concreteType = erasedToConcreteTypeMap[property.typeDescription]
			{
				dependencyType = concreteType
			}
			guard let promotedScope = typeDescriptionToScopeMap[dependencyType],
			      visitedTypes.insert(dependencyType).inserted
			else { continue }

			let (scopeReceived, scopeOnlyIfAvailable) = Self.collectReceivedProperties(
				from: promotedScope,
				cache: &cache,
			)
			for newProperty in scopeReceived where allReceived.insert(newProperty).inserted {
				worklist.append(newProperty)
			}
			allOnlyIfAvailable.formUnion(scopeOnlyIfAvailable)
		}

		// Promote all received properties that have scopes.
		// onlyIfAvailable dependencies are NOT promoted — they become optional
		// mock parameters with no default.
		// Filter out forwarded properties — they're bare mock parameters, not promoted children.
		// ScopeData.root doesn't carry forwardedProperties, so receivedProperties doesn't
		// subtract them. We filter them here instead.
		let forwardedProperties = Set(
			instantiable.dependencies
				.filter { $0.source == .forwarded }
				.map(\.property),
		)
		let mockRootScope = Scope(instantiable: instantiable)
		mockRootScope.propertiesToGenerate = scope.propertiesToGenerate

		// Track promoted (label, type) pairs to prevent duplicate promotions when
		// both required and onlyIfAvailable versions of the same dep exist.
		// Property.< sorts non-optional before optional, so the required version
		// wins and the optional version is skipped.
		var promotedLabelAndTypes = Set<String>()
		for receivedProperty in allReceived.sorted() {
			guard !allOnlyIfAvailable.contains(receivedProperty),
			      !forwardedProperties.contains(receivedProperty)
			else { continue }

			let labelAndType = "\(receivedProperty.label):\(receivedProperty.typeDescription.asInstantiatedType.asSource)"
			guard promotedLabelAndTypes.insert(labelAndType).inserted else { continue }

			var dependencyType = receivedProperty.typeDescription.asInstantiatedType
			var erasedToConcreteExistential = false
			if typeDescriptionToScopeMap[dependencyType] == nil,
			   let concreteType = erasedToConcreteTypeMap[receivedProperty.typeDescription]
			{
				dependencyType = concreteType
				erasedToConcreteExistential = true
			}
			guard let receivedScope = typeDescriptionToScopeMap[dependencyType] else {
				continue
			}
			mockRootScope.propertiesToGenerate.append(.instantiated(
				receivedProperty,
				receivedScope,
				erasedToConcreteExistential: erasedToConcreteExistential,
			))
		}

		// Validate the promoted mock scope for cycles before generating code.
		// This catches cycles that only become visible after @Received dependencies
		// are promoted to the mock root (e.g., B @Receives Instantiator<A> where A
		// instantiates B — the promotion creates a cycle in the mock root scope).
		try validateMockRootScopeForCycles(
			mockRootScope,
			typeDescriptionToScopeMap: typeDescriptionToScopeMap,
		)

		// Build the final ScopeGenerator once.
		return try mockRootScope.createScopeGenerator(
			for: nil,
			propertyStack: [],
			receivableProperties: [],
			erasedToConcreteExistential: false,
			forMockGeneration: true,
		)
	}

	/// Recursively collects all unsatisfied received properties from a Scope tree.
	/// Walks a post-promotion mock root scope for dependency cycles.
	/// The mock root scope has @Received dependencies promoted as children,
	/// which can create cycles not visible in the pre-promotion scope.
	private func validateMockRootScopeForCycles(
		_ scope: Scope,
		typeDescriptionToScopeMap: [TypeDescription: Scope],
		propertyStack: [Property] = [],
	) throws {
		// Check dependencies for cycles (catches @Received references back to ancestors).
		// Skip forwarded dependencies — they're runtime Instantiator closure parameters.
		for dependency in scope.instantiable.dependencies where dependency.source != .forwarded {
			let propertyForDependency = dependency.source.fulfillingProperty ?? dependency.property
			guard let cycleIndex = propertyStack.firstIndex(of: propertyForDependency) else {
				continue
			}
			let typesInCycle = (
				[propertyForDependency]
					+ propertyStack[0...cycleIndex],
			).map(\.typeDescription)
			try Self.throwIfInvalidCycle(
				typesInCycle: typesInCycle,
				property: propertyForDependency,
				directParent: scope.instantiable.concreteInstantiable,
				isReceived: dependency.source.isReceived,
			)
		}

		// Recurse into children.
		for childPropertyToGenerate in scope.propertiesToGenerate {
			switch childPropertyToGenerate {
			case let .instantiated(childProperty, childScope, _):
				guard !propertyStack.contains(childProperty) else { continue }
				let nextStack = [childProperty] + propertyStack
				try validateMockRootScopeForCycles(
					childScope,
					typeDescriptionToScopeMap: typeDescriptionToScopeMap,
					propertyStack: nextStack,
				)
			case .aliased:
				break
			}
		}
	}

	/// Throws the appropriate cycle error based on the property types in the cycle.
	/// For fully-lazy cycles (all Instantiator hops, no constant entry point), does nothing —
	/// those are valid and produce compilable code.
	private static func throwIfInvalidCycle(
		typesInCycle: [TypeDescription],
		property: Property,
		directParent: TypeDescription,
		isReceived: Bool,
	) throws {
		if property.propertyType.isConstant {
			let hasLazyHop = typesInCycle.contains(where: { !$0.propertyType.isConstant })
			if hasLazyHop {
				throw DependencyTreeGeneratorError.partiallyLazyDependencyCycleDetected(typesInCycle)
			} else {
				throw DependencyTreeGeneratorError.constantDependencyCycleDetected(typesInCycle)
			}
		} else if isReceived {
			throw DependencyTreeGeneratorError.receivedInstantiatorDependencyCycleDetected(
				property: property,
				directParent: directParent,
				cycle: typesInCycle,
			)
		}
		// Fully-lazy cycle (Instantiator entry, not received) — valid, no error.
	}

	/// Mirrors ScopeGenerator's `receivedProperties` and `onlyIfAvailableUnwrappedReceivedProperties`
	/// computation but operates on Scope objects directly, with memoization for O(1) revisits.
	private static func collectReceivedProperties(
		from scope: Scope,
		cache: inout [ObjectIdentifier: (received: Set<Property>, onlyIfAvailable: Set<Property>)],
	) -> (received: Set<Property>, onlyIfAvailable: Set<Property>) {
		let id = ObjectIdentifier(scope)
		if let cached = cache[id] { return cached }
		// Cycle sentinel — re-entrant calls return empty (cycles contribute no new received).
		cache[id] = ([], [])

		// Properties declared at this scope (instantiated/aliased children).
		let propertiesToDeclare = Set(scope.propertiesToGenerate.compactMap { propertyToGenerate -> Property? in
			switch propertyToGenerate {
			case let .instantiated(property, _, _): return property
			case let .aliased(property, _, _, _): return property
			}
		})

		// Forwarded properties at this scope.
		let forwardedProperties = Set(
			scope.instantiable.dependencies
				.filter { $0.source == .forwarded }
				.map(\.property),
		)

		var received = Set<Property>()
		var onlyIfAvailable = Set<Property>()

		// Collect from instantiated children — mirrors ScopeGenerator's receivedProperties aggregation.
		// Aliases are handled below in the own-dependency loop: alias children's receivedProperties
		// = [fulfillingProperty], but the own-dependency union unconditionally adds the same
		// fulfillingProperty, making the child-path subtraction/filter redundant.
		for case let .instantiated(_, childScope, _) in scope.propertiesToGenerate {
			let (childReceived, childOnlyIfAvailable) = collectReceivedProperties(
				from: childScope,
				cache: &cache,
			)
			received.formUnion(
				childReceived
					.subtracting(propertiesToDeclare)
					.filter { property in
						!property.typeDescription.isOptional
							|| !propertiesToDeclare.contains(property.asUnwrappedProperty)
					}
					.subtracting(forwardedProperties),
			)
			// Subtract by unwrapped form — a declared `x: X` satisfies onlyIfAvailable `x: X?`.
			onlyIfAvailable.formUnion(
				childOnlyIfAvailable.filter { property in
					!propertiesToDeclare.contains(property.asUnwrappedProperty)
						&& !forwardedProperties.contains(property.asUnwrappedProperty)
				},
			)
		}

		// This scope's own received/aliased dependencies.
		// Store exact properties (not unwrapped) in onlyIfAvailable. This avoids
		// collisions between a required `x: X` and an onlyIfAvailable `x: X?` —
		// they are distinct Properties. The subtraction above uses unwrapped comparison
		// to correctly subtract when a declared property satisfies an optional one.
		for dependency in scope.instantiable.dependencies {
			switch dependency.source {
			case let .received(isOnlyIfAvailable):
				received.insert(dependency.property)
				if isOnlyIfAvailable {
					onlyIfAvailable.insert(dependency.property)
				}
			case let .aliased(fulfillingProperty, _, isOnlyIfAvailable):
				received.insert(fulfillingProperty)
				if isOnlyIfAvailable {
					onlyIfAvailable.insert(fulfillingProperty)
				}
			case .instantiated, .forwarded:
				break
			}
		}

		let result = (received, onlyIfAvailable)
		cache[id] = result
		return result
	}

	/// Builds a scope mapping for mock generation. Similar to `createTypeDescriptionToScopeMapping`
	/// but includes ALL types (not just reachable from roots). Received dependencies are NOT
	/// promoted here — they're promoted at the root level in `createMockRootScopeGenerator`.
	private func createMockTypeDescriptionToScopeMapping() -> [TypeDescription: Scope] {
		// Create scopes for all types. Process non-mockOnly types first so they
		// claim additional-type slots. mockOnly types then overwrite slots whose
		// existing scope lacks its own mock (generateMock or a compatible
		// hand-written mock). Multiple map entries can share a concreteInstantiable but have different
		// instantiableTypes (e.g., a mockOnly with extra fulfillingAdditionalTypes).
		// Reuse the same scope for all entries sharing a concreteInstantiable so
		// every instantiableType is mapped.
		var visitedConcreteTypeToScope = [TypeDescription: Scope]()
		let typeDescriptionToScopeMap: [TypeDescription: Scope] = typeDescriptionToFulfillingInstantiableMap.values
			.sorted { lhs, rhs in
				// Non-mockOnly before mockOnly (production claims slots first).
				if lhs.mockOnly != rhs.mockOnly {
					return !lhs.mockOnly
				} else {
					// Within the same mockOnly tier, entries with mock info first
					// so scope-reuse creates scopes from mock-capable entries.
					let lhsHasMock = lhs.generateMock || lhs.mockInitializer != nil
					let rhsHasMock = rhs.generateMock || rhs.mockInitializer != nil
					if lhsHasMock != rhsHasMock {
						return lhsHasMock
					} else {
						// Stable tiebreaker: sort by concrete type name so scope-reuse
						// selects the same entry across runs.
						return lhs.concreteInstantiable < rhs.concreteInstantiable
					}
				}
			}
			.reduce(into: [TypeDescription: Scope]()) { partialResult, instantiable in
				let scope = visitedConcreteTypeToScope[instantiable.concreteInstantiable] ?? Scope(instantiable: instantiable)
				visitedConcreteTypeToScope[instantiable.concreteInstantiable] = scope
				for instantiableType in instantiable.instantiableTypes {
					guard let existingScope = partialResult[instantiableType] else {
						partialResult[instantiableType] = scope
						continue
					}
					// A mockOnly type overwrites a non-mockOnly scope that lacks
					// its own mock. A mockInitializer whose return type doesn't match
					// the scope's concrete type was inherited from a mockOnly merge
					// and doesn't count as the production type's own mock.
					if instantiable.mockOnly,
					   !existingScope.instantiable.generateMock,
					   !existingScope.instantiable.mockReturnTypeIsCompatible(withPropertyType: existingScope.instantiable.concreteInstantiable)
					{
						partialResult[instantiableType] = scope
					}
				}
			}

		// Populate propertiesToGenerate on each scope.
		for scope in Set(typeDescriptionToScopeMap.values) {
			for dependency in scope.instantiable.dependencies {
				switch dependency.source {
				case let .instantiated(fulfillingTypeDescription, erasedToConcreteExistential):
					let instantiatedType = dependency.asInstantiatedType
					if let instantiatedScope = typeDescriptionToScopeMap[instantiatedType] {
						scope.propertiesToGenerate.append(.instantiated(
							dependency.property,
							instantiatedScope,
							erasedToConcreteExistential: erasedToConcreteExistential,
						))
					} else if fulfillingTypeDescription != nil,
					          let declaredTypeScope = typeDescriptionToScopeMap[dependency.property.typeDescription.asInstantiatedType]
					{
						// The fulfilling type (from fulfilledByType:) is not visible in this
						// module. Fall back to the declared property type, which may be
						// fulfilled by a mockOnly type visible in the current module.
						scope.propertiesToGenerate.append(.instantiated(
							dependency.property,
							declaredTypeScope,
							erasedToConcreteExistential: erasedToConcreteExistential,
						))
					}
				case .received:
					// Received dependencies are NOT promoted on individual scopes.
					// They bubble up through receivedProperties to the mock root,
					// where they're promoted as root-level children.
					continue
				case let .aliased(fulfillingProperty, erasedToConcreteExistential, onlyIfAvailable):
					scope.propertiesToGenerate.append(.aliased(
						dependency.property,
						fulfilledBy: fulfillingProperty,
						erasedToConcreteExistential: erasedToConcreteExistential,
						onlyIfAvailable: onlyIfAvailable,
					))
				case .forwarded:
					continue
				}
			}
		}
		return typeDescriptionToScopeMap
	}

	/// A collection of `@Instantiable`-decorated types that are at the roots of their respective dependency trees.
	private lazy var rootInstantiables: Set<TypeDescription> = Set(
		typeDescriptionToFulfillingInstantiableMap
			.values
			.filter(\.isRoot)
			.map(\.concreteInstantiable),
	)

	/// A collection of `@Instantiable`-decorated types that are instantiated by at least one other
	/// `@Instantiable`-decorated type or do not explicitly receive dependencies.
	private lazy var reachableTypeDescriptions: Set<TypeDescription> = {
		var reachableTypeDescriptions = Set<TypeDescription>()

		func recordReachableTypeDescription(_ reachableTypeDescription: TypeDescription) {
			guard !reachableTypeDescriptions.contains(reachableTypeDescription) else {
				// We've visited this tree already. Ignore.
				return
			}
			reachableTypeDescriptions.insert(reachableTypeDescription)
			guard let instantiable = typeDescriptionToFulfillingInstantiableMap[reachableTypeDescription] else {
				// We can't find an instantiable for this type.
				// This is bad, but we'll handle this error in `validateReachableTypeDescriptions()`.
				return
			}
			let reachableChildTypeDescriptions = instantiable
				.dependencies
				.filter(\.isInstantiated)
				.map(\.asInstantiatedType)
			for reachableChildTypeDescription in reachableChildTypeDescriptions {
				recordReachableTypeDescription(reachableChildTypeDescription)
			}
		}

		for reachableTypeDescription in rootInstantiables {
			recordReachableTypeDescription(reachableTypeDescription)
		}

		return reachableTypeDescriptions
	}()

	private func createTypeDescriptionToScopeMapping() throws -> [TypeDescription: Scope] {
		// Create the mapping.
		let typeDescriptionToScopeMap: [TypeDescription: Scope] = reachableTypeDescriptions
			.reduce(into: [TypeDescription: Scope]()) { partialResult, typeDescription in
				if let instantiable = typeDescriptionToFulfillingInstantiableMap[typeDescription],
				   partialResult[instantiable.concreteInstantiable] == nil
				{
					let scope = Scope(instantiable: instantiable)
					for instantiableType in instantiable.instantiableTypes {
						partialResult[instantiableType] = scope
					}
				}
			}

		// Populate the propertiesToGenerate on each scope.
		for scope in Set(typeDescriptionToScopeMap.values) {
			for dependency in scope.instantiable.dependencies {
				switch dependency.source {
				case let .instantiated(_, erasedToConcreteExistential):
					let instantiatedType = dependency.asInstantiatedType
					if let instantiable = typeDescriptionToFulfillingInstantiableMap[instantiatedType],
					   let instantiatedScope = typeDescriptionToScopeMap[instantiatedType]
					{
						try validateNoForwardedProperties(
							for: dependency,
							instantiable: instantiable,
							parent: scope.instantiable,
						)
						scope.propertiesToGenerate.append(.instantiated(
							dependency.property,
							instantiatedScope,
							erasedToConcreteExistential: erasedToConcreteExistential,
						))
					}
				case let .aliased(fulfillingProperty, erasedToConcreteExistential, onlyIfAvailable):
					scope.propertiesToGenerate.append(.aliased(
						dependency.property,
						fulfilledBy: fulfillingProperty,
						erasedToConcreteExistential: erasedToConcreteExistential,
						onlyIfAvailable: onlyIfAvailable,
					))
				case .forwarded, .received:
					continue
				}
			}
		}
		return typeDescriptionToScopeMap
	}

	/// Validates that a constant `@Instantiated` dependency has no `@Forwarded` properties.
	private func validateNoForwardedProperties(
		for dependency: Dependency,
		instantiable: Instantiable,
		parent: Instantiable,
	) throws {
		if dependency.property.propertyType.isConstant {
			guard instantiable.dependencies.filter(\.isForwarded).isEmpty else {
				throw DependencyTreeGeneratorError
					.instantiableHasForwardedProperty(
						property: dependency.property,
						instantiableWithForwardedProperty: instantiable,
						parent: parent,
					)
			}
		}
	}

	/// Validates scopes for cycles and optionally for unfulfillable properties.
	/// When `cyclesOnly` is true, unfulfillable property collection is skipped —
	/// used for mock-only types where unfulfillable received properties are expected
	/// (they become required mock parameters).
	private func validatePropertiesAreFulfillable(
		typeDescriptionToScopeMap: [TypeDescription: Scope],
		cyclesOnly: Bool,
	) throws {
		var unfulfillableProperties = Set<DependencyTreeGeneratorError.UnfulfillableProperty>()
		func validatePropertiesAreFulfillable(
			on scope: Scope,
			receivableProperties: Set<Property>,
			property: Property?,
			propertyStack: [Property],
			root: TypeDescription,
		) throws {
			if let property {
				func validateNoCycleInReceivedProperties(
					scope: Scope,
					receivedPropertyStack: [Property],
					instantiationStack: [Property],
				) throws {
					for childProperty in scope.requiredReceivedProperties {
						guard childProperty != property else {
							throw DependencyTreeGeneratorError.receivedConstantCycleDetected(
								instantiated: property,
								receivedPropertyChain: receivedPropertyStack + [childProperty],
							)
						}
						guard !receivedPropertyStack.contains(childProperty) else {
							// We've found a cycle, but it's not our cycle. Bail and let a future loop find this.
							return
						}
						if let cycleIndex = instantiationStack.firstIndex(of: childProperty) {
							let instantiationProperties = Array(instantiationStack[0...cycleIndex])
							let typesInCycle = (
								[childProperty]
									+ receivedPropertyStack.reversed()
									+ instantiationProperties,
							).map(\.typeDescription)
							try Self.throwIfInvalidCycle(
								typesInCycle: typesInCycle,
								property: childProperty,
								directParent: scope.instantiable.concreteInstantiable,
								isReceived: !childProperty.propertyType.isConstant,
							)
						} else if let receivedPropertyScope = typeDescriptionToScopeMap[childProperty.typeDescription] {
							var childPropertyStack = receivedPropertyStack
							childPropertyStack.append(childProperty)
							try validateNoCycleInReceivedProperties(
								scope: receivedPropertyScope,
								receivedPropertyStack: childPropertyStack,
								instantiationStack: instantiationStack,
							)
						}
					}
				}
				let instantiationStack: [Property] = [property] + propertyStack
				try validateNoCycleInReceivedProperties(
					scope: scope,
					receivedPropertyStack: [],
					instantiationStack: instantiationStack,
				)
			}

			if !cyclesOnly {
				for receivedProperty in scope.requiredReceivedProperties {
					let parentContainsProperty = receivableProperties.contains(receivedProperty)
					let propertyIsCreatedAtThisScope = scope.createdProperties.contains(receivedProperty)
					if !parentContainsProperty, !propertyIsCreatedAtThisScope {
						if property != nil {
							// This property is in a dependency tree and is unfulfillable. Record the problem.
							unfulfillableProperties.insert(.init(
								property: receivedProperty,
								instantiable: scope.instantiable,
								parentStack: propertyStack.map(\.typeDescription) + [root],
								suggestedAlternatives: receivableProperties.filter {
									receivedProperty.typeDescription.leastQualifiedTypeDescription == $0.typeDescription.leastQualifiedTypeDescription
										|| receivedProperty.label == $0.label
								}.sorted(),
							))
						}
					}
				}
			}

			// Check children for cycles.
			// Skip forwarded dependencies — they're runtime parameters passed through
			// the Instantiator closure, not scope-level dependencies that create cycles.
			var childPropertyStack = propertyStack
			if let property {
				childPropertyStack.insert(property, at: 0)
			}
			for dependency in scope.instantiable.dependencies where dependency.source != .forwarded {
				let propertyForDependency = dependency.source.fulfillingProperty ?? dependency.property
				guard let cycleIndex = childPropertyStack.firstIndex(of: propertyForDependency) else {
					continue
				}
				let typesInCycle = (
					[propertyForDependency]
						+ childPropertyStack[0...cycleIndex],
				).map(\.typeDescription)
				try Self.throwIfInvalidCycle(
					typesInCycle: typesInCycle,
					property: propertyForDependency,
					directParent: scope.instantiable.concreteInstantiable,
					isReceived: dependency.source.isReceived,
				)
			}

			for childPropertyToGenerate in scope.propertiesToGenerate {
				switch childPropertyToGenerate {
				case let .instantiated(childProperty, childScope, _):
					guard !childPropertyStack.contains(childProperty) else {
						// There is a cycle in our scope tree. Do not re-enter it.
						continue
					}
					try validatePropertiesAreFulfillable(
						on: childScope,
						receivableProperties: receivableProperties
							.union(scope.properties)
							.removing(childProperty),
						property: childProperty,
						propertyStack: childPropertyStack,
						root: root,
					)
				case .aliased:
					break
				}
			}
		}

		for rootScope in rootInstantiables.compactMap({ typeDescriptionToScopeMap[$0] }) {
			try validatePropertiesAreFulfillable(
				on: rootScope,
				receivableProperties: Set(rootScope.properties),
				property: nil,
				propertyStack: [],
				root: rootScope.instantiable.concreteInstantiable,
			)
		}

		// When checking cycles only (mock validation), also validate non-root types
		// that have generateMock enabled — they bypass root entry points.
		if cyclesOnly {
			let rootInstantiableSet = Set(rootInstantiables)
			for scope in Set(typeDescriptionToScopeMap.values)
				where scope.instantiable.generateMock && !rootInstantiableSet.contains(scope.instantiable.concreteInstantiable)
			{
				try validatePropertiesAreFulfillable(
					on: scope,
					receivableProperties: Set(scope.properties),
					property: nil,
					propertyStack: [],
					root: scope.instantiable.concreteInstantiable,
				)
			}
		}

		if !unfulfillableProperties.isEmpty {
			throw DependencyTreeGeneratorError.unfulfillableProperties(Array(unfulfillableProperties))
		}
	}

	/// Validates a mock scope for dependency cycles only (not unfulfillable properties).
	/// Mock-only types may have unfulfillable received properties by design (they become
	/// required mock parameters), but cycles still generate uncompilable code.
	private func validateReachableTypeDescriptions() throws {
		for reachableTypeDescription in reachableTypeDescriptions {
			if typeDescriptionToFulfillingInstantiableMap[reachableTypeDescription] == nil {
				throw DependencyTreeGeneratorError.noInstantiableFound(reachableTypeDescription)
			}
		}
	}
}

// MARK: - Dependency

extension Dependency {
	fileprivate var isInstantiated: Bool {
		switch source {
		case .instantiated:
			true
		case .aliased, .forwarded, .received:
			false
		}
	}

	fileprivate var isForwarded: Bool {
		switch source {
		case .forwarded:
			true
		case .aliased, .instantiated, .received:
			false
		}
	}
}

// MARK: - Set

extension Set {
	fileprivate func removing(_ element: Element) -> Self {
		var setWithoutElement = self
		setWithoutElement.remove(element)
		return setWithoutElement
	}
}

// MARK: - TypeDescription

extension TypeDescription {
	fileprivate var leastQualifiedTypeDescription: TypeDescription {
		switch self {
		case let .nested(name, _, generics):
			.simple(name: name, generics: generics)
		case let .any(typeDescription),
		     let .implicitlyUnwrappedOptional(typeDescription),
		     let .optional(typeDescription),
		     let .some(typeDescription):
			typeDescription.leastQualifiedTypeDescription
		case .array,
		     .attributed,
		     .closure,
		     .composition,
		     .dictionary,
		     .metatype,
		     .simple,
		     .tuple,
		     .unknown,
		     .void:
			self
		}
	}
}
