// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Foundation
import SafeDICore
import Testing
@testable import SafeDITool

struct SafeDIToolMockOnlyErrorTests: ~Copyable {
	// MARK: Initialization

	init() throws {
		filesToDelete = [URL]()
	}

	deinit {
		for fileToDelete in filesToDelete {
			try! FileManager.default.removeItem(at: fileToDelete)
		}
	}

	// MARK: Error Tests

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersGenerateMock_whenMockOnlyAlsoExistsForSameType() async throws {
		// generateMock: true on the production type takes priority over the mockOnly extension.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct MyService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension MyService {
				    public static func mock() -> MyService { fatalError() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// The generated mock uses the production type's init (from generateMock),
		// not the mockOnly extension's hand-written mock.
		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension MyService {
		    static func mock() -> MyService {
		        MyService()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["MyService+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_throwsError_whenTwoMockOnlyExistForSameType() async {
		await assertThrowsError(
			"Found multiple `mockOnly: true` declarations for `MyService`. A type can have at most one `mockOnly` declaration.",
		) {
			try await executeSafeDIToolTest(
				swiftFileContent: [
					"""
					@Instantiable(mockOnly: true)
					extension MyService {
					    public static func mock() -> MyService { fatalError() }
					}
					""",
					"""
					@Instantiable(mockOnly: true)
					extension MyService {
					    public static func mock() -> MyService { fatalError() }
					}
					""",
				],
				buildSwiftOutputDirectory: true,
				filesToDelete: &filesToDelete,
			)
		}
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersHandWrittenMock_whenMockOnlyAlsoExistsForSameType() async throws {
		// Production type with a hand-written mock takes priority over the mockOnly extension.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(mockOnly: true)
				extension MyService {
				    public static func mock() -> MyService { fatalError() }
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable {
				    public init() {}
				    public static func mock() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// No mock file is generated — the production type has a hand-written mock
		// and generateMock is false, so SafeDI doesn't generate a mock method.
		#expect(output.mockFiles.isEmpty, "Unexpected mock files \(output.mockFiles.keys)")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersGenerateMock_whenMockOnlyArrivesSecond() async throws {
		// Same as mock_prefersGenerateMock_whenMockOnlyAlsoExistsForSameType but
		// with reversed source file order.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct MyService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension MyService {
				    public static func mock() -> MyService { fatalError() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension MyService {
		    static func mock() -> MyService {
		        MyService()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["MyService+SafeDIMock.swift"] ?? "")")
	}

	// MARK: Private

	private var filesToDelete = [URL]()
}
