// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Foundation
import SafeDICore
import Testing
@testable import SafeDITool

struct SafeDIToolMockOnlyTests: ~Copyable {
	// MARK: Initialization

	init() throws {
		filesToDelete = [URL]()
	}

	deinit {
		for fileToDelete in filesToDelete {
			try! FileManager.default.removeItem(at: fileToDelete)
		}
	}

	// MARK: Tests

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesDefaultFromMockOnlyExtension_whenForwardedPropertyHasMockOnlyDeclaration() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(name: String) {
				        self.name = name
				    }
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension String {
				    public static func mock() -> String { "" }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        name: String = String.mock()
		    ) -> Root {
		        return Root(name: name)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesDefaultFromMockOnlyExtension_whenPrimitiveTypeHasMockOnlyDeclaration() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(count: Int) {
				        self.count = count
				    }
				    @Forwarded let count: Int
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension Int {
				    public static func mock() -> Int { 0 }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        count: Int = Int.mock()
		    ) -> Root {
		        return Root(count: count)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesDefaultFromMockOnlyExtension_whenInstantiatedPropertyHasMockOnlyDeclaration() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ExternalService) {
				        self.service = service
				    }
				    @Instantiated let service: ExternalService
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension ExternalService {
				    public static func mock() -> ExternalService { fatalError() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> ExternalService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> ExternalService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? ExternalService.mock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesCustomMockName_whenMockOnlyTypeHasCustomMockName() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(name: String) {
				        self.name = name
				    }
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "testValue")
				extension String {
				    public static func testValue() -> String { "test" }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        name: String = String.testValue()
		    ) -> Root {
		        return Root(name: name)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_mergesMockOnlyDeclarationWithRegularExtension_whenBothExistForSameType() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				public struct MyService {
				    public static func mock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(conformsElsewhere: true)
				extension MyService: Instantiable {
				    public static func instantiate() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.mock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_mergesRegularDeclarationWithMockOnlyExtension_whenBothExistForSameType() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension MyService {
				    public static func mock() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.mock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesDefaultFromMergedMockOnlyProvider_whenForwardedPropertyTypeHasSeparateMockOnlyAndProductionDeclarations() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Forwarded let service: MyService
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension MyService {
				    public static func mock() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        service: MyService = MyService.mock()
		    ) -> Root {
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	// MARK: Private

	private var filesToDelete = [URL]()
}
