// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Foundation
import SafeDICore
import Testing
@testable import SafeDITool

struct SafeDIToolMockGenerationTests: ~Copyable {
	// MARK: Initialization

	init() throws {
		filesToDelete = [URL]()
	}

	deinit {
		for fileToDelete in filesToDelete {
			try! FileManager.default.removeItem(at: fileToDelete)
		}
	}

	// MARK: Tests – Default behavior

	@Test
	mutating func mock_notGeneratedWhenNoConfigurationExists() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable
				public struct SimpleType: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		let mockContent = try #require(output.mockFiles["SimpleType+SafeDIMock.swift"])
		// When no @SafeDIConfiguration exists, generateMocks defaults to false.
		// The mock file exists (for the build system) but contains only the header.
		#expect(!mockContent.contains("extension"))
	}

	// MARK: Tests – Simple types

	@Test
	mutating func mock_generatedForTypeWithNoDependencies() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable
				public struct SimpleType: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["SimpleType+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension SimpleType {
		    public static func mock() -> SimpleType {
		        SimpleType()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForExtensionBasedInstantiable() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public class SomeThirdPartyType {}

				@Instantiable
				extension SomeThirdPartyType: Instantiable {
				    public static func instantiate() -> SomeThirdPartyType {
				        SomeThirdPartyType()
				    }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["SomeThirdPartyType+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension SomeThirdPartyType {
		    public static func mock() -> SomeThirdPartyType {
		        SomeThirdPartyType.instantiate()
		    }
		}
		#endif
		""")
	}

	// MARK: Tests – Types with dependencies

	@Test
	mutating func mock_generatedForTypeWithInstantiatedDependency() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(dep: Dep) {
				        self.dep = dep
				    }
				    @Instantiated let dep: Dep
				}
				""",
				"""
				@Instantiable
				public struct Dep: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum Dep { case root }
		    }

		    public static func mock(
		        dep: ((SafeDIMockPath.Dep) -> Dep)? = nil
		    ) -> Root {
		        let dep = dep?(.root) ?? Dep.mock()
		        return Root(dep: dep)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Dep+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Dep {
		    public static func mock() -> Dep {
		        Dep()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForTypeWithReceivedDependency() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child, shared: SharedThing) {
				        self.child = child
				        self.shared = shared
				    }
				    @Instantiated let child: Child
				    @Instantiated let shared: SharedThing
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init(shared: SharedThing) {
				        self.shared = shared
				    }
				    @Received let shared: SharedThing
				}
				""",
				"""
				@Instantiable
				public struct SharedThing: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public enum SafeDIMockPath {
		        public enum SharedThing { case parent }
		    }

		    public static func mock(
		        sharedThing: ((SafeDIMockPath.SharedThing) -> SharedThing)? = nil
		    ) -> Child {
		        let sharedThing = sharedThing?(.parent) ?? SharedThing.mock()
		        return Child(shared: sharedThing)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum Child { case root }
		        public enum SharedThing { case root }
		    }

		    public static func mock(
		        child: ((SafeDIMockPath.Child) -> Child)? = nil,
		        sharedThing: ((SafeDIMockPath.SharedThing) -> SharedThing)? = nil
		    ) -> Root {
		        let sharedThing = sharedThing?(.root) ?? SharedThing.mock()
		        let child = child?(.root) ?? Child(shared: sharedThing)
		        return Root(child: child, shared: sharedThing)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["SharedThing+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension SharedThing {
		    public static func mock() -> SharedThing {
		        SharedThing()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForFullTree() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, shared: SharedThing) {
				        self.childA = childA
				        self.shared = shared
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let shared: SharedThing
				}
				""",
				"""
				@Instantiable
				public struct ChildA: Instantiable {
				    public init(shared: SharedThing, grandchild: Grandchild) {
				        self.shared = shared
				        self.grandchild = grandchild
				    }
				    @Received let shared: SharedThing
				    @Instantiated let grandchild: Grandchild
				}
				""",
				"""
				@Instantiable
				public struct Grandchild: Instantiable {
				    public init(shared: SharedThing) {
				        self.shared = shared
				    }
				    @Received let shared: SharedThing
				}
				""",
				"""
				@Instantiable
				public struct SharedThing: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 4)
		#expect(output.mockFiles["ChildA+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildA {
		    public enum SafeDIMockPath {
		        public enum Grandchild { case root }
		        public enum SharedThing { case parent }
		    }

		    public static func mock(
		        grandchild: ((SafeDIMockPath.Grandchild) -> Grandchild)? = nil,
		        sharedThing: ((SafeDIMockPath.SharedThing) -> SharedThing)? = nil
		    ) -> ChildA {
		        let sharedThing = sharedThing?(.parent) ?? SharedThing.mock()
		        let grandchild = grandchild?(.root) ?? Grandchild(shared: sharedThing)
		        return ChildA(shared: sharedThing, grandchild: grandchild)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Grandchild+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Grandchild {
		    public enum SafeDIMockPath {
		        public enum SharedThing { case parent }
		    }

		    public static func mock(
		        sharedThing: ((SafeDIMockPath.SharedThing) -> SharedThing)? = nil
		    ) -> Grandchild {
		        let sharedThing = sharedThing?(.parent) ?? SharedThing.mock()
		        return Grandchild(shared: sharedThing)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum ChildA { case root }
		        public enum Grandchild { case childA }
		        public enum SharedThing { case root }
		    }

		    public static func mock(
		        childA: ((SafeDIMockPath.ChildA) -> ChildA)? = nil,
		        grandchild: ((SafeDIMockPath.Grandchild) -> Grandchild)? = nil,
		        sharedThing: ((SafeDIMockPath.SharedThing) -> SharedThing)? = nil
		    ) -> Root {
		        let sharedThing = sharedThing?(.root) ?? SharedThing.mock()
		        let grandchild = grandchild?(.childA) ?? Grandchild(shared: sharedThing)
		        let childA = childA?(.root) ?? ChildA(shared: sharedThing, grandchild: grandchild)
		        return Root(childA: childA, shared: sharedThing)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["SharedThing+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension SharedThing {
		    public static func mock() -> SharedThing {
		        SharedThing()
		    }
		}
		#endif
		""")
	}

	// MARK: Tests – Configuration

	@Test
	mutating func mock_respectsMockConditionalCompilationNil() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@SafeDIConfiguration
				enum Config {
				    static let additionalImportedModules: [StaticString] = []
				    static let additionalDirectoriesToInclude: [StaticString] = []
				    static let generateMocks: Bool = true
				    static let mockConditionalCompilation: StaticString? = nil
				}
				""",
				"""
				@Instantiable
				public struct NoBranch: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["NoBranch+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension NoBranch {
		    public static func mock() -> NoBranch {
		        NoBranch()
		    }
		}
		""")
	}

	@Test
	mutating func mock_respectsCustomMockConditionalCompilation() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@SafeDIConfiguration
				enum Config {
				    static let additionalImportedModules: [StaticString] = []
				    static let additionalDirectoriesToInclude: [StaticString] = []
				    static let generateMocks: Bool = true
				    static let mockConditionalCompilation: StaticString? = "TESTING"
				}
				""",
				"""
				@Instantiable
				public struct CustomFlag: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["CustomFlag+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if TESTING
		extension CustomFlag {
		    public static func mock() -> CustomFlag {
		        CustomFlag()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_typeWithDepsAndNilConditionalCompilation() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@SafeDIConfiguration
				enum Config {
				    static let additionalImportedModules: [StaticString] = []
				    static let additionalDirectoriesToInclude: [StaticString] = []
				    static let generateMocks: Bool = true
				    static let mockConditionalCompilation: StaticString? = nil
				}
				""",
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(dep: Dep) {
				        self.dep = dep
				    }
				    @Instantiated let dep: Dep
				}
				""",
				"""
				@Instantiable
				public struct Dep: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Dep+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Dep {
		    public static func mock() -> Dep {
		        Dep()
		    }
		}
		""")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Root {
		    public enum SafeDIMockPath {
		        public enum Dep { case root }
		    }

		    public static func mock(
		        dep: ((SafeDIMockPath.Dep) -> Dep)? = nil
		    ) -> Root {
		        let dep = dep?(.root) ?? Dep.mock()
		        return Root(dep: dep)
		    }
		}
		""")
	}

	@Test
	mutating func mock_notGeneratedWhenGenerateMocksIsFalse() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@SafeDIConfiguration
				enum Config {
				    static let additionalImportedModules: [StaticString] = []
				    static let additionalDirectoriesToInclude: [StaticString] = []
				    static let generateMocks: Bool = false
				    static let mockConditionalCompilation: StaticString? = "DEBUG"
				}
				""",
				"""
				@Instantiable
				public struct NoMocks: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		let mockContent = try #require(output.mockFiles["NoMocks+SafeDIMock.swift"])
		// When generateMocks is false, the file exists but contains only the header.
		#expect(!mockContent.contains("extension"))
	}

	@Test
	mutating func mock_respectsMockAttributes() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(mockAttributes: "@MainActor")
				public struct ActorBound: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["ActorBound+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ActorBound {
		    @MainActor public static func mock() -> ActorBound {
		        ActorBound()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_parameterRequiredForTypeNotInTypeMap() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol SomeProtocol {}

				@Instantiable
				public struct Consumer: Instantiable {
				    public init(dependency: SomeProtocol) {
				        self.dependency = dependency
				    }
				    @Received let dependency: SomeProtocol
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Consumer+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Consumer {
		    public enum SafeDIMockPath {
		        public enum SomeProtocol { case parent }
		    }

		    public static func mock(
		        someProtocol: @escaping (SafeDIMockPath.SomeProtocol) -> SomeProtocol
		    ) -> Consumer {
		        let someProtocol = someProtocol(.parent)
		        return Consumer(dependency: someProtocol)
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_extensionBasedWithNilConditionalCompilation() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@SafeDIConfiguration
				enum Config {
				    static let additionalImportedModules: [StaticString] = []
				    static let additionalDirectoriesToInclude: [StaticString] = []
				    static let generateMocks: Bool = true
				    static let mockConditionalCompilation: StaticString? = nil
				}
				""",
				"""
				public class ThirdParty {}

				@Instantiable
				extension ThirdParty: Instantiable {
				    public static func instantiate() -> ThirdParty {
				        ThirdParty()
				    }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["ThirdParty+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension ThirdParty {
		    public static func mock() -> ThirdParty {
		        ThirdParty.instantiate()
		    }
		}
		""")
	}

	@Test
	mutating func mock_receivedErasedTypeAutoWraps() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public class AnyService {
				    public init(_ service: some Any) {}
				}
				""",
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child, myService: AnyService) {
				        self.child = child
				        self.myService = myService
				    }
				    @Instantiated let child: Child
				    @Instantiated(fulfilledByType: "ConcreteService", erasedToConcreteExistential: true) let myService: AnyService
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init(myService: AnyService) {
				        self.myService = myService
				    }
				    @Received let myService: AnyService
				}
				""",
				"""
				@Instantiable
				public struct ConcreteService: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		// Child receives AnyService, which is erased-to-concrete.
		// The mock should auto-detect this and provide AnyService param with inline wrapping.
		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public enum SafeDIMockPath {
		        public enum AnyService { case parent }
		    }

		    public static func mock(
		        anyService: ((SafeDIMockPath.AnyService) -> AnyService)? = nil
		    ) -> Child {
		        let anyService = anyService?(.parent) ?? AnyService(ConcreteService.mock())
		        return Child(myService: anyService)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["ConcreteService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ConcreteService {
		    public static func mock() -> ConcreteService {
		        ConcreteService()
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum AnyService { case root }
		        public enum Child { case root }
		        public enum ConcreteService { case root }
		    }

		    public static func mock(
		        anyService: ((SafeDIMockPath.AnyService) -> AnyService)? = nil,
		        child: ((SafeDIMockPath.Child) -> Child)? = nil,
		        concreteService: ((SafeDIMockPath.ConcreteService) -> ConcreteService)? = nil
		    ) -> Root {
		        let concreteService = concreteService?(.root) ?? ConcreteService.mock()
		        let anyService = anyService?(.root) ?? AnyService(concreteService)
		        let child = child?(.root) ?? Child(myService: anyService)
		        return Root(child: child, myService: anyService)
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForErasedToConcreteExistential() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol MyService {}
				public class AnyMyService {
				    public init(_ service: some MyService) {}
				}
				""",
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(myService: AnyMyService) {
				        self.myService = myService
				    }
				    @Instantiated(fulfilledByType: "DefaultMyService", erasedToConcreteExistential: true) let myService: AnyMyService
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [MyService.self])
				public struct DefaultMyService: Instantiable, MyService {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["DefaultMyService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension DefaultMyService {
		    public static func mock() -> DefaultMyService {
		        DefaultMyService()
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum AnyMyService { case root }
		        public enum DefaultMyService { case root }
		    }

		    public static func mock(
		        anyMyService: ((SafeDIMockPath.AnyMyService) -> AnyMyService)? = nil,
		        defaultMyService: ((SafeDIMockPath.DefaultMyService) -> DefaultMyService)? = nil
		    ) -> Root {
		        let defaultMyService = defaultMyService?(.root) ?? DefaultMyService.mock()
		        let anyMyService = anyMyService?(.root) ?? AnyMyService(defaultMyService)
		        return Root(myService: anyMyService)
		    }
		}
		#endif
		""")
	}

	// MARK: Tests – Complex configurations

	@Test
	mutating func mock_generatedForRootWithMultipleBranchesReceivingSameProperty() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public final class Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB, shared: Shared) {
				        self.childA = childA
				        self.childB = childB
				        self.shared = shared
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				    @Instantiated let shared: Shared
				}
				""",
				"""
				@Instantiable
				public final class ChildA: Instantiable {
				    public init(grandchildAA: GrandchildAA, grandchildAB: GrandchildAB) {
				        self.grandchildAA = grandchildAA
				        self.grandchildAB = grandchildAB
				    }
				    @Instantiated let grandchildAA: GrandchildAA
				    @Instantiated let grandchildAB: GrandchildAB
				}
				""",
				"""
				@Instantiable
				public final class GrandchildAA: Instantiable {
				    public init(shared: Shared) {
				        self.shared = shared
				    }
				    @Received let shared: Shared
				}
				""",
				"""
				@Instantiable
				public final class GrandchildAB: Instantiable {
				    public init(shared: Shared) {
				        self.shared = shared
				    }
				    @Received let shared: Shared
				}
				""",
				"""
				@Instantiable
				public final class ChildB: Instantiable {
				    public init(shared: Shared) {
				        self.shared = shared
				    }
				    @Received let shared: Shared
				}
				""",
				"""
				@Instantiable
				public final class Shared: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 6)
		#expect(output.mockFiles["ChildA+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildA {
		    public enum SafeDIMockPath {
		        public enum GrandchildAA { case root }
		        public enum GrandchildAB { case root }
		    }

		    public static func mock(
		        grandchildAA: ((SafeDIMockPath.GrandchildAA) -> GrandchildAA)? = nil,
		        grandchildAB: ((SafeDIMockPath.GrandchildAB) -> GrandchildAB)? = nil
		    ) -> ChildA {
		        let grandchildAA = grandchildAA?(.root) ?? GrandchildAA.mock()
		        let grandchildAB = grandchildAB?(.root) ?? GrandchildAB.mock()
		        return ChildA(grandchildAA: grandchildAA, grandchildAB: grandchildAB)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["ChildB+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildB {
		    public enum SafeDIMockPath {
		        public enum Shared { case parent }
		    }

		    public static func mock(
		        shared: ((SafeDIMockPath.Shared) -> Shared)? = nil
		    ) -> ChildB {
		        let shared = shared?(.parent) ?? Shared.mock()
		        return ChildB(shared: shared)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["GrandchildAA+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension GrandchildAA {
		    public enum SafeDIMockPath {
		        public enum Shared { case parent }
		    }

		    public static func mock(
		        shared: ((SafeDIMockPath.Shared) -> Shared)? = nil
		    ) -> GrandchildAA {
		        let shared = shared?(.parent) ?? Shared.mock()
		        return GrandchildAA(shared: shared)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["GrandchildAB+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension GrandchildAB {
		    public enum SafeDIMockPath {
		        public enum Shared { case parent }
		    }

		    public static func mock(
		        shared: ((SafeDIMockPath.Shared) -> Shared)? = nil
		    ) -> GrandchildAB {
		        let shared = shared?(.parent) ?? Shared.mock()
		        return GrandchildAB(shared: shared)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum ChildA { case root }
		        public enum ChildB { case root }
		        public enum GrandchildAA { case childA }
		        public enum GrandchildAB { case childA }
		        public enum Shared { case root }
		    }

		    public static func mock(
		        childA: ((SafeDIMockPath.ChildA) -> ChildA)? = nil,
		        childB: ((SafeDIMockPath.ChildB) -> ChildB)? = nil,
		        grandchildAA: ((SafeDIMockPath.GrandchildAA) -> GrandchildAA)? = nil,
		        grandchildAB: ((SafeDIMockPath.GrandchildAB) -> GrandchildAB)? = nil,
		        shared: ((SafeDIMockPath.Shared) -> Shared)? = nil
		    ) -> Root {
		        let shared = shared?(.root) ?? Shared.mock()
		        let childB = childB?(.root) ?? ChildB(shared: shared)
		        let grandchildAA = grandchildAA?(.childA) ?? GrandchildAA(shared: shared)
		        let grandchildAB = grandchildAB?(.childA) ?? GrandchildAB(shared: shared)
		        let childA = childA?(.root) ?? ChildA.mock()
		        return Root(childA: childA, childB: childB, shared: shared)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Shared+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Shared {
		    public static func mock() -> Shared {
		        Shared()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForRootWithProtocolFulfilledByAdditionalType() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol NetworkService {}

				@Instantiable(fulfillingAdditionalTypes: [NetworkService.self])
				public final class DefaultNetworkService: Instantiable, NetworkService {
				    public init() {}
				}
				""",
				"""
				@Instantiable(isRoot: true)
				public final class Root: Instantiable {
				    public init(networkService: NetworkService) {
				        self.networkService = networkService
				    }
				    @Instantiated let networkService: NetworkService
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["DefaultNetworkService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension DefaultNetworkService {
		    public static func mock() -> DefaultNetworkService {
		        DefaultNetworkService()
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum NetworkService { case root }
		    }

		    public static func mock(
		        networkService: ((SafeDIMockPath.NetworkService) -> NetworkService)? = nil
		    ) -> Root {
		        let networkService = networkService?(.root) ?? DefaultNetworkService.mock()
		        return Root(networkService: networkService)
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForMultipleRootsEachGetsOwnMockFile() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct RootA: Instantiable {
				    public init(dep: Dep) {
				        self.dep = dep
				    }
				    @Instantiated let dep: Dep
				}
				""",
				"""
				@Instantiable(isRoot: true)
				public struct RootB: Instantiable {
				    public init(dep: Dep) {
				        self.dep = dep
				    }
				    @Instantiated let dep: Dep
				}
				""",
				"""
				@Instantiable
				public struct Dep: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		// Each root gets its own mock. Dep also gets a mock.
		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["RootA+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension RootA {
		    public enum SafeDIMockPath {
		        public enum Dep { case root }
		    }

		    public static func mock(
		        dep: ((SafeDIMockPath.Dep) -> Dep)? = nil
		    ) -> RootA {
		        let dep = dep?(.root) ?? Dep.mock()
		        return RootA(dep: dep)
		    }
		}
		#endif
		""")
		#expect(output.mockFiles["RootB+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension RootB {
		    public enum SafeDIMockPath {
		        public enum Dep { case root }
		    }

		    public static func mock(
		        dep: ((SafeDIMockPath.Dep) -> Dep)? = nil
		    ) -> RootB {
		        let dep = dep?(.root) ?? Dep.mock()
		        return RootB(dep: dep)
		    }
		}
		#endif
		""")
		#expect(output.mockFiles["Dep+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Dep {
		    public static func mock() -> Dep {
		        Dep()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_constructionOrderRespectsReceivedDependencies() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB, shared: Shared) {
				        self.childA = childA
				        self.childB = childB
				        self.shared = shared
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				    @Instantiated let shared: Shared
				}
				""",
				"""
				@Instantiable
				public struct ChildA: Instantiable {
				    public init(shared: Shared) {
				        self.shared = shared
				    }
				    @Received let shared: Shared
				}
				""",
				"""
				@Instantiable
				public struct ChildB: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable
				public struct Shared: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		// Shared must be constructed before ChildA (which depends on it via @Received).
		#expect(output.mockFiles.count == 4)
		#expect(output.mockFiles["ChildA+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildA {
		    public enum SafeDIMockPath {
		        public enum Shared { case parent }
		    }

		    public static func mock(
		        shared: ((SafeDIMockPath.Shared) -> Shared)? = nil
		    ) -> ChildA {
		        let shared = shared?(.parent) ?? Shared.mock()
		        return ChildA(shared: shared)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["ChildB+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildB {
		    public static func mock() -> ChildB {
		        ChildB()
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum ChildA { case root }
		        public enum ChildB { case root }
		        public enum Shared { case root }
		    }

		    public static func mock(
		        childA: ((SafeDIMockPath.ChildA) -> ChildA)? = nil,
		        childB: ((SafeDIMockPath.ChildB) -> ChildB)? = nil,
		        shared: ((SafeDIMockPath.Shared) -> Shared)? = nil
		    ) -> Root {
		        let childB = childB?(.root) ?? ChildB.mock()
		        let shared = shared?(.root) ?? Shared.mock()
		        let childA = childA?(.root) ?? ChildA(shared: shared)
		        return Root(childA: childA, childB: childB, shared: shared)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Shared+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Shared {
		    public static func mock() -> Shared {
		        Shared()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForFourLevelDeepTreeWithSharedLeaf() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child, leaf: Leaf) {
				        self.child = child
				        self.leaf = leaf
				    }
				    @Instantiated let child: Child
				    @Instantiated let leaf: Leaf
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init(grandchild: Grandchild, leaf: Leaf) {
				        self.grandchild = grandchild
				        self.leaf = leaf
				    }
				    @Instantiated let grandchild: Grandchild
				    @Received let leaf: Leaf
				}
				""",
				"""
				@Instantiable
				public struct Grandchild: Instantiable {
				    public init(greatGrandchild: GreatGrandchild, leaf: Leaf) {
				        self.greatGrandchild = greatGrandchild
				        self.leaf = leaf
				    }
				    @Instantiated let greatGrandchild: GreatGrandchild
				    @Received let leaf: Leaf
				}
				""",
				"""
				@Instantiable
				public struct GreatGrandchild: Instantiable {
				    public init(leaf: Leaf) {
				        self.leaf = leaf
				    }
				    @Received let leaf: Leaf
				}
				""",
				"""
				@Instantiable
				public struct Leaf: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 5)
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public enum SafeDIMockPath {
		        public enum Grandchild { case root }
		        public enum GreatGrandchild { case grandchild }
		        public enum Leaf { case parent }
		    }

		    public static func mock(
		        grandchild: ((SafeDIMockPath.Grandchild) -> Grandchild)? = nil,
		        greatGrandchild: ((SafeDIMockPath.GreatGrandchild) -> GreatGrandchild)? = nil,
		        leaf: ((SafeDIMockPath.Leaf) -> Leaf)? = nil
		    ) -> Child {
		        let leaf = leaf?(.parent) ?? Leaf.mock()
		        let greatGrandchild = greatGrandchild?(.grandchild) ?? GreatGrandchild(leaf: leaf)
		        let grandchild = grandchild?(.root) ?? Grandchild(greatGrandchild: greatGrandchild, leaf: leaf)
		        return Child(grandchild: grandchild, leaf: leaf)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Grandchild+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Grandchild {
		    public enum SafeDIMockPath {
		        public enum GreatGrandchild { case root }
		        public enum Leaf { case parent }
		    }

		    public static func mock(
		        greatGrandchild: ((SafeDIMockPath.GreatGrandchild) -> GreatGrandchild)? = nil,
		        leaf: ((SafeDIMockPath.Leaf) -> Leaf)? = nil
		    ) -> Grandchild {
		        let leaf = leaf?(.parent) ?? Leaf.mock()
		        let greatGrandchild = greatGrandchild?(.root) ?? GreatGrandchild(leaf: leaf)
		        return Grandchild(greatGrandchild: greatGrandchild, leaf: leaf)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["GreatGrandchild+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension GreatGrandchild {
		    public enum SafeDIMockPath {
		        public enum Leaf { case parent }
		    }

		    public static func mock(
		        leaf: ((SafeDIMockPath.Leaf) -> Leaf)? = nil
		    ) -> GreatGrandchild {
		        let leaf = leaf?(.parent) ?? Leaf.mock()
		        return GreatGrandchild(leaf: leaf)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Leaf+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Leaf {
		    public static func mock() -> Leaf {
		        Leaf()
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum Child { case root }
		        public enum Grandchild { case child }
		        public enum GreatGrandchild { case child_grandchild }
		        public enum Leaf { case root }
		    }

		    public static func mock(
		        child: ((SafeDIMockPath.Child) -> Child)? = nil,
		        grandchild: ((SafeDIMockPath.Grandchild) -> Grandchild)? = nil,
		        greatGrandchild: ((SafeDIMockPath.GreatGrandchild) -> GreatGrandchild)? = nil,
		        leaf: ((SafeDIMockPath.Leaf) -> Leaf)? = nil
		    ) -> Root {
		        let leaf = leaf?(.root) ?? Leaf.mock()
		        let greatGrandchild = greatGrandchild?(.child_grandchild) ?? GreatGrandchild(leaf: leaf)
		        let grandchild = grandchild?(.child) ?? Grandchild(greatGrandchild: greatGrandchild, leaf: leaf)
		        let child = child?(.root) ?? Child(grandchild: grandchild, leaf: leaf)
		        return Root(child: child, leaf: leaf)
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_inlineConstructionSkipsDefaultValuedArguments() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child, shared: Shared) {
				        self.child = child
				        self.shared = shared
				    }
				    @Instantiated let child: Child
				    @Instantiated let shared: Shared
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init(shared: Shared, flag: Bool = false) {
				        self.shared = shared
				    }
				    @Received let shared: Shared
				}
				""",
				"""
				@Instantiable
				public struct Shared: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public enum SafeDIMockPath {
		        public enum Shared { case parent }
		    }

		    public static func mock(
		        shared: ((SafeDIMockPath.Shared) -> Shared)? = nil
		    ) -> Child {
		        let shared = shared?(.parent) ?? Shared.mock()
		        return Child(shared: shared)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum Child { case root }
		        public enum Shared { case root }
		    }

		    public static func mock(
		        child: ((SafeDIMockPath.Child) -> Child)? = nil,
		        shared: ((SafeDIMockPath.Shared) -> Shared)? = nil
		    ) -> Root {
		        let shared = shared?(.root) ?? Shared.mock()
		        let child = child?(.root) ?? Child(shared: shared)
		        return Root(child: child, shared: shared)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Shared+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Shared {
		    public static func mock() -> Shared {
		        Shared()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForTypeWithInstantiatorDependency() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(shared: Shared, childBuilder: Instantiator<Child>) {
				        self.shared = shared
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let shared: Shared
				    @Instantiated let childBuilder: Instantiator<Child>
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init(name: String, shared: Shared) {
				        self.name = name
				        self.shared = shared
				    }
				    @Forwarded let name: String
				    @Received let shared: Shared
				}
				""",
				"""
				@Instantiable
				public struct Shared: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public enum SafeDIMockPath {
		        public enum Shared { case parent }
		    }

		    public static func mock(
		        name: String,
		        shared: ((SafeDIMockPath.Shared) -> Shared)? = nil
		    ) -> Child {
		        let shared = shared?(.parent) ?? Shared.mock()
		        return Child(name: name, shared: shared)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum ChildBuilder { case root }
		        public enum Shared { case root }
		    }

		    public static func mock(
		        childBuilder: ((SafeDIMockPath.ChildBuilder) -> Instantiator<Child>)? = nil,
		        shared: ((SafeDIMockPath.Shared) -> Shared)? = nil
		    ) -> Root {
		        let shared = shared?(.root) ?? Shared.mock()
		        let childBuilder = childBuilder?(.root)
		            ?? Instantiator<Child> { name in
		            Child(name: name, shared: shared)
		        }
		        return Root(shared: shared, childBuilder: childBuilder)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Shared+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Shared {
		    public static func mock() -> Shared {
		        Shared()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForTypeWithInstantiatorNoForwardedProperties() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(viewBuilder: Instantiator<SimpleView>) {
				        self.viewBuilder = viewBuilder
				    }
				    @Instantiated let viewBuilder: Instantiator<SimpleView>
				}
				""",
				"""
				@Instantiable
				public struct SimpleView: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum ViewBuilder { case root }
		    }

		    public static func mock(
		        viewBuilder: ((SafeDIMockPath.ViewBuilder) -> Instantiator<SimpleView>)? = nil
		    ) -> Root {
		        let viewBuilder = viewBuilder?(.root)
		            ?? Instantiator<SimpleView> {
		            SimpleView()
		        }
		        return Root(viewBuilder: viewBuilder)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["SimpleView+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension SimpleView {
		    public static func mock() -> SimpleView {
		        SimpleView()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForInstantiatorWithMultipleForwardedProperties() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(childBuilder: Instantiator<Child>) {
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let childBuilder: Instantiator<Child>
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init(name: String, age: Int) {
				        self.name = name
				        self.age = age
				    }
				    @Forwarded let name: String
				    @Forwarded let age: Int
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public enum SafeDIMockPath {
		    }

		    public static func mock(
		        age: Int,
		        name: String
		    ) -> Child {
		        return Child(name: name, age: age)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum ChildBuilder { case root }
		    }

		    public static func mock(
		        childBuilder: ((SafeDIMockPath.ChildBuilder) -> Instantiator<Child>)? = nil
		    ) -> Root {
		        let childBuilder = childBuilder?(.root)
		            ?? Instantiator<Child> { (name, age) in
		            Child(name: name, age: age)
		        }
		        return Root(childBuilder: childBuilder)
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForTypeWithPublishedReceivedDependency() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				import Combine
				public protocol StringStorage {}
				@Instantiable(fulfillingAdditionalTypes: [StringStorage.self])
				extension UserDefaults: Instantiable, StringStorage {
				    public static func instantiate() -> UserDefaults { .standard }
				}
				""",
				"""
				import Combine
				@Instantiable
				public final class DefaultUserService: Instantiable {
				    public init(stringStorage: StringStorage) {
				        self.stringStorage = stringStorage
				    }
				    @Received @Published private var stringStorage: StringStorage
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		// DefaultUserService should get a mock even with @Published on the property.
		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["DefaultUserService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if canImport(Combine)
		import Combine
		#endif

		#if DEBUG
		extension DefaultUserService {
		    public enum SafeDIMockPath {
		        public enum StringStorage { case parent }
		    }

		    public static func mock(
		        stringStorage: ((SafeDIMockPath.StringStorage) -> StringStorage)? = nil
		    ) -> DefaultUserService {
		        let stringStorage = stringStorage?(.parent) ?? UserDefaults.instantiate()
		        return DefaultUserService(stringStorage: stringStorage)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["StringStorage+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if canImport(Combine)
		import Combine
		#endif

		#if DEBUG
		extension UserDefaults {
		    public static func mock() -> UserDefaults {
		        UserDefaults.instantiate()
		    }
		}
		#endif
		""")
	}

	// MARK: Tests – Coverage for edge cases

	@Test
	mutating func mock_generatedForExtensionBasedTypeWithReceivedDeps() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(thirdParty: ThirdParty, helper: Helper) {
				        self.thirdParty = thirdParty
				        self.helper = helper
				    }
				    @Instantiated let thirdParty: ThirdParty
				    @Instantiated let helper: Helper
				}
				""",
				"""
				public class ThirdParty {}

				@Instantiable
				extension ThirdParty: Instantiable {
				    public static func instantiate(helper: Helper) -> ThirdParty {
				        ThirdParty()
				    }
				    @Received let helper: Helper
				}
				""",
				"""
				@Instantiable
				public struct Helper: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Helper+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Helper {
		    public static func mock() -> Helper {
		        Helper()
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum Helper { case root }
		        public enum ThirdParty { case root }
		    }

		    public static func mock(
		        helper: ((SafeDIMockPath.Helper) -> Helper)? = nil,
		        thirdParty: ((SafeDIMockPath.ThirdParty) -> ThirdParty)? = nil
		    ) -> Root {
		        let helper = helper?(.root) ?? Helper.mock()
		        let thirdParty = thirdParty?(.root) ?? ThirdParty.instantiate(helper: helper)
		        return Root(thirdParty: thirdParty, helper: helper)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["ThirdParty+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ThirdParty {
		    public enum SafeDIMockPath {
		        public enum Helper { case parent }
		    }

		    public static func mock(
		        helper: ((SafeDIMockPath.Helper) -> Helper)? = nil
		    ) -> ThirdParty {
		        let helper = helper?(.parent) ?? Helper.mock()
		        return ThirdParty(helper: helper)
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForExtensionBasedTypeInInlineConstruction() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public class ThirdPartyDep {}

				@Instantiable
				extension ThirdPartyDep: Instantiable {
				    public static func instantiate() -> ThirdPartyDep {
				        ThirdPartyDep()
				    }
				}
				""",
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child, dep: ThirdPartyDep) {
				        self.child = child
				        self.dep = dep
				    }
				    @Instantiated let child: Child
				    @Instantiated let dep: ThirdPartyDep
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init(dep: ThirdPartyDep) {
				        self.dep = dep
				    }
				    @Received let dep: ThirdPartyDep
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public enum SafeDIMockPath {
		        public enum ThirdPartyDep { case parent }
		    }

		    public static func mock(
		        thirdPartyDep: ((SafeDIMockPath.ThirdPartyDep) -> ThirdPartyDep)? = nil
		    ) -> Child {
		        let thirdPartyDep = thirdPartyDep?(.parent) ?? ThirdPartyDep.instantiate()
		        return Child(dep: thirdPartyDep)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum Child { case root }
		        public enum ThirdPartyDep { case root }
		    }

		    public static func mock(
		        child: ((SafeDIMockPath.Child) -> Child)? = nil,
		        thirdPartyDep: ((SafeDIMockPath.ThirdPartyDep) -> ThirdPartyDep)? = nil
		    ) -> Root {
		        let thirdPartyDep = thirdPartyDep?(.root) ?? ThirdPartyDep.instantiate()
		        let child = child?(.root) ?? Child(dep: thirdPartyDep)
		        return Root(child: child, dep: thirdPartyDep)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["ThirdPartyDep+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ThirdPartyDep {
		    public static func mock() -> ThirdPartyDep {
		        ThirdPartyDep.instantiate()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForInstantiatorWithDefaultValuedBuiltTypeArg() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(shared: Shared, childBuilder: Instantiator<Child>) {
				        self.shared = shared
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let shared: Shared
				    @Instantiated let childBuilder: Instantiator<Child>
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init(name: String, shared: Shared, flag: Bool = false) {
				        self.name = name
				        self.shared = shared
				    }
				    @Forwarded let name: String
				    @Received let shared: Shared
				}
				""",
				"""
				@Instantiable
				public struct Shared: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public enum SafeDIMockPath {
		        public enum Shared { case parent }
		    }

		    public static func mock(
		        name: String,
		        shared: ((SafeDIMockPath.Shared) -> Shared)? = nil
		    ) -> Child {
		        let shared = shared?(.parent) ?? Shared.mock()
		        return Child(name: name, shared: shared)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum ChildBuilder { case root }
		        public enum Shared { case root }
		    }

		    public static func mock(
		        childBuilder: ((SafeDIMockPath.ChildBuilder) -> Instantiator<Child>)? = nil,
		        shared: ((SafeDIMockPath.Shared) -> Shared)? = nil
		    ) -> Root {
		        let shared = shared?(.root) ?? Shared.mock()
		        let childBuilder = childBuilder?(.root)
		            ?? Instantiator<Child> { name in
		            Child(name: name, shared: shared)
		        }
		        return Root(shared: shared, childBuilder: childBuilder)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Shared+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Shared {
		    public static func mock() -> Shared {
		        Shared()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForInstantiatorWithExtensionBasedBuiltType() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(shared: Shared, thirdPartyBuilder: Instantiator<ThirdParty>) {
				        self.shared = shared
				        self.thirdPartyBuilder = thirdPartyBuilder
				    }
				    @Instantiated let shared: Shared
				    @Instantiated let thirdPartyBuilder: Instantiator<ThirdParty>
				}
				""",
				"""
				public class ThirdParty {}

				@Instantiable
				extension ThirdParty: Instantiable {
				    public static func instantiate(shared: Shared) -> ThirdParty {
				        ThirdParty()
				    }
				    @Received let shared: Shared
				}
				""",
				"""
				@Instantiable
				public struct Shared: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum Shared { case root }
		        public enum ThirdPartyBuilder { case root }
		    }

		    public static func mock(
		        shared: ((SafeDIMockPath.Shared) -> Shared)? = nil,
		        thirdPartyBuilder: ((SafeDIMockPath.ThirdPartyBuilder) -> Instantiator<ThirdParty>)? = nil
		    ) -> Root {
		        let shared = shared?(.root) ?? Shared.mock()
		        let thirdPartyBuilder = thirdPartyBuilder?(.root)
		            ?? Instantiator<ThirdParty> {
		            ThirdParty.instantiate(shared: shared)
		        }
		        return Root(shared: shared, thirdPartyBuilder: thirdPartyBuilder)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Shared+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Shared {
		    public static func mock() -> Shared {
		        Shared()
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["ThirdParty+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ThirdParty {
		    public enum SafeDIMockPath {
		        public enum Shared { case parent }
		    }

		    public static func mock(
		        shared: ((SafeDIMockPath.Shared) -> Shared)? = nil
		    ) -> ThirdParty {
		        let shared = shared?(.parent) ?? Shared.mock()
		        return ThirdParty(shared: shared)
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForLazySelfInstantiationCycle() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(selfBuilder: Instantiator<Root>) {
				        self.selfBuilder = selfBuilder
				    }
				    @Instantiated let selfBuilder: Instantiator<Root>
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
			enableMockGeneration: true,
		)

		// Lazy self-cycle: Root instantiates Instantiator<Root>.
		// The topo sort cycle breaker should handle this gracefully.
		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum SelfBuilder { case root; case selfBuilder }
		    }

		    public static func mock(
		        selfBuilder: ((SafeDIMockPath.SelfBuilder) -> Instantiator<Root>)? = nil
		    ) -> Root {
		        let selfBuilder = selfBuilder?(.root)
		            ?? Instantiator<Root> {
		            Root()
		        }
		        return Root(selfBuilder: selfBuilder)
		    }
		}
		#endif
		""")
	}

	// MARK: Private

	private var filesToDelete: [URL]
}
