// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Foundation
import SafeDICore
import Testing
@testable import SafeDITool

struct SafeDIToolMockOnlyTests: ~Copyable {
	// MARK: Initialization

	init() throws {
		filesToDelete = [URL]()
	}

	deinit {
		for fileToDelete in filesToDelete {
			try! FileManager.default.removeItem(at: fileToDelete)
		}
	}

	// MARK: Tests

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesDefaultFromMockOnlyExtension_whenForwardedPropertyHasMockOnlyDeclaration() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(name: String) {
				        self.name = name
				    }
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension String {
				    public static func mock() -> String { "" }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        name: String = String.mock()
		    ) -> Root {
		        return Root(name: name)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesDefaultFromMockOnlyExtension_whenPrimitiveTypeHasMockOnlyDeclaration() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(count: Int) {
				        self.count = count
				    }
				    @Forwarded let count: Int
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension Int {
				    public static func mock() -> Int { 0 }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        count: Int = Int.mock()
		    ) -> Root {
		        return Root(count: count)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesDefaultFromMockOnlyExtension_whenInstantiatedPropertyHasMockOnlyDeclaration() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ExternalService) {
				        self.service = service
				    }
				    @Instantiated let service: ExternalService
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension ExternalService {
				    public static func mock() -> ExternalService { fatalError() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> ExternalService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> ExternalService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? ExternalService.mock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesCustomMockName_whenMockOnlyTypeHasCustomMockName() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(name: String) {
				        self.name = name
				    }
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "testValue")
				extension String {
				    public static func testValue() -> String { "test" }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        name: String = String.testValue()
		    ) -> Root {
		        return Root(name: name)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_mergesMockOnlyDeclarationWithRegularExtension_whenBothExistForSameType() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				public struct MyService {
				    public static func mock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(conformsElsewhere: true)
				extension MyService: Instantiable {
				    public static func instantiate() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.mock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_mergesRegularDeclarationWithMockOnlyExtension_whenBothExistForSameType() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension MyService {
				    public static func mock() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.mock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesDefaultFromMergedMockOnlyProvider_whenForwardedPropertyTypeHasSeparateMockOnlyAndProductionDeclarations() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Forwarded let service: MyService
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension MyService {
				    public static func mock() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        service: MyService = MyService.mock()
		    ) -> Root {
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesCustomMockNameFromMergedMockOnlyProvider_whenForwardedPropertyTypeHasSeparateDeclarations() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Forwarded let service: MyService
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        service: MyService = MyService.preview()
		    ) -> Root {
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesCustomMockNameFromMergedMockOnlyProvider_whenInstantiatedPropertyTypeHasSeparateDeclarations() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.preview)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesCustomMockName_whenProductionHasAdditionalTypeThatMockOnlyDoesNotRepeat() async throws {
		// Production fulfills both MyService and ServiceProtocol.
		// MockOnly only declares MyService. The merged entry (under MyService key)
		// has mock info, but the unmerged entry (under ServiceProtocol key) does not.
		// The scope map must use the merged entry for both.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ServiceProtocol) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceProtocol
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self])
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.preview)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	// MARK: Production Isolation Tests

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func productionCodeUnchanged_whenMockOnlyMergeAddsHandWrittenMock() async throws {
		// Generate production code WITHOUT mockOnly.
		let baselineOutput = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Generate production code WITH a mockOnly merge for Child.
		let mergedOutput = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension Child {
				    public static func preview() -> Child { Child() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Production output must be identical — mockOnly must not leak.
		#expect(
			baselineOutput.dependencyTreeFiles == mergedOutput.dependencyTreeFiles,
			"Production code changed after mockOnly merge. Baseline: \(baselineOutput.dependencyTreeFiles). Merged: \(mergedOutput.dependencyTreeFiles)",
		)
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func productionCodeUnchanged_whenMockOnlyMergeAddsHandWrittenMockWithMockAttributes() async throws {
		// Generate production code WITHOUT mockOnly.
		let baselineOutput = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Generate production code WITH a mockOnly merge that includes mockAttributes.
		let mergedOutput = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true, mockAttributes: "@MainActor")
				extension Child {
				    @MainActor public static func mock() -> Child { Child() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Production output must be identical.
		#expect(
			baselineOutput.dependencyTreeFiles == mergedOutput.dependencyTreeFiles,
			"Production code changed after mockOnly merge with mockAttributes. Baseline: \(baselineOutput.dependencyTreeFiles). Merged: \(mergedOutput.dependencyTreeFiles)",
		)
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_omitsDefaultForForwardedParameter_whenHandWrittenMockHasRequiredParameters() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Forwarded let service: MyService
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable {
				    public init(name: String) {
				        self.name = name
				    }
				    @Received let name: String
				    public static func mock(name: String) -> MyService { MyService(name: name) }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        service: MyService
		    ) -> Root {
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func productionCodeUsesConcreteType_whenMockOnlyAlsoFulfillsSameAdditionalType() async throws {
		// Both ConcreteService and MockService fulfill AnyService via fulfillingAdditionalTypes.
		// MockService is mockOnly. Production code should use ConcreteService without error.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public class AnyService {
				    public init(_ value: some Any) {}
				}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: AnyService) {
				        self.service = service
				    }
				    @Instantiated let service: AnyService
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [AnyService.self])
				public struct ConcreteService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [AnyService.self], mockOnly: true)
				public struct MockService: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Production code uses ConcreteService (the non-mockOnly type).
		#expect(output.dependencyTreeFiles["Root+SafeDI.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Root {
		    public init() {
		        let service: AnyService = ConcreteService()
		        self.init(service: service)
		    }
		}
		""", "Unexpected output \(output.dependencyTreeFiles["Root+SafeDI.swift"] ?? "")")

		// Mock code uses MockService (the mockOnly type takes priority in the
		// mock scope map over the production ConcreteService).
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MockService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MockService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MockService.init)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mockScopePrefersConcreteMock_whenConcreteHasGenerateMockAndMockOnlyAlsoFulfillsSameAdditionalType() async throws {
		// ConcreteService has generateMock: true and fulfills AnyService.
		// MockService is mockOnly and also fulfills AnyService.
		// The mock scope map should prefer ConcreteService (has its own mock).
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public class AnyService {
				    public init(_ value: some Any) {}
				}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: AnyService) {
				        self.service = service
				    }
				    @Instantiated let service: AnyService
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [AnyService.self], generateMock: true)
				public struct ConcreteService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [AnyService.self], mockOnly: true)
				public struct MockService: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Production code uses ConcreteService.
		#expect(output.dependencyTreeFiles["Root+SafeDI.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Root {
		    public init() {
		        let service: AnyService = ConcreteService()
		        self.init(service: service)
		    }
		}
		""", "Unexpected output \(output.dependencyTreeFiles["Root+SafeDI.swift"] ?? "")")

		// Mock code uses ConcreteService (its generateMock mock takes priority
		// over the mockOnly MockService).
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> ConcreteService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> ConcreteService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? ConcreteService.init)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesMockOnlyFallback_whenFulfilledByTypeNotVisible() async throws {
		// When the fulfilledByType concrete type (ConcreteService) is not visible,
		// but a mockOnly type fulfills the declared type (AnyService),
		// mock generation should use the mockOnly type — matching the behavior
		// of plain @Instantiated when the concrete type isn't in the scope map.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public class AnyService {
				    public init(_ value: some Any) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(service: AnyService) {
				        self.service = service
				    }
				    @Instantiated(fulfilledByType: "ConcreteService", erasedToConcreteExistential: true) let service: AnyService
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [AnyService.self], mockOnly: true)
				public struct MockService: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MockService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MockService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = AnyService((safeDIOverrides.service ?? MockService.init)())
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesFulfillingType_whenFulfilledByTypeIsVisibleAndMockOnlyAlsoFulfillsDeclaredType() async throws {
		// When the fulfilledByType concrete type IS visible, it should be used
		// even if a mockOnly also fulfills the declared type. No fallback needed.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public class AnyService {
				    public init(_ value: some Any) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(service: AnyService) {
				        self.service = service
				    }
				    @Instantiated(fulfilledByType: "ConcreteService", erasedToConcreteExistential: true) let service: AnyService
				}
				""",
				"""
				@Instantiable
				public struct ConcreteService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [AnyService.self], mockOnly: true)
				public struct MockService: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// ConcreteService is visible, so the mock uses it — no fallback to MockService.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> ConcreteService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> ConcreteService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = AnyService((safeDIOverrides.service ?? ConcreteService.init)())
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesMockOnlyAdditionalType_whenMockOnlyHasAdditionalTypeProductionDoesNot() async throws {
		// Production fulfills only MyService. MockOnly fulfills MyService and
		// ServiceProtocol. A root referencing ServiceProtocol should get the
		// mockOnly scope.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ServiceProtocol) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceProtocol
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// The mock should use MyService.preview (from the mockOnly) for ServiceProtocol.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.preview)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_propagationPreservesGenerateMock_whenMockOnlyHasExtraAdditionalType() async throws {
		// P1: When a production type has generateMock: true and a mockOnly adds
		// extra fulfillingAdditionalTypes, the mock propagation pass must not
		// overwrite the production type's generated mock behavior with the
		// mockOnly's hand-written mock.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// The generated mock should use init (from generateMock), not preview
		// (from mockOnly). generateMock takes priority.
		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension MyService {
		    static func mock() -> MyService {
		        MyService()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["MyService+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersGenerateMock_whenMockOnlyAlsoExistsForSameType() async throws {
		// generateMock: true on the production type takes priority over the mockOnly extension.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct MyService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension MyService {
				    public static func mock() -> MyService { fatalError() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// The generated mock uses the production type's init (from generateMock),
		// not the mockOnly extension's hand-written mock.
		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension MyService {
		    static func mock() -> MyService {
		        MyService()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["MyService+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersHandWrittenMock_whenMockOnlyAlsoExistsForSameType() async throws {
		// Production type with a hand-written mock takes priority over the mockOnly extension.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(mockOnly: true)
				extension MyService {
				    public static func mock() -> MyService { fatalError() }
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable {
				    public init() {}
				    public static func mock() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// No mock file is generated — the production type has a hand-written mock
		// and generateMock is false, so SafeDI doesn't generate a mock method.
		#expect(output.mockFiles.isEmpty, "Unexpected mock files \(output.mockFiles.keys)")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersGenerateMock_whenMockOnlyArrivesSecond() async throws {
		// Same as mock_prefersGenerateMock_whenMockOnlyAlsoExistsForSameType but
		// with reversed source file order.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct MyService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension MyService {
				    public static func mock() -> MyService { fatalError() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension MyService {
		    static func mock() -> MyService {
		        MyService()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["MyService+SafeDIMock.swift"] ?? "")")
	}

	// MARK: Tests – generateMock + mockOnly additional-type gaps

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesMockOnlyScope_whenGenerateMockProductionAndMockOnlyHasExtraAdditionalType_referencedByMockOnlyAdditionalType() async throws {
		// B+Z, ref by mockOnly additional: production has generateMock, mockOnly
		// adds ServiceProtocol. Parent references ServiceProtocol. The mockOnly
		// scope should be used for ServiceProtocol since the production type
		// doesn't fulfill it.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ServiceProtocol) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceProtocol
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// MyService has generateMock, so its own mock uses init.
		// Root references ServiceProtocol, which is fulfilled by the mockOnly scope.
		// The scope's instantiable has the mock info propagated, so it uses preview.
		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension MyService {
		    static func mock() -> MyService {
		        MyService()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["MyService+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] != nil, "Expected Root mock file")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersGenerateMock_whenProductionHasExtraAdditionalTypeAndMockOnlyForConcreteOnly() async throws {
		// B+W: production has generateMock + fulfillingAdditionalTypes, mockOnly
		// for concrete type only. Parent references via the production's additional type.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ServiceProtocol) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceProtocol
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], generateMock: true)
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// MyService has generateMock — its generated mock should use init, not preview.
		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension MyService {
		    static func mock() -> MyService {
		        MyService()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["MyService+SafeDIMock.swift"] ?? "")")

		// Root references ServiceProtocol — fulfilled by MyService (production, non-mockOnly).
		#expect(output.mockFiles["Root+SafeDIMock.swift"] != nil, "Expected Root mock file")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersGenerateMock_whenProductionHasExtraAdditionalTypeAndMockOnlyForConcreteOnly_referencedByConcrete() async throws {
		// B+W, ref by concrete: same as above but parent references MyService directly.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], generateMock: true)
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension MyService {
		    static func mock() -> MyService {
		        MyService()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["MyService+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_forwardedDefaultUsesGeneratedMock_notStaleMockOnlyMethod_whenProductionHasGenerateMock() async throws {
		// When production has generateMock and a mockOnly with extra additional
		// types is silently ignored, @Forwarded defaults must not use the
		// mockOnly's method. The generated mock should win.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Forwarded let service: MyService
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// The forwarded parameter should NOT use MyService.preview() from the
		// ignored mockOnly. Since generateMock types don't provide forwarded
		// defaults, the parameter is required (no default).
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        service: MyService
		    ) -> Root {
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_forwardedDefaultUsesHandWrittenMock_notStaleMockOnlyMethod_whenProductionHasHandWrittenMock() async throws {
		// Mirror of the generateMock test but with a hand-written mock.
		// The stale mockOnly's customMockName must not leak into forwarded defaults.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Forwarded let service: MyService
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				    public static func mock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// The forwarded default should use MyService.mock() (production's
		// hand-written mock), not MyService.preview() (from the ignored mockOnly).
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        service: MyService = MyService.mock()
		    ) -> Root {
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	// MARK: Tests – hand-written mock + mockOnly additional-type gaps

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersHandWrittenMock_whenBothFulfillSameAdditionalType() async throws {
		// C+Y: production has hand-written mock, both fulfill ServiceProtocol.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ServiceProtocol) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceProtocol
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self])
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				    public static func mock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// No mock file generated for MyService — it has a hand-written mock but
		// not generateMock. Root mock should reference MyService.
		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == nil, "Should not generate mock for hand-written mock type")
		#expect(output.mockFiles["Root+SafeDIMock.swift"] != nil, "Expected Root mock file")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersHandWrittenMock_whenBothFulfillSameAdditionalType_referencedByConcrete() async throws {
		// C+Y, ref by concrete.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self])
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				    public static func mock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == nil, "Should not generate mock for hand-written mock type")
		#expect(output.mockFiles["Root+SafeDIMock.swift"] != nil, "Expected Root mock file")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersHandWrittenMock_whenMockOnlyHasExtraAdditionalType() async throws {
		// C+Z: production has hand-written mock, mockOnly adds extra additional type.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				    public static func mock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// No mock generated — hand-written mock exists but generateMock is false.
		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == nil, "Should not generate mock for hand-written mock type")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersHandWrittenMock_whenMockOnlyHasExtraAdditionalType_referencedByMockOnlyAdditionalType() async throws {
		// C+Z, ref by mockOnly additional: parent references ServiceProtocol
		// (only fulfilled by mockOnly). The scope should use MyService with its
		// hand-written mock, not the mockOnly's customMockName.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ServiceProtocol) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceProtocol
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				    public static func mock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] != nil, "Expected Root mock file")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersHandWrittenMock_whenProductionHasExtraAdditionalType() async throws {
		// C+W: production has hand-written mock + extra additional type, mockOnly for concrete only.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ServiceProtocol) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceProtocol
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self])
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				    public static func mock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == nil, "Should not generate mock for hand-written mock type")
		#expect(output.mockFiles["Root+SafeDIMock.swift"] != nil, "Expected Root mock file")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersHandWrittenMock_whenProductionHasExtraAdditionalType_referencedByConcrete() async throws {
		// C+W, ref by concrete.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self])
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				    public static func mock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == nil, "Should not generate mock for hand-written mock type")
		#expect(output.mockFiles["Root+SafeDIMock.swift"] != nil, "Expected Root mock file")
	}

	// MARK: Private

	private var filesToDelete = [URL]()
}
