// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import ArgumentParser
import Foundation
import SafeDICore
import Testing
@testable import SafeDITool

struct SafeDIToolCombinedOutputTests: ~Copyable {
	// MARK: Initialization

	init() throws {
		filesToDelete = [URL]()
	}

	deinit {
		for fileToDelete in filesToDelete {
			try! FileManager.default.removeItem(at: fileToDelete)
		}
	}

	// MARK: Tests

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_writesRootDependencyTreeAndMockIntoOneFile() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(dep: Dep) {
				        self.dep = dep
				    }
				    @Instantiated let dep: Dep
				}
				""",
				"""
				@Instantiable
				public struct Dep: Instantiable {
				    public init() {}
				}
				""",
			],
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
		)

		let combined = try #require(output.combinedOutput)

		// File header appears exactly once at the top.
		let headerLine = "// This file was generated by the SafeDIGenerateDependencyTree build tool plugin."
		let headerOccurrences = combined.components(separatedBy: headerLine).count - 1
		#expect(headerOccurrences == 1, "Expected header once, got \(headerOccurrences):\n\(combined)")

		// Dependency-tree wiring for `Root` is present.
		let rootExtensionOpener = "extension Root {\n    public init() {"
		#expect(combined.contains(rootExtensionOpener), "Missing root extension:\n\(combined)")

		// Mock surface is present.
		let mockFunction = "static func mock("
		#expect(combined.contains(mockFunction), "Missing mock method:\n\(combined)")

		// Order is root dependency tree → mock.
		let rootRange = try #require(combined.range(of: rootExtensionOpener))
		let mockRange = try #require(combined.range(of: mockFunction))
		#expect(rootRange.lowerBound < mockRange.lowerBound, "Expected root tree to precede mock:\n\(combined)")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_includesSharedMockConfiguration_whenMocksShareConfigurationExtensions() async throws {
		// Middle lacks `generateMock: true`; its `SafeDIMockConfiguration`
		// extension therefore lives in the shared mock-configuration section
		// and gets appended onto the combined output.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(middle: Middle) {
				        self.middle = middle
				    }
				    @Instantiated let middle: Middle
				}
				""",
				"""
				@Instantiable
				public struct Middle: Instantiable {
				    public init(leaf: Leaf) {
				        self.leaf = leaf
				    }
				    @Instantiated let leaf: Leaf
				}
				""",
				"""
				@Instantiable
				public struct Leaf: Instantiable {
				    public init() {}
				}
				""",
			],
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
		)

		let combined = try #require(output.combinedOutput)
		#expect(combined.contains("extension Middle {"))
		#expect(combined.contains("struct SafeDIMockConfiguration"))
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_isStableForStableInputsRegardlessOfFixtureOrdering() async throws {
		// Generating the same module twice — with the input files in different
		// declaration orders — should produce byte-identical combined output.
		// Guards against ordering non-determinism (dictionary iteration,
		// unsorted collections) leaking into the concatenated result.
		let fileAlpha = """
		@Instantiable(isRoot: true)
		public struct AlphaRoot: Instantiable {
		    public init(a: Alpha) {
		        self.a = a
		    }
		    @Instantiated let a: Alpha
		}
		"""
		let fileBeta = """
		@Instantiable(generateMock: true)
		public struct Alpha: Instantiable {
		    public init() {}
		}
		"""
		let fileGamma = """
		@Instantiable(isRoot: true)
		public struct BetaRoot: Instantiable {
		    public init(a: Alpha) {
		        self.a = a
		    }
		    @Instantiated let a: Alpha
		}
		"""

		let firstOutput = try await executeSafeDIToolTest(
			swiftFileContent: [fileAlpha, fileBeta, fileGamma],
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
		)
		let secondOutput = try await executeSafeDIToolTest(
			swiftFileContent: [fileGamma, fileBeta, fileAlpha],
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
		)

		let first = try #require(firstOutput.combinedOutput)
		let second = try #require(secondOutput.combinedOutput)
		#expect(first == second, "Combined output drifted with input order:\n--- first ---\n\(first)\n--- second ---\n\(second)")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_writesParseErrorStub_whenSourcesContainUnexpectedSwiftNodes() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public final class Root: Instantiable {
				    public init(dep: Dep) {
				        self.dep = dep
				    }

				    :::brokenSyntax

				    @Instantiated let dep: Dep
				}

				@Instantiable
				public final class Dep: Instantiable {
				    public init() {}
				}
				""",
			],
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
			skipCompileVerification: true,
		)

		let combined = try #require(output.combinedOutput)
		#expect(combined.contains("#error"), "Expected #error stub: \(combined)")
		#expect(combined.contains("Compiler errors prevented the generation of the dependency tree"))
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_enumeratesIncludeDirectoriesWithoutRequiringSourcesCSV() async throws {
		// Driving `generate` purely from `--include` (no positional CSV) is
		// a supported workflow; combined mode has to cope with it.
		let tempDir = FileManager.default.temporaryDirectory
			.appendingPathComponent("SafeDIToolIncludeTest-\(UUID().uuidString)", isDirectory: true)
		try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
		filesToDelete.append(tempDir)

		let sourceURL = tempDir.appendingPathComponent("Root.swift")
		try """
		@Instantiable(isRoot: true)
		public struct Root: Instantiable {
		    public init(dep: Dep) {
		        self.dep = dep
		    }
		    @Instantiated let dep: Dep
		}

		@Instantiable
		public struct Dep: Instantiable {
		    public init() {}
		}
		""".write(to: sourceURL, atomically: true, encoding: .utf8)

		let combinedOutput = URL.temporaryFile.appendingPathExtension("swift")
		filesToDelete.append(combinedOutput)

		let tool = try Generate.parse([
			"--include", tempDir.path,
			"--combined-output", combinedOutput.path,
		])
		try await tool.run()

		let combined = try String(contentsOf: combinedOutput, encoding: .utf8)
		#expect(combined.contains("extension Root {"), "Missing Root extension: \(combined)")
		#expect(combined.contains("public init() {"), "Missing synthesized init: \(combined)")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_rejectsCombinationWithOutputDirectory() async throws {
		let tool = try Generate.parse([
			"/tmp/nonexistent-sources.csv",
			"--combined-output", "/tmp/combined.swift",
			"--output-directory", "/tmp/out-dir",
		])
		await assertThrowsError(
			containing: "--combined-output is mutually exclusive with --output-directory and --swift-manifest",
		) {
			try await tool.run()
		}
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_rejectsCombinationWithSwiftManifest() async throws {
		let tool = try Generate.parse([
			"/tmp/nonexistent-sources.csv",
			"--combined-output", "/tmp/combined.swift",
			"--swift-manifest", "/tmp/manifest.json",
		])
		await assertThrowsError(
			containing: "--combined-output is mutually exclusive with --output-directory and --swift-manifest",
		) {
			try await tool.run()
		}
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_writesOnlyHeader_whenModuleHasNothingToEmit() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable
				public struct NonRootWithoutMock: Instantiable {
				    public init() {}
				}
				""",
			],
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
		)

		let combined = try #require(output.combinedOutput)
		#expect(combined == emptyMockConfigurationFileOutput, "Unexpected combined output: \(combined)")
	}

	// MARK: Private

	private var filesToDelete: [URL]
}

@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
extension URL {
	fileprivate static var temporaryFile: URL {
		#if os(Linux)
			FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
		#else
			URL.temporaryDirectory.appending(path: UUID().uuidString)
		#endif
	}
}
