// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import ArgumentParser
import Foundation
import SafeDICore
import Testing
@testable import SafeDITool

struct SafeDIToolCombinedOutputTests: ~Copyable {
	// MARK: Initialization

	init() throws {
		filesToDelete = [URL]()
	}

	deinit {
		for fileToDelete in filesToDelete {
			try! FileManager.default.removeItem(at: fileToDelete)
		}
	}

	// MARK: Tests

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_writesRootDependencyTreeAndMockIntoOneFile() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(dep: Dep) {
				        self.dep = dep
				    }
				    @Instantiated let dep: Dep
				}
				""",
				"""
				@Instantiable
				public struct Dep: Instantiable {
				    public init() {}
				}
				""",
			],
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.combinedOutput == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Root {
		    public init() {
		        let dep = Dep()
		        self.init(dep: dep)
		    }
		}

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            dep: (() -> Dep)? = nil
		        ) {
		            self.dep = dep
		        }

		        let dep: (() -> Dep)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let dep = (safeDIOverrides.dep ?? Dep.init)()
		        return Root(dep: dep)
		    }
		}
		#endif
		""", "Unexpected combined output: \(output.combinedOutput ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_includesSharedMockConfiguration_whenMocksShareConfigurationExtensions() async throws {
		// Middle lacks `generateMock: true`; its `SafeDIMockConfiguration`
		// extension therefore lives in the shared mock-configuration section
		// and gets appended onto the combined output.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(middle: Middle) {
				        self.middle = middle
				    }
				    @Instantiated let middle: Middle
				}
				""",
				"""
				@Instantiable
				public struct Middle: Instantiable {
				    public init(leaf: Leaf) {
				        self.leaf = leaf
				    }
				    @Instantiated let leaf: Leaf
				}
				""",
				"""
				@Instantiable
				public struct Leaf: Instantiable {
				    public init() {}
				}
				""",
			],
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.combinedOutput == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Root {
		    public init() {
		        func __safeDI_middle() -> Middle {
		            let leaf = Leaf()
		            return Middle(leaf: leaf)
		        }
		        let middle: Middle = __safeDI_middle()
		        self.init(middle: middle)
		    }
		}

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            middle: Middle.SafeDIMockConfiguration = .init()
		        ) {
		            self.middle = middle
		        }

		        let middle: Middle.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        func __safeDI_middle() -> Middle {
		            let leaf = (safeDIOverrides.middle.leaf ?? Leaf.init)()
		            return (safeDIOverrides.middle.safeDIBuilder ?? Middle.init(leaf:))(leaf)
		        }
		        let middle: Middle = __safeDI_middle()
		        return Root(middle: middle)
		    }
		}
		#endif

		#if DEBUG
		extension Middle {
		    /// Configuration for how this type is constructed within a mock tree.
		    struct SafeDIMockConfiguration {
		        init(
		            leaf: (() -> Leaf)? = nil,
		            _ safeDIBuilder: ((Leaf) -> Middle)? = nil
		        ) {
		            self.leaf = leaf
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let leaf: (() -> Leaf)?
		        /// Overrides how this type is constructed. Parameters match the type’s initializer or custom mock method. When `nil`, the default generated construction function is used.
		        let safeDIBuilder: ((Leaf) -> Middle)?
		    }
		}
		#endif

		""", "Unexpected combined output: \(output.combinedOutput ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_isStableForStableInputsRegardlessOfFixtureOrdering() async throws {
		// Generating the same module twice — with the input files in different
		// declaration orders — should produce byte-identical combined output.
		// Guards against ordering non-determinism (dictionary iteration,
		// unsorted collections) leaking into the concatenated result.
		let fileAlpha = """
		@Instantiable(isRoot: true)
		public struct AlphaRoot: Instantiable {
		    public init(a: Alpha) {
		        self.a = a
		    }
		    @Instantiated let a: Alpha
		}
		"""
		let fileBeta = """
		@Instantiable(generateMock: true)
		public struct Alpha: Instantiable {
		    public init() {}
		}
		"""
		let fileGamma = """
		@Instantiable(isRoot: true)
		public struct BetaRoot: Instantiable {
		    public init(a: Alpha) {
		        self.a = a
		    }
		    @Instantiated let a: Alpha
		}
		"""

		let firstOutput = try await executeSafeDIToolTest(
			swiftFileContent: [fileAlpha, fileBeta, fileGamma],
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
		)
		let secondOutput = try await executeSafeDIToolTest(
			swiftFileContent: [fileGamma, fileBeta, fileAlpha],
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
		)

		let first = try #require(firstOutput.combinedOutput)
		let second = try #require(secondOutput.combinedOutput)
		#expect(first == second, "Combined output drifted with input order:\n--- first ---\n\(first)\n--- second ---\n\(second)")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_writesParseErrorStub_whenSourcesContainUnexpectedSwiftNodes() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public final class Root: Instantiable {
				    public init(dep: Dep) {
				        self.dep = dep
				    }

				    :::brokenSyntax

				    @Instantiated let dep: Dep
				}

				@Instantiable
				public final class Dep: Instantiable {
				    public init() {}
				}
				""",
			],
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
			skipCompileVerification: true,
		)

		let combined = try #require(output.combinedOutput)
		// Normalize the fixture's absolute-path line so the
		// comparison is portable across runs.
		let normalized = combined.replacing(#/\t[^\n]+?\.swift/#, with: "\t<FIXTURE_PATH>/Root.swift")
		#expect(normalized == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#error(\"\"\"
		Compiler errors prevented the generation of the dependency tree. Files with errors:
			<FIXTURE_PATH>/Root.swift
		\"\"\")
		""", "Unexpected combined output: \(normalized)")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_enumeratesIncludeDirectoriesWithoutRequiringSourcesCSV() async throws {
		// Driving `generate` purely from `--include` (no positional CSV) is
		// a supported workflow; combined mode has to cope with it.
		let tempDir = FileManager.default.temporaryDirectory
			.appendingPathComponent("SafeDIToolIncludeTest-\(UUID().uuidString)", isDirectory: true)
		try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
		filesToDelete.append(tempDir)

		let sourceURL = tempDir.appendingPathComponent("Root.swift")
		try """
		@Instantiable(isRoot: true)
		public struct Root: Instantiable {
		    public init(dep: Dep) {
		        self.dep = dep
		    }
		    @Instantiated let dep: Dep
		}

		@Instantiable
		public struct Dep: Instantiable {
		    public init() {}
		}
		""".write(to: sourceURL, atomically: true, encoding: .utf8)

		let combinedOutput = URL.temporaryFile.appendingPathExtension("swift")
		filesToDelete.append(combinedOutput)

		let tool = try Generate.parse([
			"--include", tempDir.path,
			"--combined-output", combinedOutput.path,
		])
		try await tool.run()

		let combined = try String(contentsOf: combinedOutput, encoding: .utf8)
		#expect(combined == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Root {
		    public init() {
		        let dep = Dep()
		        self.init(dep: dep)
		    }
		}
		""", "Unexpected combined output: \(combined)")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_rejectsCombinationWithOutputDirectory() async throws {
		let tool = try Generate.parse([
			"/tmp/nonexistent-sources.csv",
			"--combined-output", "/tmp/combined.swift",
			"--output-directory", "/tmp/out-dir",
		])
		await assertThrowsError(
			containing: "--combined-output is mutually exclusive with --output-directory and --swift-manifest",
		) {
			try await tool.run()
		}
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_rejectsCombinationWithSwiftManifest() async throws {
		let tool = try Generate.parse([
			"/tmp/nonexistent-sources.csv",
			"--combined-output", "/tmp/combined.swift",
			"--swift-manifest", "/tmp/manifest.json",
		])
		await assertThrowsError(
			containing: "--combined-output is mutually exclusive with --output-directory and --swift-manifest",
		) {
			try await tool.run()
		}
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_manifest_writesDeclaredMockConfigurationOutput_whenMockGenerationEmptyAndAdditionalMocksNonEmpty() async throws {
		// When a manifest declares `mockConfigurationOutputFilePath`
		// and `additionalMocksToGenerate`, but no `mockGeneration`
		// entries, the shared mock-configuration file must still be
		// written — Bazel/Buck2 style build systems expect every
		// declared output to exist, and silently dropping the write
		// previously caused "missing declared output" build failures.
		let crossModuleOutput = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable
				public struct CrossModuleService: Instantiable {
				    public init() {}
				}
				""",
			],
			filesToDelete: &filesToDelete,
		)

		let tempDir = FileManager.default.temporaryDirectory
			.appendingPathComponent("SafeDIToolMockConfigOnlyTest-\(UUID().uuidString)", isDirectory: true)
		try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
		filesToDelete.append(tempDir)

		let rootURL = tempDir.appendingPathComponent("Root.swift")
		try """
		@Instantiable(isRoot: true)
		public struct Root: Instantiable {
		    public init() {}
		}
		""".write(to: rootURL, atomically: true, encoding: .utf8)

		let csvURL = tempDir.appendingPathComponent("sources.csv")
		try rootURL.path.write(to: csvURL, atomically: true, encoding: .utf8)

		let dependentModuleCSV = tempDir.appendingPathComponent("dependent-modules.csv")
		try crossModuleOutput.moduleInfoOutputPath.write(to: dependentModuleCSV, atomically: true, encoding: .utf8)

		let rootOutputURL = tempDir.appendingPathComponent("Root+SafeDI.swift")
		let mockConfigURL = tempDir.appendingPathComponent("SafeDIMockConfiguration.swift")
		let manifest = SafeDIToolManifest(
			dependencyTreeGeneration: [
				.init(inputFilePath: rootURL.path, outputFilePath: rootOutputURL.path),
			],
			mockGeneration: [],
			mockConfigurationOutputFilePath: mockConfigURL.path,
			additionalMocksToGenerate: ["CrossModuleService"],
		)
		let manifestURL = tempDir.appendingPathComponent("manifest.json")
		try JSONEncoder().encode(manifest).write(to: manifestURL)

		let tool = try Generate.parse([
			csvURL.path,
			"--swift-manifest", manifestURL.path,
			"--dependent-module-info-file-path", dependentModuleCSV.path,
		])
		try await tool.run()

		#expect(
			FileManager.default.fileExists(atPath: mockConfigURL.path),
			"Declared mockConfigurationOutputFilePath was not written",
		)
		let mockConfig = try String(contentsOf: mockConfigURL, encoding: .utf8)
		#expect(mockConfig == emptyMockConfigurationFileOutput, "Unexpected mock configuration output: \(mockConfig)")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_resolvesDependentModuleInfo_whenDepsCSVHasTrailingNewline() async throws {
		// Build systems and shell scripts commonly produce the deps CSV with
		// `echo "path.safedi" > deps.csv`, which writes a trailing newline.
		// Generate must tolerate trailing/embedded whitespace and newlines in
		// the CSV — otherwise the resolved file path includes "\n" and the
		// `.safedi` load fails with a misleading file-not-found error.
		let crossModuleOutput = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable
				public struct CrossModuleService: Instantiable {
				    public init() {}
				}
				""",
			],
			filesToDelete: &filesToDelete,
		)

		let tempDir = FileManager.default.temporaryDirectory
			.appendingPathComponent("SafeDIToolDepsCSVNewlineTest-\(UUID().uuidString)", isDirectory: true)
		try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
		filesToDelete.append(tempDir)

		let rootURL = tempDir.appendingPathComponent("Root.swift")
		try """
		@Instantiable(isRoot: true)
		public struct Root: Instantiable {
		    public init(crossModuleService: CrossModuleService) {
		        self.crossModuleService = crossModuleService
		    }
		    @Instantiated let crossModuleService: CrossModuleService
		}
		""".write(to: rootURL, atomically: true, encoding: .utf8)

		let csvURL = tempDir.appendingPathComponent("sources.csv")
		try rootURL.path.write(to: csvURL, atomically: true, encoding: .utf8)

		let dependentModuleCSV = tempDir.appendingPathComponent("dependent-modules.csv")
		// Emulate `echo "path.safedi" > deps.csv` — trailing newline included.
		try "\(crossModuleOutput.moduleInfoOutputPath)\n".write(to: dependentModuleCSV, atomically: true, encoding: .utf8)

		let combinedOutputURL = tempDir.appendingPathComponent("SafeDIGenerated.swift")
		let tool = try Generate.parse([
			csvURL.path,
			"--combined-output", combinedOutputURL.path,
			"--dependent-module-info-file-path", dependentModuleCSV.path,
		])
		try await tool.run()

		#expect(
			FileManager.default.fileExists(atPath: combinedOutputURL.path),
			"Combined output was not written — Generate likely failed to load the dependent .safedi file",
		)
		let combinedOutput = try String(contentsOf: combinedOutputURL, encoding: .utf8)
		#expect(
			combinedOutput.contains("CrossModuleService()"),
			"Combined output did not pick up the dependent module's type: \(combinedOutput)",
		)
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_emitsAdditionalMockFromConfiguration() async throws {
		// `#SafeDIConfiguration(additionalMocksToGenerate:)` is how a
		// module requests mocks for types defined in a dependent
		// module. Combined mode should append those type-name-keyed
		// mocks after the per-source ones.
		let crossModuleOutput = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable
				public struct CrossModuleService: Instantiable {
				    public init() {}
				}
				""",
			],
			filesToDelete: &filesToDelete,
		)

		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				#SafeDIConfiguration(
				    additionalMocksToGenerate: [
				        "CrossModuleService",
				    ]
				)
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(crossModuleService: CrossModuleService) {
				        self.crossModuleService = crossModuleService
				    }
				    @Instantiated let crossModuleService: CrossModuleService
				}
				""",
			],
			dependentModuleInfoPaths: [crossModuleOutput.moduleInfoOutputPath],
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
			skipCompileVerification: true,
		)

		#expect(output.combinedOutput == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Root {
		    public init() {
		        let crossModuleService = CrossModuleService()
		        self.init(crossModuleService: crossModuleService)
		    }
		}

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            crossModuleService: (() -> CrossModuleService)? = nil
		        ) {
		            self.crossModuleService = crossModuleService
		        }

		        let crossModuleService: (() -> CrossModuleService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let crossModuleService = (safeDIOverrides.crossModuleService ?? CrossModuleService.init)()
		        return Root(crossModuleService: crossModuleService)
		    }
		}
		#endif

		#if DEBUG
		extension CrossModuleService {
		    static func mock() -> CrossModuleService {
		        CrossModuleService()
		    }
		}
		#endif
		""", "Unexpected combined output: \(output.combinedOutput ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_manifest_throwsValidationError_whenDependencyTreeGenerationContainsDuplicateInputFilePath() async throws {
		// Manifest JSON is user-supplied; a duplicate `inputFilePath`
		// must surface as a recoverable `ValidationError` rather than a
		// `Dictionary(uniqueKeysWithValues:)` runtime trap.
		let tempDir = FileManager.default.temporaryDirectory
			.appendingPathComponent("SafeDIToolDuplicateManifestTest-\(UUID().uuidString)", isDirectory: true)
		try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
		filesToDelete.append(tempDir)

		let sourceURL = tempDir.appendingPathComponent("Root.swift")
		try """
		@Instantiable(isRoot: true)
		public struct Root: Instantiable {
		    public init() {}
		}
		""".write(to: sourceURL, atomically: true, encoding: .utf8)

		let csvURL = tempDir.appendingPathComponent("sources.csv")
		try sourceURL.path.write(to: csvURL, atomically: true, encoding: .utf8)

		let outputURL = tempDir.appendingPathComponent("Root+SafeDI.swift")
		let manifest = SafeDIToolManifest(
			dependencyTreeGeneration: [
				.init(inputFilePath: sourceURL.path, outputFilePath: outputURL.path),
				.init(inputFilePath: sourceURL.path, outputFilePath: outputURL.path),
			],
		)
		let manifestURL = tempDir.appendingPathComponent("manifest.json")
		try JSONEncoder().encode(manifest).write(to: manifestURL)

		let tool = try Generate.parse([
			csvURL.path,
			"--swift-manifest", manifestURL.path,
		])

		await assertThrowsError(
			containing: "Manifest contains duplicate dependencyTreeGeneration inputFilePath",
		) {
			try await tool.run()
		}
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_deduplicatesAdditionalMocksToGenerate_whenConfigContainsRepeatedTypeNames() async throws {
		// A misconfigured `additionalMocksToGenerate: ["Foo", "Foo"]`
		// should not produce duplicate `extension Foo` blocks — Swift
		// refuses to compile a file with two identical extensions.
		let crossModuleOutput = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable
				public struct CrossModuleService: Instantiable {
				    public init() {}
				}
				""",
			],
			filesToDelete: &filesToDelete,
		)

		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				#SafeDIConfiguration(
				    additionalMocksToGenerate: [
				        "CrossModuleService",
				        "CrossModuleService",
				    ]
				)
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(crossModuleService: CrossModuleService) {
				        self.crossModuleService = crossModuleService
				    }
				    @Instantiated let crossModuleService: CrossModuleService
				}
				""",
			],
			dependentModuleInfoPaths: [crossModuleOutput.moduleInfoOutputPath],
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
			skipCompileVerification: true,
		)

		#expect(output.combinedOutput == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Root {
		    public init() {
		        let crossModuleService = CrossModuleService()
		        self.init(crossModuleService: crossModuleService)
		    }
		}

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            crossModuleService: (() -> CrossModuleService)? = nil
		        ) {
		            self.crossModuleService = crossModuleService
		        }

		        let crossModuleService: (() -> CrossModuleService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let crossModuleService = (safeDIOverrides.crossModuleService ?? CrossModuleService.init)()
		        return Root(crossModuleService: crossModuleService)
		    }
		}
		#endif

		#if DEBUG
		extension CrossModuleService {
		    static func mock() -> CrossModuleService {
		        CrossModuleService()
		    }
		}
		#endif
		""", "Duplicate `CrossModuleService` leaked into combined output:\n\(output.combinedOutput ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_emitsLocalMockOnlyOnce_whenTypeIsInBothGenerateMockAndAdditionalMocksToGenerate() async throws {
		// A local type declared with `generateMock: true` that is
		// *also* listed in `additionalMocksToGenerate` would otherwise
		// be emitted twice in combined mode — once via the per-source
		// loop and once via the per-type loop — producing duplicate
		// `extension` blocks that fail to compile.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				#SafeDIConfiguration(
				    additionalMocksToGenerate: [
				        "LocalService",
				    ]
				)
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: LocalService) {
				        self.service = service
				    }
				    @Instantiated let service: LocalService
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct LocalService: Instantiable {
				    public init() {}
				}
				""",
			],
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
		)

		// Per-source loop iterates source files alphabetically:
		// `LocalService.swift` < `Root.swift`, so LocalService's mock
		// is emitted first. The `additionalMocksToGenerate` loop then
		// skips `LocalService` because the per-source loop already
		// emitted it — exactly one extension per type.
		#expect(output.combinedOutput == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Root {
		    public init() {
		        let service = LocalService()
		        self.init(service: service)
		    }
		}

		#if DEBUG
		extension LocalService {
		    static func mock() -> LocalService {
		        LocalService()
		    }
		}
		#endif

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> LocalService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> LocalService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? LocalService.init)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Duplicate `LocalService` mock leaked into combined output:\n\(output.combinedOutput ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_writesOnlyHeader_whenModuleHasNothingToEmit() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable
				public struct NonRootWithoutMock: Instantiable {
				    public init() {}
				}
				""",
			],
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
		)

		let combined = try #require(output.combinedOutput)
		#expect(combined == emptyMockConfigurationFileOutput, "Unexpected combined output: \(combined)")
	}

	// MARK: Private

	private var filesToDelete: [URL]
}

@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
extension URL {
	fileprivate static var temporaryFile: URL {
		#if os(Linux)
			FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
		#else
			URL.temporaryDirectory.appending(path: UUID().uuidString)
		#endif
	}
}
