// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Foundation
import SafeDICore
import Testing
@testable import SafeDITool

struct SafeDIToolMockGenerationTests: ~Copyable {
	// MARK: Initialization

	init() throws {
		filesToDelete = [URL]()
	}

	deinit {
		for fileToDelete in filesToDelete {
			try! FileManager.default.removeItem(at: fileToDelete)
		}
	}

	// MARK: Tests – Simple types

	@Test
	mutating func mock_generatedForTypeWithNoDependencies() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable
				public struct SimpleType: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["SimpleType+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension SimpleType {
		    public static func mock() -> SimpleType {
		        SimpleType()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForExtensionBasedInstantiable() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public class SomeThirdPartyType {}

				@Instantiable
				extension SomeThirdPartyType: Instantiable {
				    public static func instantiate() -> SomeThirdPartyType {
				        SomeThirdPartyType()
				    }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["SomeThirdPartyType+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension SomeThirdPartyType {
		    public static func mock() -> SomeThirdPartyType {
		        SomeThirdPartyType.instantiate()
		    }
		}
		#endif
		""")
	}

	// MARK: Tests – Types with dependencies

	@Test
	mutating func mock_generatedForTypeWithInstantiatedDependency() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(dep: Dep) {
				        self.dep = dep
				    }
				    @Instantiated let dep: Dep
				}
				""",
				"""
				@Instantiable
				public struct Dep: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum Dep { case root }
		    }

		    public static func mock(
		        dep: ((SafeDIMockPath.Dep) -> Dep)? = nil
		    ) -> Root {
		        let dep = dep?(.root) ?? Dep.mock()
		        return Root(dep: dep)
		    }
		}
		#endif
		""")

		#expect(output.mockFiles["Dep+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Dep {
		    public static func mock() -> Dep {
		        Dep()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForTypeWithReceivedDependency() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child, shared: SharedThing) {
				        self.child = child
				        self.shared = shared
				    }
				    @Instantiated let child: Child
				    @Instantiated let shared: SharedThing
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init(shared: SharedThing) {
				        self.shared = shared
				    }
				    @Received let shared: SharedThing
				}
				""",
				"""
				@Instantiable
				public struct SharedThing: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public enum SafeDIMockPath {
		        public enum SharedThing { case parent }
		    }

		    public static func mock(
		        sharedThing: ((SafeDIMockPath.SharedThing) -> SharedThing)? = nil
		    ) -> Child {
		        let sharedThing = sharedThing?(.parent) ?? SharedThing.mock()
		        return Child(shared: sharedThing)
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForFullTree() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, shared: SharedThing) {
				        self.childA = childA
				        self.shared = shared
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let shared: SharedThing
				}
				""",
				"""
				@Instantiable
				public struct ChildA: Instantiable {
				    public init(shared: SharedThing, grandchild: Grandchild) {
				        self.shared = shared
				        self.grandchild = grandchild
				    }
				    @Received let shared: SharedThing
				    @Instantiated let grandchild: Grandchild
				}
				""",
				"""
				@Instantiable
				public struct Grandchild: Instantiable {
				    public init(shared: SharedThing) {
				        self.shared = shared
				    }
				    @Received let shared: SharedThing
				}
				""",
				"""
				@Instantiable
				public struct SharedThing: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum ChildA { case root }
		        public enum Grandchild { case childA }
		        public enum SharedThing { case root }
		    }

		    public static func mock(
		        childA: ((SafeDIMockPath.ChildA) -> ChildA)? = nil,
		        grandchild: ((SafeDIMockPath.Grandchild) -> Grandchild)? = nil,
		        sharedThing: ((SafeDIMockPath.SharedThing) -> SharedThing)? = nil
		    ) -> Root {
		        let sharedThing = sharedThing?(.root) ?? SharedThing.mock()
		        let grandchild = grandchild?(.childA) ?? Grandchild(shared: sharedThing)
		        let childA = childA?(.root) ?? ChildA(shared: sharedThing, grandchild: grandchild)
		        return Root(childA: childA, shared: sharedThing)
		    }
		}
		#endif
		""")
	}

	// MARK: Tests – Configuration

	@Test
	mutating func mock_respectsMockConditionalCompilationNil() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@SafeDIConfiguration
				enum Config {
				    static let additionalImportedModules: [StaticString] = []
				    static let additionalDirectoriesToInclude: [StaticString] = []
				    static let generateMocks: Bool = true
				    static let mockConditionalCompilation: StaticString? = nil
				}
				""",
				"""
				@Instantiable
				public struct NoBranch: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["NoBranch+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension NoBranch {
		    public static func mock() -> NoBranch {
		        NoBranch()
		    }
		}
		""")
	}

	@Test
	mutating func mock_respectsCustomMockConditionalCompilation() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@SafeDIConfiguration
				enum Config {
				    static let additionalImportedModules: [StaticString] = []
				    static let additionalDirectoriesToInclude: [StaticString] = []
				    static let generateMocks: Bool = true
				    static let mockConditionalCompilation: StaticString? = "TESTING"
				}
				""",
				"""
				@Instantiable
				public struct CustomFlag: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["CustomFlag+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if TESTING
		extension CustomFlag {
		    public static func mock() -> CustomFlag {
		        CustomFlag()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_typeWithDepsAndNilConditionalCompilation() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@SafeDIConfiguration
				enum Config {
				    static let additionalImportedModules: [StaticString] = []
				    static let additionalDirectoriesToInclude: [StaticString] = []
				    static let generateMocks: Bool = true
				    static let mockConditionalCompilation: StaticString? = nil
				}
				""",
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(dep: Dep) {
				        self.dep = dep
				    }
				    @Instantiated let dep: Dep
				}
				""",
				"""
				@Instantiable
				public struct Dep: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Root {
		    public enum SafeDIMockPath {
		        public enum Dep { case root }
		    }

		    public static func mock(
		        dep: ((SafeDIMockPath.Dep) -> Dep)? = nil
		    ) -> Root {
		        let dep = dep?(.root) ?? Dep.mock()
		        return Root(dep: dep)
		    }
		}
		""")
	}

	@Test
	mutating func mock_notGeneratedWhenGenerateMocksIsFalse() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@SafeDIConfiguration
				enum Config {
				    static let additionalImportedModules: [StaticString] = []
				    static let additionalDirectoriesToInclude: [StaticString] = []
				    static let generateMocks: Bool = false
				    static let mockConditionalCompilation: StaticString? = "DEBUG"
				}
				""",
				"""
				@Instantiable
				public struct NoMocks: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		let mockContent = try #require(output.mockFiles["NoMocks+SafeDIMock.swift"])
		// When generateMocks is false, the file exists but contains only the header.
		#expect(!mockContent.contains("extension"))
	}

	@Test
	mutating func mock_respectsMockAttributes() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(mockAttributes: "@MainActor")
				public struct ActorBound: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["ActorBound+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ActorBound {
		    @MainActor public static func mock() -> ActorBound {
		        ActorBound()
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_parameterRequiredForTypeNotInTypeMap() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol SomeProtocol {}

				@Instantiable
				public struct Consumer: Instantiable {
				    public init(dependency: SomeProtocol) {
				        self.dependency = dependency
				    }
				    @Received let dependency: SomeProtocol
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Consumer+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Consumer {
		    public enum SafeDIMockPath {
		        public enum SomeProtocol { case parent }
		    }

		    public static func mock(
		        someProtocol: @escaping (SafeDIMockPath.SomeProtocol) -> SomeProtocol
		    ) -> Consumer {
		        let someProtocol = someProtocol(.parent)
		        return Consumer(dependency: someProtocol)
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_extensionBasedWithNilConditionalCompilation() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@SafeDIConfiguration
				enum Config {
				    static let additionalImportedModules: [StaticString] = []
				    static let additionalDirectoriesToInclude: [StaticString] = []
				    static let generateMocks: Bool = true
				    static let mockConditionalCompilation: StaticString? = nil
				}
				""",
				"""
				public class ThirdParty {}

				@Instantiable
				extension ThirdParty: Instantiable {
				    public static func instantiate() -> ThirdParty {
				        ThirdParty()
				    }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["ThirdParty+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension ThirdParty {
		    public static func mock() -> ThirdParty {
		        ThirdParty.instantiate()
		    }
		}
		""")
	}

	@Test
	mutating func mock_receivedErasedTypeAutoWraps() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public class AnyService {
				    public init(_ service: some Any) {}
				}
				""",
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child, myService: AnyService) {
				        self.child = child
				        self.myService = myService
				    }
				    @Instantiated let child: Child
				    @Instantiated(fulfilledByType: "ConcreteService", erasedToConcreteExistential: true) let myService: AnyService
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init(myService: AnyService) {
				        self.myService = myService
				    }
				    @Received let myService: AnyService
				}
				""",
				"""
				@Instantiable
				public struct ConcreteService: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Child receives AnyService, which is erased-to-concrete.
		// The mock should auto-detect this and provide AnyService param with inline wrapping.
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public enum SafeDIMockPath {
		        public enum AnyService { case parent }
		    }

		    public static func mock(
		        anyService: ((SafeDIMockPath.AnyService) -> AnyService)? = nil
		    ) -> Child {
		        let anyService = anyService?(.parent) ?? AnyService(ConcreteService.mock())
		        return Child(myService: anyService)
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForErasedToConcreteExistential() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol MyService {}
				public class AnyMyService {
				    public init(_ service: some MyService) {}
				}
				""",
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(myService: AnyMyService) {
				        self.myService = myService
				    }
				    @Instantiated(fulfilledByType: "DefaultMyService", erasedToConcreteExistential: true) let myService: AnyMyService
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [MyService.self])
				public struct DefaultMyService: Instantiable, MyService {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum AnyMyService { case root }
		        public enum DefaultMyService { case root }
		    }

		    public static func mock(
		        anyMyService: ((SafeDIMockPath.AnyMyService) -> AnyMyService)? = nil,
		        defaultMyService: ((SafeDIMockPath.DefaultMyService) -> DefaultMyService)? = nil
		    ) -> Root {
		        let defaultMyService = defaultMyService?(.root) ?? DefaultMyService.mock()
		        let anyMyService = anyMyService?(.root) ?? AnyMyService(defaultMyService)
		        return Root(myService: anyMyService)
		    }
		}
		#endif
		""")
	}

	// MARK: Tests – Complex configurations

	@Test
	mutating func mock_generatedForRootWithMultipleBranchesReceivingSameProperty() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public final class Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB, shared: Shared) {
				        self.childA = childA
				        self.childB = childB
				        self.shared = shared
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				    @Instantiated let shared: Shared
				}
				""",
				"""
				@Instantiable
				public final class ChildA: Instantiable {
				    public init(grandchildAA: GrandchildAA, grandchildAB: GrandchildAB) {
				        self.grandchildAA = grandchildAA
				        self.grandchildAB = grandchildAB
				    }
				    @Instantiated let grandchildAA: GrandchildAA
				    @Instantiated let grandchildAB: GrandchildAB
				}
				""",
				"""
				@Instantiable
				public final class GrandchildAA: Instantiable {
				    public init(shared: Shared) {
				        self.shared = shared
				    }
				    @Received let shared: Shared
				}
				""",
				"""
				@Instantiable
				public final class GrandchildAB: Instantiable {
				    public init(shared: Shared) {
				        self.shared = shared
				    }
				    @Received let shared: Shared
				}
				""",
				"""
				@Instantiable
				public final class ChildB: Instantiable {
				    public init(shared: Shared) {
				        self.shared = shared
				    }
				    @Received let shared: Shared
				}
				""",
				"""
				@Instantiable
				public final class Shared: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum ChildA { case root }
		        public enum ChildB { case root }
		        public enum GrandchildAA { case childA }
		        public enum GrandchildAB { case childA }
		        public enum Shared { case root }
		    }

		    public static func mock(
		        childA: ((SafeDIMockPath.ChildA) -> ChildA)? = nil,
		        childB: ((SafeDIMockPath.ChildB) -> ChildB)? = nil,
		        grandchildAA: ((SafeDIMockPath.GrandchildAA) -> GrandchildAA)? = nil,
		        grandchildAB: ((SafeDIMockPath.GrandchildAB) -> GrandchildAB)? = nil,
		        shared: ((SafeDIMockPath.Shared) -> Shared)? = nil
		    ) -> Root {
		        let shared = shared?(.root) ?? Shared.mock()
		        let childB = childB?(.root) ?? ChildB(shared: shared)
		        let grandchildAA = grandchildAA?(.childA) ?? GrandchildAA(shared: shared)
		        let grandchildAB = grandchildAB?(.childA) ?? GrandchildAB(shared: shared)
		        let childA = childA?(.root) ?? ChildA.mock()
		        return Root(childA: childA, childB: childB, shared: shared)
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForRootWithProtocolFulfilledByAdditionalType() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol NetworkService {}

				@Instantiable(fulfillingAdditionalTypes: [NetworkService.self])
				public final class DefaultNetworkService: Instantiable, NetworkService {
				    public init() {}
				}
				""",
				"""
				@Instantiable(isRoot: true)
				public final class Root: Instantiable {
				    public init(networkService: NetworkService) {
				        self.networkService = networkService
				    }
				    @Instantiated let networkService: NetworkService
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum NetworkService { case root }
		    }

		    public static func mock(
		        networkService: ((SafeDIMockPath.NetworkService) -> NetworkService)? = nil
		    ) -> Root {
		        let networkService = networkService?(.root) ?? DefaultNetworkService.mock()
		        return Root(networkService: networkService)
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_generatedForMultipleRootsEachGetsOwnMockFile() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct RootA: Instantiable {
				    public init(dep: Dep) {
				        self.dep = dep
				    }
				    @Instantiated let dep: Dep
				}
				""",
				"""
				@Instantiable(isRoot: true)
				public struct RootB: Instantiable {
				    public init(dep: Dep) {
				        self.dep = dep
				    }
				    @Instantiated let dep: Dep
				}
				""",
				"""
				@Instantiable
				public struct Dep: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Each root gets its own mock. Dep also gets a mock.
		#expect(output.mockFiles["RootA+SafeDIMock.swift"] != nil)
		#expect(output.mockFiles["RootB+SafeDIMock.swift"] != nil)
		#expect(output.mockFiles["Dep+SafeDIMock.swift"] != nil)
		let rootAMock = try #require(output.mockFiles["RootA+SafeDIMock.swift"])
		#expect(rootAMock.contains("public enum Dep { case root }"))
		let rootBMock = try #require(output.mockFiles["RootB+SafeDIMock.swift"])
		#expect(rootBMock.contains("public enum Dep { case root }"))
	}

	@Test
	mutating func mock_constructionOrderRespectsReceivedDependencies() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB, shared: Shared) {
				        self.childA = childA
				        self.childB = childB
				        self.shared = shared
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				    @Instantiated let shared: Shared
				}
				""",
				"""
				@Instantiable
				public struct ChildA: Instantiable {
				    public init(shared: Shared) {
				        self.shared = shared
				    }
				    @Received let shared: Shared
				}
				""",
				"""
				@Instantiable
				public struct ChildB: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable
				public struct Shared: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Shared must be constructed before ChildA (which depends on it via @Received).
		let rootMock = try #require(output.mockFiles["Root+SafeDIMock.swift"])
		let sharedLine = try #require(rootMock.range(of: "let shared = shared?")?.lowerBound)
		let childALine = try #require(rootMock.range(of: "let childA = childA?")?.lowerBound)
		#expect(sharedLine < childALine)
	}

	@Test
	mutating func mock_generatedForFourLevelDeepTreeWithSharedLeaf() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child, leaf: Leaf) {
				        self.child = child
				        self.leaf = leaf
				    }
				    @Instantiated let child: Child
				    @Instantiated let leaf: Leaf
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init(grandchild: Grandchild, leaf: Leaf) {
				        self.grandchild = grandchild
				        self.leaf = leaf
				    }
				    @Instantiated let grandchild: Grandchild
				    @Received let leaf: Leaf
				}
				""",
				"""
				@Instantiable
				public struct Grandchild: Instantiable {
				    public init(greatGrandchild: GreatGrandchild, leaf: Leaf) {
				        self.greatGrandchild = greatGrandchild
				        self.leaf = leaf
				    }
				    @Instantiated let greatGrandchild: GreatGrandchild
				    @Received let leaf: Leaf
				}
				""",
				"""
				@Instantiable
				public struct GreatGrandchild: Instantiable {
				    public init(leaf: Leaf) {
				        self.leaf = leaf
				    }
				    @Received let leaf: Leaf
				}
				""",
				"""
				@Instantiable
				public struct Leaf: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public enum SafeDIMockPath {
		        public enum Child { case root }
		        public enum Grandchild { case child }
		        public enum GreatGrandchild { case child_grandchild }
		        public enum Leaf { case root }
		    }

		    public static func mock(
		        child: ((SafeDIMockPath.Child) -> Child)? = nil,
		        grandchild: ((SafeDIMockPath.Grandchild) -> Grandchild)? = nil,
		        greatGrandchild: ((SafeDIMockPath.GreatGrandchild) -> GreatGrandchild)? = nil,
		        leaf: ((SafeDIMockPath.Leaf) -> Leaf)? = nil
		    ) -> Root {
		        let leaf = leaf?(.root) ?? Leaf.mock()
		        let greatGrandchild = greatGrandchild?(.child_grandchild) ?? GreatGrandchild(leaf: leaf)
		        let grandchild = grandchild?(.child) ?? Grandchild(greatGrandchild: greatGrandchild, leaf: leaf)
		        let child = child?(.root) ?? Child(grandchild: grandchild, leaf: leaf)
		        return Root(child: child, leaf: leaf)
		    }
		}
		#endif
		""")
	}

	@Test
	mutating func mock_inlineConstructionSkipsDefaultValuedArguments() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child, shared: Shared) {
				        self.child = child
				        self.shared = shared
				    }
				    @Instantiated let child: Child
				    @Instantiated let shared: Shared
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init(shared: Shared, flag: Bool = false) {
				        self.shared = shared
				    }
				    @Received let shared: Shared
				}
				""",
				"""
				@Instantiable
				public struct Shared: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		let rootMock = try #require(output.mockFiles["Root+SafeDIMock.swift"])
		// Child's inline construction should skip the `flag` default-valued argument.
		#expect(rootMock.contains("Child(shared: shared)"))
		#expect(!rootMock.contains("flag"))
	}

	@Test
	mutating func mock_generatedForTypeWithInstantiatorDependency() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(shared: Shared, childBuilder: Instantiator<Child>) {
				        self.shared = shared
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let shared: Shared
				    @Instantiated let childBuilder: Instantiator<Child>
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init(name: String, shared: Shared) {
				        self.name = name
				        self.shared = shared
				    }
				    @Forwarded let name: String
				    @Received let shared: Shared
				}
				""",
				"""
				@Instantiable
				public struct Shared: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		let rootMock = try #require(output.mockFiles["Root+SafeDIMock.swift"])
		// Instantiator uses property label as enum name.
		#expect(rootMock.contains("public enum ChildBuilder { case root }"))
		// Parameter type is the full Instantiator<Child>.
		#expect(rootMock.contains("childBuilder: ((SafeDIMockPath.ChildBuilder) -> Instantiator<Child>)? = nil"))
		// Default wraps inline tree in Instantiator closure with forwarded prop.
		#expect(rootMock.contains("Instantiator<Child> {"))
		#expect(rootMock.contains("name in"))
		#expect(rootMock.contains("Child(name: name, shared: shared)"))
	}

	@Test
	mutating func mock_generatedForTypeWithInstantiatorNoForwardedProperties() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(viewBuilder: Instantiator<SimpleView>) {
				        self.viewBuilder = viewBuilder
				    }
				    @Instantiated let viewBuilder: Instantiator<SimpleView>
				}
				""",
				"""
				@Instantiable
				public struct SimpleView: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		let rootMock = try #require(output.mockFiles["Root+SafeDIMock.swift"])
		#expect(rootMock.contains("public enum ViewBuilder { case root }"))
		#expect(rootMock.contains("viewBuilder: ((SafeDIMockPath.ViewBuilder) -> Instantiator<SimpleView>)? = nil"))
		// No forwarded props → empty closure params.
		#expect(rootMock.contains("Instantiator<SimpleView> {"))
		#expect(rootMock.contains("SimpleView()"))
	}

	@Test
	mutating func mock_generatedForTypeWithPublishedReceivedDependency() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				import Combine
				public protocol StringStorage {}
				@Instantiable(fulfillingAdditionalTypes: [StringStorage.self])
				extension UserDefaults: Instantiable, StringStorage {
				    public static func instantiate() -> UserDefaults { .standard }
				}
				""",
				"""
				import Combine
				@Instantiable
				public final class DefaultUserService: Instantiable {
				    public init(stringStorage: StringStorage) {
				        self.stringStorage = stringStorage
				    }
				    @Received @Published private var stringStorage: StringStorage
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// DefaultUserService should get a mock even with @Published on the property.
		let mock = try #require(output.mockFiles["DefaultUserService+SafeDIMock.swift"])
		#expect(mock.contains("extension DefaultUserService"))
		#expect(mock.contains("public static func mock"))
	}

	// MARK: Private

	private var filesToDelete: [URL]
}
