// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Foundation
import SafeDICore
import Testing
@testable import SafeDITool

struct SafeDIToolMockGenerationDisambiguationTests: ~Copyable {
	// MARK: Initialization

	init() throws {
		filesToDelete = [URL]()
	}

	deinit {
		for fileToDelete in filesToDelete {
			try! FileManager.default.removeItem(at: fileToDelete)
		}
	}

	// MARK: Tests – Parameter disambiguation

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatesParameters_whenInstantiatorLabelCollidesWithTypeName() async throws {
		// Root has @Instantiated let childB: ChildB (constant).
		// Root has @Instantiated let childA: ChildA, which has @Instantiated let childB: Instantiator<Other>.
		// The label "childB" collides between the constant and the Instantiator.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(childB: Instantiator<Other>) {
				        self.childB = childB
				    }
				    @Instantiated let childB: Instantiator<Other>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Other: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 4)

		#expect(output.mockFiles["ChildA+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildA {
		    public static func mock(
		        childB __safeDI_mock_childB: Instantiator<Other>? = nil
		    ) -> ChildA {
		        func __safeDI_childB() -> Other {
		            Other()
		        }
		        let childB = __safeDI_mock_childB ?? Instantiator<Other>(__safeDI_childB)
		        return ChildA(childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["ChildA+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["ChildB+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildB {
		    public static func mock() -> ChildB {
		        ChildB()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["ChildB+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Other+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Other {
		    public static func mock() -> Other {
		        Other()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Other+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        childA __safeDI_mock_childA: ChildA? = nil,
		        childB_ChildB __safeDI_mock_childB_ChildB: @autoclosure @escaping () -> ChildB = ChildB(),
		        childB_Instantiator__Other __safeDI_mock_childB_Instantiator__Other: Instantiator<Other>? = nil
		    ) -> Root {
		        func __safeDI_childA() -> ChildA {
		            func __safeDI_childB() -> Other {
		                Other()
		            }
		            let childB_Instantiator__Other = __safeDI_mock_childB_Instantiator__Other ?? Instantiator<Other>(__safeDI_childB)
		            return ChildA(childB: childB_Instantiator__Other)
		        }
		        let childA: ChildA = __safeDI_mock_childA ?? __safeDI_childA()
		        let childB_ChildB = __safeDI_mock_childB_ChildB()
		        return Root(childA: childA, childB: childB_ChildB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatesParameterLabelsWhenSameInitLabelAppearsTwice() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(service: ServiceA) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceA
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(service: ServiceB) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ServiceA: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ServiceB: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Both ChildA and ChildB have `@Instantiated let service: ...` with different types.
		// The mock parameters must be disambiguated since both would otherwise be named `service`.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        childA __safeDI_mock_childA: ChildA? = nil,
		        childB __safeDI_mock_childB: ChildB? = nil,
		        service_ServiceA __safeDI_mock_service_ServiceA: @autoclosure @escaping () -> ServiceA = ServiceA(),
		        service_ServiceB __safeDI_mock_service_ServiceB: @autoclosure @escaping () -> ServiceB = ServiceB()
		    ) -> Root {
		        func __safeDI_childA() -> ChildA {
		            let service_ServiceA = __safeDI_mock_service_ServiceA()
		            return ChildA(service: service_ServiceA)
		        }
		        let childA: ChildA = __safeDI_mock_childA ?? __safeDI_childA()
		        func __safeDI_childB() -> ChildB {
		            let service_ServiceB = __safeDI_mock_service_ServiceB()
		            return ChildB(service: service_ServiceB)
		        }
		        let childB: ChildB = __safeDI_mock_childB ?? __safeDI_childB()
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguationUsesSimplifiedSuffixWhenUnique() async throws {
		// Two children have `service` with different types. One is optional.
		// Simplified suffixes (stripping ?) are unique → use simplified.
		// service: ExternalService → service_ExternalService (not service_ExternalService)
		// service: LocalService? → service_LocalService (not service_LocalService_Optional)
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(service: ExternalService) { self.service = service }
				    @Received let service: ExternalService
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(service: LocalService?) { self.service = service }
				    @Received(onlyIfAvailable: true) let service: LocalService?
				}
				""",
				"""
				public struct ExternalService {}
				""",
				"""
				public struct LocalService {}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        childA __safeDI_mock_childA: ChildA? = nil,
		        childB __safeDI_mock_childB: ChildB? = nil,
		        service_ExternalService __safeDI_mock_service_ExternalService: @autoclosure @escaping () -> ExternalService,
		        service_LocalService __safeDI_mock_service_LocalService: @autoclosure @escaping () -> LocalService? = nil
		    ) -> Root {
		        let service_ExternalService = __safeDI_mock_service_ExternalService()
		        let service_LocalService = __safeDI_mock_service_LocalService()
		        let childA = __safeDI_mock_childA ?? ChildA(service: service_ExternalService)
		        let childB = __safeDI_mock_childB ?? ChildB(service: service_LocalService)
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguationFallsBackToFullSuffixWhenSimplifiedCollides() async throws {
		// Two children have `service` — one is `Service` (non-optional),
		// one is `Service?` (optional). Simplified types are both `Service` → collision.
		// Must fall back to full suffix: service_Service vs service_Service_Optional.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(service: Service) { self.service = service }
				    @Instantiated let service: Service
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(service: Service?) { self.service = service }
				    @Received(onlyIfAvailable: true) let service: Service?
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Service: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        childA __safeDI_mock_childA: ChildA? = nil,
		        childB __safeDI_mock_childB: ChildB? = nil,
		        service_Service __safeDI_mock_service_Service: @autoclosure @escaping () -> Service = Service(),
		        service_Service_Optional __safeDI_mock_service_Service_Optional: @autoclosure @escaping () -> Service? = nil
		    ) -> Root {
		        let service_Service_Optional = __safeDI_mock_service_Service_Optional()
		        func __safeDI_childA() -> ChildA {
		            let service_Service = __safeDI_mock_service_Service()
		            return ChildA(service: service_Service)
		        }
		        let childA: ChildA = __safeDI_mock_childA ?? __safeDI_childA()
		        let childB = __safeDI_mock_childB ?? ChildB(service: service_Service_Optional)
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedParamUsedInInstantiatorBuilderFunction() async throws {
		// ChildA is built via Instantiator and @Receives presenter: PresenterA.
		// ChildB @Receives presenter: PresenterB (same label, different type).
		// Both "presenter" params get disambiguated. The Instantiator builder for ChildA
		// must pass presenter_PresenterA (not raw "presenter") to the init.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childABuilder: Instantiator<ChildA>, childB: ChildB) {
				        self.childABuilder = childABuilder
				        self.childB = childB
				    }
				    @Instantiated let childABuilder: Instantiator<ChildA>
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(name: String, presenter: PresenterA) {
				        self.name = name
				        self.presenter = presenter
				    }
				    @Forwarded let name: String
				    @Received let presenter: PresenterA
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(presenter: PresenterB) {
				        self.presenter = presenter
				    }
				    @Received let presenter: PresenterB
				}
				""",
				"""
				public struct PresenterA {}
				""",
				"""
				public struct PresenterB {}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        childABuilder __safeDI_mock_childABuilder: Instantiator<ChildA>? = nil,
		        childB __safeDI_mock_childB: ChildB? = nil,
		        presenter_PresenterA __safeDI_mock_presenter_PresenterA: @autoclosure @escaping () -> PresenterA,
		        presenter_PresenterB __safeDI_mock_presenter_PresenterB: @autoclosure @escaping () -> PresenterB
		    ) -> Root {
		        let presenter_PresenterA = __safeDI_mock_presenter_PresenterA()
		        let presenter_PresenterB = __safeDI_mock_presenter_PresenterB()
		        func __safeDI_childABuilder(name: String) -> ChildA {
		            ChildA(name: name, presenter: presenter_PresenterA)
		        }
		        let childABuilder = __safeDI_mock_childABuilder ?? Instantiator<ChildA> {
		            __safeDI_childABuilder(name: $0)
		        }
		        let childB = __safeDI_mock_childB ?? ChildB(presenter: presenter_PresenterB)
		        return Root(childABuilder: childABuilder, childB: childB)
		    }
		}
		#endif
		""")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedInstantiatorBindingUsesDisambiguatedLocalName() async throws {
		// Two Instantiator children share label "childBuilder" but different types.
		// After disambiguation, the ?? binding local must use the disambiguated name.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(parent: Parent, childBuilder: Instantiator<ChildA>) {
				        self.parent = parent
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let parent: Parent
				    @Instantiated let childBuilder: Instantiator<ChildA>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(childBuilder: Instantiator<ChildB>) {
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let childBuilder: Instantiator<ChildB>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        childBuilder_Instantiator__ChildA __safeDI_mock_childBuilder_Instantiator__ChildA: Instantiator<ChildA>? = nil,
		        childBuilder_Instantiator__ChildB __safeDI_mock_childBuilder_Instantiator__ChildB: Instantiator<ChildB>? = nil,
		        parent __safeDI_mock_parent: Parent? = nil
		    ) -> Root {
		        func __safeDI_parent() -> Parent {
		            func __safeDI_childBuilder(name: String) -> ChildB {
		                ChildB(name: name)
		            }
		            let childBuilder_Instantiator__ChildB = __safeDI_mock_childBuilder_Instantiator__ChildB ?? Instantiator<ChildB> {
		                __safeDI_childBuilder(name: $0)
		            }
		            return Parent(childBuilder: childBuilder_Instantiator__ChildB)
		        }
		        let parent: Parent = __safeDI_mock_parent ?? __safeDI_parent()
		        func __safeDI_childBuilder(name: String) -> ChildA {
		            ChildA(name: name)
		        }
		        let childBuilder_Instantiator__ChildA = __safeDI_mock_childBuilder_Instantiator__ChildA ?? Instantiator<ChildA> {
		            __safeDI_childBuilder(name: $0)
		        }
		        return Root(parent: parent, childBuilder: childBuilder_Instantiator__ChildA)
		    }
		}
		#endif
		""")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedInstantiatorResolvedBySiblingInNestedBuilder() async throws {
		// ChildC and ChildD both have a dep named "childBuilder" but with different generic types.
		// At root, both are promoted → disambiguated. ChildC's builder must reference
		// childBuilder_Instantiator__ChildA (not childBuilder) since disambiguation occurred.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childC: ChildC, childD: ChildD) {
				        self.childC = childC
				        self.childD = childD
				    }
				    @Instantiated let childC: ChildC
				    @Instantiated let childD: ChildD
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildC: Instantiable {
				    public init(childBuilder: Instantiator<ChildA>) {
				        self.childBuilder = childBuilder
				    }
				    @Received let childBuilder: Instantiator<ChildA>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildD: Instantiable {
				    public init(childBuilder: Instantiator<ChildB>) {
				        self.childBuilder = childBuilder
				    }
				    @Received let childBuilder: Instantiator<ChildB>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        childBuilder_Instantiator__ChildA __safeDI_mock_childBuilder_Instantiator__ChildA: Instantiator<ChildA>? = nil,
		        childBuilder_Instantiator__ChildB __safeDI_mock_childBuilder_Instantiator__ChildB: Instantiator<ChildB>? = nil,
		        childC __safeDI_mock_childC: ChildC? = nil,
		        childD __safeDI_mock_childD: ChildD? = nil
		    ) -> Root {
		        func __safeDI_childBuilder(name: String) -> ChildA {
		            ChildA(name: name)
		        }
		        let childBuilder_Instantiator__ChildA = __safeDI_mock_childBuilder_Instantiator__ChildA ?? Instantiator<ChildA> {
		            __safeDI_childBuilder(name: $0)
		        }
		        let childC = __safeDI_mock_childC ?? ChildC(childBuilder: childBuilder_Instantiator__ChildA)
		        func __safeDI_childBuilder(name: String) -> ChildB {
		            ChildB(name: name)
		        }
		        let childBuilder_Instantiator__ChildB = __safeDI_mock_childBuilder_Instantiator__ChildB ?? Instantiator<ChildB> {
		            __safeDI_childBuilder(name: $0)
		        }
		        let childD = __safeDI_mock_childD ?? ChildD(childBuilder: childBuilder_Instantiator__ChildB)
		        return Root(childC: childC, childD: childD)
		    }
		}
		#endif
		""")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedInstantiatorResolvedThroughIntermediateInstantiatorBuilder() async throws {
		// Root → parentBuilder (Instantiator<Parent>) + childBuilder (Instantiator<ChildA>).
		// Parent uses childBuilder (Instantiator<ChildA>) + also has otherBuilder (Instantiator<ChildB>)
		// with same label "childBuilder" — causing disambiguation at root.
		// Inside parentBuilder's function, Parent is constructed.
		// Parent's init references childBuilder → must be childBuilder_Instantiator__ChildA.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(parentBuilder: Instantiator<Parent>, childBuilder: Instantiator<ChildA>) {
				        self.parentBuilder = parentBuilder
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let parentBuilder: Instantiator<Parent>
				    @Instantiated let childBuilder: Instantiator<ChildA>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(childBuilder: Instantiator<ChildA>, otherBuilder: Instantiator<ChildB>) {
				        self.childBuilder = childBuilder
				        self.otherBuilder = otherBuilder
				    }
				    @Received let childBuilder: Instantiator<ChildA>
				    @Instantiated let otherBuilder: Instantiator<ChildB>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        childBuilder __safeDI_mock_childBuilder: Instantiator<ChildA>? = nil,
		        otherBuilder __safeDI_mock_otherBuilder: Instantiator<ChildB>? = nil,
		        parentBuilder __safeDI_mock_parentBuilder: Instantiator<Parent>? = nil
		    ) -> Root {
		        func __safeDI_childBuilder(name: String) -> ChildA {
		            ChildA(name: name)
		        }
		        let childBuilder = __safeDI_mock_childBuilder ?? Instantiator<ChildA> {
		            __safeDI_childBuilder(name: $0)
		        }
		        func __safeDI_parentBuilder() -> Parent {
		            func __safeDI_otherBuilder(name: String) -> ChildB {
		                ChildB(name: name)
		            }
		            let otherBuilder = __safeDI_mock_otherBuilder ?? Instantiator<ChildB> {
		                __safeDI_otherBuilder(name: $0)
		            }
		            return Parent(childBuilder: childBuilder, otherBuilder: otherBuilder)
		        }
		        let parentBuilder = __safeDI_mock_parentBuilder ?? Instantiator<Parent>(__safeDI_parentBuilder)
		        return Root(parentBuilder: parentBuilder, childBuilder: childBuilder)
		    }
		}
		#endif
		""")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedInstantiatorInDeepNestedBuilderUsesResolvedName() async throws {
		// Root has two children that each receive a different-typed builder with same label.
		// ChildA → receives builder: Instantiator<TypeA>
		// ChildB → has sub: SubChild which also receives builder: Instantiator<TypeA>
		// Both "builder" Instantiators get disambiguated at root.
		// Inside ChildB's SubChild construction, the resolved builder must use
		// the disambiguated name, not the original label.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childBBuilder: Instantiator<ChildB>) {
				        self.childA = childA
				        self.childBBuilder = childBBuilder
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childBBuilder: Instantiator<ChildB>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(builder: Instantiator<TypeA>) {
				        self.builder = builder
				    }
				    @Received let builder: Instantiator<TypeA>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(subChild: SubChild) {
				        self.subChild = subChild
				    }
				    @Instantiated let subChild: SubChild
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct SubChild: Instantiable {
				    public init(builder: Instantiator<TypeB>) {
				        self.builder = builder
				    }
				    @Received let builder: Instantiator<TypeB>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct TypeA: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct TypeB: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        builder_Instantiator__TypeA __safeDI_mock_builder_Instantiator__TypeA: Instantiator<TypeA>? = nil,
		        builder_Instantiator__TypeB __safeDI_mock_builder_Instantiator__TypeB: Instantiator<TypeB>? = nil,
		        childA __safeDI_mock_childA: ChildA? = nil,
		        childBBuilder __safeDI_mock_childBBuilder: Instantiator<ChildB>? = nil,
		        subChild __safeDI_mock_subChild: SubChild? = nil
		    ) -> Root {
		        func __safeDI_builder(name: String) -> TypeA {
		            TypeA(name: name)
		        }
		        let builder_Instantiator__TypeA = __safeDI_mock_builder_Instantiator__TypeA ?? Instantiator<TypeA> {
		            __safeDI_builder(name: $0)
		        }
		        let childA = __safeDI_mock_childA ?? ChildA(builder: builder_Instantiator__TypeA)
		        func __safeDI_builder(name: String) -> TypeB {
		            TypeB(name: name)
		        }
		        let builder_Instantiator__TypeB = __safeDI_mock_builder_Instantiator__TypeB ?? Instantiator<TypeB> {
		            __safeDI_builder(name: $0)
		        }
		        func __safeDI_childBBuilder() -> ChildB {
		            let subChild = __safeDI_mock_subChild ?? SubChild(builder: builder_Instantiator__TypeB)
		            return ChildB(subChild: subChild)
		        }
		        let childBBuilder = __safeDI_mock_childBBuilder ?? Instantiator<ChildB>(__safeDI_childBBuilder)
		        return Root(childA: childA, childBBuilder: childBBuilder)
		    }
		}
		#endif
		""")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedAutoclosureEvaluatedInInstantiatorBuilder() async throws {
		// Root has parentBuilder (Instantiator<Parent>) and childB: ChildB.
		// Parent @Receives config: ConfigA. ChildB @Receives config: ConfigB.
		// Same label "config", different types — both disambiguated as config_ConfigA, config_ConfigB.
		// Inside parentBuilder's function, config_ConfigA must be evaluated before constructing Parent.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(parentBuilder: Instantiator<Parent>, childB: ChildB) {
				        self.parentBuilder = parentBuilder
				        self.childB = childB
				    }
				    @Instantiated let parentBuilder: Instantiator<Parent>
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(name: String, config: ConfigA) {
				        self.name = name
				        self.config = config
				    }
				    @Forwarded let name: String
				    @Received let config: ConfigA
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(config: ConfigB) { self.config = config }
				    @Received let config: ConfigB
				}
				""",
				"""
				public struct ConfigA {}
				""",
				"""
				public struct ConfigB {}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        childB __safeDI_mock_childB: ChildB? = nil,
		        config_ConfigA __safeDI_mock_config_ConfigA: @autoclosure @escaping () -> ConfigA,
		        config_ConfigB __safeDI_mock_config_ConfigB: @autoclosure @escaping () -> ConfigB,
		        parentBuilder __safeDI_mock_parentBuilder: Instantiator<Parent>? = nil
		    ) -> Root {
		        let config_ConfigA = __safeDI_mock_config_ConfigA()
		        let config_ConfigB = __safeDI_mock_config_ConfigB()
		        func __safeDI_parentBuilder(name: String) -> Parent {
		            Parent(name: name, config: config_ConfigA)
		        }
		        let parentBuilder = __safeDI_mock_parentBuilder ?? Instantiator<Parent> {
		            __safeDI_parentBuilder(name: $0)
		        }
		        let childB = __safeDI_mock_childB ?? ChildB(config: config_ConfigB)
		        return Root(parentBuilder: parentBuilder, childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedUncoveredDependencyInNestedInstantiator() async throws {
		// Root @Instantiates parent: Parent and child: Child.
		// Parent @Receives engine: EngineA. Child @Receives engine: EngineB.
		// Same label "engine", different types — both uncovered (required mock params).
		// Both are disambiguated: engine_EngineA and engine_EngineB.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(parent: Parent, child: Child) {
				        self.parent = parent
				        self.child = child
				    }
				    @Instantiated let parent: Parent
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(engine: EngineA) { self.engine = engine }
				    @Received let engine: EngineA
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(engine: EngineB) { self.engine = engine }
				    @Received let engine: EngineB
				}
				""",
				"""
				public struct EngineA {}
				""",
				"""
				public struct EngineB {}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        child __safeDI_mock_child: Child? = nil,
		        engine_EngineA __safeDI_mock_engine_EngineA: @autoclosure @escaping () -> EngineA,
		        engine_EngineB __safeDI_mock_engine_EngineB: @autoclosure @escaping () -> EngineB,
		        parent __safeDI_mock_parent: Parent? = nil
		    ) -> Root {
		        let engine_EngineA = __safeDI_mock_engine_EngineA()
		        let engine_EngineB = __safeDI_mock_engine_EngineB()
		        let parent = __safeDI_mock_parent ?? Parent(engine: engine_EngineA)
		        let child = __safeDI_mock_child ?? Child(engine: engine_EngineB)
		        return Root(parent: parent, child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_onlyIfAvailableDisambiguatedSimplifiedUnique() async throws {
		// ChildA @Receives service: ExternalService. ChildB @Receives(onlyIfAvailable: true) service: LocalService?.
		// Both share label "service" — disambiguated by type. Optional suffix stripped from
		// onlyIfAvailable dep: service_LocalService (not service_Optional_LocalService).
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(service: ExternalService) { self.service = service }
				    @Received let service: ExternalService
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(service: LocalService?) { self.service = service }
				    @Received(onlyIfAvailable: true) let service: LocalService?
				}
				""",
				"""
				public struct ExternalService {}
				""",
				"""
				public struct LocalService {}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        childA __safeDI_mock_childA: ChildA? = nil,
		        childB __safeDI_mock_childB: ChildB? = nil,
		        service_ExternalService __safeDI_mock_service_ExternalService: @autoclosure @escaping () -> ExternalService,
		        service_LocalService __safeDI_mock_service_LocalService: @autoclosure @escaping () -> LocalService? = nil
		    ) -> Root {
		        let service_ExternalService = __safeDI_mock_service_ExternalService()
		        let service_LocalService = __safeDI_mock_service_LocalService()
		        let childA = __safeDI_mock_childA ?? ChildA(service: service_ExternalService)
		        let childB = __safeDI_mock_childB ?? ChildB(service: service_LocalService)
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_closureTypedDefaultDisambiguated() async throws {
		// ChildA has default-valued `onAction: @escaping () -> Void = {}`.
		// ChildB has default-valued `onAction: @escaping (String) -> Void = { _ in }`.
		// Same label "onAction", different closure types. Both are closure-typed defaults.
		// Disambiguated: onAction_Void_to_Void and onAction_String_to_Void (or similar suffix).
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(onAction: @escaping () -> Void = {}) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(onAction: @escaping (String) -> Void = { _ in }) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        childA __safeDI_mock_childA: ChildA? = nil,
		        childB __safeDI_mock_childB: ChildB? = nil,
		        onAction_String_to_Void __safeDI_mock_onAction_String_to_Void: @escaping (String) -> Void = { _ in },
		        onAction_Void_to_Void __safeDI_mock_onAction_Void_to_Void: @escaping () -> Void = {}
		    ) -> Root {
		        func __safeDI_childA() -> ChildA {
		            let onAction_Void_to_Void = __safeDI_mock_onAction_Void_to_Void
		            return ChildA(onAction: onAction_Void_to_Void)
		        }
		        let childA: ChildA = __safeDI_mock_childA ?? __safeDI_childA()
		        func __safeDI_childB() -> ChildB {
		            let onAction_String_to_Void = __safeDI_mock_onAction_String_to_Void
		            return ChildB(onAction: onAction_String_to_Void)
		        }
		        let childB: ChildB = __safeDI_mock_childB ?? __safeDI_childB()
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatesAllParameters_whenThreeChildrenShareSameLabel() async throws {
		// Three children each receive "service" with a different type.
		// All three get disambiguated: service_ServiceA, service_ServiceB, service_ServiceC.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB, childC: ChildC) {
				        self.childA = childA
				        self.childB = childB
				        self.childC = childC
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				    @Instantiated let childC: ChildC
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(service: ServiceA) { self.service = service }
				    @Received let service: ServiceA
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(service: ServiceB) { self.service = service }
				    @Received let service: ServiceB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildC: Instantiable {
				    public init(service: ServiceC) { self.service = service }
				    @Received let service: ServiceC
				}
				""",
				"""
				public struct ServiceA {}
				""",
				"""
				public struct ServiceB {}
				""",
				"""
				public struct ServiceC {}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        childA __safeDI_mock_childA: ChildA? = nil,
		        childB __safeDI_mock_childB: ChildB? = nil,
		        childC __safeDI_mock_childC: ChildC? = nil,
		        service_ServiceA __safeDI_mock_service_ServiceA: @autoclosure @escaping () -> ServiceA,
		        service_ServiceB __safeDI_mock_service_ServiceB: @autoclosure @escaping () -> ServiceB,
		        service_ServiceC __safeDI_mock_service_ServiceC: @autoclosure @escaping () -> ServiceC
		    ) -> Root {
		        let service_ServiceA = __safeDI_mock_service_ServiceA()
		        let service_ServiceB = __safeDI_mock_service_ServiceB()
		        let service_ServiceC = __safeDI_mock_service_ServiceC()
		        let childA = __safeDI_mock_childA ?? ChildA(service: service_ServiceA)
		        let childB = __safeDI_mock_childB ?? ChildB(service: service_ServiceB)
		        let childC = __safeDI_mock_childC ?? ChildC(service: service_ServiceC)
		        return Root(childA: childA, childB: childB, childC: childC)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedInstantiatorResolvedFromRootInNestedScope() async throws {
		// Root @Instantiates childBuilder: Instantiator<ChildA> (disambiguated).
		// Root also @Instantiates parentBuilder: Instantiator<Parent>.
		// Parent @Instantiates childBuilder: Instantiator<ChildA> (same label+type as root).
		// Root also promotes childBuilder: Instantiator<ChildB> from another branch.
		// Both "childBuilder" get disambiguated at root.
		// Inside parentBuilder's function, Parent's childBuilder is resolved from root
		// (not re-constructed). It must use the disambiguated name.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(
				        childBuilder: Instantiator<ChildA>,
				        parentBuilder: Instantiator<Parent>,
				        other: Other
				    ) {
				        self.childBuilder = childBuilder
				        self.parentBuilder = parentBuilder
				        self.other = other
				    }
				    @Instantiated let childBuilder: Instantiator<ChildA>
				    @Instantiated let parentBuilder: Instantiator<Parent>
				    @Instantiated let other: Other
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(childBuilder: Instantiator<ChildA>) {
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let childBuilder: Instantiator<ChildA>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Other: Instantiable {
				    public init(childBuilder: Instantiator<ChildB>) {
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let childBuilder: Instantiator<ChildB>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        childBuilder_Instantiator__ChildA __safeDI_mock_childBuilder_Instantiator__ChildA: Instantiator<ChildA>? = nil,
		        childBuilder_Instantiator__ChildB __safeDI_mock_childBuilder_Instantiator__ChildB: Instantiator<ChildB>? = nil,
		        other __safeDI_mock_other: Other? = nil,
		        parentBuilder __safeDI_mock_parentBuilder: Instantiator<Parent>? = nil
		    ) -> Root {
		        func __safeDI_childBuilder(name: String) -> ChildA {
		            ChildA(name: name)
		        }
		        let childBuilder_Instantiator__ChildA = __safeDI_mock_childBuilder_Instantiator__ChildA ?? Instantiator<ChildA> {
		            __safeDI_childBuilder(name: $0)
		        }
		        func __safeDI_parentBuilder() -> Parent {
		            func __safeDI_childBuilder(name: String) -> ChildA {
		                ChildA(name: name)
		            }
		            let childBuilder_Instantiator__ChildA = Instantiator<ChildA> {
		                __safeDI_childBuilder(name: $0)
		            }
		            return Parent(childBuilder: childBuilder_Instantiator__ChildA)
		        }
		        let parentBuilder = __safeDI_mock_parentBuilder ?? Instantiator<Parent>(__safeDI_parentBuilder)
		        func __safeDI_other() -> Other {
		            func __safeDI_childBuilder(name: String) -> ChildB {
		                ChildB(name: name)
		            }
		            let childBuilder_Instantiator__ChildB = __safeDI_mock_childBuilder_Instantiator__ChildB ?? Instantiator<ChildB> {
		                __safeDI_childBuilder(name: $0)
		            }
		            return Other(childBuilder: childBuilder_Instantiator__ChildB)
		        }
		        let other: Other = __safeDI_mock_other ?? __safeDI_other()
		        return Root(childBuilder: childBuilder_Instantiator__ChildA, parentBuilder: parentBuilder, other: other)
		    }
		}
		#endif
		""")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_postDisambiguationLabelDoesNotCollideWithExistingPropertyLabel() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB, childC: ChildC) {
				        self.childA = childA
				        self.childB = childB
				        self.childC = childC
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				    @Instantiated let childC: ChildC
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(service: UserService) {
				        self.service = service
				    }
				    @Received let service: UserService
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(service: AdminService) {
				        self.service = service
				    }
				    @Received let service: AdminService
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildC: Instantiable {
				    public init(service_UserService: OtherType) {
				        self.service_UserService = service_UserService
				    }
				    @Received let service_UserService: OtherType
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct UserService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct AdminService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct OtherType: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// After disambiguation, "service" splits into "service_UserService" and "service_AdminService".
		// ChildC has a literal property labeled "service_UserService" — the disambiguated version
		// must get a further suffix to avoid colliding with the literal label.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        childA __safeDI_mock_childA: ChildA? = nil,
		        childB __safeDI_mock_childB: ChildB? = nil,
		        childC __safeDI_mock_childC: ChildC? = nil,
		        service_AdminService __safeDI_mock_service_AdminService: @autoclosure @escaping () -> AdminService = AdminService(),
		        service_UserService __safeDI_mock_service_UserService: @autoclosure @escaping () -> OtherType = OtherType(),
		        service_UserService_UserService __safeDI_mock_service_UserService_UserService: @autoclosure @escaping () -> UserService = UserService()
		    ) -> Root {
		        let service_UserService_UserService = __safeDI_mock_service_UserService_UserService()
		        let childA = __safeDI_mock_childA ?? ChildA(service: service_UserService_UserService)
		        let service_AdminService = __safeDI_mock_service_AdminService()
		        let childB = __safeDI_mock_childB ?? ChildB(service: service_AdminService)
		        let service_UserService = __safeDI_mock_service_UserService()
		        let childC = __safeDI_mock_childC ?? ChildC(service_UserService: service_UserService)
		        return Root(childA: childA, childB: childB, childC: childC)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_aliasedBindingUsesDisambiguatedFulfillingPropertyLabel() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child, service: TypeA) {
				        self.child = child
				        self.service = service
				    }
				    @Instantiated let child: Child
				    @Instantiated let service: TypeA
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(service: TypeB, serviceAlias: TypeB) {
				        self.service = service
				        self.serviceAlias = serviceAlias
				    }
				    @Instantiated let service: TypeB
				    @Received(fulfilledByDependencyNamed: "service", ofType: TypeB.self, erasedToConcreteExistential: false) let serviceAlias: TypeB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct TypeA: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct TypeB: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Root has "service: TypeA" and Child has "service: TypeB" — the label "service"
		// collides at the root mock level, causing disambiguation to "service_TypeA" and
		// "service_TypeB". Child's alias (serviceAlias fulfilled by "service") must
		// reference the disambiguated "service_TypeB", not the raw "service".
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        child __safeDI_mock_child: Child? = nil,
		        service_TypeA __safeDI_mock_service_TypeA: @autoclosure @escaping () -> TypeA = TypeA(),
		        service_TypeB __safeDI_mock_service_TypeB: @autoclosure @escaping () -> TypeB = TypeB()
		    ) -> Root {
		        let service_TypeB = __safeDI_mock_service_TypeB()
		        func __safeDI_child() -> Child {
		            let serviceAlias: TypeB = service_TypeB
		            return Child(service: service_TypeB, serviceAlias: serviceAlias)
		        }
		        let child: Child = __safeDI_mock_child ?? __safeDI_child()
		        let service_TypeA = __safeDI_mock_service_TypeA()
		        return Root(child: child, service: service_TypeA)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguationFallsBackToFullSuffixWhenSimplifiedSuffixesCollide() async throws {
		// Root instantiates three children. Each child has a default-valued init
		// parameter named "value" with a different type. ServiceA and ServiceA?
		// both simplify to "ServiceA", forcing the full suffix fallback.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB, childC: ChildC) {
				        self.childA = childA
				        self.childB = childB
				        self.childC = childC
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				    @Instantiated let childC: ChildC
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(value: ServiceA = ServiceA()) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(value: ServiceA? = nil) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildC: Instantiable {
				    public init(value: ServiceB = ServiceB()) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ServiceA: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ServiceB: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// "value" label appears three times: ServiceA, ServiceA?, ServiceB.
		// ServiceA and ServiceA? both simplify to "ServiceA", so their simplified
		// candidate "value_ServiceA" collides. Both fall back to full asIdentifier:
		// ServiceA stays "value_ServiceA", ServiceA? becomes "value_ServiceA_Optional".
		// ServiceB has no collision and uses simplified "value_ServiceB".
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public static func mock(
		        childA __safeDI_mock_childA: ChildA? = nil,
		        childB __safeDI_mock_childB: ChildB? = nil,
		        childC __safeDI_mock_childC: ChildC? = nil,
		        value_ServiceA __safeDI_mock_value_ServiceA: @autoclosure @escaping () -> ServiceA = ServiceA(),
		        value_ServiceA_Optional __safeDI_mock_value_ServiceA_Optional: @autoclosure @escaping () -> ServiceA? = nil,
		        value_ServiceB __safeDI_mock_value_ServiceB: @autoclosure @escaping () -> ServiceB = ServiceB()
		    ) -> Root {
		        func __safeDI_childA() -> ChildA {
		            let value_ServiceA = __safeDI_mock_value_ServiceA()
		            return ChildA(value: value_ServiceA)
		        }
		        let childA: ChildA = __safeDI_mock_childA ?? __safeDI_childA()
		        func __safeDI_childB() -> ChildB {
		            let value_ServiceA_Optional = __safeDI_mock_value_ServiceA_Optional()
		            return ChildB(value: value_ServiceA_Optional)
		        }
		        let childB: ChildB = __safeDI_mock_childB ?? __safeDI_childB()
		        func __safeDI_childC() -> ChildC {
		            let value_ServiceB = __safeDI_mock_value_ServiceB()
		            return ChildC(value: value_ServiceB)
		        }
		        let childC: ChildC = __safeDI_mock_childC ?? __safeDI_childC()
		        return Root(childA: childA, childB: childB, childC: childC)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	// MARK: Private

	private var filesToDelete: [URL]
}
