// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Foundation
import SafeDICore
import Testing
@testable import SafeDITool

struct SafeDIToolMockGenerationDefaultValueTests: ~Copyable {
	// MARK: Initialization

	init() throws {
		filesToDelete = [URL]()
	}

	deinit {
		for fileToDelete in filesToDelete {
			try! FileManager.default.removeItem(at: fileToDelete)
		}
	}

	// MARK: Tests – Default-valued parameters

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterBubblesUpToRootMock() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child, shared: Shared) {
				        self.child = child
				        self.shared = shared
				    }
				    @Instantiated let child: Child
				    @Instantiated let shared: Shared
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(shared: Shared, flag: Bool = false) {
				        self.shared = shared
				    }
				    @Received let shared: Shared
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Shared: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    struct SafeDIParameters {
		        init(
		            shared: Shared.SafeDIMockConfiguration = .init()
		        ) {
		            self.shared = shared
		        }

		        let shared: Shared.SafeDIMockConfiguration
		    }

		    static func mock(
		        flag: Bool = false,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Child {
		        let shared = (safeDIParameters.shared.safeDIBuilder ?? Shared.init)()
		        return Child(shared: shared, flag: flag)
		    }
		}
		#endif

		#if DEBUG
		extension Child {
		    struct SafeDIMockConfiguration {
		        init(
		            flag: Bool = false,
		            _ safeDIBuilder: ((Shared, Bool) -> Child)? = nil
		        ) {
		            self.flag = flag
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let flag: Bool
		        let safeDIBuilder: ((Shared, Bool) -> Child)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            shared: Shared.SafeDIMockConfiguration = .init(),
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.shared = shared
		            self.child = child
		        }

		        let shared: Shared.SafeDIMockConfiguration
		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let shared = (safeDIParameters.shared.safeDIBuilder ?? Shared.init)()
		        func __safeDI_child() -> Child {
		            return (safeDIParameters.child.safeDIBuilder ?? Child.init(shared:flag:))(shared, safeDIParameters.child.flag)
		        }
		        let child: Child = __safeDI_child()
		        return Root(child: child, shared: shared)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")

		#expect(output.mockFiles["Shared+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Shared {
		    static func mock() -> Shared {
		        Shared()
		    }
		}
		#endif

		#if DEBUG
		extension Shared {
		    struct SafeDIMockConfiguration {
		        init(
		            _ safeDIBuilder: (() -> Shared)? = nil
		        ) {
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let safeDIBuilder: (() -> Shared)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Shared+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterUsesOriginalDefaultExpression() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(config: String = "hello") {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    static func mock(
		        config: String = "hello"
		    ) -> Child {
		        return Child(config: config)
		    }
		}
		#endif

		#if DEBUG
		extension Child {
		    struct SafeDIMockConfiguration {
		        init(
		            config: String = "hello",
		            _ safeDIBuilder: ((String) -> Child)? = nil
		        ) {
		            self.config = config
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let config: String
		        let safeDIBuilder: ((String) -> Child)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            return (safeDIParameters.child.safeDIBuilder ?? Child.init(config:))(safeDIParameters.child.config)
		        }
		        let child: Child = __safeDI_child()
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterDoesNotBubbleThroughInstantiator() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childBuilder: Instantiator<Child>) { self.childBuilder = childBuilder }
				    @Instantiated let childBuilder: Instantiator<Child>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(name: String, flag: Bool = false) { self.name = name }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childBuilder: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.childBuilder = childBuilder
		        }

		        let childBuilder: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childBuilder(name: String) -> Child {
		            (safeDIParameters.childBuilder.safeDIBuilder ?? Child.init(name:flag:))(name, safeDIParameters.childBuilder.flag)
		        }
		        let childBuilder = Instantiator<Child> {
		            __safeDI_childBuilder(name: $0)
		        }
		        return Root(childBuilder: childBuilder)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    static func mock(
		        name: String,
		        flag: Bool = false
		    ) -> Child {
		        return Child(name: name, flag: flag)
		    }
		}
		#endif

		#if DEBUG
		extension Child {
		    struct SafeDIMockConfiguration {
		        init(
		            flag: Bool = false,
		            _ safeDIBuilder: ((String, Bool) -> Child)? = nil
		        ) {
		            self.flag = flag
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let flag: Bool
		        let safeDIBuilder: ((String, Bool) -> Child)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterBubblesFromGrandchildToRoot() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(grandchild: Grandchild) { self.grandchild = grandchild }
				    @Instantiated let grandchild: Grandchild
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Grandchild: Instantiable {
				    public init(viewModel: String = "default") {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            func __safeDI_grandchild() -> Grandchild {
		                return (safeDIParameters.child.grandchild.safeDIBuilder ?? Grandchild.init(viewModel:))(safeDIParameters.child.grandchild.viewModel)
		            }
		            let grandchild: Grandchild = __safeDI_grandchild()
		            return (safeDIParameters.child.safeDIBuilder ?? Child.init(grandchild:))(grandchild)
		        }
		        let child: Child = __safeDI_child()
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    struct SafeDIParameters {
		        init(
		            grandchild: Grandchild.SafeDIMockConfiguration = .init()
		        ) {
		            self.grandchild = grandchild
		        }

		        let grandchild: Grandchild.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Child {
		        func __safeDI_grandchild() -> Grandchild {
		            return (safeDIParameters.grandchild.safeDIBuilder ?? Grandchild.init(viewModel:))(safeDIParameters.grandchild.viewModel)
		        }
		        let grandchild: Grandchild = __safeDI_grandchild()
		        return Child(grandchild: grandchild)
		    }
		}
		#endif

		#if DEBUG
		extension Child {
		    struct SafeDIMockConfiguration {
		        init(
		            grandchild: Grandchild.SafeDIMockConfiguration = .init(),
		            _ safeDIBuilder: ((Grandchild) -> Child)? = nil
		        ) {
		            self.grandchild = grandchild
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let grandchild: Grandchild.SafeDIMockConfiguration
		        let safeDIBuilder: ((Grandchild) -> Child)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")

		#expect(output.mockFiles["Grandchild+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Grandchild {
		    static func mock(
		        viewModel: String = "default"
		    ) -> Grandchild {
		        return Grandchild(viewModel: viewModel)
		    }
		}
		#endif

		#if DEBUG
		extension Grandchild {
		    struct SafeDIMockConfiguration {
		        init(
		            viewModel: String = "default",
		            _ safeDIBuilder: ((String) -> Grandchild)? = nil
		        ) {
		            self.viewModel = viewModel
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let viewModel: String
		        let safeDIBuilder: ((String) -> Grandchild)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Grandchild+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterOnRootType() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child, debug: Bool = false) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        debug: Bool = false,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let child = (safeDIParameters.child.safeDIBuilder ?? Child.init)()
		        return Root(child: child, debug: debug)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterDoesNotBubbleThroughSendableInstantiator() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childBuilder: SendableInstantiator<Child>) { self.childBuilder = childBuilder }
				    @Instantiated let childBuilder: SendableInstantiator<Child>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(name: String, flag: Bool = false) { self.name = name }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childBuilder: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.childBuilder = childBuilder
		        }

		        let childBuilder: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let __safeDI_childBuilder__safeDIBuilder = safeDIParameters.childBuilder.safeDIBuilder ?? Child.init(name:flag:)
		        @Sendable func __safeDI_childBuilder(name: String) -> Child {
		            __safeDI_childBuilder__safeDIBuilder(name, safeDIParameters.childBuilder.flag)
		        }
		        let childBuilder = SendableInstantiator<Child> {
		            __safeDI_childBuilder(name: $0)
		        }
		        return Root(childBuilder: childBuilder)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_multipleDefaultValuedParametersFromDifferentChildren() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(flagA: Bool = true) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(flagB: Int = 42) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childA: ChildA.SafeDIMockConfiguration = .init(),
		            childB: ChildB.SafeDIMockConfiguration = .init()
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        let childA: ChildA.SafeDIMockConfiguration
		        let childB: ChildB.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childA() -> ChildA {
		            return (safeDIParameters.childA.safeDIBuilder ?? ChildA.init(flagA:))(safeDIParameters.childA.flagA)
		        }
		        let childA: ChildA = __safeDI_childA()
		        func __safeDI_childB() -> ChildB {
		            return (safeDIParameters.childB.safeDIBuilder ?? ChildB.init(flagB:))(safeDIParameters.childB.flagB)
		        }
		        let childB: ChildB = __safeDI_childB()
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterWithNilDefault() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(viewModel: String? = nil) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            return (safeDIParameters.child.safeDIBuilder ?? Child.init(viewModel:))(safeDIParameters.child.viewModel)
		        }
		        let child: Child = __safeDI_child()
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    static func mock(
		        viewModel: String? = nil
		    ) -> Child {
		        return Child(viewModel: viewModel)
		    }
		}
		#endif

		#if DEBUG
		extension Child {
		    struct SafeDIMockConfiguration {
		        init(
		            viewModel: String? = nil,
		            _ safeDIBuilder: ((String?) -> Child)? = nil
		        ) {
		            self.viewModel = viewModel
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let viewModel: String?
		        let safeDIBuilder: ((String?) -> Child)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterDisambiguatedWhenLabelCollides() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(flag: Bool = true) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(flag: String = "on") {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childA: ChildA.SafeDIMockConfiguration = .init(),
		            childB: ChildB.SafeDIMockConfiguration = .init()
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        let childA: ChildA.SafeDIMockConfiguration
		        let childB: ChildB.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childA() -> ChildA {
		            return (safeDIParameters.childA.safeDIBuilder ?? ChildA.init(flag:))(safeDIParameters.childA.flag)
		        }
		        let childA: ChildA = __safeDI_childA()
		        func __safeDI_childB() -> ChildB {
		            return (safeDIParameters.childB.safeDIBuilder ?? ChildB.init(flag:))(safeDIParameters.childB.flag)
		        }
		        let childB: ChildB = __safeDI_childB()
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterDoesNotBubbleThroughErasedInstantiator() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childBuilder: ErasedInstantiator<String, Child>) {
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let childBuilder: ErasedInstantiator<String, Child>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(name: String, flag: Bool = false) {
				        self.name = name
				    }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childBuilder: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.childBuilder = childBuilder
		        }

		        let childBuilder: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childBuilder(name: String) -> Child {
		            (safeDIParameters.childBuilder.safeDIBuilder ?? Child.init(name:flag:))(name, safeDIParameters.childBuilder.flag)
		        }
		        let childBuilder = ErasedInstantiator<String, Child> {
		            __safeDI_childBuilder(name: $0)
		        }
		        return Root(childBuilder: childBuilder)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterDoesNotBubbleThroughSendableErasedInstantiator() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childBuilder: SendableErasedInstantiator<String, Child>) {
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let childBuilder: SendableErasedInstantiator<String, Child>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(name: String, flag: Bool = false) {
				        self.name = name
				    }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childBuilder: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.childBuilder = childBuilder
		        }

		        let childBuilder: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let __safeDI_childBuilder__safeDIBuilder = safeDIParameters.childBuilder.safeDIBuilder ?? Child.init(name:flag:)
		        @Sendable func __safeDI_childBuilder(name: String) -> Child {
		            __safeDI_childBuilder__safeDIBuilder(name, safeDIParameters.childBuilder.flag)
		        }
		        let childBuilder = SendableErasedInstantiator<String, Child> {
		            __safeDI_childBuilder(name: $0)
		        }
		        return Root(childBuilder: childBuilder)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterWithComplexDefault() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(values: [Int] = [1, 2, 3]) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            return (safeDIParameters.child.safeDIBuilder ?? Child.init(values:))(safeDIParameters.child.values)
		        }
		        let child: Child = __safeDI_child()
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_childDefaultParamDoesNotReEvaluateRootBoundLabel() async throws {
		// Parent @Receives clientId (uncovered, no scope for String).
		// Child has clientId as a non-dependency default-valued init param.
		// The root binds `let clientId = clientId()`. The child function
		// must NOT re-bind it — clientId is already a String, not callable.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Parent: Instantiable {
				    public init(clientId: String, child: Child) {
				        self.clientId = clientId
				        self.child = child
				    }
				    @Received let clientId: String
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(clientId: String = "default") {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Parent+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Parent {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        clientId: String,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Parent {
		        func __safeDI_child() -> Child {
		            return (safeDIParameters.child.safeDIBuilder ?? Child.init(clientId:))(safeDIParameters.child.clientId)
		        }
		        let child: Child = __safeDI_child()
		        return Parent(clientId: clientId, child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Parent+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedDefaultParamsFromDifferentChildrenDoNotCollideAtRoot() async throws {
		// ChildA has `viewModel: ViewModelA = ViewModelA()` and ChildB has `viewModel: ViewModelB = ViewModelB()`.
		// Both bubble to root as disambiguated autoclosure params. They must NOT both produce
		// `let viewModel = ...` at root scope — each should bind inside its own child function.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(viewModel: ViewModelA = ViewModelA()) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(viewModel: ViewModelB = ViewModelB()) {}
				}
				""",
				"""
				public struct ViewModelA {}
				""",
				"""
				public struct ViewModelB {}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Each viewModel binding must be INSIDE its child function, not at root scope.
		// Root scope should NOT have `let viewModel = ...` at all.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childA: ChildA.SafeDIMockConfiguration = .init(),
		            childB: ChildB.SafeDIMockConfiguration = .init()
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        let childA: ChildA.SafeDIMockConfiguration
		        let childB: ChildB.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childA() -> ChildA {
		            return (safeDIParameters.childA.safeDIBuilder ?? ChildA.init(viewModel:))(safeDIParameters.childA.viewModel)
		        }
		        let childA: ChildA = __safeDI_childA()
		        func __safeDI_childB() -> ChildB {
		            return (safeDIParameters.childB.safeDIBuilder ?? ChildB.init(viewModel:))(safeDIParameters.childB.viewModel)
		        }
		        let childB: ChildB = __safeDI_childB()
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""", "Unexpected Root output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParametersFromMultipleLevelsAllAppearAtRoot() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(grandchild: Grandchild, config: String = "dev") {
				        self.grandchild = grandchild
				    }
				    @Instantiated let grandchild: Grandchild
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Grandchild: Instantiable {
				    public init(viewModel: String = "default") {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            func __safeDI_grandchild() -> Grandchild {
		                return (safeDIParameters.child.grandchild.safeDIBuilder ?? Grandchild.init(viewModel:))(safeDIParameters.child.grandchild.viewModel)
		            }
		            let grandchild: Grandchild = __safeDI_grandchild()
		            return (safeDIParameters.child.safeDIBuilder ?? Child.init(grandchild:config:))(grandchild, safeDIParameters.child.config)
		        }
		        let child: Child = __safeDI_child()
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterFromGrandchildStopsAtInstantiatorBoundary() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(grandchildBuilder: Instantiator<Grandchild>) {
				        self.grandchildBuilder = grandchildBuilder
				    }
				    @Instantiated let grandchildBuilder: Instantiator<Grandchild>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Grandchild: Instantiable {
				    public init(name: String, viewModel: String = "default") {
				        self.name = name
				    }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            func __safeDI_grandchildBuilder(name: String) -> Grandchild {
		                (safeDIParameters.child.grandchildBuilder.safeDIBuilder ?? Grandchild.init(name:viewModel:))(name, safeDIParameters.child.grandchildBuilder.viewModel)
		            }
		            let grandchildBuilder = Instantiator<Grandchild> {
		                __safeDI_grandchildBuilder(name: $0)
		            }
		            return (safeDIParameters.child.safeDIBuilder ?? Child.init(grandchildBuilder:))(grandchildBuilder)
		        }
		        let child: Child = __safeDI_child()
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedClosureParameterStripsEscaping() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(onDismiss: @escaping () -> Void = {}) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            return (safeDIParameters.child.safeDIBuilder ?? Child.init(onDismiss:))(safeDIParameters.child.onDismiss)
		        }
		        let child: Child = __safeDI_child()
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedMainActorClosurePreservesMainActor() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(
				        onCancel: @escaping @MainActor (String) -> Void = { _ in },
				        onSubmit: @escaping @MainActor (String) throws -> Void = { _ in }
				    ) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    static func mock(
		        onCancel: @escaping @MainActor (String) -> Void = { _ in },
		        onSubmit: @escaping @MainActor (String) throws -> Void = { _ in }
		    ) -> Child {
		        return Child(onCancel: onCancel, onSubmit: onSubmit)
		    }
		}
		#endif

		#if DEBUG
		extension Child {
		    struct SafeDIMockConfiguration {
		        init(
		            onCancel: @escaping @MainActor (String) -> Void = { _ in },
		            onSubmit: @escaping @MainActor (String) throws -> Void = { _ in },
		            _ safeDIBuilder: ((@escaping @MainActor (String) -> Void, @escaping @MainActor (String) throws -> Void) -> Child)? = nil
		        ) {
		            self.onCancel = onCancel
		            self.onSubmit = onSubmit
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let onCancel: @MainActor (String) -> Void
		        let onSubmit: @MainActor (String) throws -> Void
		        let safeDIBuilder: ((@escaping @MainActor (String) -> Void, @escaping @MainActor (String) throws -> Void) -> Child)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedSendableClosurePreservesSendable() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(onComplete: @escaping @Sendable () -> Void = {}) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            return (safeDIParameters.child.safeDIBuilder ?? Child.init(onComplete:))(safeDIParameters.child.onComplete)
		        }
		        let child: Child = __safeDI_child()
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParamDoesNotSuppressReceivedPropertyBinding() async throws {
		// A child has a default-valued init param with the same label as a received
		// dependency on another child. The default-valued declaration must NOT suppress
		// the received property's root-level binding.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(service: Service?) {
				        self.service = service
				    }
				    @Received(onlyIfAvailable: true) let service: Service?
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(service: Service? = nil) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Service: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// ChildA receives `service` (onlyIfAvailable). ChildB has `service` as a
		// default-valued param. The root-level binding for `service` must exist
		// so ChildA's construction can reference the resolved value, not the closure.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childA: ChildA.SafeDIMockConfiguration = .init(),
		            childB: ChildB.SafeDIMockConfiguration = .init()
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        let childA: ChildA.SafeDIMockConfiguration
		        let childB: ChildB.SafeDIMockConfiguration
		    }

		    static func mock(
		        service: Service? = nil,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let childA = (safeDIParameters.childA.safeDIBuilder ?? ChildA.init(service:))(service)
		        func __safeDI_childB() -> ChildB {
		            return (safeDIParameters.childB.safeDIBuilder ?? ChildB.init(service:))(safeDIParameters.childB.service)
		        }
		        let childB: ChildB = __safeDI_childB()
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_forwardedParamDoesNotCollideWithBubbledDefault() async throws {
		// Root @Forwards `name: String`. Child has default-valued `name: String = "default"`.
		// Both produce mock params with label "name". Disambiguation must handle forwarded too.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(name: String, child: Child) {
				        self.name = name
				        self.child = child
				    }
				    @Forwarded let name: String
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(name: String = "default") {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// name (forwarded, bare) stays as-is. name_String (bubbled default) is disambiguated.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        name: String,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            return (safeDIParameters.child.safeDIBuilder ?? Child.init(name:))(safeDIParameters.child.name)
		        }
		        let child: Child = __safeDI_child()
		        return Root(name: name, child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesOuterLabel_whenDefaultValuedParameterHasUnderscoreInnerLabel() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(isLoggingEnabled _: Bool = false) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            return (safeDIParameters.child.safeDIBuilder ?? Child.init(isLoggingEnabled:))(safeDIParameters.child.isLoggingEnabled)
		        }
		        let child: Child = __safeDI_child()
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    static func mock(
		        isLoggingEnabled: Bool = false
		    ) -> Child {
		        return Child(isLoggingEnabled: isLoggingEnabled)
		    }
		}
		#endif

		#if DEBUG
		extension Child {
		    struct SafeDIMockConfiguration {
		        init(
		            isLoggingEnabled: Bool = false,
		            _ safeDIBuilder: ((Bool) -> Child)? = nil
		        ) {
		            self.isLoggingEnabled = isLoggingEnabled
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let isLoggingEnabled: Bool
		        let safeDIBuilder: ((Bool) -> Child)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_doesNotBubbleDefaultValuedParameter_whenOuterLabelIsUnderscore() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(_ isLoggingEnabled: Bool = false) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let child = (safeDIParameters.child.safeDIBuilder ?? Child.init(_:))(isLoggingEnabled)
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    static func mock() -> Child {
		        Child()
		    }
		}
		#endif

		#if DEBUG
		extension Child {
		    struct SafeDIMockConfiguration {
		        init(
		            _ safeDIBuilder: ((Bool) -> Child)? = nil
		        ) {
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let safeDIBuilder: ((Bool) -> Child)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_doesNotBubbleDefaultValuedParameter_whenOnlyLabelIsUnderscore() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(_: Bool = false) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let child = (safeDIParameters.child.safeDIBuilder ?? Child.init(_:))(_)
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    static func mock() -> Child {
		        Child()
		    }
		}
		#endif

		#if DEBUG
		extension Child {
		    struct SafeDIMockConfiguration {
		        init(
		            _ safeDIBuilder: ((Bool) -> Child)? = nil
		        ) {
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let safeDIBuilder: ((Bool) -> Child)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")
	}

	// MARK: Private

	private var filesToDelete: [URL]
}
