// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Foundation
import SafeDICore
import Testing
@testable import SafeDITool

struct SafeDIToolCombinedOutputTests: ~Copyable {
	// MARK: Initialization

	init() throws {
		filesToDelete = [URL]()
	}

	deinit {
		for fileToDelete in filesToDelete {
			try! FileManager.default.removeItem(at: fileToDelete)
		}
	}

	// MARK: Tests

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_writesRootDependencyTreeAndMockIntoOneFile() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(dep: Dep) {
				        self.dep = dep
				    }
				    @Instantiated let dep: Dep
				}
				""",
				"""
				@Instantiable
				public struct Dep: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
		)

		let combined = try #require(output.combinedOutput)

		// File header appears exactly once at the top.
		let headerLine = "// This file was generated by the SafeDIGenerateDependencyTree build tool plugin."
		let headerOccurrences = combined.components(separatedBy: headerLine).count - 1
		#expect(headerOccurrences == 1, "Expected header once, got \(headerOccurrences):\n\(combined)")

		// Dependency-tree wiring for `Root` is present.
		let rootExtensionOpener = "extension Root {\n    public init() {"
		#expect(combined.contains(rootExtensionOpener), "Missing root extension:\n\(combined)")

		// Mock surface is present.
		let mockFunction = "static func mock("
		#expect(combined.contains(mockFunction), "Missing mock method:\n\(combined)")

		// Order is root dependency tree → mock.
		let rootRange = try #require(combined.range(of: rootExtensionOpener))
		let mockRange = try #require(combined.range(of: mockFunction))
		#expect(rootRange.lowerBound < mockRange.lowerBound, "Expected root tree to precede mock:\n\(combined)")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func run_combinedOutput_writesOnlyHeader_whenModuleHasNothingToEmit() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable
				public struct NonRootWithoutMock: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			buildCombinedOutput: true,
			filesToDelete: &filesToDelete,
		)

		let combined = try #require(output.combinedOutput)
		#expect(combined == emptyMockConfigurationFileOutput, "Unexpected combined output: \(combined)")
	}

	// MARK: Private

	private var filesToDelete: [URL]
}
