// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Foundation
import SafeDICore
import Testing
@testable import SafeDITool

struct SafeDIToolMockGenerationCustomMockTests: ~Copyable {
	// MARK: Initialization

	init() throws {
		filesToDelete = [URL]()
	}

	deinit {
		for fileToDelete in filesToDelete {
			try! FileManager.default.removeItem(at: fileToDelete)
		}
	}

	// MARK: Tests – Custom mock coexistence

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_generatedWithCustomMockCallThrough_whenTypeHasExistingMockMethodAndCustomMockName() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct TypeWithMock: Instantiable {
				    public init() {}
				    public static func customMock() -> TypeWithMock {
				        TypeWithMock()
				    }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["TypeWithMock+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension TypeWithMock {
		    static func mock() -> TypeWithMock {
		        TypeWithMock.customMock()
		    }
		}
		#endif
		""")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_generatedWhenTypeHasExistingMockMethodWithCustomMockNameAndGenerateMock() async throws {
		// Type has generateMock: true AND a hand-written customMock with a dependency parameter.
		// The generated mock calls through to the hand-written .customMock(dependency:).
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct TypeWithCustomMock: Instantiable {
				    public init(dependency: Dependency) {
				        self.dependency = dependency
				    }
				    @Received let dependency: Dependency
				    public static func customMock(dependency: Dependency) -> TypeWithCustomMock {
				        TypeWithCustomMock(dependency: dependency)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Dependency: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		// Type has generateMock: true — SafeDI generates a mock that calls through to customMock.
		#expect(output.mockFiles["TypeWithCustomMock+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension TypeWithCustomMock {
		    struct SafeDIParameters {
		        init(
		            dependency: Dependency.SafeDIMockConfiguration = .init()
		        ) {
		            self.dependency = dependency
		        }

		        let dependency: Dependency.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> TypeWithCustomMock {
		        let dependency = (safeDIParameters.dependency.safeDIBuilder ?? Dependency.init)()
		        return TypeWithCustomMock.customMock(dependency: dependency)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["TypeWithCustomMock+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Dependency+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Dependency {
		    static func mock() -> Dependency {
		        Dependency()
		    }
		}
		#endif

		#if DEBUG
		extension Dependency {
		    struct SafeDIMockConfiguration {
		        init(
		            _ safeDIBuilder: (() -> Dependency)? = nil
		        ) {
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let safeDIBuilder: (() -> Dependency)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Dependency+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_generatedWhenTypeHasNonStaticMockMethod() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct TypeWithInstanceMock: Instantiable {
				    public init() {}
				    public func mock() -> TypeWithInstanceMock {
				        TypeWithInstanceMock()
				    }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		// Instance method named "mock" is NOT a static func mock — should still generate.
		#expect(output.mockFiles["TypeWithInstanceMock+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension TypeWithInstanceMock {
		    static func mock() -> TypeWithInstanceMock {
		        TypeWithInstanceMock()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["TypeWithInstanceMock+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesExistingMockMethodInChildConstruction() async throws {
		// When a child type has a user-defined mock() with parameters matching its
		// dependencies, the parent's generated mock calls Child.mock(...) instead
		// of Child(...).
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Dependency: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct Child: Instantiable {
				    public init(dependency: Dependency) {
				        self.dependency = dependency
				    }
				    @Received let dependency: Dependency

				    public static func customMock(dependency: Dependency) -> Child {
				        Child(dependency: dependency)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(child: Child) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Parent's mock should call Child.mock(dependency:) not Child(dependency:).
		#expect(output.mockFiles["Parent+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Parent {
		    struct SafeDIParameters {
		        init(
		            dependency: Dependency.SafeDIMockConfiguration = .init(),
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.dependency = dependency
		            self.child = child
		        }

		        let dependency: Dependency.SafeDIMockConfiguration
		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Parent {
		        let dependency = (safeDIParameters.dependency.safeDIBuilder ?? Dependency.init)()
		        let child = (safeDIParameters.child.safeDIBuilder ?? Child.customMock(dependency:))(dependency)
		        return Parent(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Parent+SafeDIMock.swift"] ?? "")")

		// Child has generateMock: true and a hand-written mock — generated mock calls through.
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    struct SafeDIParameters {
		        init(
		            dependency: Dependency.SafeDIMockConfiguration = .init()
		        ) {
		            self.dependency = dependency
		        }

		        let dependency: Dependency.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Child {
		        let dependency = (safeDIParameters.dependency.safeDIBuilder ?? Dependency.init)()
		        return Child.customMock(dependency: dependency)
		    }
		}
		#endif

		#if DEBUG
		extension Child {
		    struct SafeDIMockConfiguration {
		        init(
		            _ safeDIBuilder: ((Dependency) -> Child)? = nil
		        ) {
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let safeDIBuilder: ((Dependency) -> Child)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_existingMockMethodCoexistsWithNonMockChildren() async throws {
		// Some children have user-defined mocks, others don't. The generated
		// mock uses .mock() for the former and regular init for the latter.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct ServiceA: Instantiable {
				    public init() {}

				    public static func customMock() -> ServiceA {
				        ServiceA()
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ServiceB: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(serviceA: ServiceA, serviceB: ServiceB) {
				        self.serviceA = serviceA
				        self.serviceB = serviceB
				    }
				    @Instantiated let serviceA: ServiceA
				    @Instantiated let serviceB: ServiceB
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// ServiceA has a no-param mock() — can't thread dependencies, so use regular init.
		// ServiceB has no mock — use regular init.
		#expect(output.mockFiles["Parent+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Parent {
		    struct SafeDIParameters {
		        init(
		            serviceA: ServiceA.SafeDIMockConfiguration = .init(),
		            serviceB: ServiceB.SafeDIMockConfiguration = .init()
		        ) {
		            self.serviceA = serviceA
		            self.serviceB = serviceB
		        }

		        let serviceA: ServiceA.SafeDIMockConfiguration
		        let serviceB: ServiceB.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Parent {
		        let serviceA = (safeDIParameters.serviceA.safeDIBuilder ?? ServiceA.customMock)()
		        let serviceB = (safeDIParameters.serviceB.safeDIBuilder ?? ServiceB.init)()
		        return Parent(serviceA: serviceA, serviceB: serviceB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Parent+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_existingMockMethodInDeepTree() async throws {
		// Grandchild has a user-defined mock with parameters. Parent → Child → Grandchild.
		// The construction chain should call Grandchild.mock() at the deepest level.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Service: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct Grandchild: Instantiable {
				    public init(service: Service) {
				        self.service = service
				    }
				    @Received let service: Service

				    public static func customMock(service: Service) -> Grandchild {
				        Grandchild(service: service)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(grandchild: Grandchild) {
				        self.grandchild = grandchild
				    }
				    @Instantiated let grandchild: Grandchild
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(child: Child) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Parent → Child → Grandchild.mock(service:)
		#expect(output.mockFiles["Parent+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Parent {
		    struct SafeDIParameters {
		        init(
		            service: Service.SafeDIMockConfiguration = .init(),
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.service = service
		            self.child = child
		        }

		        let service: Service.SafeDIMockConfiguration
		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Parent {
		        let service = (safeDIParameters.service.safeDIBuilder ?? Service.init)()
		        func __safeDI_child() -> Child {
		            let grandchild = (safeDIParameters.child.grandchild.safeDIBuilder ?? Grandchild.customMock(service:))(service)
		            return (safeDIParameters.child.safeDIBuilder ?? Child.init(grandchild:))(grandchild)
		        }
		        let child: Child = __safeDI_child()
		        return Parent(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Parent+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_existingMockMethodOnExtensionBasedType() async throws {
		// An extension-based @Instantiable type with a user-defined mock method.
		// Parent should call Child.mock() instead of Child.instantiate().
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Service: Instantiable {
				    public init() {}
				}
				""",
				"""
				public struct Child {
				    let service: Service
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				extension Child: Instantiable {
				    public static func instantiate(service: Service) -> Child {
				        Child(service: service)
				    }

				    public static func customMock(service: Service) -> Child {
				        Child(service: service)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(child: Child) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Parent should call Child.mock(service:) instead of Child.instantiate(service:).
		#expect(output.mockFiles["Parent+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Parent {
		    struct SafeDIParameters {
		        init(
		            service: Service.SafeDIMockConfiguration = .init(),
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.service = service
		            self.child = child
		        }

		        let service: Service.SafeDIMockConfiguration
		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Parent {
		        let service = (safeDIParameters.service.safeDIBuilder ?? Service.init)()
		        let child = (safeDIParameters.child.safeDIBuilder ?? Child.customMock(service:))(service)
		        return Parent(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Parent+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_existingMockMethodOnExtensionBasedTypeWithReversedSourceOrder() async throws {
		// Same as mock_existingMockMethodOnExtensionBasedType but with mock() declared
		// before instantiate() in source order. Verifies visit order doesn't matter.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Service: Instantiable {
				    public init() {}
				}
				""",
				"""
				public struct Child {
				    let service: Service
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				extension Child: Instantiable {
				    public static func customMock(service: Service) -> Child {
				        Child(service: service)
				    }

				    public static func instantiate(service: Service) -> Child {
				        Child(service: service)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(child: Child) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Same expectation as the non-reversed test — source order must not matter.
		#expect(output.mockFiles["Parent+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Parent {
		    struct SafeDIParameters {
		        init(
		            service: Service.SafeDIMockConfiguration = .init(),
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.service = service
		            self.child = child
		        }

		        let service: Service.SafeDIMockConfiguration
		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Parent {
		        let service = (safeDIParameters.service.safeDIBuilder ?? Service.init)()
		        let child = (safeDIParameters.child.safeDIBuilder ?? Child.customMock(service:))(service)
		        return Parent(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Parent+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_existingMockMethodWithMultipleDependencies() async throws {
		// Child has a user-defined mock with multiple dependency parameters.
		// All parameters are correctly threaded through the parent's mock.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct ServiceA: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ServiceB: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct Child: Instantiable {
				    public init(serviceA: ServiceA, serviceB: ServiceB) {
				        self.serviceA = serviceA
				        self.serviceB = serviceB
				    }
				    @Received let serviceA: ServiceA
				    @Received let serviceB: ServiceB

				    public static func customMock(serviceA: ServiceA, serviceB: ServiceB) -> Child {
				        Child(serviceA: serviceA, serviceB: serviceB)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(child: Child) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Both serviceA and serviceB should be threaded to Child.mock().
		#expect(output.mockFiles["Parent+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Parent {
		    struct SafeDIParameters {
		        init(
		            serviceA: ServiceA.SafeDIMockConfiguration = .init(),
		            serviceB: ServiceB.SafeDIMockConfiguration = .init(),
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.serviceA = serviceA
		            self.serviceB = serviceB
		            self.child = child
		        }

		        let serviceA: ServiceA.SafeDIMockConfiguration
		        let serviceB: ServiceB.SafeDIMockConfiguration
		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Parent {
		        let serviceA = (safeDIParameters.serviceA.safeDIBuilder ?? ServiceA.init)()
		        let serviceB = (safeDIParameters.serviceB.safeDIBuilder ?? ServiceB.init)()
		        let child = (safeDIParameters.child.safeDIBuilder ?? Child.customMock(serviceA:serviceB:))(serviceA, serviceB)
		        return Parent(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Parent+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_existingMockMethodWithReversedParameterOrder() async throws {
		// Child's customMock has parameters in reversed order from init.
		// The generated mock's call-through must match the custom mock's parameter order.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct ServiceA: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ServiceB: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct Child: Instantiable {
				    public init(serviceA: ServiceA, serviceB: ServiceB) {
				        self.serviceA = serviceA
				        self.serviceB = serviceB
				    }
				    @Received let serviceA: ServiceA
				    @Received let serviceB: ServiceB

				    public static func customMock(serviceB: ServiceB, serviceA: ServiceA) -> Child {
				        Child(serviceA: serviceA, serviceB: serviceB)
				    }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// The generated mock's parameter order and call-through should match customMock's parameter order (serviceB, serviceA).
		// Body bindings follow topological order (alphabetical for leaf dependencies).
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    struct SafeDIParameters {
		        init(
		            serviceA: ServiceA.SafeDIMockConfiguration = .init(),
		            serviceB: ServiceB.SafeDIMockConfiguration = .init()
		        ) {
		            self.serviceA = serviceA
		            self.serviceB = serviceB
		        }

		        let serviceA: ServiceA.SafeDIMockConfiguration
		        let serviceB: ServiceB.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Child {
		        let serviceA = (safeDIParameters.serviceA.safeDIBuilder ?? ServiceA.init)()
		        let serviceB = (safeDIParameters.serviceB.safeDIBuilder ?? ServiceB.init)()
		        return Child.customMock(serviceB: serviceB, serviceA: serviceA)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_existingMockMethodSkipsGenerationForTypeButGeneratesForParent() async throws {
		// A type with a user-defined mock() gets no generated mock file, but its parent
		// still gets a generated mock with parameters and inline construction.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct Child: Instantiable {
				    public init(name: String) {
				        self.name = name
				    }
				    @Received let name: String

				    public static func customMock(name: String) -> Child {
				        Child(name: name)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(child: Child) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Child has generateMock: true and a hand-written mock — generated mock calls through.
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    static func mock(
		        name: String
		    ) -> Child {
		        return Child.customMock(name: name)
		    }
		}
		#endif

		#if DEBUG
		extension Child {
		    struct SafeDIMockConfiguration {
		        init(
		            _ safeDIBuilder: ((String) -> Child)? = nil
		        ) {
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let safeDIBuilder: ((String) -> Child)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")

		// Parent DOES get a generated mock with parameters and Child.mock() call.
		#expect(output.mockFiles["Parent+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Parent {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        name: String,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Parent {
		        let child = (safeDIParameters.child.safeDIBuilder ?? Child.customMock(name:))(name)
		        return Parent(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Parent+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterOnTypeWithExistingMock() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct Child: Instantiable {
				    public init(dependency: Dependency, extra: Bool = false) {
				        self.dependency = dependency
				    }
				    @Instantiated let dependency: Dependency
				    public static func customMock(dependency: Dependency, extra: Bool = false) -> Child {
				        Child(dependency: dependency, extra: extra)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Dependency: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Child has a user-defined mock() with `extra: Bool = false` (non-dependency default).
		// Non-dependency defaults DO bubble from mock methods.
		// The .mock() call passes dependency and extra (bubbled default).
		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            let dependency = (safeDIParameters.child.dependency.safeDIBuilder ?? Dependency.init)()
		            return (safeDIParameters.child.safeDIBuilder ?? Child.customMock(dependency:extra:))(dependency, safeDIParameters.child.extra)
		        }
		        let child: Child = __safeDI_child()
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_uncoveredDependencyEvaluatedBeforePassingToUserMock() async throws {
		// Root @Instantiates ChildService which has a user-defined mock(engine:).
		// engine comes from a parallel module (uncovered dep).
		// The autoclosure must be evaluated before passing to .mock().
		let crossModuleOutput = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable
				public struct Engine: Instantiable {
				    public init() {}
				}
				""",
			],
			filesToDelete: &filesToDelete,
		)

		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childService: ChildService) { self.childService = childService }
				    @Instantiated let childService: ChildService
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct ChildService: Instantiable {
				    public init(engine: Engine) { self.engine = engine }
				    @Instantiated let engine: Engine
				    public static func customMock(engine: Engine) -> ChildService {
				        ChildService(engine: engine)
				    }
				}
				""",
			],
			dependentModuleInfoPaths: [crossModuleOutput.moduleInfoOutputPath],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// engine must be evaluated before passing to .mock()
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childService: ChildService.SafeDIMockConfiguration = .init()
		        ) {
		            self.childService = childService
		        }

		        let childService: ChildService.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childService() -> ChildService {
		            let engine = (safeDIParameters.childService.engine.safeDIBuilder ?? Engine.init)()
		            return (safeDIParameters.childService.safeDIBuilder ?? ChildService.customMock(engine:))(engine)
		        }
		        let childService: ChildService = __safeDI_childService()
		        return Root(childService: childService)
		    }
		}
		#endif
		""", "Unexpected Root output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Engine {
		    struct SafeDIMockConfiguration {
		        init(
		            _ safeDIBuilder: (() -> Engine)? = nil
		        ) {
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let safeDIBuilder: (() -> Engine)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_typeWithUserMockAndOnlyDefaultValuedParamsGeneratesCallThrough_whenCustomMockNameIsSet() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: Service) { self.service = service }
				    @Instantiated let service: Service
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock") @MainActor
				public final class Service: Instantiable {
				    public init(
				        onCancel: @escaping @MainActor (String) -> Void = { _ in },
				        onSubmit: @escaping @MainActor (String) throws -> Void = { _ in }
				    ) {
				        self.onCancel = onCancel
				        self.onSubmit = onSubmit
				    }
				    public static func customMock() -> Self {
				        .init(onCancel: { _ in }, onSubmit: { _ in })
				    }
				    private let onCancel: @MainActor (String) -> Void
				    private let onSubmit: @MainActor (String) throws -> Void
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Service has customMockName — generated mock calls through to customMock().
		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Service+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Service {
		    static func mock() -> Service {
		        Service.customMock()
		    }
		}
		#endif

		#if DEBUG
		extension Service {
		    struct SafeDIMockConfiguration {
		        init(
		            _ safeDIBuilder: ((@escaping @MainActor (String) -> Void, @escaping @MainActor (String) throws -> Void) -> Service)? = nil
		        ) {
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let safeDIBuilder: ((@escaping @MainActor (String) -> Void, @escaping @MainActor (String) throws -> Void) -> Service)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Service+SafeDIMock.swift"] ?? "")")
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            service: Service.SafeDIMockConfiguration = .init()
		        ) {
		            self.service = service
		        }

		        let service: Service.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let service = (safeDIParameters.service.safeDIBuilder ?? Service.customMock(onCancel:onSubmit:))({ _ in }, { _ in })
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_userMockDependencyIsOptionalParameterWhenFulfillableFromTree() async throws {
		// Child has a user-defined mock() with a dep that IS constructible.
		// The dep should be an optional parameter with tree construction as default.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct Child: Instantiable {
				    public init(service: Service) { self.service = service }
				    @Instantiated let service: Service
				    public static func customMock(service: Service = Service()) -> Child {
				        Child(service: service)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Service: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            let service = (safeDIParameters.child.service.safeDIBuilder ?? Service.init)()
		            return (safeDIParameters.child.safeDIBuilder ?? Child.customMock(service:))(service)
		        }
		        let child: Child = __safeDI_child()
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_userMockDependencyBecomesRequiredParameterWhenNotFulfillable() async throws {
		// Child has a user-defined mock() with a dep from a dependent module.
		// The dep is constructible (via .safedi) but from another module.
		// It should be an optional parameter (constructible from .safedi).
		let crossModuleOutput = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable
				public struct ExternalService: Instantiable {
				    public init() {}
				}
				""",
			],
			filesToDelete: &filesToDelete,
		)

		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct Child: Instantiable {
				    public init(externalService: ExternalService) { self.externalService = externalService }
				    @Instantiated let externalService: ExternalService
				    public static func customMock(externalService: ExternalService = ExternalService()) -> Child {
				        Child(externalService: externalService)
				    }
				}
				""",
			],
			dependentModuleInfoPaths: [crossModuleOutput.moduleInfoOutputPath],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            let externalService = (safeDIParameters.child.externalService.safeDIBuilder ?? ExternalService.init)()
		            return (safeDIParameters.child.safeDIBuilder ?? Child.customMock(externalService:))(externalService)
		        }
		        let child: Child = __safeDI_child()
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ExternalService {
		    struct SafeDIMockConfiguration {
		        init(
		            _ safeDIBuilder: (() -> ExternalService)? = nil
		        ) {
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let safeDIBuilder: (() -> ExternalService)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_userMockOnlyIfAvailableDependencyUsesNilDefaultWhenNotFulfillable() async throws {
		// Child has @Received(onlyIfAvailable: true) dep. The mock() has it as optional.
		// At the root, it should be an optional parameter with nil default.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct Child: Instantiable {
				    public init(service: Service?) { self.service = service }
				    @Received(onlyIfAvailable: true) let service: Service?
				    public static func customMock(service: Service? = nil) -> Child {
				        Child(service: service)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Service: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            service: Service.SafeDIMockConfiguration? = nil,
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.service = service
		            self.child = child
		        }

		        let service: Service.SafeDIMockConfiguration?
		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let service: Service? = safeDIParameters.service.map { serviceConfiguration in
		            (serviceConfiguration.safeDIBuilder ?? Service.init)()
		        }
		        let child = (safeDIParameters.child.safeDIBuilder ?? Child.customMock(service:))(service)
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_userMockReturningAdditionalTypeUsedForProtocolProperty() async throws {
		// ChildService fulfills ChildServiceProtocol. Its mock returns the protocol type
		// and accepts a received dependency. Root's property is typed as the protocol.
		// The generator should use .mock for construction, threading the dependency through.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childService: ChildServiceProtocol, engine: Engine) {
				        self.childService = childService
				        self.engine = engine
				    }
				    @Instantiated let childService: ChildServiceProtocol
				    @Instantiated let engine: Engine
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ChildServiceProtocol.self], generateMock: true, customMockName: "customMock")
				public struct ChildService: ChildServiceProtocol, Instantiable {
				    public init(engine: Engine) { self.engine = engine }
				    @Received let engine: Engine
				    public static func customMock(engine: Engine) -> ChildServiceProtocol {
				        ChildService(engine: engine)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Engine: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            engine: Engine.SafeDIMockConfiguration = .init(),
		            childService: ChildService.SafeDIMockConfiguration = .init()
		        ) {
		            self.engine = engine
		            self.childService = childService
		        }

		        let engine: Engine.SafeDIMockConfiguration
		        let childService: ChildService.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let engine = (safeDIParameters.engine.safeDIBuilder ?? Engine.init)()
		        let childService = (safeDIParameters.childService.safeDIBuilder ?? ChildService.customMock(engine:))(engine)
		        return Root(childService: childService, engine: engine)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_userMockReturningAdditionalTypeNotUsedForConcreteProperty() async throws {
		// ChildService fulfills ChildServiceProtocol. Its mock returns the protocol type
		// and accepts a received dependency. Root's property is typed as the concrete type.
		// The generator should NOT use .mock and instead fall through to init,
		// threading the dependency through init's parameter list.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childService: ChildService, engine: Engine) {
				        self.childService = childService
				        self.engine = engine
				    }
				    @Instantiated let childService: ChildService
				    @Instantiated let engine: Engine
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ChildServiceProtocol.self], generateMock: true, customMockName: "customMock")
				public struct ChildService: ChildServiceProtocol, Instantiable {
				    public init(engine: Engine) { self.engine = engine }
				    @Received let engine: Engine
				    public static func customMock(engine: Engine) -> ChildServiceProtocol {
				        ChildService(engine: engine)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Engine: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            engine: Engine.SafeDIMockConfiguration = .init(),
		            childService: ChildService.SafeDIMockConfiguration = .init()
		        ) {
		            self.engine = engine
		            self.childService = childService
		        }

		        let engine: Engine.SafeDIMockConfiguration
		        let childService: ChildService.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let engine = (safeDIParameters.engine.safeDIBuilder ?? Engine.init)()
		        let childService = (safeDIParameters.childService.safeDIBuilder ?? ChildService.init(engine:))(engine)
		        return Root(childService: childService, engine: engine)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_extensionUserMockReturningAdditionalTypeUsedForProtocolProperty() async throws {
		// Extension-based ChildService fulfills ChildServiceProtocol. Its mock returns the protocol
		// type and accepts a received dependency. Root's property is typed as the protocol.
		// The generator should use .mock for construction, threading the dependency through.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childService: ChildServiceProtocol, engine: Engine) {
				        self.childService = childService
				        self.engine = engine
				    }
				    @Instantiated let childService: ChildServiceProtocol
				    @Instantiated let engine: Engine
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ChildServiceProtocol.self], generateMock: true, customMockName: "customMock")
				extension ChildService: Instantiable {
				    public static func instantiate(engine: Engine) -> ChildService { ChildService() }
				    public static func customMock(engine: Engine) -> ChildServiceProtocol {
				        ChildService()
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Engine: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            engine: Engine.SafeDIMockConfiguration = .init(),
		            childService: ChildService.SafeDIMockConfiguration = .init()
		        ) {
		            self.engine = engine
		            self.childService = childService
		        }

		        let engine: Engine.SafeDIMockConfiguration
		        let childService: ChildService.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let engine = (safeDIParameters.engine.safeDIBuilder ?? Engine.init)()
		        let childService = (safeDIParameters.childService.safeDIBuilder ?? ChildService.customMock(engine:))(engine)
		        return Root(childService: childService, engine: engine)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_extensionUserMockReturningAdditionalTypeNotUsedForConcreteProperty() async throws {
		// Extension-based ChildService fulfills ChildServiceProtocol. Its mock returns the protocol
		// type and accepts a received dependency. Root's property is typed as the concrete type.
		// The generator should NOT use .mock and instead fall through to instantiate(),
		// threading the dependency through instantiate's parameter list.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childService: ChildService, engine: Engine) {
				        self.childService = childService
				        self.engine = engine
				    }
				    @Instantiated let childService: ChildService
				    @Instantiated let engine: Engine
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ChildServiceProtocol.self], generateMock: true, customMockName: "customMock")
				extension ChildService: Instantiable {
				    public static func instantiate(engine: Engine) -> ChildService { ChildService() }
				    public static func customMock(engine: Engine) -> ChildServiceProtocol {
				        ChildService()
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Engine: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            engine: Engine.SafeDIMockConfiguration = .init(),
		            childService: ChildService.SafeDIMockConfiguration = .init()
		        ) {
		            self.engine = engine
		            self.childService = childService
		        }

		        let engine: Engine.SafeDIMockConfiguration
		        let childService: ChildService.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let engine = (safeDIParameters.engine.safeDIBuilder ?? Engine.init)()
		        let childService = (safeDIParameters.childService.safeDIBuilder ?? ChildService.instantiate(engine:))(engine)
		        return Root(childService: childService, engine: engine)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_generatedMockCallsThroughToHandWrittenMock() async throws {
		// Type has generateMock: true AND a hand-written mock with a dependency parameter.
		// The generated mock should call through to the hand-written .mock(dependency:).
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: Service) { self.service = service }
				    @Instantiated let service: Service
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct Service: Instantiable {
				    public init(engine: Engine) { self.engine = engine }
				    @Instantiated let engine: Engine
				    public static func customMock(engine: Engine) -> Service {
				        Service(engine: engine)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Engine: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Service+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Service {
		    struct SafeDIParameters {
		        init(
		            engine: Engine.SafeDIMockConfiguration = .init()
		        ) {
		            self.engine = engine
		        }

		        let engine: Engine.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Service {
		        let engine = (safeDIParameters.engine.safeDIBuilder ?? Engine.init)()
		        return Service.customMock(engine: engine)
		    }
		}
		#endif

		#if DEBUG
		extension Service {
		    struct SafeDIMockConfiguration {
		        init(
		            engine: Engine.SafeDIMockConfiguration = .init(),
		            _ safeDIBuilder: ((Engine) -> Service)? = nil
		        ) {
		            self.engine = engine
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let engine: Engine.SafeDIMockConfiguration
		        let safeDIBuilder: ((Engine) -> Service)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Service+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_generatedMockDoesNotExposeInitDefaultsNotOnHandWrittenMock() async throws {
		// Service has a default-valued init parameter (showDebugInfo) that the hand-written
		// mock does NOT expose. The generated mock should NOT bubble it up — the hand-written
		// mock controls which parameters are public.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: Service) { self.service = service }
				    @Instantiated let service: Service
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct Service: Instantiable {
				    public init(engine: Engine, showDebugInfo: Bool = false) {
				        self.engine = engine
				    }
				    @Instantiated let engine: Engine
				    public static func customMock(engine: Engine) -> Service {
				        Service(engine: engine)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Engine: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Service's generated mock should have `engine` (from hand-written mock) but NOT
		// `showDebugInfo` (init default not exposed by hand-written mock).
		#expect(output.mockFiles["Service+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Service {
		    struct SafeDIParameters {
		        init(
		            engine: Engine.SafeDIMockConfiguration = .init()
		        ) {
		            self.engine = engine
		        }

		        let engine: Engine.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Service {
		        let engine = (safeDIParameters.engine.safeDIBuilder ?? Engine.init)()
		        return Service.customMock(engine: engine)
		    }
		}
		#endif

		#if DEBUG
		extension Service {
		    struct SafeDIMockConfiguration {
		        init(
		            engine: Engine.SafeDIMockConfiguration = .init(),
		            _ safeDIBuilder: ((Engine) -> Service)? = nil
		        ) {
		            self.engine = engine
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let engine: Engine.SafeDIMockConfiguration
		        let safeDIBuilder: ((Engine) -> Service)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Service+SafeDIMock.swift"] ?? "")")

		// Root's generated mock should also NOT have showDebugInfo — it's hidden
		// behind Service's hand-written mock.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            service: Service.SafeDIMockConfiguration = .init()
		        ) {
		            self.service = service
		        }

		        let service: Service.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_service() -> Service {
		            let engine = (safeDIParameters.service.engine.safeDIBuilder ?? Engine.init)()
		            return (safeDIParameters.service.safeDIBuilder ?? Service.customMock(engine:))(engine)
		        }
		        let service: Service = __safeDI_service()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_generatedMockExposesHandWrittenMockExtraParams() async throws {
		// Service's hand-written mock has an extra non-dependency parameter (showDebugInfo)
		// with a default. The generated mock SHOULD expose it since the hand-written mock
		// chose to expose it.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: Service) { self.service = service }
				    @Instantiated let service: Service
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct Service: Instantiable {
				    public init(engine: Engine, showDebugInfo: Bool = false) {
				        self.engine = engine
				    }
				    @Instantiated let engine: Engine
				    public static func customMock(engine: Engine, showDebugInfo: Bool = false) -> Service {
				        Service(engine: engine, showDebugInfo: showDebugInfo)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Engine: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Service's generated mock should have both `engine` and `showDebugInfo`.
		#expect(output.mockFiles["Service+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Service {
		    struct SafeDIParameters {
		        init(
		            engine: Engine.SafeDIMockConfiguration = .init()
		        ) {
		            self.engine = engine
		        }

		        let engine: Engine.SafeDIMockConfiguration
		    }

		    static func mock(
		        showDebugInfo: Bool = false,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Service {
		        let engine = (safeDIParameters.engine.safeDIBuilder ?? Engine.init)()
		        return Service.customMock(engine: engine, showDebugInfo: showDebugInfo)
		    }
		}
		#endif

		#if DEBUG
		extension Service {
		    struct SafeDIMockConfiguration {
		        init(
		            engine: Engine.SafeDIMockConfiguration = .init(),
		            showDebugInfo: Bool = false,
		            _ safeDIBuilder: ((Engine, Bool) -> Service)? = nil
		        ) {
		            self.engine = engine
		            self.showDebugInfo = showDebugInfo
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let engine: Engine.SafeDIMockConfiguration
		        let showDebugInfo: Bool
		        let safeDIBuilder: ((Engine, Bool) -> Service)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Service+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_generatedMockCallsThroughToHandWrittenMockForExtension() async throws {
		// Extension-based type has generateMock: true AND a hand-written mock with a dependency.
		// The generated mock should call through to .mock(dependency:).
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: Service, engine: Engine) {
				        self.service = service
				        self.engine = engine
				    }
				    @Instantiated let service: Service
				    @Instantiated let engine: Engine
				}
				""",
				"""
				public struct Service {}

				@Instantiable(generateMock: true, customMockName: "customMock")
				extension Service: Instantiable {
				    public static func instantiate(engine: Engine) -> Service { Service() }
				    public static func customMock(engine: Engine) -> Service {
				        Service()
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Engine: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Service+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Service {
		    struct SafeDIParameters {
		        init(
		            engine: Engine.SafeDIMockConfiguration = .init()
		        ) {
		            self.engine = engine
		        }

		        let engine: Engine.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Service {
		        let engine = (safeDIParameters.engine.safeDIBuilder ?? Engine.init)()
		        return Service.customMock(engine: engine)
		    }
		}
		#endif

		#if DEBUG
		extension Service {
		    struct SafeDIMockConfiguration {
		        init(
		            _ safeDIBuilder: ((Engine) -> Service)? = nil
		        ) {
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let safeDIBuilder: ((Engine) -> Service)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Service+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_bubblesCustomMockDependencyDefault_whenForwardedPropertyReceivedByChild() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child, name: String) {
				        self.child = child
				        self.name = name
				    }
				    @Instantiated let child: Child
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct Child: Instantiable {
				    public init(name: String) {
				        self.name = name
				    }
				    @Received let name: String

				    public static func customMock(name: String = "hello") -> Child {
				        Child(name: name)
				    }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        name: String,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let child = (safeDIParameters.child.safeDIBuilder ?? Child.customMock(name:))(name)
		        return Root(child: child, name: name)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    static func mock(
		        name: String
		    ) -> Child {
		        return Child.customMock(name: name)
		    }
		}
		#endif

		#if DEBUG
		extension Child {
		    struct SafeDIMockConfiguration {
		        init(
		            _ safeDIBuilder: ((String) -> Child)? = nil
		        ) {
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let safeDIBuilder: ((String) -> Child)?
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_nearestReceiverDefaultWins_whenMultipleChildrenAtSameDepth() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB, name: String) {
				        self.childA = childA
				        self.childB = childB
				        self.name = name
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct ChildA: Instantiable {
				    public init(name: String) { self.name = name }
				    @Received let name: String
				    public static func customMock(name: String = "A") -> ChildA {
				        ChildA(name: name)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct ChildB: Instantiable {
				    public init(name: String) { self.name = name }
				    @Received let name: String
				    public static func customMock(name: String = "B") -> ChildB {
				        ChildB(name: name)
				    }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childA: ChildA.SafeDIMockConfiguration = .init(),
		            childB: ChildB.SafeDIMockConfiguration = .init()
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        let childA: ChildA.SafeDIMockConfiguration
		        let childB: ChildB.SafeDIMockConfiguration
		    }

		    static func mock(
		        name: String,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let childA = (safeDIParameters.childA.safeDIBuilder ?? ChildA.customMock(name:))(name)
		        let childB = (safeDIParameters.childB.safeDIBuilder ?? ChildB.customMock(name:))(name)
		        return Root(childA: childA, childB: childB, name: name)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_forwardedPropertyDefaultBubblesAcrossThreeLevels_eachWithCustomMock() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB, name: String) {
				        self.childA = childA
				        self.childB = childB
				        self.name = name
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct ChildA: Instantiable {
				    public init(grandchild: Grandchild, name: String) {
				        self.grandchild = grandchild
				        self.name = name
				    }
				    @Instantiated let grandchild: Grandchild
				    @Received let name: String
				    public static func customMock(grandchild: Grandchild, name: String = "childA") -> ChildA {
				        ChildA(grandchild: grandchild, name: name)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct Grandchild: Instantiable {
				    public init(name: String) { self.name = name }
				    @Received let name: String
				    public static func customMock(name: String = "grandchild") -> Grandchild {
				        Grandchild(name: name)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct ChildB: Instantiable {
				    public init(name: String) { self.name = name }
				    @Received let name: String
				    public static func customMock(name: String = "childB") -> ChildB {
				        ChildB(name: name)
				    }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 4)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childA: ChildA.SafeDIMockConfiguration = .init(),
		            childB: ChildB.SafeDIMockConfiguration = .init()
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        let childA: ChildA.SafeDIMockConfiguration
		        let childB: ChildB.SafeDIMockConfiguration
		    }

		    static func mock(
		        name: String,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childA() -> ChildA {
		            let grandchild = (safeDIParameters.childA.grandchild.safeDIBuilder ?? Grandchild.customMock(name:))(name)
		            return (safeDIParameters.childA.safeDIBuilder ?? ChildA.customMock(grandchild:name:))(grandchild, name)
		        }
		        let childA: ChildA = __safeDI_childA()
		        let childB = (safeDIParameters.childB.safeDIBuilder ?? ChildB.customMock(name:))(name)
		        return Root(childA: childA, childB: childB, name: name)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_doesNotBubbleDefault_whenNoChildHasCustomMock() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child, name: String) {
				        self.child = child
				        self.name = name
				    }
				    @Instantiated let child: Child
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(name: String) { self.name = name }
				    @Received let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        name: String,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let child = (safeDIParameters.child.safeDIBuilder ?? Child.init(name:))(name)
		        return Root(child: child, name: name)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_doesNotApplyDefaultFromWrongType_whenSameLabelDifferentTypes() async throws {
		// ChildA has `value: String` with a custom mock default.
		// ChildB has `value: Int` with no custom mock.
		// Both are @Instantiated children — their `value` properties are independent.
		// The `String` default from ChildA must NOT be applied to ChildB's `Int` parameter.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true, customMockName: "customMock")
				public struct ChildA: Instantiable {
				    public init(value: String) { self.value = value }
				    @Instantiated let value: String
				    public static func customMock(value: String = "hello") -> ChildA {
				        ChildA(value: value)
				    }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(value: Int) { self.value = value }
				    @Instantiated let value: Int
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct String: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Int: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 5)
		// ChildA's `value: String = "hello"` default must NOT bleed into ChildB's `value: Int`.
		// Both children should have subtree construction (T? = nil pattern).
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childA: ChildA.SafeDIMockConfiguration = .init(),
		            childB: ChildB.SafeDIMockConfiguration = .init()
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        let childA: ChildA.SafeDIMockConfiguration
		        let childB: ChildB.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childA() -> ChildA {
		            let value = (safeDIParameters.childA.value.safeDIBuilder ?? String.init)()
		            return (safeDIParameters.childA.safeDIBuilder ?? ChildA.customMock(value:))(value)
		        }
		        let childA: ChildA = __safeDI_childA()
		        func __safeDI_childB() -> ChildB {
		            let value = (safeDIParameters.childB.value.safeDIBuilder ?? Int.init)()
		            return (safeDIParameters.childB.safeDIBuilder ?? ChildB.init(value:))(value)
		        }
		        let childB: ChildB = __safeDI_childB()
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_customMockUncoveredDependencyBecomesBuilderArgument() async throws {
		// Child has a custom mock that takes an @Instantiated dep (Engine) whose type
		// is NOT in the scope map (cross-module). The generated builder call for the
		// child should pass the dep, which must be a flat parameter on mock().
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(engine: Engine, name: String = "default") {
				        self.engine = engine
				    }
				    @Instantiated let engine: Engine

				    public static func mock(
				        engine: Engine,
				        name: String = "default"
				    ) -> Child {
				        Child(engine: engine, name: name)
				    }
				}
				""",
				// Engine is NOT @Instantiable — simulates cross-module type.
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// `engine` must appear as a flat required parameter on Root.mock() since it's
		// an uncovered @Instantiated dep surfaced through Child's custom mock.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        engine: Engine,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            return (safeDIParameters.child.safeDIBuilder ?? Child.mock(engine:name:))(engine, safeDIParameters.child.name)
		        }
		        let child: Child = __safeDI_child()
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	// MARK: Private

	private var filesToDelete: [URL]
}
