// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Foundation
import SafeDICore
import Testing
@testable import SafeDITool

struct SafeDIToolMockGenerationConfigurationTests: ~Copyable {
	// MARK: Initialization

	init() throws {
		filesToDelete = [URL]()
	}

	deinit {
		for fileToDelete in filesToDelete {
			try! FileManager.default.removeItem(at: fileToDelete)
		}
	}

	// MARK: Tests – SafeDI configuration

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_respectsMockConditionalCompilationNil() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				#SafeDIConfiguration(
				    mockConditionalCompilation: nil
				)
				""",
				"""
				@Instantiable(generateMock: true)
				public struct NoBranch: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["NoBranch+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension NoBranch {
		    static func mock() -> NoBranch {
		        NoBranch()
		    }
		}
		""", "Unexpected output \(output.mockFiles["NoBranch+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_respectsCustomMockConditionalCompilation() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				#SafeDIConfiguration(
				    mockConditionalCompilation: "TESTING"
				)
				""",
				"""
				@Instantiable(generateMock: true)
				public struct CustomFlag: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["CustomFlag+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if TESTING
		extension CustomFlag {
		    static func mock() -> CustomFlag {
		        CustomFlag()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["CustomFlag+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_typeWithDependenciesAndNilConditionalCompilation() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				#SafeDIConfiguration(
				    mockConditionalCompilation: nil
				)
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(dependency: Dependency) {
				        self.dependency = dependency
				    }
				    @Instantiated let dependency: Dependency
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Dependency: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Dependency+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Dependency {
		    static func mock() -> Dependency {
		        Dependency()
		    }
		}
		""", "Unexpected output \(output.mockFiles["Dependency+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Root {
		    struct SafeDIParameters {
		        init(
		            dependency: (() -> Dependency)? = nil
		        ) {
		            self.dependency = dependency
		        }

		        let dependency: (() -> Dependency)?
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let dependency = (safeDIParameters.dependency ?? Dependency.init)()
		        return Root(dependency: dependency)
		    }
		}
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_respectsMockAttributes() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(mockAttributes: "@MainActor", generateMock: true)
				public struct ActorBound: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["ActorBound+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ActorBound {
		    @MainActor static func mock() -> ActorBound {
		        ActorBound()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["ActorBound+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_extensionBasedWithNilConditionalCompilation() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				#SafeDIConfiguration(
				    mockConditionalCompilation: nil
				)
				""",
				"""
				public class ThirdParty {}

				@Instantiable(generateMock: true)
				extension ThirdParty: Instantiable {
				    public static func instantiate() -> ThirdParty {
				        ThirdParty()
				    }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["ThirdParty+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension ThirdParty {
		    static func mock() -> ThirdParty {
		        ThirdParty.instantiate()
		    }
		}
		""", "Unexpected output \(output.mockFiles["ThirdParty+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_extensionBasedTypeRespectsMockAttributes() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public class ExternalService {}

				@Instantiable(mockAttributes: "@MainActor", generateMock: true)
				extension ExternalService {
				    public static func instantiate() -> ExternalService {
				        ExternalService()
				    }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["ExternalService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ExternalService {
		    @MainActor static func mock() -> ExternalService {
		        ExternalService.instantiate()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["ExternalService+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_generatedForType_whenGenerateMockIsTrue() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct OptedIn: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["OptedIn+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension OptedIn {
		    static func mock() -> OptedIn {
		        OptedIn()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["OptedIn+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_generatedForType_whenEnableMockGenerationIsTrue() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct DefaultType: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// With generateMock: true, the type gets a mock.
		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["DefaultType+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension DefaultType {
		    static func mock() -> DefaultType {
		        DefaultType()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["DefaultType+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_notGeneratedForType_whenGenerateMockIsDefault() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable
				public struct NoMock: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.isEmpty)
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_notGeneratedForType_whenGenerateMockIsFalse() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: false)
				public struct NoMock: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.isEmpty)
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_generatedOnlyForOptedInTypes_whenMixOfGenerateMockValues() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct OptedIn: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable
				public struct DefaultType: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: false)
				public struct OptedOut: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["OptedIn+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension OptedIn {
		    static func mock() -> OptedIn {
		        OptedIn()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["OptedIn+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_crossModuleTypeWithGenerateMockIsSkipped() async throws {
		// CrossModuleService has generateMock: true, but its source file belongs
		// to the dependent module. The consuming module must NOT generate a mock
		// for it — that's the dependent module's responsibility.
		let crossModuleOutput = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct CrossModuleService: Instantiable {
				    public init() {}
				}
				""",
			],
			filesToDelete: &filesToDelete,
		)

		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(crossModuleService: CrossModuleService) {
				        self.crossModuleService = crossModuleService
				    }
				    @Instantiated let crossModuleService: CrossModuleService
				}
				""",
			],
			dependentModuleInfoPaths: [crossModuleOutput.moduleInfoOutputPath],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Root mock should exist.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            crossModuleService: (() -> CrossModuleService)? = nil
		        ) {
		            self.crossModuleService = crossModuleService
		        }

		        let crossModuleService: (() -> CrossModuleService)?
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let crossModuleService = (safeDIParameters.crossModuleService ?? CrossModuleService.init)()
		        return Root(crossModuleService: crossModuleService)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		// CrossModuleService mock must NOT be generated by this module.
		#expect(output.mockFiles["CrossModuleService+SafeDIMock.swift"] == nil,
		        "Cross-module type should not have a mock generated in consuming module")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_configurationFileGeneratedWithoutConditionalCompilation_whenMockConditionalCompilationIsNil() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				#SafeDIConfiguration(
				    mockConditionalCompilation: nil
				)
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(leaf: Leaf) {
				        self.leaf = leaf
				    }
				    @Instantiated let leaf: Leaf
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Leaf: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Root {
		    struct SafeDIParameters {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let child = Child.__safeDI_mockBuild(safeDIMockConfiguration: safeDIParameters.child)
		        return Root(child: child)
		    }
		}
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Child {
		    struct SafeDIMockConfiguration {
		        init(
		            leaf: (() -> Leaf)? = nil,
		            _ safeDIBuilder: ((Leaf) -> Child)? = nil
		        ) {
		            self.leaf = leaf
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let leaf: (() -> Leaf)?
		        let safeDIBuilder: ((Leaf) -> Child)?
		    }

		    static func __safeDI_mockBuild(
		        safeDIMockConfiguration: SafeDIMockConfiguration
		    ) -> Child {
		        let leaf = (safeDIMockConfiguration.leaf ?? Leaf.init)()
		        return (safeDIMockConfiguration.safeDIBuilder ?? Child.init(leaf:))(leaf)
		    }
		}

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	// MARK: Tests – additionalMocksToGenerate

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_additionalMocksToGenerateProducesMockForCrossModuleType() async throws {
		// CrossModuleService is defined in a dependent module without generateMock: true.
		let crossModuleOutput = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable
				public struct CrossModuleService: Instantiable {
				    public init() {}
				}
				""",
			],
			filesToDelete: &filesToDelete,
		)

		// Current module uses additionalMocksToGenerate to request a mock for CrossModuleService.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				#SafeDIConfiguration(
				    additionalMocksToGenerate: [
				        "CrossModuleService",
				    ]
				)
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(crossModuleService: CrossModuleService) {
				        self.crossModuleService = crossModuleService
				    }
				    @Instantiated let crossModuleService: CrossModuleService
				}
				""",
			],
			dependentModuleInfoPaths: [crossModuleOutput.moduleInfoOutputPath],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["CrossModuleService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension CrossModuleService {
		    static func mock() -> CrossModuleService {
		        CrossModuleService()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["CrossModuleService+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            crossModuleService: (() -> CrossModuleService)? = nil
		        ) {
		            self.crossModuleService = crossModuleService
		        }

		        let crossModuleService: (() -> CrossModuleService)?
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let crossModuleService = (safeDIParameters.crossModuleService ?? CrossModuleService.init)()
		        return Root(crossModuleService: crossModuleService)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	// MARK: Private

	private var filesToDelete: [URL]
}
