// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Foundation
import SafeDICore
import Testing
@testable import SafeDITool

struct SafeDIToolMockOnlyTests: ~Copyable {
	// MARK: Initialization

	init() throws {
		filesToDelete = [URL]()
	}

	deinit {
		for fileToDelete in filesToDelete {
			try! FileManager.default.removeItem(at: fileToDelete)
		}
	}

	// MARK: Tests

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesDefaultFromMockOnlyExtension_whenForwardedPropertyHasMockOnlyDeclaration() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(name: String) {
				        self.name = name
				    }
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension String {
				    public static func mock() -> String { "" }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        name: String = String.mock()
		    ) -> Root {
		        return Root(name: name)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesDefaultFromMockOnlyExtension_whenPrimitiveTypeHasMockOnlyDeclaration() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(count: Int) {
				        self.count = count
				    }
				    @Forwarded let count: Int
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension Int {
				    public static func mock() -> Int { 0 }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        count: Int = Int.mock()
		    ) -> Root {
		        return Root(count: count)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesDefaultFromMockOnlyExtension_whenInstantiatedPropertyHasMockOnlyDeclaration() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ExternalService) {
				        self.service = service
				    }
				    @Instantiated let service: ExternalService
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension ExternalService {
				    public static func mock() -> ExternalService { fatalError() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> ExternalService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> ExternalService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? ExternalService.mock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesCustomMockName_whenMockOnlyTypeHasCustomMockName() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(name: String) {
				        self.name = name
				    }
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "testValue")
				extension String {
				    public static func testValue() -> String { "test" }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        name: String = String.testValue()
		    ) -> Root {
		        return Root(name: name)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_mergesMockOnlyDeclarationWithRegularExtension_whenBothExistForSameType() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				public struct MyService {
				    public static func mock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(conformsElsewhere: true)
				extension MyService: Instantiable {
				    public static func instantiate() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.mock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_mergesRegularDeclarationWithMockOnlyExtension_whenBothExistForSameType() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension MyService {
				    public static func mock() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.mock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesDefaultFromMergedMockOnlyProvider_whenForwardedPropertyTypeHasSeparateMockOnlyAndProductionDeclarations() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Forwarded let service: MyService
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true)
				extension MyService {
				    public static func mock() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        service: MyService = MyService.mock()
		    ) -> Root {
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesCustomMockNameFromMergedMockOnlyProvider_whenForwardedPropertyTypeHasSeparateDeclarations() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Forwarded let service: MyService
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        service: MyService = MyService.preview()
		    ) -> Root {
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesCustomMockNameFromMergedMockOnlyProvider_whenInstantiatedPropertyTypeHasSeparateDeclarations() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.preview)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesCustomMockName_whenProductionHasAdditionalTypeThatMockOnlyDoesNotRepeat() async throws {
		// Production fulfills both MyService and ServiceProtocol.
		// MockOnly only declares MyService. The merged entry (under MyService key)
		// has mock info, but the unmerged entry (under ServiceProtocol key) does not.
		// The scope map must use the merged entry for both.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ServiceProtocol) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceProtocol
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self])
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.preview)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	// MARK: Production Isolation Tests

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func productionCodeUnchanged_whenMockOnlyMergeAddsHandWrittenMock() async throws {
		// Generate production code WITHOUT mockOnly.
		let baselineOutput = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Generate production code WITH a mockOnly merge for Child.
		let mergedOutput = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension Child {
				    public static func preview() -> Child { Child() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Production output must be identical — mockOnly must not leak.
		#expect(
			baselineOutput.dependencyTreeFiles == mergedOutput.dependencyTreeFiles,
			"Production code changed after mockOnly merge. Baseline: \(baselineOutput.dependencyTreeFiles). Merged: \(mergedOutput.dependencyTreeFiles)",
		)
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func productionCodeUnchanged_whenMockOnlyMergeAddsHandWrittenMockWithMockAttributes() async throws {
		// Generate production code WITHOUT mockOnly.
		let baselineOutput = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Generate production code WITH a mockOnly merge that includes mockAttributes.
		let mergedOutput = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true)
				public struct Root: Instantiable {
				    public init(child: Child) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable
				public struct Child: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true, mockAttributes: "@MainActor")
				extension Child {
				    @MainActor public static func mock() -> Child { Child() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Production output must be identical.
		#expect(
			baselineOutput.dependencyTreeFiles == mergedOutput.dependencyTreeFiles,
			"Production code changed after mockOnly merge with mockAttributes. Baseline: \(baselineOutput.dependencyTreeFiles). Merged: \(mergedOutput.dependencyTreeFiles)",
		)
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_omitsDefaultForForwardedParameter_whenHandWrittenMockHasRequiredParameters() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Forwarded let service: MyService
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable {
				    public init(name: String) {
				        self.name = name
				    }
				    @Received let name: String
				    public static func mock(name: String) -> MyService { MyService(name: name) }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        service: MyService
		    ) -> Root {
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesProductionConcreteType_whenMockOnlyAlsoFulfillsSameAdditionalType() async throws {
		// Both ConcreteService and MockService fulfill AnyService via fulfillingAdditionalTypes.
		// MockService is mockOnly. Production code should use ConcreteService without error.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public class AnyService {
				    public init(_ value: some Any) {}
				}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: AnyService) {
				        self.service = service
				    }
				    @Instantiated let service: AnyService
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [AnyService.self])
				public struct ConcreteService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [AnyService.self], mockOnly: true)
				public struct MockService: Instantiable {
				    public init() {}
				    public static func mock() -> MockService { MockService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Production code uses ConcreteService (the non-mockOnly type).
		#expect(output.dependencyTreeFiles["Root+SafeDI.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Root {
		    public init() {
		        let service: AnyService = ConcreteService()
		        self.init(service: service)
		    }
		}
		""", "Unexpected output \(output.dependencyTreeFiles["Root+SafeDI.swift"] ?? "")")

		// Mock code uses MockService (the mockOnly type takes priority in the
		// mock scope map over the production ConcreteService).
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MockService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MockService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MockService.mock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersMockOnlyHandWrittenMock_whenProductionOnlyHasGenerateMockForSameAdditionalType() async throws {
		// MockService (mockOnly) has a hand-written mock. ConcreteService has
		// generateMock (which wraps init). Hand-written mock takes priority.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public class AnyService {
				    public init(_ value: some Any) {}
				}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: AnyService) {
				        self.service = service
				    }
				    @Instantiated let service: AnyService
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [AnyService.self], generateMock: true)
				public struct ConcreteService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [AnyService.self], mockOnly: true)
				public struct MockService: Instantiable {
				    public init() {}
				    public static func mock() -> MockService { MockService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Production code uses ConcreteService (mockOnly is excluded from production).
		#expect(output.dependencyTreeFiles["Root+SafeDI.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		extension Root {
		    public init() {
		        let service: AnyService = ConcreteService()
		        self.init(service: service)
		    }
		}
		""", "Unexpected output \(output.dependencyTreeFiles["Root+SafeDI.swift"] ?? "")")

		// Mock uses MockService.mock (hand-written mock wins over generateMock).
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MockService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MockService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MockService.mock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesMockOnlyFallback_whenFulfilledByTypeNotVisible() async throws {
		// When the fulfilledByType concrete type (ConcreteService) is not visible,
		// but a mockOnly type fulfills the declared type (AnyService),
		// mock generation should use the mockOnly type — matching the behavior
		// of plain @Instantiated when the concrete type isn't in the scope map.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public class AnyService {
				    public init(_ value: some Any) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(service: AnyService) {
				        self.service = service
				    }
				    @Instantiated(fulfilledByType: "ConcreteService", erasedToConcreteExistential: true) let service: AnyService
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [AnyService.self], mockOnly: true)
				public struct MockService: Instantiable {
				    public init() {}
				    public static func mock() -> MockService { MockService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 1)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MockService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MockService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = AnyService((safeDIOverrides.service ?? MockService.mock)())
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == emptyMockConfigurationFileOutput, "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesFulfillingType_whenFulfilledByTypeIsVisibleAndMockOnlyAlsoFulfillsDeclaredType() async throws {
		// When the fulfilledByType concrete type IS visible, it should be used
		// even if a mockOnly also fulfills the declared type. No fallback needed.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public class AnyService {
				    public init(_ value: some Any) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(service: AnyService) {
				        self.service = service
				    }
				    @Instantiated(fulfilledByType: "ConcreteService", erasedToConcreteExistential: true) let service: AnyService
				}
				""",
				"""
				@Instantiable
				public struct ConcreteService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [AnyService.self], mockOnly: true)
				public struct MockService: Instantiable {
				    public init() {}
				    public static func mock() -> MockService { MockService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// ConcreteService is visible, so the mock uses it — no fallback to MockService.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> ConcreteService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> ConcreteService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = AnyService((safeDIOverrides.service ?? ConcreteService.init)())
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesMockOnlyAdditionalType_whenMockOnlyHasAdditionalTypeProductionDoesNot() async throws {
		// Production fulfills only MyService. MockOnly fulfills MyService and
		// ServiceProtocol. A root referencing ServiceProtocol should get the
		// mockOnly scope.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ServiceProtocol) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceProtocol
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// The mock should use MyService.preview (from the mockOnly) for ServiceProtocol.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.preview)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesMockOnlyMock_whenProductionHasGenerateMockAndMockOnlyHasExtraAdditionalType() async throws {
		// The mockOnly's hand-written mock takes priority over generateMock.
		// The generated mock calls through to preview().
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension MyService {
		    static func mock() -> MyService {
		        MyService.preview()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["MyService+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesMockOnlyMock_whenProductionHasGenerateMockForSameType() async throws {
		// B+X: production has generateMock, mockOnly has customMockName "preview".
		// The mockOnly's hand-written mock wins — the generated mock calls through
		// to preview() since hand-written mocks take priority over generated ones.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct MyService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// MyService's generated mock calls through to preview (the mockOnly's method).
		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension MyService {
		    static func mock() -> MyService {
		        MyService.preview()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["MyService+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.preview)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersHandWrittenMock_whenMockOnlyAlsoExistsForSameType() async throws {
		// C+X: production has hand-written mock, mockOnly for same concrete type.
		// The parent's generated mock should call the production mock (customMock),
		// not the mockOnly's method (preview).
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable(customMockName: "customMock")
				public struct MyService: Instantiable {
				    public init() {}
				    public static func customMock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.customMock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesMockOnlyMock_whenProductionHasGenerateMockForSameType_reversedOrder() async throws {
		// Same as above but with reversed source file order.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct MyService: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension MyService {
		    static func mock() -> MyService {
		        MyService.preview()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["MyService+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.preview)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	// MARK: Tests – generateMock + mockOnly additional-type gaps

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_generatesForMockOnlyAdditionalType_whenProductionHasGenerateMockButDoesNotFulfillAdditionalType() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ServiceProtocol) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceProtocol
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension MyService {
		    static func mock() -> MyService {
		        MyService.preview()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["MyService+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.preview)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesMockOnlyMock_whenProductionHasGenerateMockAndExtraAdditionalType() async throws {
		// B+W: production has generateMock + fulfillingAdditionalTypes, mockOnly
		// for concrete type only. Hand-written mock wins over generateMock.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ServiceProtocol) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceProtocol
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], generateMock: true)
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension MyService {
		    static func mock() -> MyService {
		        MyService.preview()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["MyService+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.preview)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesMockOnlyMock_whenProductionHasGenerateMockAndExtraAdditionalType_referencedByConcrete() async throws {
		// B+W, ref by concrete: same as above but parent references MyService directly.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], generateMock: true)
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["MyService+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension MyService {
		    static func mock() -> MyService {
		        MyService.preview()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["MyService+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.preview)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_forwardedDefaultUsesMockOnlyMethod_whenProductionHasGenerateMock() async throws {
		// The mockOnly's hand-written mock merges in and provides the forwarded
		// default, since hand-written mocks take priority over generateMock.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Forwarded let service: MyService
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        service: MyService = MyService.preview()
		    ) -> Root {
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_forwardedDefaultUsesHandWrittenMock_notStaleMockOnlyMethod_whenProductionHasHandWrittenMock() async throws {
		// Mirror of the generateMock test but with a hand-written mock.
		// The stale mockOnly's customMockName must not leak into forwarded defaults.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Forwarded let service: MyService
				}
				""",
				"""
				@Instantiable
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				    public static func mock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// The forwarded default should use MyService.mock() (production's
		// hand-written mock), not MyService.preview() (from the ignored mockOnly).
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    static func mock(
		        service: MyService = MyService.mock()
		    ) -> Root {
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	// MARK: Tests – hand-written mock + mockOnly additional-type gaps

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersHandWrittenMock_whenBothFulfillSameAdditionalType() async throws {
		// C+Y: production has hand-written mock, both fulfill ServiceProtocol.
		// Root references ServiceProtocol — should use customMock, not preview.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ServiceProtocol) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceProtocol
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], customMockName: "customMock")
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				    public static func customMock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.customMock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersHandWrittenMock_whenBothFulfillSameAdditionalType_referencedByConcrete() async throws {
		// C+Y, ref by concrete — should use customMock, not preview.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], customMockName: "customMock")
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				    public static func customMock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.customMock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersHandWrittenMock_whenMockOnlyHasExtraAdditionalType() async throws {
		// C+Z: production has hand-written mock, mockOnly adds extra additional type.
		// Root references MyService directly — should use customMock, not preview.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable(customMockName: "customMock")
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				    public static func customMock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.customMock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersHandWrittenMock_whenMockOnlyHasExtraAdditionalType_referencedByMockOnlyAdditionalType() async throws {
		// C+Z, ref by mockOnly additional: parent references ServiceProtocol
		// (only fulfilled by mockOnly). Should use customMock, not preview.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ServiceProtocol) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceProtocol
				}
				""",
				"""
				@Instantiable(customMockName: "customMock")
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				    public static func customMock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.customMock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersHandWrittenMock_whenProductionHasExtraAdditionalType() async throws {
		// C+W: production has hand-written mock + extra additional type, mockOnly for concrete only.
		// Root references ServiceProtocol — should use customMock, not preview.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: ServiceProtocol) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceProtocol
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], customMockName: "customMock")
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				    public static func customMock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.customMock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_prefersHandWrittenMock_whenProductionHasExtraAdditionalType_referencedByConcrete() async throws {
		// C+W, ref by concrete — should use customMock, not preview.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				public protocol ServiceProtocol {}
				""",
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(service: MyService) {
				        self.service = service
				    }
				    @Instantiated let service: MyService
				}
				""",
				"""
				@Instantiable(fulfillingAdditionalTypes: [ServiceProtocol.self], customMockName: "customMock")
				public struct MyService: Instantiable, ServiceProtocol {
				    public init() {}
				    public static func customMock() -> MyService { MyService() }
				}
				""",
				"""
				@Instantiable(mockOnly: true, customMockName: "preview")
				extension MyService {
				    public static func preview() -> MyService { MyService() }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            service: (() -> MyService)? = nil
		        ) {
		            self.service = service
		        }

		        let service: (() -> MyService)?
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Root {
		        let service = (safeDIOverrides.service ?? MyService.customMock)()
		        return Root(service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	// MARK: Private

	private var filesToDelete = [URL]()
}
