// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Foundation
import Testing
@testable import SafeDITool

struct SafeDIToolMockGenerationMockOnlyTests: ~Copyable {
	init() throws {
		filesToDelete = [URL]()
	}

	deinit {
		for fileToDelete in filesToDelete {
			try! FileManager.default.removeItem(at: fileToDelete)
		}
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_doesNotBubbleMockOnlyDependencies_whenMockOnlyTypeFulfillsInstantiatedProperty() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(child: Child) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(external: External) {
				        self.external = external
				    }
				    @Instantiated let external: External
				}
				""",
				"""
				public struct External {
				    public init() {}
				}

				@Instantiable(mockOnly: true, conformsElsewhere: true)
				extension External {
				    public static func mock() -> External {
				        External()
				    }
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Parent+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Parent {
		    /// Overrides for the mock dependency tree.
		    struct SafeDIOverrides {
		        init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        let child: Child.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIOverrides: SafeDIOverrides = .init()
		    ) -> Parent {
		        func __safeDI_child() -> Child {
		            let external = (safeDIOverrides.child.external ?? External.mock)()
		            return (safeDIOverrides.child.safeDIBuilder ?? Child.init(external:))(external)
		        }
		        let child: Child = __safeDI_child()
		        return Parent(child: child)
		    }
		}
		#endif
		""")
	}

	private var filesToDelete: [URL]
}
