// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Foundation
import SafeDICore
import Testing
@testable import SafeDITool

struct SafeDIToolMockGenerationDisambiguationTests: ~Copyable {
	// MARK: Initialization

	init() throws {
		filesToDelete = [URL]()
	}

	deinit {
		for fileToDelete in filesToDelete {
			try! FileManager.default.removeItem(at: fileToDelete)
		}
	}

	// MARK: Tests – Parameter disambiguation

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatesParameters_whenInstantiatorLabelCollidesWithTypeName() async throws {
		// Root has @Instantiated let childB: ChildB (constant).
		// Root has @Instantiated let childA: ChildA, which has @Instantiated let childB: Instantiator<Other>.
		// The label "childB" collides between the constant and the Instantiator.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(childB: Instantiator<Other>) {
				        self.childB = childB
				    }
				    @Instantiated let childB: Instantiator<Other>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Other: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 4)

		#expect(output.mockFiles["ChildA+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildA {
		    struct SafeDIParameters {
		        init(
		            childB: (() -> Other)? = nil
		        ) {
		            self.childB = childB
		        }

		        let childB: (() -> Other)?
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> ChildA {
		        func __safeDI_childB() -> Other {
		            (safeDIParameters.childB ?? Other.init)()
		        }
		        let childB = Instantiator<Other>(__safeDI_childB)
		        return ChildA(childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["ChildA+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["ChildB+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildB {
		    static func mock() -> ChildB {
		        ChildB()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["ChildB+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Other+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Other {
		    static func mock() -> Other {
		        Other()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Other+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childA: ChildA.SafeDIMockConfiguration = .init(),
		            childB: (() -> ChildB)? = nil
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        let childA: ChildA.SafeDIMockConfiguration
		        let childB: (() -> ChildB)?
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childA() -> ChildA {
		            func __safeDI_childB() -> Other {
		                (safeDIParameters.childA.childB ?? Other.init)()
		            }
		            let childB = Instantiator<Other>(__safeDI_childB)
		            return (safeDIParameters.childA.safeDIBuilder ?? ChildA.init(childB:))(childB)
		        }
		        let childA: ChildA = __safeDI_childA()
		        let childB = (safeDIParameters.childB ?? ChildB.init)()
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildA {
		    struct SafeDIMockConfiguration {
		        init(
		            childB: (() -> Other)? = nil,
		            _ safeDIBuilder: ((Instantiator<Other>) -> ChildA)? = nil
		        ) {
		            self.childB = childB
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let childB: (() -> Other)?
		        let safeDIBuilder: ((Instantiator<Other>) -> ChildA)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatesParameterLabelsWhenSameInitLabelAppearsTwice() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(service: ServiceA) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceA
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(service: ServiceB) {
				        self.service = service
				    }
				    @Instantiated let service: ServiceB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ServiceA: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ServiceB: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Both ChildA and ChildB have `@Instantiated let service: ...` with different types.
		// The mock parameters must be disambiguated since both would otherwise be named `service`.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childA: ChildA.SafeDIMockConfiguration = .init(),
		            childB: ChildB.SafeDIMockConfiguration = .init()
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        let childA: ChildA.SafeDIMockConfiguration
		        let childB: ChildB.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childA() -> ChildA {
		            let service = (safeDIParameters.childA.service ?? ServiceA.init)()
		            return (safeDIParameters.childA.safeDIBuilder ?? ChildA.init(service:))(service)
		        }
		        let childA: ChildA = __safeDI_childA()
		        func __safeDI_childB() -> ChildB {
		            let service = (safeDIParameters.childB.service ?? ServiceB.init)()
		            return (safeDIParameters.childB.safeDIBuilder ?? ChildB.init(service:))(service)
		        }
		        let childB: ChildB = __safeDI_childB()
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildA {
		    struct SafeDIMockConfiguration {
		        init(
		            service: (() -> ServiceA)? = nil,
		            _ safeDIBuilder: ((ServiceA) -> ChildA)? = nil
		        ) {
		            self.service = service
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let service: (() -> ServiceA)?
		        let safeDIBuilder: ((ServiceA) -> ChildA)?
		    }
		}

		extension ChildB {
		    struct SafeDIMockConfiguration {
		        init(
		            service: (() -> ServiceB)? = nil,
		            _ safeDIBuilder: ((ServiceB) -> ChildB)? = nil
		        ) {
		            self.service = service
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let service: (() -> ServiceB)?
		        let safeDIBuilder: ((ServiceB) -> ChildB)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguationUsesSimplifiedSuffixWhenUnique() async throws {
		// Two children have `service` with different types. One is optional.
		// Simplified suffixes (stripping ?) are unique → use simplified.
		// service: ExternalService → service_ExternalService (not service_ExternalService)
		// service: LocalService? → service_LocalService (not service_LocalService_Optional)
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(service: ExternalService) { self.service = service }
				    @Received let service: ExternalService
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(service: LocalService?) { self.service = service }
				    @Received(onlyIfAvailable: true) let service: LocalService?
				}
				""",
				"""
				public struct ExternalService {}
				""",
				"""
				public struct LocalService {}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childA: ((ExternalService) -> ChildA)? = nil,
		            childB: ((LocalService?) -> ChildB)? = nil
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        let childA: ((ExternalService) -> ChildA)?
		        let childB: ((LocalService?) -> ChildB)?
		    }

		    static func mock(
		        service_ExternalService: ExternalService,
		        service_LocalService: LocalService? = nil,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let childA = (safeDIParameters.childA ?? ChildA.init(service:))(service)
		        let childB = (safeDIParameters.childB ?? ChildB.init(service:))(service)
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguationFallsBackToFullSuffixWhenSimplifiedCollides() async throws {
		// Two children have `service` — one is `Service` (non-optional),
		// one is `Service?` (optional). Simplified types are both `Service` → collision.
		// Must fall back to full suffix: service_Service vs service_Service_Optional.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(service: Service) { self.service = service }
				    @Instantiated let service: Service
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(service: Service?) { self.service = service }
				    @Received(onlyIfAvailable: true) let service: Service?
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Service: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childA: ChildA.SafeDIMockConfiguration = .init(),
		            childB: ((Service?) -> ChildB)? = nil
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        let childA: ChildA.SafeDIMockConfiguration
		        let childB: ((Service?) -> ChildB)?
		    }

		    static func mock(
		        service: Service? = nil,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childA() -> ChildA {
		            let service = (safeDIParameters.childA.service ?? Service.init)()
		            return (safeDIParameters.childA.safeDIBuilder ?? ChildA.init(service:))(service)
		        }
		        let childA: ChildA = __safeDI_childA()
		        let childB = (safeDIParameters.childB ?? ChildB.init(service:))(service)
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildA {
		    struct SafeDIMockConfiguration {
		        init(
		            service: (() -> Service)? = nil,
		            _ safeDIBuilder: ((Service) -> ChildA)? = nil
		        ) {
		            self.service = service
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let service: (() -> Service)?
		        let safeDIBuilder: ((Service) -> ChildA)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedParamUsedInInstantiatorBuilderFunction() async throws {
		// ChildA is built via Instantiator and @Receives presenter: PresenterA.
		// ChildB @Receives presenter: PresenterB (same label, different type).
		// Both "presenter" params get disambiguated. The Instantiator builder for ChildA
		// must pass presenter_PresenterA (not raw "presenter") to the init.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childABuilder: Instantiator<ChildA>, childB: ChildB) {
				        self.childABuilder = childABuilder
				        self.childB = childB
				    }
				    @Instantiated let childABuilder: Instantiator<ChildA>
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(name: String, presenter: PresenterA) {
				        self.name = name
				        self.presenter = presenter
				    }
				    @Forwarded let name: String
				    @Received let presenter: PresenterA
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(presenter: PresenterB) {
				        self.presenter = presenter
				    }
				    @Received let presenter: PresenterB
				}
				""",
				"""
				public struct PresenterA {}
				""",
				"""
				public struct PresenterB {}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childABuilder: ((String, PresenterA) -> ChildA)? = nil,
		            childB: ((PresenterB) -> ChildB)? = nil
		        ) {
		            self.childABuilder = childABuilder
		            self.childB = childB
		        }

		        let childABuilder: ((String, PresenterA) -> ChildA)?
		        let childB: ((PresenterB) -> ChildB)?
		    }

		    static func mock(
		        presenter_PresenterA: PresenterA,
		        presenter_PresenterB: PresenterB,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childABuilder(name: String) -> ChildA {
		            (safeDIParameters.childABuilder ?? ChildA.init(name:presenter:))(name, presenter)
		        }
		        let childABuilder = Instantiator<ChildA> {
		            __safeDI_childABuilder(name: $0)
		        }
		        let childB = (safeDIParameters.childB ?? ChildB.init(presenter:))(presenter)
		        return Root(childABuilder: childABuilder, childB: childB)
		    }
		}
		#endif
		""")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedInstantiatorBindingUsesDisambiguatedLocalName() async throws {
		// Two Instantiator children share label "childBuilder" but different types.
		// After disambiguation, the ?? binding local must use the disambiguated name.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(parent: Parent, childBuilder: Instantiator<ChildA>) {
				        self.parent = parent
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let parent: Parent
				    @Instantiated let childBuilder: Instantiator<ChildA>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(childBuilder: Instantiator<ChildB>) {
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let childBuilder: Instantiator<ChildB>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            parent: Parent.SafeDIMockConfiguration = .init(),
		            childBuilder: ((String) -> ChildA)? = nil
		        ) {
		            self.parent = parent
		            self.childBuilder = childBuilder
		        }

		        let parent: Parent.SafeDIMockConfiguration
		        let childBuilder: ((String) -> ChildA)?
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_parent() -> Parent {
		            func __safeDI_childBuilder(name: String) -> ChildB {
		                (safeDIParameters.parent.childBuilder ?? ChildB.init(name:))(name)
		            }
		            let childBuilder = Instantiator<ChildB> {
		                __safeDI_childBuilder(name: $0)
		            }
		            return (safeDIParameters.parent.safeDIBuilder ?? Parent.init(childBuilder:))(childBuilder)
		        }
		        let parent: Parent = __safeDI_parent()
		        func __safeDI_childBuilder(name: String) -> ChildA {
		            (safeDIParameters.childBuilder ?? ChildA.init(name:))(name)
		        }
		        let childBuilder = Instantiator<ChildA> {
		            __safeDI_childBuilder(name: $0)
		        }
		        return Root(parent: parent, childBuilder: childBuilder)
		    }
		}
		#endif
		""")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Parent {
		    struct SafeDIMockConfiguration {
		        init(
		            childBuilder: ((String) -> ChildB)? = nil,
		            _ safeDIBuilder: ((Instantiator<ChildB>) -> Parent)? = nil
		        ) {
		            self.childBuilder = childBuilder
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let childBuilder: ((String) -> ChildB)?
		        let safeDIBuilder: ((Instantiator<ChildB>) -> Parent)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedInstantiatorResolvedBySiblingInNestedBuilder() async throws {
		// ChildC and ChildD both have a dep named "childBuilder" but with different generic types.
		// At root, both are promoted → disambiguated. ChildC's builder must reference
		// childBuilder_Instantiator__ChildA (not childBuilder) since disambiguation occurred.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childC: ChildC, childD: ChildD) {
				        self.childC = childC
				        self.childD = childD
				    }
				    @Instantiated let childC: ChildC
				    @Instantiated let childD: ChildD
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildC: Instantiable {
				    public init(childBuilder: Instantiator<ChildA>) {
				        self.childBuilder = childBuilder
				    }
				    @Received let childBuilder: Instantiator<ChildA>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildD: Instantiable {
				    public init(childBuilder: Instantiator<ChildB>) {
				        self.childBuilder = childBuilder
				    }
				    @Received let childBuilder: Instantiator<ChildB>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childBuilder_ChildA: ((String) -> ChildA)? = nil,
		            childC: ((Instantiator<ChildA>) -> ChildC)? = nil,
		            childBuilder_ChildB: ((String) -> ChildB)? = nil,
		            childD: ((Instantiator<ChildB>) -> ChildD)? = nil
		        ) {
		            self.childBuilder_ChildA = childBuilder_ChildA
		            self.childC = childC
		            self.childBuilder_ChildB = childBuilder_ChildB
		            self.childD = childD
		        }

		        let childBuilder_ChildA: ((String) -> ChildA)?
		        let childC: ((Instantiator<ChildA>) -> ChildC)?
		        let childBuilder_ChildB: ((String) -> ChildB)?
		        let childD: ((Instantiator<ChildB>) -> ChildD)?
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childBuilder(name: String) -> ChildA {
		            (safeDIParameters.childBuilder_ChildA ?? ChildA.init(name:))(name)
		        }
		        let childBuilder = Instantiator<ChildA> {
		            __safeDI_childBuilder(name: $0)
		        }
		        let childC = (safeDIParameters.childC ?? ChildC.init(childBuilder:))(childBuilder)
		        func __safeDI_childBuilder(name: String) -> ChildB {
		            (safeDIParameters.childBuilder_ChildB ?? ChildB.init(name:))(name)
		        }
		        let childBuilder = Instantiator<ChildB> {
		            __safeDI_childBuilder(name: $0)
		        }
		        let childD = (safeDIParameters.childD ?? ChildD.init(childBuilder:))(childBuilder)
		        return Root(childC: childC, childD: childD)
		    }
		}
		#endif
		""")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedInstantiatorResolvedThroughIntermediateInstantiatorBuilder() async throws {
		// Root → parentBuilder (Instantiator<Parent>) + childBuilder (Instantiator<ChildA>).
		// Parent uses childBuilder (Instantiator<ChildA>) + also has otherBuilder (Instantiator<ChildB>)
		// with same label "childBuilder" — causing disambiguation at root.
		// Inside parentBuilder's function, Parent is constructed.
		// Parent's init references childBuilder → must be childBuilder_Instantiator__ChildA.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(parentBuilder: Instantiator<Parent>, childBuilder: Instantiator<ChildA>) {
				        self.parentBuilder = parentBuilder
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let parentBuilder: Instantiator<Parent>
				    @Instantiated let childBuilder: Instantiator<ChildA>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(childBuilder: Instantiator<ChildA>, otherBuilder: Instantiator<ChildB>) {
				        self.childBuilder = childBuilder
				        self.otherBuilder = otherBuilder
				    }
				    @Received let childBuilder: Instantiator<ChildA>
				    @Instantiated let otherBuilder: Instantiator<ChildB>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childBuilder: ((String) -> ChildA)? = nil,
		            parentBuilder: Parent.SafeDIMockConfiguration = .init()
		        ) {
		            self.childBuilder = childBuilder
		            self.parentBuilder = parentBuilder
		        }

		        let childBuilder: ((String) -> ChildA)?
		        let parentBuilder: Parent.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childBuilder(name: String) -> ChildA {
		            (safeDIParameters.childBuilder ?? ChildA.init(name:))(name)
		        }
		        let childBuilder = Instantiator<ChildA> {
		            __safeDI_childBuilder(name: $0)
		        }
		        func __safeDI_parentBuilder() -> Parent {
		            func __safeDI_otherBuilder(name: String) -> ChildB {
		                (safeDIParameters.parentBuilder.otherBuilder ?? ChildB.init(name:))(name)
		            }
		            let otherBuilder = Instantiator<ChildB> {
		                __safeDI_otherBuilder(name: $0)
		            }
		            return (safeDIParameters.parentBuilder.safeDIBuilder ?? Parent.init(childBuilder:otherBuilder:))(childBuilder, otherBuilder)
		        }
		        let parentBuilder = Instantiator<Parent>(__safeDI_parentBuilder)
		        return Root(parentBuilder: parentBuilder, childBuilder: childBuilder)
		    }
		}
		#endif
		""")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Parent {
		    struct SafeDIMockConfiguration {
		        init(
		            otherBuilder: ((String) -> ChildB)? = nil,
		            _ safeDIBuilder: ((Instantiator<ChildA>, Instantiator<ChildB>) -> Parent)? = nil
		        ) {
		            self.otherBuilder = otherBuilder
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let otherBuilder: ((String) -> ChildB)?
		        let safeDIBuilder: ((Instantiator<ChildA>, Instantiator<ChildB>) -> Parent)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedInstantiatorInDeepNestedBuilderUsesResolvedName() async throws {
		// Root has two children that each receive a different-typed builder with same label.
		// ChildA → receives builder: Instantiator<TypeA>
		// ChildB → has sub: SubChild which also receives builder: Instantiator<TypeA>
		// Both "builder" Instantiators get disambiguated at root.
		// Inside ChildB's SubChild construction, the resolved builder must use
		// the disambiguated name, not the original label.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childBBuilder: Instantiator<ChildB>) {
				        self.childA = childA
				        self.childBBuilder = childBBuilder
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childBBuilder: Instantiator<ChildB>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(builder: Instantiator<TypeA>) {
				        self.builder = builder
				    }
				    @Received let builder: Instantiator<TypeA>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(subChild: SubChild) {
				        self.subChild = subChild
				    }
				    @Instantiated let subChild: SubChild
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct SubChild: Instantiable {
				    public init(builder: Instantiator<TypeB>) {
				        self.builder = builder
				    }
				    @Received let builder: Instantiator<TypeB>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct TypeA: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct TypeB: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            builder_TypeA: ((String) -> TypeA)? = nil,
		            childA: ((Instantiator<TypeA>) -> ChildA)? = nil,
		            builder_TypeB: ((String) -> TypeB)? = nil,
		            childBBuilder: ChildB.SafeDIMockConfiguration = .init()
		        ) {
		            self.builder_TypeA = builder_TypeA
		            self.childA = childA
		            self.builder_TypeB = builder_TypeB
		            self.childBBuilder = childBBuilder
		        }

		        let builder_TypeA: ((String) -> TypeA)?
		        let childA: ((Instantiator<TypeA>) -> ChildA)?
		        let builder_TypeB: ((String) -> TypeB)?
		        let childBBuilder: ChildB.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_builder(name: String) -> TypeA {
		            (safeDIParameters.builder_TypeA ?? TypeA.init(name:))(name)
		        }
		        let builder = Instantiator<TypeA> {
		            __safeDI_builder(name: $0)
		        }
		        let childA = (safeDIParameters.childA ?? ChildA.init(builder:))(builder)
		        func __safeDI_builder(name: String) -> TypeB {
		            (safeDIParameters.builder_TypeB ?? TypeB.init(name:))(name)
		        }
		        let builder = Instantiator<TypeB> {
		            __safeDI_builder(name: $0)
		        }
		        func __safeDI_childBBuilder() -> ChildB {
		            let subChild = (safeDIParameters.childBBuilder.subChild ?? SubChild.init(builder:))(builder)
		            return (safeDIParameters.childBBuilder.safeDIBuilder ?? ChildB.init(subChild:))(subChild)
		        }
		        let childBBuilder = Instantiator<ChildB>(__safeDI_childBBuilder)
		        return Root(childA: childA, childBBuilder: childBBuilder)
		    }
		}
		#endif
		""")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildB {
		    struct SafeDIMockConfiguration {
		        init(
		            subChild: ((Instantiator<TypeB>) -> SubChild)? = nil,
		            _ safeDIBuilder: ((SubChild) -> ChildB)? = nil
		        ) {
		            self.subChild = subChild
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let subChild: ((Instantiator<TypeB>) -> SubChild)?
		        let safeDIBuilder: ((SubChild) -> ChildB)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedAutoclosureEvaluatedInInstantiatorBuilder() async throws {
		// Root has parentBuilder (Instantiator<Parent>) and childB: ChildB.
		// Parent @Receives config: ConfigA. ChildB @Receives config: ConfigB.
		// Same label "config", different types — both disambiguated as config_ConfigA, config_ConfigB.
		// Inside parentBuilder's function, config_ConfigA must be evaluated before constructing Parent.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(parentBuilder: Instantiator<Parent>, childB: ChildB) {
				        self.parentBuilder = parentBuilder
				        self.childB = childB
				    }
				    @Instantiated let parentBuilder: Instantiator<Parent>
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(name: String, config: ConfigA) {
				        self.name = name
				        self.config = config
				    }
				    @Forwarded let name: String
				    @Received let config: ConfigA
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(config: ConfigB) { self.config = config }
				    @Received let config: ConfigB
				}
				""",
				"""
				public struct ConfigA {}
				""",
				"""
				public struct ConfigB {}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            parentBuilder: ((String, ConfigA) -> Parent)? = nil,
		            childB: ((ConfigB) -> ChildB)? = nil
		        ) {
		            self.parentBuilder = parentBuilder
		            self.childB = childB
		        }

		        let parentBuilder: ((String, ConfigA) -> Parent)?
		        let childB: ((ConfigB) -> ChildB)?
		    }

		    static func mock(
		        config_ConfigA: ConfigA,
		        config_ConfigB: ConfigB,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_parentBuilder(name: String) -> Parent {
		            (safeDIParameters.parentBuilder ?? Parent.init(name:config:))(name, config)
		        }
		        let parentBuilder = Instantiator<Parent> {
		            __safeDI_parentBuilder(name: $0)
		        }
		        let childB = (safeDIParameters.childB ?? ChildB.init(config:))(config)
		        return Root(parentBuilder: parentBuilder, childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedUncoveredDependencyInNestedInstantiator() async throws {
		// Root @Instantiates parent: Parent and child: Child.
		// Parent @Receives engine: EngineA. Child @Receives engine: EngineB.
		// Same label "engine", different types — both uncovered (required mock params).
		// Both are disambiguated: engine_EngineA and engine_EngineB.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(parent: Parent, child: Child) {
				        self.parent = parent
				        self.child = child
				    }
				    @Instantiated let parent: Parent
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(engine: EngineA) { self.engine = engine }
				    @Received let engine: EngineA
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(engine: EngineB) { self.engine = engine }
				    @Received let engine: EngineB
				}
				""",
				"""
				public struct EngineA {}
				""",
				"""
				public struct EngineB {}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            parent: ((EngineA) -> Parent)? = nil,
		            child: ((EngineB) -> Child)? = nil
		        ) {
		            self.parent = parent
		            self.child = child
		        }

		        let parent: ((EngineA) -> Parent)?
		        let child: ((EngineB) -> Child)?
		    }

		    static func mock(
		        engine_EngineA: EngineA,
		        engine_EngineB: EngineB,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let parent = (safeDIParameters.parent ?? Parent.init(engine:))(engine)
		        let child = (safeDIParameters.child ?? Child.init(engine:))(engine)
		        return Root(parent: parent, child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_onlyIfAvailableDisambiguatedSimplifiedUnique() async throws {
		// ChildA @Receives service: ExternalService. ChildB @Receives(onlyIfAvailable: true) service: LocalService?.
		// Both share label "service" — disambiguated by type. Optional suffix stripped from
		// onlyIfAvailable dep: service_LocalService (not service_Optional_LocalService).
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(service: ExternalService) { self.service = service }
				    @Received let service: ExternalService
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(service: LocalService?) { self.service = service }
				    @Received(onlyIfAvailable: true) let service: LocalService?
				}
				""",
				"""
				public struct ExternalService {}
				""",
				"""
				public struct LocalService {}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childA: ((ExternalService) -> ChildA)? = nil,
		            childB: ((LocalService?) -> ChildB)? = nil
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        let childA: ((ExternalService) -> ChildA)?
		        let childB: ((LocalService?) -> ChildB)?
		    }

		    static func mock(
		        service_ExternalService: ExternalService,
		        service_LocalService: LocalService? = nil,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let childA = (safeDIParameters.childA ?? ChildA.init(service:))(service)
		        let childB = (safeDIParameters.childB ?? ChildB.init(service:))(service)
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_closureTypedDefaultDisambiguated() async throws {
		// ChildA has default-valued `onAction: @escaping () -> Void = {}`.
		// ChildB has default-valued `onAction: @escaping (String) -> Void = { _ in }`.
		// Same label "onAction", different closure types. Both are closure-typed defaults.
		// Disambiguated: onAction_Void_to_Void and onAction_String_to_Void (or similar suffix).
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(onAction: @escaping () -> Void = {}) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(onAction: @escaping (String) -> Void = { _ in }) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childA: ChildA.SafeDIMockConfiguration = .init(),
		            childB: ChildB.SafeDIMockConfiguration = .init()
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        let childA: ChildA.SafeDIMockConfiguration
		        let childB: ChildB.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childA() -> ChildA {
		            return (safeDIParameters.childA.safeDIBuilder ?? ChildA.init(onAction:))(safeDIParameters.childA.onAction)
		        }
		        let childA: ChildA = __safeDI_childA()
		        func __safeDI_childB() -> ChildB {
		            return (safeDIParameters.childB.safeDIBuilder ?? ChildB.init(onAction:))(safeDIParameters.childB.onAction)
		        }
		        let childB: ChildB = __safeDI_childB()
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildA {
		    struct SafeDIMockConfiguration {
		        init(
		            onAction: @escaping () -> Void = {},
		            _ safeDIBuilder: ((@escaping () -> Void) -> ChildA)? = nil
		        ) {
		            self.onAction = onAction
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let onAction: () -> Void
		        let safeDIBuilder: ((@escaping () -> Void) -> ChildA)?
		    }
		}

		extension ChildB {
		    struct SafeDIMockConfiguration {
		        init(
		            onAction: @escaping (String) -> Void = { _ in },
		            _ safeDIBuilder: ((@escaping (String) -> Void) -> ChildB)? = nil
		        ) {
		            self.onAction = onAction
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let onAction: (String) -> Void
		        let safeDIBuilder: ((@escaping (String) -> Void) -> ChildB)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatesAllParameters_whenThreeChildrenShareSameLabel() async throws {
		// Three children each receive "service" with a different type.
		// All three get disambiguated: service_ServiceA, service_ServiceB, service_ServiceC.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB, childC: ChildC) {
				        self.childA = childA
				        self.childB = childB
				        self.childC = childC
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				    @Instantiated let childC: ChildC
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(service: ServiceA) { self.service = service }
				    @Received let service: ServiceA
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(service: ServiceB) { self.service = service }
				    @Received let service: ServiceB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildC: Instantiable {
				    public init(service: ServiceC) { self.service = service }
				    @Received let service: ServiceC
				}
				""",
				"""
				public struct ServiceA {}
				""",
				"""
				public struct ServiceB {}
				""",
				"""
				public struct ServiceC {}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childA: ((ServiceA) -> ChildA)? = nil,
		            childB: ((ServiceB) -> ChildB)? = nil,
		            childC: ((ServiceC) -> ChildC)? = nil
		        ) {
		            self.childA = childA
		            self.childB = childB
		            self.childC = childC
		        }

		        let childA: ((ServiceA) -> ChildA)?
		        let childB: ((ServiceB) -> ChildB)?
		        let childC: ((ServiceC) -> ChildC)?
		    }

		    static func mock(
		        service_ServiceA: ServiceA,
		        service_ServiceB: ServiceB,
		        service_ServiceC: ServiceC,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let childA = (safeDIParameters.childA ?? ChildA.init(service:))(service)
		        let childB = (safeDIParameters.childB ?? ChildB.init(service:))(service)
		        let childC = (safeDIParameters.childC ?? ChildC.init(service:))(service)
		        return Root(childA: childA, childB: childB, childC: childC)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedInstantiatorResolvedFromRootInNestedScope() async throws {
		// Root @Instantiates childBuilder: Instantiator<ChildA> (disambiguated).
		// Root also @Instantiates parentBuilder: Instantiator<Parent>.
		// Parent @Instantiates childBuilder: Instantiator<ChildA> (same label+type as root).
		// Root also promotes childBuilder: Instantiator<ChildB> from another branch.
		// Both "childBuilder" get disambiguated at root.
		// Inside parentBuilder's function, Parent's childBuilder is resolved from root
		// (not re-constructed). It must use the disambiguated name.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(
				        childBuilder: Instantiator<ChildA>,
				        parentBuilder: Instantiator<Parent>,
				        other: Other
				    ) {
				        self.childBuilder = childBuilder
				        self.parentBuilder = parentBuilder
				        self.other = other
				    }
				    @Instantiated let childBuilder: Instantiator<ChildA>
				    @Instantiated let parentBuilder: Instantiator<Parent>
				    @Instantiated let other: Other
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Parent: Instantiable {
				    public init(childBuilder: Instantiator<ChildA>) {
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let childBuilder: Instantiator<ChildA>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Other: Instantiable {
				    public init(childBuilder: Instantiator<ChildB>) {
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let childBuilder: Instantiator<ChildB>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(name: String) { self.name = name }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childBuilder: ((String) -> ChildA)? = nil,
		            parentBuilder: Parent.SafeDIMockConfiguration = .init(),
		            other: Other.SafeDIMockConfiguration = .init()
		        ) {
		            self.childBuilder = childBuilder
		            self.parentBuilder = parentBuilder
		            self.other = other
		        }

		        let childBuilder: ((String) -> ChildA)?
		        let parentBuilder: Parent.SafeDIMockConfiguration
		        let other: Other.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childBuilder(name: String) -> ChildA {
		            (safeDIParameters.childBuilder ?? ChildA.init(name:))(name)
		        }
		        let childBuilder = Instantiator<ChildA> {
		            __safeDI_childBuilder(name: $0)
		        }
		        func __safeDI_parentBuilder() -> Parent {
		            func __safeDI_childBuilder(name: String) -> ChildA {
		                (safeDIParameters.parentBuilder.childBuilder ?? ChildA.init(name:))(name)
		            }
		            let childBuilder = Instantiator<ChildA> {
		                __safeDI_childBuilder(name: $0)
		            }
		            return (safeDIParameters.parentBuilder.safeDIBuilder ?? Parent.init(childBuilder:))(childBuilder)
		        }
		        let parentBuilder = Instantiator<Parent>(__safeDI_parentBuilder)
		        func __safeDI_other() -> Other {
		            func __safeDI_childBuilder(name: String) -> ChildB {
		                (safeDIParameters.other.childBuilder ?? ChildB.init(name:))(name)
		            }
		            let childBuilder = Instantiator<ChildB> {
		                __safeDI_childBuilder(name: $0)
		            }
		            return (safeDIParameters.other.safeDIBuilder ?? Other.init(childBuilder:))(childBuilder)
		        }
		        let other: Other = __safeDI_other()
		        return Root(childBuilder: childBuilder, parentBuilder: parentBuilder, other: other)
		    }
		}
		#endif
		""")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Parent {
		    struct SafeDIMockConfiguration {
		        init(
		            childBuilder: ((String) -> ChildA)? = nil,
		            _ safeDIBuilder: ((Instantiator<ChildA>) -> Parent)? = nil
		        ) {
		            self.childBuilder = childBuilder
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let childBuilder: ((String) -> ChildA)?
		        let safeDIBuilder: ((Instantiator<ChildA>) -> Parent)?
		    }
		}

		extension Other {
		    struct SafeDIMockConfiguration {
		        init(
		            childBuilder: ((String) -> ChildB)? = nil,
		            _ safeDIBuilder: ((Instantiator<ChildB>) -> Other)? = nil
		        ) {
		            self.childBuilder = childBuilder
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let childBuilder: ((String) -> ChildB)?
		        let safeDIBuilder: ((Instantiator<ChildB>) -> Other)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_postDisambiguationLabelDoesNotCollideWithExistingPropertyLabel() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB, childC: ChildC) {
				        self.childA = childA
				        self.childB = childB
				        self.childC = childC
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				    @Instantiated let childC: ChildC
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(service: UserService) {
				        self.service = service
				    }
				    @Received let service: UserService
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(service: AdminService) {
				        self.service = service
				    }
				    @Received let service: AdminService
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildC: Instantiable {
				    public init(service_UserService: OtherType) {
				        self.service_UserService = service_UserService
				    }
				    @Received let service_UserService: OtherType
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct UserService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct AdminService: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct OtherType: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// After disambiguation, "service" splits into "service_UserService" and "service_AdminService".
		// ChildC has a literal property labeled "service_UserService" — the disambiguated version
		// must get a further suffix to avoid colliding with the literal label.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            service_UserService: (() -> UserService)? = nil,
		            childA: ((UserService) -> ChildA)? = nil,
		            service_AdminService: (() -> AdminService)? = nil,
		            childB: ((AdminService) -> ChildB)? = nil,
		            service_UserService: (() -> OtherType)? = nil,
		            childC: ((OtherType) -> ChildC)? = nil
		        ) {
		            self.service_UserService = service_UserService
		            self.childA = childA
		            self.service_AdminService = service_AdminService
		            self.childB = childB
		            self.service_UserService = service_UserService
		            self.childC = childC
		        }

		        let service_UserService: (() -> UserService)?
		        let childA: ((UserService) -> ChildA)?
		        let service_AdminService: (() -> AdminService)?
		        let childB: ((AdminService) -> ChildB)?
		        let service_UserService: (() -> OtherType)?
		        let childC: ((OtherType) -> ChildC)?
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let service = (safeDIParameters.service_UserService ?? UserService.init)()
		        let childA = (safeDIParameters.childA ?? ChildA.init(service:))(service)
		        let service = (safeDIParameters.service_AdminService ?? AdminService.init)()
		        let childB = (safeDIParameters.childB ?? ChildB.init(service:))(service)
		        let service_UserService = (safeDIParameters.service_UserService ?? OtherType.init)()
		        let childC = (safeDIParameters.childC ?? ChildC.init(service_UserService:))(service_UserService)
		        return Root(childA: childA, childB: childB, childC: childC)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_aliasedBindingUsesDisambiguatedFulfillingPropertyLabel() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child, service: TypeA) {
				        self.child = child
				        self.service = service
				    }
				    @Instantiated let child: Child
				    @Instantiated let service: TypeA
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(service: TypeB, serviceAlias: TypeB) {
				        self.service = service
				        self.serviceAlias = serviceAlias
				    }
				    @Instantiated let service: TypeB
				    @Received(fulfilledByDependencyNamed: "service", ofType: TypeB.self, erasedToConcreteExistential: false) let serviceAlias: TypeB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct TypeA: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct TypeB: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Root has "service: TypeA" and Child has "service: TypeB" — the label "service"
		// collides at the root mock level, causing disambiguation to "service_TypeA" and
		// "service_TypeB". Child's alias (serviceAlias fulfilled by "service") must
		// reference the disambiguated "service_TypeB", not the raw "service".
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            service_TypeB: (() -> TypeB)? = nil,
		            child: Child.SafeDIMockConfiguration = .init(),
		            service_TypeA: (() -> TypeA)? = nil
		        ) {
		            self.service_TypeB = service_TypeB
		            self.child = child
		            self.service_TypeA = service_TypeA
		        }

		        let service_TypeB: (() -> TypeB)?
		        let child: Child.SafeDIMockConfiguration
		        let service_TypeA: (() -> TypeA)?
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let service = (safeDIParameters.service_TypeB ?? TypeB.init)()
		        func __safeDI_child() -> Child {
		            let service = (safeDIParameters.child.service ?? TypeB.init)()
		            return (safeDIParameters.child.safeDIBuilder ?? Child.init(service:serviceAlias:))(service, serviceAlias)
		        }
		        let child: Child = __safeDI_child()
		        let service = (safeDIParameters.service_TypeA ?? TypeA.init)()
		        return Root(child: child, service: service)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    struct SafeDIMockConfiguration {
		        init(
		            service: (() -> TypeB)? = nil,
		            _ safeDIBuilder: ((TypeB, TypeB) -> Child)? = nil
		        ) {
		            self.service = service
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let service: (() -> TypeB)?
		        let safeDIBuilder: ((TypeB, TypeB) -> Child)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguationFallsBackToFullSuffixWhenSimplifiedSuffixesCollide() async throws {
		// Root instantiates three children. Each child has a default-valued init
		// parameter named "value" with a different type. ServiceA and ServiceA?
		// both simplify to "ServiceA", forcing the full suffix fallback.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB, childC: ChildC) {
				        self.childA = childA
				        self.childB = childB
				        self.childC = childC
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				    @Instantiated let childC: ChildC
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(value: ServiceA = ServiceA()) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(value: ServiceA? = nil) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildC: Instantiable {
				    public init(value: ServiceB = ServiceB()) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ServiceA: Instantiable {
				    public init() {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ServiceB: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// "value" label appears three times: ServiceA, ServiceA?, ServiceB.
		// ServiceA and ServiceA? both simplify to "ServiceA", so their simplified
		// candidate "value_ServiceA" collides. Both fall back to full asIdentifier:
		// ServiceA stays "value_ServiceA", ServiceA? becomes "value_ServiceA_Optional".
		// ServiceB has no collision and uses simplified "value_ServiceB".
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    struct SafeDIParameters {
		        init(
		            childA: ChildA.SafeDIMockConfiguration = .init(),
		            childB: ChildB.SafeDIMockConfiguration = .init(),
		            childC: ChildC.SafeDIMockConfiguration = .init()
		        ) {
		            self.childA = childA
		            self.childB = childB
		            self.childC = childC
		        }

		        let childA: ChildA.SafeDIMockConfiguration
		        let childB: ChildB.SafeDIMockConfiguration
		        let childC: ChildC.SafeDIMockConfiguration
		    }

		    static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childA() -> ChildA {
		            return (safeDIParameters.childA.safeDIBuilder ?? ChildA.init(value:))(safeDIParameters.childA.value)
		        }
		        let childA: ChildA = __safeDI_childA()
		        func __safeDI_childB() -> ChildB {
		            return (safeDIParameters.childB.safeDIBuilder ?? ChildB.init(value:))(safeDIParameters.childB.value)
		        }
		        let childB: ChildB = __safeDI_childB()
		        func __safeDI_childC() -> ChildC {
		            return (safeDIParameters.childC.safeDIBuilder ?? ChildC.init(value:))(safeDIParameters.childC.value)
		        }
		        let childC: ChildC = __safeDI_childC()
		        return Root(childA: childA, childB: childB, childC: childC)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildA {
		    struct SafeDIMockConfiguration {
		        init(
		            value: ServiceA = ServiceA(),
		            _ safeDIBuilder: ((ServiceA) -> ChildA)? = nil
		        ) {
		            self.value = value
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let value: ServiceA
		        let safeDIBuilder: ((ServiceA) -> ChildA)?
		    }
		}

		extension ChildB {
		    struct SafeDIMockConfiguration {
		        init(
		            value: ServiceA? = nil,
		            _ safeDIBuilder: ((ServiceA?) -> ChildB)? = nil
		        ) {
		            self.value = value
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let value: ServiceA?
		        let safeDIBuilder: ((ServiceA?) -> ChildB)?
		    }
		}

		extension ChildC {
		    struct SafeDIMockConfiguration {
		        init(
		            value: ServiceB = ServiceB(),
		            _ safeDIBuilder: ((ServiceB) -> ChildC)? = nil
		        ) {
		            self.value = value
		            self.safeDIBuilder = safeDIBuilder
		        }

		        let value: ServiceB
		        let safeDIBuilder: ((ServiceB) -> ChildC)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	// MARK: Private

	private var filesToDelete: [URL]
}
