// Distributed under the MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Foundation
import SafeDICore
import Testing
@testable import SafeDITool

struct SafeDIToolMockGenerationDefaultValueTests: ~Copyable {
	// MARK: Initialization

	init() throws {
		filesToDelete = [URL]()
	}

	deinit {
		for fileToDelete in filesToDelete {
			try! FileManager.default.removeItem(at: fileToDelete)
		}
	}

	// MARK: Tests – Default-valued parameters

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterBubblesUpToRootMock() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child, shared: Shared) {
				        self.child = child
				        self.shared = shared
				    }
				    @Instantiated let child: Child
				    @Instantiated let shared: Shared
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(shared: Shared, flag: Bool = false) {
				        self.shared = shared
				    }
				    @Received let shared: Shared
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Shared: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public struct SafeDIParameters {
		        public init(
		            shared: (() -> Shared)? = nil
		        ) {
		            self.shared = shared
		        }

		        public let shared: (() -> Shared)?
		    }

		    public static func mock(
		        flag: Bool = false,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Child {
		        let shared: Shared
		        if let safeDIBuilder = safeDIParameters.shared {
		            shared = safeDIBuilder()
		        } else {
		            shared = Shared()
		        }
		        return Child(shared: shared, flag: flag)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            shared: (() -> Shared)? = nil,
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.shared = shared
		            self.child = child
		        }

		        public let shared: (() -> Shared)?
		        public let child: Child.SafeDIMockConfiguration
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let shared: Shared
		        if let safeDIBuilder = safeDIParameters.shared {
		            shared = safeDIBuilder()
		        } else {
		            shared = Shared()
		        }
		        let child: Child
		        if let safeDIBuilder = safeDIParameters.child.safeDIBuilder {
		            child = safeDIBuilder(shared, safeDIParameters.child.flag)
		        } else {
		            child = Child(shared: shared, flag: safeDIParameters.child.flag)
		        }
		        return Root(child: child, shared: shared)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public struct SafeDIMockConfiguration {
		        public init(
		            flag: Bool = false,
		            _ safeDIBuilder: ((Shared, Bool) -> Child)? = nil
		        ) {
		            self.flag = flag
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let flag: Bool
		        public let safeDIBuilder: ((Shared, Bool) -> Child)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")

		#expect(output.mockFiles["Shared+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Shared {
		    public static func mock() -> Shared {
		        Shared()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Shared+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterUsesOriginalDefaultExpression() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(config: String = "hello") {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public static func mock(
		        config: String = "hello"
		    ) -> Child {
		        return Child(config: config)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        public let child: Child.SafeDIMockConfiguration
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let child: Child
		        if let safeDIBuilder = safeDIParameters.child.safeDIBuilder {
		            child = safeDIBuilder(safeDIParameters.child.config)
		        } else {
		            child = Child(config: safeDIParameters.child.config)
		        }
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public struct SafeDIMockConfiguration {
		        public init(
		            config: String = "hello",
		            _ safeDIBuilder: ((String) -> Child)? = nil
		        ) {
		            self.config = config
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let config: String
		        public let safeDIBuilder: ((String) -> Child)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterDoesNotBubbleThroughInstantiator() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childBuilder: Instantiator<Child>) { self.childBuilder = childBuilder }
				    @Instantiated let childBuilder: Instantiator<Child>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(name: String, flag: Bool = false) { self.name = name }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            childBuilder: ((String, Bool) -> Child)? = nil
		        ) {
		            self.childBuilder = childBuilder
		        }

		        public let childBuilder: ((String, Bool) -> Child)?
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childBuilder(name: String) -> Child {
		            if let safeDIBuilder = safeDIParameters.childBuilder {
		                return safeDIBuilder(name, false)
		            } else {
		                return Child(name: name, flag: false)
		            }
		        }
		        let childBuilder = Instantiator<Child> {
		            __safeDI_childBuilder(name: $0)
		        }
		        return Root(childBuilder: childBuilder)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public static func mock(
		        name: String,
		        flag: Bool = false
		    ) -> Child {
		        return Child(name: name, flag: flag)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterBubblesFromGrandchildToRoot() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(grandchild: Grandchild) { self.grandchild = grandchild }
				    @Instantiated let grandchild: Grandchild
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Grandchild: Instantiable {
				    public init(viewModel: String = "default") {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        public let child: Child.SafeDIMockConfiguration
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            let grandchild: Grandchild
		            if let safeDIBuilder = safeDIParameters.child.grandchild.safeDIBuilder {
		                grandchild = safeDIBuilder(safeDIParameters.child.grandchild.viewModel)
		            } else {
		                grandchild = Grandchild(viewModel: safeDIParameters.child.grandchild.viewModel)
		            }
		            if let safeDIBuilder = safeDIParameters.child.safeDIBuilder {
		                return safeDIBuilder(grandchild)
		            } else {
		                return Child(grandchild: grandchild)
		            }
		        }
		        let child = __safeDI_child()
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public struct SafeDIParameters {
		        public init(
		            grandchild: Grandchild.SafeDIMockConfiguration = .init()
		        ) {
		            self.grandchild = grandchild
		        }

		        public let grandchild: Grandchild.SafeDIMockConfiguration
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Child {
		        let grandchild: Grandchild
		        if let safeDIBuilder = safeDIParameters.grandchild.safeDIBuilder {
		            grandchild = safeDIBuilder(safeDIParameters.grandchild.viewModel)
		        } else {
		            grandchild = Grandchild(viewModel: safeDIParameters.grandchild.viewModel)
		        }
		        return Child(grandchild: grandchild)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Grandchild {
		    public struct SafeDIMockConfiguration {
		        public init(
		            viewModel: String = "default",
		            _ safeDIBuilder: ((String) -> Grandchild)? = nil
		        ) {
		            self.viewModel = viewModel
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let viewModel: String
		        public let safeDIBuilder: ((String) -> Grandchild)?
		    }
		}

		extension Child {
		    public struct SafeDIMockConfiguration {
		        public init(
		            grandchild: Grandchild.SafeDIMockConfiguration = .init(),
		            _ safeDIBuilder: ((Grandchild) -> Child)? = nil
		        ) {
		            self.grandchild = grandchild
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let grandchild: Grandchild.SafeDIMockConfiguration
		        public let safeDIBuilder: ((Grandchild) -> Child)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")

		#expect(output.mockFiles["Grandchild+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Grandchild {
		    public static func mock(
		        viewModel: String = "default"
		    ) -> Grandchild {
		        return Grandchild(viewModel: viewModel)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Grandchild+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterOnRootType() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child, debug: Bool = false) {
				        self.child = child
				    }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            child: (() -> Child)? = nil
		        ) {
		            self.child = child
		        }

		        public let child: (() -> Child)?
		    }

		    public static func mock(
		        debug: Bool = false,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let child: Child
		        if let safeDIBuilder = safeDIParameters.child {
		            child = safeDIBuilder()
		        } else {
		            child = Child()
		        }
		        return Root(child: child, debug: debug)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterDoesNotBubbleThroughSendableInstantiator() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childBuilder: SendableInstantiator<Child>) { self.childBuilder = childBuilder }
				    @Instantiated let childBuilder: SendableInstantiator<Child>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(name: String, flag: Bool = false) { self.name = name }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            childBuilder: (@Sendable (String, Bool) -> Child)? = nil
		        ) {
		            self.childBuilder = childBuilder
		        }

		        public let childBuilder: (@Sendable (String, Bool) -> Child)?
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let __safeDI_childBuilder__safeDIBuilder: @Sendable (String, Bool) -> Child
		        if let safeDIBuilder = safeDIParameters.childBuilder {
		            __safeDI_childBuilder__safeDIBuilder = safeDIBuilder
		        } else {
		            __safeDI_childBuilder__safeDIBuilder = Child.init(name:flag:)
		        }
		        @Sendable func __safeDI_childBuilder(name: String) -> Child {
		            __safeDI_childBuilder__safeDIBuilder(name, false)
		        }
		        let childBuilder = SendableInstantiator<Child> {
		            __safeDI_childBuilder(name: $0)
		        }
		        return Root(childBuilder: childBuilder)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_multipleDefaultValuedParametersFromDifferentChildren() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(flagA: Bool = true) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(flagB: Int = 42) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            childA: ChildA.SafeDIMockConfiguration = .init(),
		            childB: ChildB.SafeDIMockConfiguration = .init()
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        public let childA: ChildA.SafeDIMockConfiguration
		        public let childB: ChildB.SafeDIMockConfiguration
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let childA: ChildA
		        if let safeDIBuilder = safeDIParameters.childA.safeDIBuilder {
		            childA = safeDIBuilder(safeDIParameters.childA.flagA)
		        } else {
		            childA = ChildA(flagA: safeDIParameters.childA.flagA)
		        }
		        let childB: ChildB
		        if let safeDIBuilder = safeDIParameters.childB.safeDIBuilder {
		            childB = safeDIBuilder(safeDIParameters.childB.flagB)
		        } else {
		            childB = ChildB(flagB: safeDIParameters.childB.flagB)
		        }
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildA {
		    public struct SafeDIMockConfiguration {
		        public init(
		            flagA: Bool = true,
		            _ safeDIBuilder: ((Bool) -> ChildA)? = nil
		        ) {
		            self.flagA = flagA
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let flagA: Bool
		        public let safeDIBuilder: ((Bool) -> ChildA)?
		    }
		}

		extension ChildB {
		    public struct SafeDIMockConfiguration {
		        public init(
		            flagB: Int = 42,
		            _ safeDIBuilder: ((Int) -> ChildB)? = nil
		        ) {
		            self.flagB = flagB
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let flagB: Int
		        public let safeDIBuilder: ((Int) -> ChildB)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterWithNilDefault() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(viewModel: String? = nil) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        public let child: Child.SafeDIMockConfiguration
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let child: Child
		        if let safeDIBuilder = safeDIParameters.child.safeDIBuilder {
		            child = safeDIBuilder(safeDIParameters.child.viewModel)
		        } else {
		            child = Child(viewModel: safeDIParameters.child.viewModel)
		        }
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public static func mock(
		        viewModel: String? = nil
		    ) -> Child {
		        return Child(viewModel: viewModel)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public struct SafeDIMockConfiguration {
		        public init(
		            viewModel: String? = nil,
		            _ safeDIBuilder: ((String?) -> Child)? = nil
		        ) {
		            self.viewModel = viewModel
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let viewModel: String?
		        public let safeDIBuilder: ((String?) -> Child)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterDisambiguatedWhenLabelCollides() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(flag: Bool = true) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(flag: String = "on") {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            childA: ChildA.SafeDIMockConfiguration = .init(),
		            childB: ChildB.SafeDIMockConfiguration = .init()
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        public let childA: ChildA.SafeDIMockConfiguration
		        public let childB: ChildB.SafeDIMockConfiguration
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let childA: ChildA
		        if let safeDIBuilder = safeDIParameters.childA.safeDIBuilder {
		            childA = safeDIBuilder(safeDIParameters.childA.flag)
		        } else {
		            childA = ChildA(flag: safeDIParameters.childA.flag)
		        }
		        let childB: ChildB
		        if let safeDIBuilder = safeDIParameters.childB.safeDIBuilder {
		            childB = safeDIBuilder(safeDIParameters.childB.flag)
		        } else {
		            childB = ChildB(flag: safeDIParameters.childB.flag)
		        }
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildA {
		    public struct SafeDIMockConfiguration {
		        public init(
		            flag: Bool = true,
		            _ safeDIBuilder: ((Bool) -> ChildA)? = nil
		        ) {
		            self.flag = flag
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let flag: Bool
		        public let safeDIBuilder: ((Bool) -> ChildA)?
		    }
		}

		extension ChildB {
		    public struct SafeDIMockConfiguration {
		        public init(
		            flag: String = "on",
		            _ safeDIBuilder: ((String) -> ChildB)? = nil
		        ) {
		            self.flag = flag
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let flag: String
		        public let safeDIBuilder: ((String) -> ChildB)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterDoesNotBubbleThroughErasedInstantiator() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childBuilder: ErasedInstantiator<String, Child>) {
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let childBuilder: ErasedInstantiator<String, Child>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(name: String, flag: Bool = false) {
				        self.name = name
				    }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            childBuilder: ((String, Bool) -> Child)? = nil
		        ) {
		            self.childBuilder = childBuilder
		        }

		        public let childBuilder: ((String, Bool) -> Child)?
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_childBuilder(name: String) -> Child {
		            if let safeDIBuilder = safeDIParameters.childBuilder {
		                return safeDIBuilder(name, false)
		            } else {
		                return Child(name: name, flag: false)
		            }
		        }
		        let childBuilder = ErasedInstantiator<String, Child> {
		            __safeDI_childBuilder(name: $0)
		        }
		        return Root(childBuilder: childBuilder)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterDoesNotBubbleThroughSendableErasedInstantiator() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childBuilder: SendableErasedInstantiator<String, Child>) {
				        self.childBuilder = childBuilder
				    }
				    @Instantiated let childBuilder: SendableErasedInstantiator<String, Child>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(name: String, flag: Bool = false) {
				        self.name = name
				    }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            childBuilder: (@Sendable (String, Bool) -> Child)? = nil
		        ) {
		            self.childBuilder = childBuilder
		        }

		        public let childBuilder: (@Sendable (String, Bool) -> Child)?
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let __safeDI_childBuilder__safeDIBuilder: @Sendable (String, Bool) -> Child
		        if let safeDIBuilder = safeDIParameters.childBuilder {
		            __safeDI_childBuilder__safeDIBuilder = safeDIBuilder
		        } else {
		            __safeDI_childBuilder__safeDIBuilder = Child.init(name:flag:)
		        }
		        @Sendable func __safeDI_childBuilder(name: String) -> Child {
		            __safeDI_childBuilder__safeDIBuilder(name, false)
		        }
		        let childBuilder = SendableErasedInstantiator<String, Child> {
		            __safeDI_childBuilder(name: $0)
		        }
		        return Root(childBuilder: childBuilder)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterWithComplexDefault() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(values: [Int] = [1, 2, 3]) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        public let child: Child.SafeDIMockConfiguration
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let child: Child
		        if let safeDIBuilder = safeDIParameters.child.safeDIBuilder {
		            child = safeDIBuilder(safeDIParameters.child.values)
		        } else {
		            child = Child(values: safeDIParameters.child.values)
		        }
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public struct SafeDIMockConfiguration {
		        public init(
		            values: [Int] = [1, 2, 3],
		            _ safeDIBuilder: (([Int]) -> Child)? = nil
		        ) {
		            self.values = values
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let values: [Int]
		        public let safeDIBuilder: (([Int]) -> Child)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_childDefaultParamDoesNotReEvaluateRootBoundLabel() async throws {
		// Parent @Receives clientId (uncovered, no scope for String).
		// Child has clientId as a non-dependency default-valued init param.
		// The root binds `let clientId = clientId()`. The child function
		// must NOT re-bind it — clientId is already a String, not callable.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Parent: Instantiable {
				    public init(clientId: String, child: Child) {
				        self.clientId = clientId
				        self.child = child
				    }
				    @Received let clientId: String
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(clientId: String = "default") {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles["Parent+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Parent {
		    public struct SafeDIParameters {
		        public init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        public let child: Child.SafeDIMockConfiguration
		    }

		    public static func mock(
		        clientId: String,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Parent {
		        let child: Child
		        if let safeDIBuilder = safeDIParameters.child.safeDIBuilder {
		            child = safeDIBuilder(safeDIParameters.child.clientId)
		        } else {
		            child = Child(clientId: safeDIParameters.child.clientId)
		        }
		        return Parent(clientId: clientId, child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Parent+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public struct SafeDIMockConfiguration {
		        public init(
		            clientId: String = "default",
		            _ safeDIBuilder: ((String) -> Child)? = nil
		        ) {
		            self.clientId = clientId
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let clientId: String
		        public let safeDIBuilder: ((String) -> Child)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_disambiguatedDefaultParamsFromDifferentChildrenDoNotCollideAtRoot() async throws {
		// ChildA has `viewModel: ViewModelA = ViewModelA()` and ChildB has `viewModel: ViewModelB = ViewModelB()`.
		// Both bubble to root as disambiguated autoclosure params. They must NOT both produce
		// `let viewModel = ...` at root scope — each should bind inside its own child function.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(viewModel: ViewModelA = ViewModelA()) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(viewModel: ViewModelB = ViewModelB()) {}
				}
				""",
				"""
				public struct ViewModelA {}
				""",
				"""
				public struct ViewModelB {}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// Each viewModel binding must be INSIDE its child function, not at root scope.
		// Root scope should NOT have `let viewModel = ...` at all.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            childA: ChildA.SafeDIMockConfiguration = .init(),
		            childB: ChildB.SafeDIMockConfiguration = .init()
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        public let childA: ChildA.SafeDIMockConfiguration
		        public let childB: ChildB.SafeDIMockConfiguration
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let childA: ChildA
		        if let safeDIBuilder = safeDIParameters.childA.safeDIBuilder {
		            childA = safeDIBuilder(safeDIParameters.childA.viewModel)
		        } else {
		            childA = ChildA(viewModel: safeDIParameters.childA.viewModel)
		        }
		        let childB: ChildB
		        if let safeDIBuilder = safeDIParameters.childB.safeDIBuilder {
		            childB = safeDIBuilder(safeDIParameters.childB.viewModel)
		        } else {
		            childB = ChildB(viewModel: safeDIParameters.childB.viewModel)
		        }
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""", "Unexpected Root output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildA {
		    public struct SafeDIMockConfiguration {
		        public init(
		            viewModel: ViewModelA = ViewModelA(),
		            _ safeDIBuilder: ((ViewModelA) -> ChildA)? = nil
		        ) {
		            self.viewModel = viewModel
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let viewModel: ViewModelA
		        public let safeDIBuilder: ((ViewModelA) -> ChildA)?
		    }
		}

		extension ChildB {
		    public struct SafeDIMockConfiguration {
		        public init(
		            viewModel: ViewModelB = ViewModelB(),
		            _ safeDIBuilder: ((ViewModelB) -> ChildB)? = nil
		        ) {
		            self.viewModel = viewModel
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let viewModel: ViewModelB
		        public let safeDIBuilder: ((ViewModelB) -> ChildB)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParametersFromMultipleLevelsAllAppearAtRoot() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(grandchild: Grandchild, config: String = "dev") {
				        self.grandchild = grandchild
				    }
				    @Instantiated let grandchild: Grandchild
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Grandchild: Instantiable {
				    public init(viewModel: String = "default") {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        public let child: Child.SafeDIMockConfiguration
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            let grandchild: Grandchild
		            if let safeDIBuilder = safeDIParameters.child.grandchild.safeDIBuilder {
		                grandchild = safeDIBuilder(safeDIParameters.child.grandchild.viewModel)
		            } else {
		                grandchild = Grandchild(viewModel: safeDIParameters.child.grandchild.viewModel)
		            }
		            if let safeDIBuilder = safeDIParameters.child.safeDIBuilder {
		                return safeDIBuilder(grandchild, safeDIParameters.child.config)
		            } else {
		                return Child(grandchild: grandchild, config: safeDIParameters.child.config)
		            }
		        }
		        let child = __safeDI_child()
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Grandchild {
		    public struct SafeDIMockConfiguration {
		        public init(
		            viewModel: String = "default",
		            _ safeDIBuilder: ((String) -> Grandchild)? = nil
		        ) {
		            self.viewModel = viewModel
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let viewModel: String
		        public let safeDIBuilder: ((String) -> Grandchild)?
		    }
		}

		extension Child {
		    public struct SafeDIMockConfiguration {
		        public init(
		            grandchild: Grandchild.SafeDIMockConfiguration = .init(),
		            config: String = "dev",
		            _ safeDIBuilder: ((Grandchild, String) -> Child)? = nil
		        ) {
		            self.grandchild = grandchild
		            self.config = config
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let grandchild: Grandchild.SafeDIMockConfiguration
		        public let config: String
		        public let safeDIBuilder: ((Grandchild, String) -> Child)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParameterFromGrandchildStopsAtInstantiatorBoundary() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(grandchildBuilder: Instantiator<Grandchild>) {
				        self.grandchildBuilder = grandchildBuilder
				    }
				    @Instantiated let grandchildBuilder: Instantiator<Grandchild>
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Grandchild: Instantiable {
				    public init(name: String, viewModel: String = "default") {
				        self.name = name
				    }
				    @Forwarded let name: String
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 3)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        public let child: Child.SafeDIMockConfiguration
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        func __safeDI_child() -> Child {
		            func __safeDI_grandchildBuilder(name: String) -> Grandchild {
		                if let safeDIBuilder = safeDIParameters.child.grandchildBuilder {
		                    return safeDIBuilder(name, "default")
		                } else {
		                    return Grandchild(name: name, viewModel: "default")
		                }
		            }
		            let grandchildBuilder = Instantiator<Grandchild> {
		                __safeDI_grandchildBuilder(name: $0)
		            }
		            if let safeDIBuilder = safeDIParameters.child.safeDIBuilder {
		                return safeDIBuilder(grandchildBuilder)
		            } else {
		                return Child(grandchildBuilder: grandchildBuilder)
		            }
		        }
		        let child = __safeDI_child()
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public struct SafeDIMockConfiguration {
		        public init(
		            grandchildBuilder: ((String, String) -> Grandchild)? = nil,
		            _ safeDIBuilder: ((Instantiator<Grandchild>) -> Child)? = nil
		        ) {
		            self.grandchildBuilder = grandchildBuilder
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let grandchildBuilder: ((String, String) -> Grandchild)?
		        public let safeDIBuilder: ((Instantiator<Grandchild>) -> Child)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedClosureParameterStripsEscaping() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(onDismiss: @escaping () -> Void = {}) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        public let child: Child.SafeDIMockConfiguration
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let child: Child
		        if let safeDIBuilder = safeDIParameters.child.safeDIBuilder {
		            child = safeDIBuilder(safeDIParameters.child.onDismiss)
		        } else {
		            child = Child(onDismiss: safeDIParameters.child.onDismiss)
		        }
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public struct SafeDIMockConfiguration {
		        public init(
		            onDismiss: @escaping () -> Void = {},
		            _ safeDIBuilder: ((@escaping () -> Void) -> Child)? = nil
		        ) {
		            self.onDismiss = onDismiss
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let onDismiss: () -> Void
		        public let safeDIBuilder: ((@escaping () -> Void) -> Child)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedMainActorClosurePreservesMainActor() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(
				        onCancel: @escaping @MainActor (String) -> Void = { _ in },
				        onSubmit: @escaping @MainActor (String) throws -> Void = { _ in }
				    ) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public static func mock(
		        onCancel: @escaping @MainActor (String) -> Void = { _ in },
		        onSubmit: @escaping @MainActor (String) throws -> Void = { _ in }
		    ) -> Child {
		        return Child(onCancel: onCancel, onSubmit: onSubmit)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedSendableClosurePreservesSendable() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(onComplete: @escaping @Sendable () -> Void = {}) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        public let child: Child.SafeDIMockConfiguration
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let child: Child
		        if let safeDIBuilder = safeDIParameters.child.safeDIBuilder {
		            child = safeDIBuilder(safeDIParameters.child.onComplete)
		        } else {
		            child = Child(onComplete: safeDIParameters.child.onComplete)
		        }
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public struct SafeDIMockConfiguration {
		        public init(
		            onComplete: @escaping @Sendable () -> Void = {},
		            _ safeDIBuilder: ((@escaping @Sendable () -> Void) -> Child)? = nil
		        ) {
		            self.onComplete = onComplete
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let onComplete: @Sendable () -> Void
		        public let safeDIBuilder: ((@escaping @Sendable () -> Void) -> Child)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_defaultValuedParamDoesNotSuppressReceivedPropertyBinding() async throws {
		// A child has a default-valued init param with the same label as a received
		// dependency on another child. The default-valued declaration must NOT suppress
		// the received property's root-level binding.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(childA: ChildA, childB: ChildB) {
				        self.childA = childA
				        self.childB = childB
				    }
				    @Instantiated let childA: ChildA
				    @Instantiated let childB: ChildB
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildA: Instantiable {
				    public init(service: Service?) {
				        self.service = service
				    }
				    @Received(onlyIfAvailable: true) let service: Service?
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct ChildB: Instantiable {
				    public init(service: Service? = nil) {}
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Service: Instantiable {
				    public init() {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// ChildA receives `service` (onlyIfAvailable). ChildB has `service` as a
		// default-valued param. The root-level binding for `service` must exist
		// so ChildA's construction can reference the resolved value, not the closure.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            childA: ((Service?) -> ChildA)? = nil,
		            childB: ChildB.SafeDIMockConfiguration = .init()
		        ) {
		            self.childA = childA
		            self.childB = childB
		        }

		        public let childA: ((Service?) -> ChildA)?
		        public let childB: ChildB.SafeDIMockConfiguration
		    }

		    public static func mock(
		        service: Service? = nil,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let childA: ChildA
		        if let safeDIBuilder = safeDIParameters.childA {
		            childA = safeDIBuilder(service)
		        } else {
		            childA = ChildA(service: service)
		        }
		        let childB: ChildB
		        if let safeDIBuilder = safeDIParameters.childB.safeDIBuilder {
		            childB = safeDIBuilder(safeDIParameters.childB.service)
		        } else {
		            childB = ChildB(service: safeDIParameters.childB.service)
		        }
		        return Root(childA: childA, childB: childB)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension ChildB {
		    public struct SafeDIMockConfiguration {
		        public init(
		            service: Service? = nil,
		            _ safeDIBuilder: ((Service?) -> ChildB)? = nil
		        ) {
		            self.service = service
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let service: Service?
		        public let safeDIBuilder: ((Service?) -> ChildB)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_forwardedParamDoesNotCollideWithBubbledDefault() async throws {
		// Root @Forwards `name: String`. Child has default-valued `name: String = "default"`.
		// Both produce mock params with label "name". Disambiguation must handle forwarded too.
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(name: String, child: Child) {
				        self.name = name
				        self.child = child
				    }
				    @Forwarded let name: String
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(name: String = "default") {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		// name (forwarded, bare) stays as-is. name_String (bubbled default) is disambiguated.
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        public let child: Child.SafeDIMockConfiguration
		    }

		    public static func mock(
		        name: String,
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let child: Child
		        if let safeDIBuilder = safeDIParameters.child.safeDIBuilder {
		            child = safeDIBuilder(safeDIParameters.child.name)
		        } else {
		            child = Child(name: safeDIParameters.child.name)
		        }
		        return Root(name: name, child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public struct SafeDIMockConfiguration {
		        public init(
		            name: String = "default",
		            _ safeDIBuilder: ((String) -> Child)? = nil
		        ) {
		            self.name = name
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let name: String
		        public let safeDIBuilder: ((String) -> Child)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_usesOuterLabel_whenDefaultValuedParameterHasUnderscoreInnerLabel() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(isLoggingEnabled _: Bool = false) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            child: Child.SafeDIMockConfiguration = .init()
		        ) {
		            self.child = child
		        }

		        public let child: Child.SafeDIMockConfiguration
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let child: Child
		        if let safeDIBuilder = safeDIParameters.child.safeDIBuilder {
		            child = safeDIBuilder(safeDIParameters.child.isLoggingEnabled)
		        } else {
		            child = Child(isLoggingEnabled: safeDIParameters.child.isLoggingEnabled)
		        }
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public static func mock(
		        isLoggingEnabled: Bool = false
		    ) -> Child {
		        return Child(isLoggingEnabled: isLoggingEnabled)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")

		#expect(output.mockConfigurationFile == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public struct SafeDIMockConfiguration {
		        public init(
		            isLoggingEnabled: Bool = false,
		            _ safeDIBuilder: ((Bool) -> Child)? = nil
		        ) {
		            self.isLoggingEnabled = isLoggingEnabled
		            self.safeDIBuilder = safeDIBuilder
		        }

		        public let isLoggingEnabled: Bool
		        public let safeDIBuilder: ((Bool) -> Child)?
		    }
		}
		#endif

		""", "Unexpected output \(output.mockConfigurationFile ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_doesNotBubbleDefaultValuedParameter_whenOuterLabelIsUnderscore() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(_ isLoggingEnabled: Bool = false) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            child: ((Bool) -> Child)? = nil
		        ) {
		            self.child = child
		        }

		        public let child: ((Bool) -> Child)?
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let child: Child
		        if let safeDIBuilder = safeDIParameters.child {
		            child = safeDIBuilder(isLoggingEnabled)
		        } else {
		            child = Child(_: isLoggingEnabled)
		        }
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public static func mock() -> Child {
		        Child()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")
	}

	@Test
	@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
	mutating func mock_doesNotBubbleDefaultValuedParameter_whenOnlyLabelIsUnderscore() async throws {
		let output = try await executeSafeDIToolTest(
			swiftFileContent: [
				"""
				@Instantiable(isRoot: true, generateMock: true)
				public struct Root: Instantiable {
				    public init(child: Child) { self.child = child }
				    @Instantiated let child: Child
				}
				""",
				"""
				@Instantiable(generateMock: true)
				public struct Child: Instantiable {
				    public init(_: Bool = false) {}
				}
				""",
			],
			buildSwiftOutputDirectory: true,
			filesToDelete: &filesToDelete,
		)

		#expect(output.mockFiles.count == 2)
		#expect(output.mockFiles["Root+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Root {
		    public struct SafeDIParameters {
		        public init(
		            child: ((Bool) -> Child)? = nil
		        ) {
		            self.child = child
		        }

		        public let child: ((Bool) -> Child)?
		    }

		    public static func mock(
		        safeDIParameters: SafeDIParameters = .init()
		    ) -> Root {
		        let child: Child
		        if let safeDIBuilder = safeDIParameters.child {
		            child = safeDIBuilder(_)
		        } else {
		            child = Child(_: _)
		        }
		        return Root(child: child)
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Root+SafeDIMock.swift"] ?? "")")
		#expect(output.mockFiles["Child+SafeDIMock.swift"] == """
		// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
		// Any modifications made to this file will be overwritten on subsequent builds.
		// Please refrain from editing this file directly.

		#if DEBUG
		extension Child {
		    public static func mock() -> Child {
		        Child()
		    }
		}
		#endif
		""", "Unexpected output \(output.mockFiles["Child+SafeDIMock.swift"] ?? "")")
	}

	// MARK: Private

	private var filesToDelete: [URL]
}
